### ISSUE TITLE
Introduce MIN and MAX peers options

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1029]
`--min-peers` A minimum number of peers required. Actively attempt connections below this value.
`--max-peers` Maximum number of peers we can handle. Refuse incoming connections over this value.
It is getting more difficult to find a node with a free incoming connection slot on the network. Nodes that can accept incoming connections should allow more connections. The ratio for default values should be about 1:4 (needs research)

**Comment by rphmeier** [comment]
I would like to work on this.

**Comment by arkpar** [comment]
@rphmeier please go ahead

**Comment by rphmeier** [comment]
There is already a --peers option (formerly --maxpeers) which seems to do max-peers' job already (it is referred to as such still in RPC and most of the codebase). It could be strange to have both. A min-peers flag wouldn't have any such conflicts.

**Comment by arkpar** [comment]
I guess we can leave `--peers` which sets both MIN and MAX for geth compatibility and have additional `---min-peers` and `--max-peers`. Setting `--peers` together with any of the other two options would result in an error. RPC only deals with a number of peers currently connected, not the limit.
