### ISSUE TITLE
PoA: Delayed block sealing

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1034]
Seal blocks if there are pending transactions and a time interval has passed. Make the interval configurable

**Comment by keorn** [comment]
Seems like a nice way would be to have a `Sealer` which would be implemented by `Miner` and `AuthoritySealer`. This could be then extended to `BftSealer`, which would have to pass messages to reach consensus.

**Comment by gavofyork** [comment]
ok - sounds like this is going to be refactoring as part of @keorn 's PoS stuff.

will close, since that's not the intent of the original issue.
