### ISSUE TITLE
"PV64" Turbo syncing

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1037]
Minor wire protocol addition, codename PV64 (it may yet identify itself using some other form, since it's best not to pollute the version namespace without consensus) which would allow for non-interactive parallel downloading of the state.

Basically, we'd work out some sweet point for state/receipt-archive downloading versus block-downloading/transaction-execution. We parallel download the last few thousand headers "normally" (and check PoW), do an interactive proof of a few thousand chosen at random previously on the chain, then sync up to the last archive checkpoint (e.g. one archive every N blocks, to optimise clients and simplify the data they'll have to be hosting. N could be 5000? Archive is a bunch of zips of parts of the state trie and receipts series; one zip per peer. We then sync up the last few K blocks normally and progressively download previous headers and blocks. (Though eventually we'll not bother downloading all previous blocks/receipts, rather we'll query the network when we find headers that are interesting to us.)

**Comment by rphmeier** [comment]
depends on #1557

**Comment by arkpar** [comment]
Implemented with `--warp` in 1.4.
