### ISSUE TITLE
From fn to Fn?

### ISSUE THREAD

**Issue by efaysal** [ethcore/parity#1042]
This is mainly related to jsonrpc_core library. 

To illustrate the issue ( it may be not really a serious issue), let's give a concrete example:

The DelegateMethod struct is specific about the nature of the closure:

struct DelegateMethod<T, F> where
	F: Fn(&T, Params) -> Result<Value, Error>  // ( better to have a Fn, it has the environment by reference)

DelegateMethod has the trait MethodCommand. 

struct IoDelegate<T>  can store MethodCommand ( hence including DelegateMethod ) where T has the traits and lifetime: Send + Sync + 'static

Let's pick for instance T as pub trait Personal, 

Couple of ordinary or normal  fn functions are defined and after considered as closure to be inserted in IoDelegate<Personal>. 

Now those fn functions are considered as Fn closure as it is required by DelegateMethod. 

Are you sure that the compiler always infer fn as Fn? 

In general the compiler looks at the closure body to see how external variables are handled and infers how they should be included in the body of the closure:
1) if shared reference, it is included or captured by & reference,
2) if  mutable reference, it is captured by &mut reference,
3) if by-value to escape from the environment, , it is included or captured by copy.
4) if no environment variables are needed, for instance when it's fn, so which one is by default or adequately  inferred by the compiler?

**Comment by arkpar** [comment]
Function pointers are treated as closures as long as the signature matches. See https://doc.rust-lang.org/book/closures.html#function-pointers-and-closures

**Comment by efaysal** [comment]
hi arkpar, 

a detailed answer is in  http://efaysal.github.io/Rust/RustF2f.html

The code is in  https://github.com/efaysal/Rustf2F/

I will contact Rust for more clarifications.
