### ISSUE TITLE
Can't run with `--geth` option on OSX

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#1061]
Crashed with `ERROR: RPC: Error { repr: Os { code: 2, message: "No such file or directory" } }` on OSX.

**Comment by sammy007** [comment]
Because I see that parity trying to set IPC path to `$HOME/.ethereum/` but on OSX it should set to `$HOME/Library/Ethereum/`.

**Comment by gavofyork** [comment]
will put in a fix now

**Comment by gavofyork** [comment]
Should be fixed in #1062
