### ISSUE TITLE
Handle syncing attack vectors.

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1079]
* Check DejaVu eth report.
* https://github.com/ethereum/section_9/blob/master/eth_bounty_submission.pdf.
* Estimate max blocks for main network.
* Prevent incoming peers from reconnecting with fresh keys and stalling the sync (deny incoming connections while not fully synced?)

**Comment by gavofyork** [comment]
Maybe helped by #1095 ?

**Comment by gavofyork** [comment]
All in, now.

**Comment by arkpar** [comment]
#345 to track tests
