### ISSUE TITLE
Install via cargo

### ISSUE THREAD

**Issue by NastyRigger** [ethcore/parity#1084]
I've just tried: **cargo install parity** but it seems there's no parity on cartes.io

I think it should be the quickset method of installing from source, don't ya?

**Comment by debris** [comment]
To achieve that we need to use only libraries available on crates.io. 

Currently, we use forks of `ctrlc`, `mio` (and probably few more). Also, we need to publish all of our eth* libraries to crates.io. That's a lot of time consuming work. I would not prioritize it.

Pull requests are welcomed ;)

**Comment by NastyRigger** [comment]
Is is the same as?:

- cargo install --git https://github.com/ethcore/parity.git
-     Updating git repository `https://github.com/ethcore/parity.git`
- error: multiple packages with binaries found: parity, rpctest

**Comment by NikVolf** [comment]
@NastyRigger 
Funny
Guess it tries to find any `Cargo.toml` inside repository with `[[bin]]` target, build & run it. Obviosly fails because we have multiple binaries here

**Comment by debris** [comment]
Parity can be installed via `cargo install --git https://github.com/ethcore/parity.git parity`
