### ISSUE TITLE
Relock account from personal_unlockAccount after first usage

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#1086]
can prevent brute force attack vector when RPC is exposed to public and user never unlocks accounts

**Comment by gavofyork** [comment]
tbh this API is dangerous and should just be removed.

**Comment by gavofyork** [comment]
if we keep it, it shouldn't be a timeout but rather until the first usage (i.e. `eth_sendTransaction`), after which it should be locked again.

**Comment by gavofyork** [comment]
Fixed in #1120
