### ISSUE TITLE
Lookup for keystore in a testnet dir

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#1089]
I believe parity should look for accounts in `~/Library/Ethereum/testnet/keystore` if `--testnet` used.

**Comment by gavofyork** [comment]
@NikVolf this is more short-sighted geth-compatibility than core client stuff.

for this to work nicely, we need to separate the keystore path from the main DB path, then as a geth-compatibility thing, make `--testnet` mean two things; `--chain morden` (it means this already) and `--keys-path $ETHEREUM/testnet/keystore` (where `$ETHEREUM` = `$HOME/.ethereum` on linux and `$HOME/Library/Ethereum` on Mac).

**Comment by jorisbontje** [comment]
Running `parity --chain morden --keys-path ~/Library/Ethereum/testnet/keystore` causes parity to dump my mainnet geth keys into the testnet keystore; while ignoring my testnet keys. So that doesn't work as viable workaround.

**Comment by gavofyork** [comment]
indeed - also need to avoid parity importing anything when a non-standard keys-path is provided.
