### ISSUE TITLE
die_with_error should use fmt::Display instead of fmt::Debug

### ISSUE THREAD

**Issue by debris** [ethcore/parity#1099]
https://github.com/ethcore/parity/blob/dcc695dda5b77fa0199a6061802d086ba59ab329/parity/die.rs#L32

Additionally it should trace error `trace!("{:?}", e)`

**Comment by rphmeier** [comment]
Do you think the same should apply to `die_with_io_error`?

**Comment by gavofyork** [comment]
almost certainly.
