### ISSUE TITLE
Don't rebuild librocksdb? (too often)

### ISSUE THREAD

**Issue by petevine** [ethcore/parity#1104]
Currently, even with the same versions of rustc/cargo, a rebuild of C++ code is triggered on `RUSTFLAGS'` change (probably on other occasions too) which seems redundant. Ideally, the only reason for a rebuild would involve modified `CFLAGS/CXXFLAGS`.

Additionally, building the benchmark suite doesn't seem to reuse an already built library from the main app, and vice-versa.

Maybe `cargo clean` could even spare librocksdb until next `build` and only then check for changed CXXFLAGS? I have no idea if anyone has ever tried stuff like that in Rust...

**Comment by arkpar** [comment]
Should be fixed in latest master
