### ISSUE TITLE
eth_syncing / web3_eth_issyncing shouldn't be kicking off as blocks are mined

### ISSUE THREAD

**Issue by jorisbontje** [ethcore/parity#1110]
Parity reports a sync for every block that gets imported from the network, even after the blockchain has done its initial sync. With the current behaviour it differs from geth, which only reports a syncing status if it has some real catching up to do (being (much) more than 1 block behind from the rest of the network).

@gavofyork on gitter:
> i guess it depends on what you call "real catching up" 
> but yes - it shouldn't be kicking off as blocks are mined

`version Parity/v1.2.0-unstable-dcc695d-20160517/x86_64-macos/rustc1.8.0`

**Comment by gavofyork** [comment]
#1122 - @jorisbontje please test that branch if you can

**Comment by jorisbontje** [comment]
@gavofyork not fixed, I believe this ties in with `starting_block` always being zero in parity, instead of being "The block number where the sync started" as according to https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethissyncing 

```
isSyncing true
isSyncing Object {currentBlock: 1570218, highestBlock: 1570217, startingBlock: 0}
isSyncing false
```

**Comment by gavofyork** [comment]
@arkpar - chain.rs:255; `starting_block` is set to 0. i don't see it set to anything else in the codebase. did you ever expect this to work?
