### ISSUE TITLE
More descriptive RPC error responses.

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1114]
When `id` field is not specified in data send to RPC server generates `405 Method Not Allowed`.
It's difficult to identify the issue, because the body is empty:
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x91be1566753de242a48159c92c9fafd526ad5cf7"]}' http://localhost:8545/
$
```

Running with verbose reveals the 405:
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x91be1566753de242a48159c92c9fafd526ad5cf7"]}' http://localhost:8545/ --verbose
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8545 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8545
> Accept: */*
> Content-Length: 99
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 99 out of 99 bytes
< HTTP/1.1 405 Method Not Allowed
< Date: Fri, 20 May 2016 12:35:46 GMT
< Allow: OPTIONS, POST
< Access-Control-Allow-Headers: origin, content-type, accept
< Transfer-Encoding: chunked
< Content-Type: application/json
< 
* Connection #0 to host localhost left intact
```

1. In case of fields missing in JSON parity should respond with `400 Bad Request` since the method used is actually correct.
2. According to spec we should also generate error object in response: http://www.jsonrpc.org/specification#error_object (for all cases)

**Comment by debris** [comment]
we should not bother with HTTP errors, since jsonrpc has it's own errors. imo we should return `200` and proper [jsonrpc error](http://www.jsonrpc.org/specification#error_object) inside. `-32600` in this case

**Comment by tomusdrw** [comment]
According to spec requests without `id` field are Notifications. Responses for notifications should always be empty. So the only thing incorrect in this request is the status code, which is fixed in https://github.com/ethcore/jsonrpc-http-server/pull/17
