### ISSUE TITLE
Snappy infectious?

### ISSUE THREAD

**Issue by petevine** [ethcore/parity#1117]
Having installed `libsnappy` recently, I've noticed two issues after building parity again:

- `librocksdb` is being dynamically linked against `libsnappy` which makes the parity binary slightly less self-hosting.
- after running the newer binary (with snappy support) for a while, trying to run any older ones leads to panic:

```rust
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Corruption: Snappy not supported or corrupted Snappy compressed block contents"', src/libcore/result.rs:785
````

Not sure if it's an issue at all but it seems the database has been converted to (infected with?) snappy compression.

**Comment by gavofyork** [comment]
Seems like a reasonable guess. I'd say this is a rocksdb issue really; I guess we could try to disable snappy compression in the flags?

**Comment by NikVolf** [comment]
https://github.com/ethcore/rust-rocksdb/blob/master/librocksdb-sys/build.rs#L104

probably this will give some insights

**Comment by petevine** [comment]
The official parity distribution doesn't seem to use snappy so maybe disabling it at build-time is the way to go? Otherwise shuffling binaries from different sources becomes more difficult.

On the other hand, if using snappy's advantageous and the licenses don't pose a problem, just link it in statically maybe?

**Comment by gavofyork** [comment]
looks like it's an issue with @arkpar 's build script for rocksdb - should be fixable there, perhaps by keeping snappy disabled.

**Comment by arkpar** [comment]
Fixed in latest master. All builds now compile-in libsnappy statically.

**Comment by petevine** [comment]
Cool, a collective thx for all the issues!
