### ISSUE TITLE
MIST Times out when accessing Parity

### ISSUE THREAD

**Issue by johnwhitton** [ethcore/parity#1161]
When running a Parity Node Locally and starting MIST I receive wrong password when trying to authorize transactions this is caused by MIST (ELECTRON) receiving a timeout when accessing Parity.
I have tried this with multiple versions of MIST (7.4, 7.2) and have tried building Parity Locally as well as installing Parity [executables](https://github.com/General-Beck/parity/releases).
Below are the details when running MIST 7.4 and Parity v1.2.0

### Parity Version
Johns-MacBook-Pro:~ johnwhitton$ parity --version
Parity
  version Parity/v1.2.0-unstable-94ec245-20160526/x86_64-macos/rustc1.8.0
Copyright 2015, 2016 Ethcore (UK) Limited
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf.

### MIST Version
Johns-MacBook-Pro:Ethereum-Wallet-macosx-0-7-4 johnwhitton$ pwd
/Users/johnwhitton/Downloads/Ethereum-Wallet-macosx-0-7-4
Johns-MacBook-Pro:Ethereum-Wallet-macosx-0-7-4 johnwhitton$ more version
v0.7.4

### Parity running locally
Johns-MacBook-Pro:~ johnwhitton$ parity --testnet --geth --pruning "fast" --force-sealing --rpc --maxpeers "100" --cache "3062" --author "cff9b7b5144f3f625b4ceb287d760d16b8a042d7" --webapp-port "8080" --webapp-user "admin" --webapp-pass "admin" --rpccorsdomain "*"
2016-05-27 09:02:04 Starting Parity/v1.2.0-unstable-94ec245-20160526/x86_64-macos/rustc1.8.0
2016-05-27 09:02:04 Configured for Morden using "Ethash" engine
2016-05-27 09:02:05 Public node URL: enode://f4b73c9d11a780293ff0ca7afa12c67797afdc33a4797a7c2ecc5b87e455b32a8b9e9804f2004072bac38350bf82d52521d1a09590d2079705fc8357aef2bf9c@0.0.0.0:30303
2016-05-27 09:02:05 Using a conversion rate of Ξ1 = US$10.93 (21783644000 wei/gas)

#### Parity Accounts
Johns-MacBook-Pro:~ johnwhitton$ parity account list
Known addresses:
690b8b3441f6cf497a2ce47507a4dae6de6c7637
1d999729bbbda3c29712148c3e077b590c7244c2
cf72c623611cde63535ebaf8d72ebe5a58e2de12
f320af2b1c1663cb16f15b06fc325a87b645a3f1
cff9b7b5144f3f625b4ceb287d760d16b8a042d7
cc009d7b6ae80a1a745ebc67c4740a66590e

### MIST LOG
[MISTLog.txt](https://github.com/ethcore/parity/files/286925/MISTLog.txt)

Above is a link to the log which I attached. I believe the key information is
_[2016-05-27 09:12:38.711] [INFO] ipcProviderBackend - IPCSOCKET 8 TIMEOUT ERROR Couldn't decode data: {"jsonrpc":"2.0","result"_

**Comment by NikVolf** [comment]
probably related to the fact that testnet ipc address is different for geth
