### ISSUE TITLE
"Installable" dapps

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1176]
- [x] - Resolving from URLHint
- [x] - Fetching ZIP
- [x] - Validating bundle
- [x] - Unpacking: serving from memory / installing to FS
- [x] - https support [rustls](https://github.com/ctz/rustls/blob/master/examples/tlsclient.rs)
- [x] - render special page while syncing
- [x] - limit number of cached dapps to prevent spamming
- [x] - address content (`hintURL`)
- [x] - get rid of "Dapp download in progress page" and use multi-listener instead.

**Comment by gavofyork** [comment]
To be done only at #1183.

**Comment by tomusdrw** [comment]
Each dapp could be linked to git repository. It would allow easy installation (just pasting the link) and upgrades/new version detection (compare hashes, update repo).

**Comment by rphmeier** [comment]
That opens up to MITM attacks where an attacker can push a bad version of a dapp to end users unsuspectingly

**Comment by tomusdrw** [comment]
We can rely on centralized web2.0 authority (`https`) or validate server (`git+ssh`)

**Comment by gavofyork** [comment]
should just be namereg + urlhint contracts. can use github raw dumps for publishing assets.

**Comment by tomusdrw** [comment]
All features ready.
