### ISSUE TITLE
eth_syncing / web3_eth_issyncing stays in 'syncing' status

### ISSUE THREAD

**Issue by jorisbontje** [ethcore/parity#1179]
Follow up after #1110: once the syncing is done, `web3.eth.isSyncing` keeps reporting a syncing object, rather than returning `false` to indicate that the syncing has stopped
```
syncing Object {currentBlock: 1613660, highestBlock: 1613660, startingBlock: 1573129}
syncing Object {currentBlock: 1613660, highestBlock: 1613660, startingBlock: 1573129}
syncing Object {currentBlock: 1613660, highestBlock: 1613660, startingBlock: 1573129}
syncing Object {currentBlock: 1613660, highestBlock: 1613660, startingBlock: 1573129}
```
see https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethissyncing for expected behaviour.

**Comment by rphmeier** [comment]
I believe I have fixed the issue -- would you try against the PR branch/master once it gets merged?
