### ISSUE TITLE
eth_getTransactionReceipt should return receipt even if transaction is pending

### ISSUE THREAD

**Issue by debris** [ethcore/parity#1180]
todo:
- implement transactionReceipt for pending transaction

then...
- check if mist (or or foundation wallet) assumes that transactionReceipt == minedTransaction
- fix it, if it does

**Comment by rphmeier** [comment]
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt

I think that we do actually follow the spec. Whether we want to follow the spec is another question.

**Comment by debris** [comment]
We do, but spec is incorrect here. It was [modified](https://github.com/ethereum/wiki/wiki/JSON-RPC/_compare/f5d8c9d4c99cd3a4502eba1384e19244e1bf0e0d...88b78a4cb70ccf401c088b928365c87de45064f5) without devs [consensus](https://github.com/ethcore/parity/pull/1074#issuecomment-220182261)
