### ISSUE TITLE
Dapps from local filesystem

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1183]
make `http://fs.parity/home/gav/Chicken/index.html` work like magic.

also consider making `http://local.parity/Chicken/index.html` act equivalently to `http://fs.parity/home/gav/.parity/dapps/Chicken/index.html`.

**Comment by tomusdrw** [comment]
1. http://fs.parity/home/gav/Chicken/index.html <-- too dangerous / insecure (`http://fs.parity/etc/passwd`)
2. `http://chicken.parity` will be pointing to `~/.parity/dapps/chicken` (if the directory exists) - this will also display the app on a home screen.
