### ISSUE TITLE
Expunge x! and *::from from codebase

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1189]
Replace:
- `x!(*)`/`*::from(*)` -> `*.into()`
- `mapx!` -> `map_into!`
- `vecx!` -> `vec_into!`

and any other uses of x!()

**Comment by rphmeier** [comment]
https://github.com/japaric/untry

this was used to traverse the AST and replace instances of `try!` with the new `?` operator. I wonder if it can be used to expunge `x!`.
