### ISSUE TITLE
running --keys-path will import keys from ~/.parity/keys into the custom keys directory

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#1213]
to reproduce:
```sh
$ parity --keys-path keystore
```

wait a little, ctrl-C.

```sh
$ ls keystore
```

For me, it's the same as my `~/.parity/keys` folder.

**Comment by gavofyork** [comment]
@NikVolf could you take a look at this one?

**Comment by NikVolf** [comment]
@gavofyork yeah already looking to this and other accounts issues

**Comment by gavofyork** [comment]
just tried to reproduce and cannot. @rphmeier are you sure it's not just re-importing your geth keys? can you try reproducing with `--no-import-keys`?

**Comment by NikVolf** [comment]
same, probably @rphmeier has the same keys in  `~/.ethereum/keystore`
and it was they that imported
