### ISSUE TITLE
Clearing browser data breaks topbar/wallet

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1223]
From Gitter:

> Clearing browser data or using private windows removes the added wallets, watched contracts and watched tokens. Not an issue if you never clear your browser data but if you like to browse in private mode then adding wallets, tokens, contracts each time you start your browser will get tedious. Is it possible to store this information outside of the browser to give it some permanence - in ~/.parity?

**Comment by tomusdrw** [comment]
Would require wallet rewrite.

**Comment by gavofyork** [comment]
Closing since we'll deprecate current wallet.
