### ISSUE TITLE
Fix cross-browser behaviour

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1224]
From Gitter: 

> Safari Technology Preview - only displays window ribbon in standard window and nothing in private window
> Safari - private window doesn’t display account and no response when icons clicked
> Chrome - private window ok but doesn't display watched tokens and wallet that were previously added in standard window
> Brave - displays ok for both standard and private tab
> Firefox - displays ok for both normal and private window

**Comment by tomusdrw** [comment]
Safari TP - should be fixed now (exceptions from local storage are handled)
Chrome - Wallet stores data in localStorage, not possible to share localStorage between private / standard mode (this requires wallet modifications / storing on parity side)

IMHO can be closed for now.

**Comment by gavofyork** [comment]
will revisit for the 1.3 release.

**Comment by gavofyork** [comment]
closing for now, at least until further reports suggest we need to revisit.
