### ISSUE TITLE
RPC is returning incorrect result of `0x`

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1243]
It should be `0x0` if the response is `0`.
See: https://github.com/ethereum/wiki/wiki/JSON-RPC#output-hex-values

Example request:
```
{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xbb9bc244d798123fde783fcc1c72d3bb8c189413","data":"0x013cf08b0000000000000000000000000000000000000000000000000000000000000001"},"latest"],"id":2}
```

**Comment by debris** [comment]
according to the spec, `eth_call` returns bytes, so the response should be `0x`, if the bytes len is 0.
