### ISSUE TITLE
Problems with MIST connecting to Parity in testnet

### ISSUE THREAD

**Issue by johnwhitton** [ethcore/parity#1260]
Hi,

This is basically the same as https://github.com/ethcore/parity/issues/1161 which was closed and assumed fixed. Although I'm not sure what testing was done there. **Please let me know if I can help in further testing You can find me on gitter**

Today I did a fresh clone and build of parity and downloaded mist 0.7.4 again.
When trying to send transactions in testnet I get see attached
[MistParityConnectionIssues.txt](https://github.com/ethcore/parity/files/310884/MistParityConnectionIssues.txt)

ipcProviderBackend - IPCSOCKET 8 TIMEOUT ERROR
ipcProviderBackend - IPCSOCKET 8 ERROR { [Error: write EPIPE]

Note I am running parity using 
a) `parity --testnet --ipcpath ~/Library/Ethereum/geth.ipc`
which places geth.ipc under _/Users/johnwhitton/Library/Ethereum/_
this is because if I run parity using 
b) `parity --testnet --geth`
it places the geth.ipc file under 
_/Users/johnwhitton/Library/Ethereum/testnet_
MIST always looks under /Users/johnwhitton/Library/Ethereum/ and so if run using a) it tries to open a second node. 
[MIST_Trying_To_Open_A_Second_Node.txt](https://github.com/ethcore/parity/files/310887/MIST_Trying_To_Open_A_Second_Node.txt)

This is a known issue documented here in geth https://github.com/ethereum/go-ethereum/issues/2629

Johns-MacBook-Pro:testnet_keys johnwhitton$ parity -v
Parity
  version Parity/v1.2.0-unstable-7064624-20160612/x86_64-macos/rustc1.9.0
Copyright 2015, 2016 Ethcore (UK) Limited
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf.
Johns-MacBook-Pro:testnet_keys johnwhitton$

**Comment by johnwhitton** [comment]
Adding logs from todays run using -l ipc=trace
[parity_ipc.txt](https://github.com/ethcore/parity/files/314432/parity_ipc.txt)
[electron.txt](https://github.com/ethcore/parity/files/314438/electron.txt)

### Version information
Johns-MacBook-Pro:testnet_keys johnwhitton$ parity -v
Parity
  version Parity/v1.2.0-unstable-7b89d6a-20160614/x86_64-macos/rustc1.9.0
Copyright 2015, 2016 Ethcore (UK) Limited
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf.
Johns-MacBook-Pro:testnet_keys johnwhitton$

**Comment by johnwhitton** [comment]
Here is the log from the new version with ipc chunking
Transactions are not being confirmed
<img width="939" alt="screen shot 2016-06-14 at 10 23 12 am" src="https://cloud.githubusercontent.com/assets/1572027/16053676/b3c2f75e-321e-11e6-82fe-597ac22b82ab.png">
[ipc.txt](https://github.com/ethcore/parity/files/314606/ipc.txt)

**Comment by gavofyork** [comment]
what transaction fees are being paid? don't forget with the ether price being high, parity will default to a fairly low `gasPrice`, probably lower than the Geth miners are configured to accept.

**Comment by johnwhitton** [comment]
Bumping the GAS price, to fastest got the transaction picked up and processed. Thanks.

**Comment by johnwhitton** [comment]
Ok to summarize it looks like there were three issues
1.  Problem when reading contact code was the initial issue which is fixed under https://github.com/ethcore/parity/pull/1285/
2. Problem sending transactions which you can workaround by increasing the gas fee to faster and relates to https://github.com/ethcore/parity/issues/1265
3. There is an issue where I get an invalid json-rpc message when trying to send from the parity-ui. (I've created https://github.com/ethcore/parity/issues/1288 for this)

Thanks @NikVolf and @gavofyork for your work on this
