### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1275]
- ~~Installs parity as a 64-bit application~~
- ~~Creates a shortcut that starts parity and opens UI in the browser~~
- On uninstall ask if blockchain and keys should be kept or deleted with a **BIG WARNING**. Keep everything by default
- ~~Also CI job should be forged to actually produce installer binaries~~
- ~~Create windows firewall exception for TCP/UDP port 30303~~
- Product version should match version in Cargo.toml
- Add a welcome page
- Use modern UI

**Comment by gavofyork** [comment]
will put this off until 1.3.
