### ISSUE TITLE
sendTransaction doesn't return useful errors

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1281]
Originally #1271.

eth_sendTransaction is returning a null TXID 0x00...00 for simple address to address sends (no contracts involved) instead of a correct hash or an error. It isn't sending a transaction in this case but it makes it so I have no idea what the error is. The sending code I'm using worked with ETH. It get's the gas price with eth_gasPrice(), eth_estimateGas() to calculate how much gas will be used, and then calls eth_sendTransaction. The estimated gas is only used to calculate the TX fee to deduct from the send and is not included in the eth_sendTransaction call, only from, to, gasPrice, and value are included in the parameters.

**Comment by gavofyork** [comment]
simple sends actually make no difference. the null return means that the transaction hash is unavailable at present (but is not, yet, in an error state) or indicates/used to indicate (@tomusdrw ?) that the key is locked.

**Comment by Crypto2** [comment]
I know the key is unlocked because I do that right before the send and personal_unlockAccount returns true. I'll keep playing with it though. I do know though the send itself doesn't go through since I've waited up to 20 minutes and it never appears in the blockchain or in pending TX lists on etherscan.

**Comment by gavofyork** [comment]
what version of parity are you on?

**Comment by tomusdrw** [comment]
Actually current RPC doesn't return any meaningful errors at all. Any error will cause `0x0` hash to be returned. The only way of knowing what happened to transaction is to run with `-lown_tx=trace`. Will fix the API to return some meaningful messages.

**Comment by Crypto2** [comment]
Was on 1.1.0, switched to latest GitHub master based on suggestion in other ticket so we'll see if it makes a difference.

**Comment by Crypto2** [comment]
With the latest master it's still having send issues, returning good TXIDs but the TXes never hit the network.

For example:
Unlocked account 0x007a5f8277749ea24d24e1ab3b1f08fd4384f1a8 for 60 seconds...
Array
(
    [from] => 0x007a5f8277749ea24d24e1ab3b1f08fd4384f1a8
    [to] => 0x8de8da8b3891197f5b6bea0a420a56dca629fe54
    [gasPrice] => 0x35fe75933
    [value] => 0x1a829b7e9961800
)
Sent 0.11939126/0.12000000 (+fee) for Ether withdrawal ID XYZ with TXID 0x7976c9c7bbc0fe7a2fd47c1a4af797d6bcf731b86f82dcf7be7ca16e091f0ad6

Output on parity with -lown_tx=trace:
2016-06-14 15:25:33 TRACE:own_tx: Importing transaction: SignedTransaction { unsigned: Transaction { nonce: 38, gas_price: 14493899059, gas: 942477, action: Call(8de8da8b3891197f5b6bea0a420a56dca629fe54), value: 119391260000000000, data: [] }, v: 27, r: 23044849726311776302730234474505197465802441666889595225391460908554994678336, s: 16552936948301853564536201502764088251021984558056826914897517942298719194382, hash: Cell { value: Some(7976c9c7bbc0fe7a2fd47c1a4af797d6bcf731b86f82dcf7be7ca16e091f0ad6) }, sender: Cell { value: None } }
2016-06-14 15:25:33 TRACE:own_tx: Imported transaction to Current (hash: 7976c9c7bbc0fe7a2fd47c1a4af797d6bcf731b86f82dcf7be7ca16e091f0ad6)

I even doubled the gasPrice to be sure it was including enough but no dice.

**Comment by Crypto2** [comment]
Spoke too soon, it did go through :)

Hopefully everything is resolved on this front now.

**Comment by tomusdrw** [comment]
Renamed the issue to address the problem more precisely. Running with `-lown_tx=trace` should not be needed to understand what happens with the transaction.

**Comment by Crypto2** [comment]
Yeah, it's still spotty at any rate. Just got a TX that returned a valid TXID but even after an hour isn't in the blockchain or seen as pending anywhere. But it is accepting and increases the transaction queue on the parity console.

**Comment by gavofyork** [comment]
possibly fixed by #1291
