### ISSUE TITLE
Problem when sending a transaction from the parity UI

### ISSUE THREAD

**Issue by johnwhitton** [ethcore/parity#1288]
When sending a transaction from the parity UI I get an invalid json-rpc message
<img width="1440" alt="screen shot 2016-06-14 at 11 19 58 am" src="https://cloud.githubusercontent.com/assets/1572027/16054636/de47a25a-3222-11e6-9ffa-450140315e57.png">
This is running on testnet using 
`parity --testnet --jsonrpc --jsonrpc-cors "http://localhost:8080" --ipcpath /Users/johnwhitton/Library/Ethereum/geth.ipc -l ipc=trace &> ~/ipc.txt`
### Version 

Johns-MacBook-Pro:testnet_keys johnwhitton$ parity -v
Parity
  version Parity/v1.2.0-unstable-7b89d6a-20160614/x86_64-macos/rustc1.9.0
Copyright 2015, 2016 Ethcore (UK) Limited
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf.

**Comment by NikVolf** [comment]
`http://localhost:808`
is that copy-paste artifact or actual parameter that was used?

**Comment by johnwhitton** [comment]
That was a copy past issue I've corrected the comment to reflect
`parity --testnet --jsonrpc --jsonrpc-cors "http://localhost:8080" --ipcpath /Users/johnwhitton/Library/Ethereum/geth.ipc -l ipc=trace &> ~/ipc.txt`

**Comment by johnwhitton** [comment]
Here is additional information from the console when running the transaction
Note : I in this instance I was running parity on PORT 8001 using
`parity --testnet --ipcpath /Users/johnwhitton/Library/Ethereum/geth.ipc --jsonrpc-cors "http://localhost:8001" --dapps-port 8001`
### Console Information
```
startNode: 7.626ms
1b1fbc3….js:401 renderAccountPage: 23.278ms
1b1fbc3….js:409 Estimated gas:  53000 null
1b1fbc3….js:409 Estimated gas:  53000 null
1b1fbc3….js:409 Estimated gas:  21000 null
1b1fbc3….js:409 Estimated gas:  21000 null
1b1fbc3….js:409 Estimated gas:  21000 null
1b1fbc3….js:409 Providing gas:  21000  + 100000
1b1fbc3….js:409 estimatedGas: 21000
1b1fbc3….js:409 Finally choosen gas 121000
1b1fbc3….js:409 Send Ether
1b1fbc3….js:409 Gas Price: 22604373007
1b1fbc3….js:409 Amount: 1000000000000000000
1b1fbc3….js:409 Error: Invalid JSON RPC response: "0x076c7cb3de9adceb177fdf79079bb04fdcb819cdc1584d009d4f0b1ea4c80027"
    at Object.InvalidResponse (http://localhost:8001/parity-utils/inject.js:5:13413)
    at Object.callbackFunc (http://localhost:8001/parity-utils/inject.js:21:19208)
    at Object.r.confirmTransaction [as onConfirm] (http://localhost:8001/parity-utils/inject.js:15:13470)
    at Object.callback (http://localhost:8001/parity-utils/inject.js:15:21515)
    at http://localhost:8001/parity-utils/inject.js:4:1230
    at http://localhost:8001/parity-utils/inject.js:21:19187
    at XMLHttpRequest.n.onreadystatechange (http://localhost:8001/parity-utils/inject.js:21:9074) undefined
```
### Code
expanding inject.jsL21:9074 points to  _t(r, e)_
```
i.prototype.sendAsync = function(e, t) {
        var n = this.prepareRequest(!0);
        n.onreadystatechange = function() {
            if (4 === n.readyState) {
                var e = n.responseText
                  , r = null ;
                try {
                    e = JSON.parse(e)
                } catch (i) {
                    r = o.InvalidResponse(n.responseText)
                }
                t(r, e)
            }
        }
        ;
```

**Comment by gavofyork** [comment]
ok it's trying to JSON parse the response string; `0x076c...0027` isn't valid JSON so it's failing. would be good to know which RPC function that it's failing on.

**Comment by johnwhitton** [comment]
My guess is [eth_sendTransaction](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction), I get the message after confirming my password for the transaction.
#### Steps to reproduce
1. Run parity `parity --testnet --jsonrpc --jsonrpc-cors "http://localhost:8080" --ipcpath /Users/johnwhitton/Library/Ethereum/geth.ipc`
2. Open up a browser on localhost:8080
3. Select the Ethereum Wallet
4. Press Send
5. Enter the accounts, Ether to send and increase the GAS
6. Confirm the pop up telling me which accounts I'm sending to and the amount
6. Enter my password to confirm the transaction **This is when the error occurs**

If you look at https://github.com/ethcore/parity/issues/1260 where transactions were sent using the downloaded MIST UI (downloaded, not the Wallet Dapp run from Parity) after @NikVolf fixed the IPC chunking and the transactions were being sent you can see the info below in the[ trace file](https://github.com/ethcore/parity/files/314606/ipc.txt) 

```
2016-06-14 10:54:52 TRACE:ipc: Request: {"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0xf320af2b1c1663cb16f15b06fc325a87b645a3f1","to":"0xCff9b7B5144F3F625B4CeB287D760d16B8a042d7","value":"0x853a0d2313c0000","gasPrice":"0x4a817c800","gas":"0x1d8a8"}],"id":778}
2016-06-14 10:54:52 TRACE:ipc: Response: {"jsonrpc":"2.0","result":"0x07ccd8cc6d113ee2f88195a91a28736c7981526239cf1b024c24beebf473e94b","id":778}
```

This was captured using
`parity --testnet --jsonrpc --jsonrpc-cors "http://localhost:8080" --ipcpath /Users/johnwhitton/Library/Ethereum/geth.ipc -l ipc=trace &> ~/ipc.txt`

However running `-l ipc=trace` doesn't provide the additional information when running the parity wallet dAPP. 

**If there is a way to capture the actual RPC call let me know and I'll retest and capture it**

**Comment by johnwhitton** [comment]
When looking at the error in the console it takes me to 

```
console.log("Gas Price: " + l),
                            console.log("Amount:", r),
                            web3.eth.sendTransaction({
                                from: c.address,
                                to: s,
                                data: m,
                                value: r,
                                gasPrice: l,
                                gas: e
                            }, function(t, a) {
                                TemplateVar.set(n, "sending", !1),
                                console.log(t, a),
                                t ? GlobalNotification.error({
                                    content: t.message,
                                    duration: 8
                                }) : (console.log("SEND simple"),
                                m = !s && u ? {
                                    contract: u,
                                    data: m
                                } : m,
                                addTransactionAfterSend(a, r, c.address, s, l, e, m),
                                FlowRouter.go("dashboard"))
                            });
```
Which if I understand it correctly comes from 
https://github.com/ethcore/parity-dapps-wallet-rs/blob/master/src/web/1b1fbc3f2c65cc5d5bdf0fa35be0d8d5d07ddccc.js
Which is a metor build of https://github.com/ethereum/mist
However I couldn't find the above code in the mist repo? 
Perhaps this is built from a branch or a fork?

**Comment by gavofyork** [comment]
could you see what geth replies with? you can just use curl and pass in:
```
{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0xf320af2b1c1663cb16f15b06fc325a87b645a3f1","to":"0xCff9b7B5144F3F625B4CeB287D760d16B8a042d7","value":"0x853a0d2313c0000","gasPrice":"0x4a817c800","gas":"0x1d8a8"}],"id":778}
```

**Comment by gavofyork** [comment]
please also compare to the [spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction) and tell me how it is non-conformant. as far as i can tell parity is perfectly compliant and it is mist/web3.js which is expecting the wrong format.

**Comment by gavofyork** [comment]
this is apparently an issue in the mist wallet code. please file there.
