### ISSUE TITLE
State DB commit failed: BaseData(NegativelyReferencedHash(...))'

### ISSUE THREAD

**Issue by 5chdn** [ethcore/parity#1292]
My parity client version 1.1.0 (binary from your website) crashes reproducably with some panic of the IO worker. I'm on ArchLinux kernel 4.5.4. Short log:

    0 ✓ user@hoster ~ $ RUST_BACKTRACE=1 parity --port 30302 --pruning basic --db-path ~/.parity-basic/  --usd-per-eth 17
    2016-06-15 08:34:30 Starting Parity/v1.1.0-beta/x86_64-linux-gnu/rustc1.8.0
    2016-06-15 08:34:30 Configured for Frontier/Homestead using "Ethash" engine
    2016-06-15 08:34:30 Public node URL: enode://e72ad6c61d440d4686cbcb31ea0fbd9e3d9356f6d6aa6cf294d0aac4133996c9f894e369cd487390c7d36385df07ee732924ae04bea5b2341a200cb6e2a3fd7d@0.0.0.0:30302
    2016-06-15 08:34:40 Using a conversion rate of Ξ1 = US$17 (14005602000 wei/gas)
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/2 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 9 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/2 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/2 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/2 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/2 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/2 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/2 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/0 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 1/1 peers, #1503088, 0+0 queued ···// mem: 0 bytes db, 7 KiB chain, 2 KiB queue, 90 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 1/1 peers, #1503280, 0+191 queued ···// mem: 0 bytes db, 69 KiB chain, 277 KiB queue, 65 KiB sync ]
    thread 'IO Worker #3' panicked at 'State DB commit failed.: BaseData(NegativelyReferencedHash(d5624200c1ac783fdc1d777f1ceae6df0e353ba5d776dd3445239ca42694ac9e))', ../src/libcore/result.rs:746
    stack backtrace:
       1:     0x555f67dae7e0 - <unknown>
       2:     0x555f67db14eb - <unknown>
       3:     0x555f67db1158 - <unknown>
       4:     0x555f67d9d6ec - <unknown>
       5:     0x555f67d9db78 - <unknown>
       6:     0x555f67dadc51 - <unknown>
       7:     0x555f67de0cdf - <unknown>
       8:     0x555f6798a71e - <unknown>
       9:     0x555f679d3bd2 - <unknown>
      10:     0x555f679c84c4 - <unknown>
      11:     0x555f679a9bac - <unknown>
      12:     0x555f67dadbdb - <unknown>
      13:     0x555f67daae1d - <unknown>
      14:     0x555f679aadd9 - <unknown>
      15:     0x555f67db0069 - <unknown>
      16:     0x7ff0c9fba473 - start_thread
      17:     0x7ff0cab4669c - clone
      18:                0x0 - <unknown>
    2016-06-15 08:35:48 Finishing work, please wait...
    2016-06-15 08:35:49 Stage 3 block verification failed for #1503090 (4383…0003)
    Error: Block(UnknownParent(db75b08425ed099b16cb1d994b7da32ba967d44cbb161c305287a429c5424da2))
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 1/1 peers, #1503280, 0+63 queued ···// mem: 0 bytes db, 190 KiB chain, 47 KiB queue, 91 KiB sync ]
    [ #1503088 f22f…65dc ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 1/1 peers, #1503280, 0+63 queued ···// mem: 0 bytes db, 190 KiB chain, 47 KiB queue, 91 KiB sync ]

It keeps coming again and again if I restart parity. Here is a full log: https://gist.github.com/5chdn/39efaf402ca2a65704960f916017821c

What else can I try? The Backtrace is not very helpful.

**Comment by gavofyork** [comment]
this is a known issue in the basic pruning algorithm. `--pruning=basic` is experimental and known to have issues. `--pruning=fast` is the most stable of the pruning algorithms and has not yet had any known bugs.  the latest `--help` documentation mentions this, though at the 1.1 release it wasn't known.

run `parity --pruning=fast` to recover.

**Comment by 5chdn** [comment]
> run `parity --pruning=fast` to recover.

ok, I'm running the client in all four pruning modes out of curiousity. I've removed the whole chain and states and resynced again and now it works.
