### ISSUE TITLE
UI hangs on initial run

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1301]
Latest master. Windows build. Completely clean install - first use. Ran `parity`, headed to 127.0.0.1:8080 and went though the key creation process.

Abnormal Parity console output:

```
2016-06-16 09:27:30 error loading key 7d9e2df55936711ba2b9588be8d9b36f: ReadError(Error { repr: Os { code: 2, message: "The system cannot find the file specified." } })
```

The UI has a blue spinner in the middle of the page, the top-bar with an account at the top-left but it otherwise completely stuck.

**Comment by NikVolf** [comment]
message about load key is unrelated, it prints (erroneously) for any key created
