### ISSUE TITLE
Prevent confusion about "block"

### ISSUE THREAD

**Issue by dsbaars** [ethcore/parity#1316]
**NOTE: This is not the place to discuss the  soft-fork itself**

In #1309 the variable "block_dao_transactions" was added. 
In the context of Ethereum and blockchain in general, this can easily be confused with blockchain blocks. 
I want to propose to use the term "reject", "refuse" or "rescue" instead to prevent this confusion.

**Comment by 1600** [comment]
agreed, because a variable name usually is conceived as a noun, though understandable, it gives people some initial confusion.

**Comment by rphmeier** [comment]
Fixed in #1324
