### ISSUE TITLE
Mist Wallet wallet-contract creation broken

### ISSUE THREAD

**Issue by Kubuxu** [ethcore/parity#1332]
I've created wallet contract and then stopped parity.

No every time I enter wallet.parity it shows transfer window that doesn't work and can't be closed.
In JS console there is `invalid address` exception shown over and over.

I tried everything including removing the whole `.parity` directory and keys, clearing caches.

**Comment by gavofyork** [comment]
Mist Wallet still very much in alpha. I don't think anyone has attempted to use the wallet-contract functionality. Will report back once we get to it.

**Comment by tomusdrw** [comment]
Wallet stores data in your browser. You should clear `localStorage` of your browser. Running your node back and refreshing the page should also solve the issue.

We plan to replace wallet in a (near) future with an implementation that's better integrated with parity.

**Comment by Kubuxu** [comment]
I also tried clearing localStorage and all those things at once, I have no idea what is going on :smile:. For now I just won't use the UI wallet.

**Comment by NikVolf** [comment]
@Kubuxu 
Last time i saw it, only clearing IndexDB entries for the site from google chrome helped
might help if you are using chrome also

**Comment by Kubuxu** [comment]
Thank you, clearing Offline storage helped on FF. For future reference: http://stackoverflow.com/a/33114180/2390806
