### ISSUE TITLE
Support executing solc for RPC code compilation

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1333]

**Comment by D-Nice** [comment]
Is this supported now, because I do still keep getting "Could not compile source code. " and "Error: Error while compiling code." dialogs when trying to compile using the parity/ethereum-wallet combo.

I'm currently running parity 1.3 and using the built-in wallet Dapp.

**Comment by rphmeier** [comment]
@D-Nice parity will just call the system `solc`, it doesn't bundle one with it. ensure that `solc` is installed and in your `PATH`. if the problem persists, please provide more details (parity version, OS) and we'll see what we can do to help.

**Comment by D-Nice** [comment]
@rphmeier Thanks for the clarification, noticed it isn't bundled that's why I was confused. Also the instructions are appreciated as well! I'll try those, and return here if there are any further issues.

**Comment by D-Nice** [comment]
@rphmeier Still having issues. I have added solc to my path variable, and was alerted of parity accessing solc (AV, and it was allowed). 

It seemed as if it was compiling the different source codes I was writing in, but then just returned the exact same errors. Also, at the bottom it indicates "We can't estimate your gas usage properly, as you need at least 1 ether in your account.". This is on the testnet, and I'm running several accounts which have more than 1 ether.

OS: Windows 7 64-bit 
Parity:  version Parity/v1.3.0-unstable-6b0749a-20160808/x86_64-windows-msvc/rustc1.10.0 (downloaded from a link in another issue, posted by you I believe)
SolC: 0.3.5-5f97274a/RelWithDebInfo-Windows/msvc/Interpreter

**Comment by rphmeier** [comment]
@D-Nice Ok thanks for checking. I'll reopen the issue until this is resolved.

**Comment by gavofyork** [comment]
there are tests for this and it works according to spec. questions on usage and calls for help with a feature should be done in a separate issue or preferably gitter.
