### ISSUE TITLE
Reserved peers

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1336]
* A file listing static (reserved) peers
* API extension to add/remove static peers and enable/disable static mode

**Comment by rphmeier** [comment]
Partially addressed by #1347

**Comment by rphmeier** [comment]
Everything but passive mode addressed by #1360

**Comment by rphmeier** [comment]
Passive mode: like accept, except disables all the sync-components of the protocol - only takes transactions, new blocks/blockhashes and passes them new blocks/blockhashes and transactions - used in periods of hightened anxiety

**Comment by gavofyork** [comment]
leave this for now. seems fine as it is
