### ISSUE TITLE
Docker brson/multirust is deprecated

### ISSUE THREAD

**Issue by kartojal** [ethcore/parity#1337]
Your docker images and Dockerfiles are using a **deprecated** Rust installation https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh , from [brson/multirust](https://github.com/brson/multirust) .

In their repo  [brson/multirust](https://github.com/brson/multirust), they have the following note at the readme.md: 

> Note: multirust is not actively maintained. Migrate to rustup.rs ([help](https://github.com/brson/multirust#migrating-to-rustup)).

Now it should be: `RUN curl https://sh.rustup.rs -sSf | sh -s -- -y ` for a silent installation, and add `/root/.cargo/bin` to the $PATH. Then you can execute `cargo build --release` and build parity.

**Comment by rphmeier** [comment]
Thanks for the issue report! We just recently migrated our build instructions in the README to rustup, and we must have missed the dockerfiles.
