### ISSUE TITLE
Panic when running HEAD

### ISSUE THREAD

**Issue by frewsxcv** [ethcore/parity#1338]
Currently on 08522eec37c0d76bc73b08b2cc405ac75de5c8e9

https://gist.github.com/frewsxcv/1ce7e1e1308e4db61e91d47007c0e7b0

If this isn't helpful or if this is a known issue, feel free to close this.

**Comment by arkpar** [comment]
fixed in #1331

**Comment by rphmeier** [comment]
Could you try testing with the `sync` branch?

**Comment by frewsxcv** [comment]
`sync` branch doesn't seem to crash.
