### ISSUE TITLE
Directory structure for DB is not created correctly.

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1366]
```
~/workspace/eth/parity [master] $ ./target/release/parity --db-path __db --pruning=fast
Adding ver.lock
Executed 1 upgrade scripts - ok
ERROR: Unexpected io error: No such file or directory (os error 2)
```

`__db` folder is created, I can also see `ver.lock` file inside, but it's empty otherwise.
Error message doesn't give much details too.

**Comment by tomusdrw** [comment]
`$ mkdir -p __db/906a34e69aec8c0d/v5.3-sec-overlayrecent` Solves the issue.

**Comment by arkpar** [comment]
Looks like it is fixed in master
