### ISSUE TITLE
Replace locks with parking_lot alternatives

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#1374]
Could be faster, might not be. Definitely needs profiling. These mutexes are supposed to be more space and time efficient, as well as consistent across platforms.

**Comment by rphmeier** [comment]
(Apparently not a drop-in replacement since they don't implement poisoning)

**Comment by arkpar** [comment]
we don't handle poisoning anyway

**Comment by rphmeier** [comment]
the problem is replacing all the `[lock() | read() | write()].unwrap()` calls while swapping out the imports. i spent about 15 minutes yesterday just trying to fix it all in util, but I didn't even get close.
