### ISSUE TITLE
Parity is not closing after CTRL+C when signer is enabled and connection is active.

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1382]
Signer should disconnect all websockets.

**Comment by tomusdrw** [comment]
Closed via #1396

**Comment by gavofyork** [comment]
Ctrl-C still doesn't work when signer active.

**Comment by gavofyork** [comment]
latest master as of 1.2.0.

**Comment by goldylucks** [comment]
works for me, parity on 1.2.0 branch

steps I took:
1. `parity --signer chain=morden`
2. open `http://127.0.0.1:8180`
3. ctrl + c

**Comment by goldylucks** [comment]
might b related:
#1435
