### ISSUE TITLE
1.2: arithmetic operation overflow

### ISSUE THREAD

**Issue by remyroy** [ethcore/parity#1390]
I left parity download the blockchain overnight and I came back with this error. I'm running it again with `RUST_BACKTRACE=1` to try and get the full backtrace.

```
thread 'IO Worker #3' panicked at 'arithmetic operation overflow', util\bigint\src\uint.rs:1137
```

Version: Parity/v1.2.0-unstable-851d09d-20160621/x86_64-windows-msvc/rustc1.9.0

**Comment by remyroy** [comment]
This might be a duplicate of #1380.

**Comment by rphmeier** [comment]
Most likely is, but let us know if the problem persists.

**Comment by gavofyork** [comment]
pretty sure it is ([fix](https://github.com/ethcore/parity/pull/1384) went in a few hours ago). please test with latest master and reopen if it happens again.
