### ISSUE TITLE
code quality tracking issue

### ISSUE THREAD

**Issue by debris** [ethcore/parity#1393]
I will list here all parts of the codebase where the code quality might be improved. This is my personal list and I understand that some changes are arguable. Also the majority of the issues listed here are *low priority* and *insignificant*.

I think that creating separate issue for each of these things is pointless, cause they are not serious issues.

----

- `util/uint.rs` as a standalone crate on `crates.io`
  - remove serde serialization from `util/uint.rs`
  - create wrapper type `Uint` in `rpc/v1/types/` implementing `serde::Serialize`/`serde::Deserialize`
- `util/hash.rs` as a standalone crate on `crates.io`
  - create `util/hash` crate
  - remove serde serialization from `util/hash.rs`
  - create wrapper type `Hash` in `rpc/v1/types/` implementing `serde::Serialize`/`serde::Deserialize`
  - figure out how to nicely convert uint to hash
- remove serde from `util` dependencies
- `util/rlp` should be a separate library and should depend only on `uint` and `hash`
  - there should be a separate type `Bytes` used for serialization of `Vec<u8>`
  - there should be no special case for serialization of `Vec<u8>`
  - `rlp::BytesEncodable` could be improved by replacing it with something like this:

  ```rust
  trait Bytes {
    type Target: Deref<Target = [u8]>
    fn encoded(&self) -> Self::Target
  }
  ```
- refactor `Header`, see #1267
- miner should lock data not code
- miner should be better integrated with POA. Currently signing block happens in method called `prepare_sealing`
- ~~client should not be templated, Verifier could be a `Box<Verifier>` instead of `PhantomData<Verifier>`~~
- since we have migrations, we should get rid of `CLIENT_DB_VER_STR`
- separate module in `ethcore` for managing path. Right now our path building is messy. It could be improved by introducing new structure. eg
  ```rust
  struct ParityDirectory {
    path: PathBuf,
  }

  impl ParityDirectory {
    fn blocks(&self) -> PathBuf {
      // extras
    }

    fn extras(&self) -> PathBuf {
      // extras
    }

    // and so on...
  }
  ```
- move `ethcore/src/db.rs` to util
- refactor of files in `parity` directory
  - we should save a file with a configuration from previous launch
  - we should not load spec if a configuration is unchanged
  - parsing configuration should be testable (at least to omit regressions)
  - there should be tests for `import`, `export`, `account`, `signer`
  - `import`, `export` should be moved to it's own module

----

Additionally I would like to propose few style guidelines (it might be worth integrating them to clippy_
- do not use `deref`/`deref_mut`.
- do not implement imported `traits` for imported `structs`

  eg.

  **BAD**
  ```rust
use util::H256;
struct MyHash;

  impl From<MyHash> for H256 {
    fn from(h: MyHash) -> H256 {
      // implementation is irrelevant
    }
  }
  ```

  **GOOD**
  ```rust
use util::H256;
struct MyHash;

  impl Into<H256> for MyHash {
    fn into(self) -> H256 {
      // implementation is irrelevant
    }
  }
  ```

- do not create multiple implementations of a single struct.

  The example below compiles fine (with warnings), but it's not a good practice.

  **BAD**
  ```rust
  struct Foo;

  impl Foo {
    fn bar() -> u8 { 1 }
  }

  impl Foo {
    fn bar() -> u8 { 2 }
  }
  ```

**Comment by rphmeier** [comment]
The multiple implementations example will compile, but there will be a name resolution error if you actually try to call `Foo::bar()`. The warnings also indicate that even this example will fail to compile in the future. Regarding multiple implementations for a struct in general, this pattern is used a couple of times in `std` (in the [vec source](https://doc.rust-lang.org/stable/src/collections/up/src/libcollections/vec.rs.html), for  example) and is useful for grouping methods and inherent impls that logically go together.

**Comment by debris** [comment]
most of the issues listed here are solved
