### ISSUE TITLE
Mist does not detect sync completion

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1404]
master branch,
After a full sync Mist still reports "0" peers connected and "Waiting for blocks.." status
Mist version 0.7.4

reported in gitter

**Comment by gavofyork** [comment]
relatedly, mist always thinks it's 90+% done since the "final block" is never more than a little bit higher than the latest block.

**Comment by arkpar** [comment]
progress update is addressed in #1411

**Comment by arkpar** [comment]
Mist appears to be working with latest master. "Waiting for blocks.." means the sync is over actually
