### ISSUE TITLE
View and fat objects should share a trait

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#143]
HeaderView & Header, TransactionView & Transaction.

**Comment by peterjoel** [comment]
I took a look at this, starting with `Header`. 

There are only three methods with identical signatures:
```Rust
pub fn hash(&self) -> H256;
pub fn number(&self) -> BlockNumber;
pub fn timestamp(&self) -> u64;
```

But there are a lot of methods that differ only in return type:
`Header` has:
```Rust
pub fn gas_limit(&self) -> &U256 { ... }
```
while `HeaderView` has:
```Rust
pub fn gas_limit(&self) -> U256 { ... }
```

Full matrix here:
https://docs.google.com/spreadsheets/d/1oVfvJZe5GbKxZXW9oidf0umTSYgw-v5KPNPYb8qDNkw/edit?usp=sharing

**Comment by gavofyork** [comment]
should probably refactor the return-by-ref functions to have an `_ref` suffix (e.g. `gas_limit_ref()`), then equalise the normal names to be return by value.

**Comment by peterjoel** [comment]
Should it be as many of the common methods as possible then?

Also, there are no methods in common at all between `Transaction` and `TransactionView`.

**Comment by peterjoel** [comment]
@gavofyork Is there a naming convention to follow for the traits? `HeaderLike`? `IsHeader`?

**Comment by gavofyork** [comment]
`IsHeader` would at least agree with `IsBlock` in block.rs

**Comment by gavofyork** [comment]
it should be the easy ones for now; i.e. where the prototype is exactly the same (except for the ref on the return).

**Comment by gavofyork** [comment]
too old and not clear this is going to be all that much use given the ref/value disconnect. closing.
