### ISSUE TITLE
Combine UI repos & streamline dev setup for UI

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1432]
There are too many UI repos leading to an unwieldy development setup for anything touching UI work:

- parity-sysui-app
- parity-sysui-chrome-extension
- parity-dapps-home
- parity-dapps-wallet
- parity-dapps-builtins
- parity-dapps-minimal-sysui
- parity-dapps-home-rs
- parity-dapps-wallet-rs
- parity-dapps-builtins-rs
- parity-dapps-minimal-sysui-rs

These two might reasonably be argued to be common-components to other projects (though until other projects use them, it may be reasonably to keep them together with the rest):
- dapps-react-ui
- eslint-config-ethcore (empty?)

Dev setup steps for topbar, wallet, extension, signer-UI, and common components should be made easier. Preferably a single repo and a single build step.

Consider placing everything in the main parity repo under `ui`.

**Comment by tomusdrw** [comment]
You forgot `parity-dapps-status` and `parity-dapps-status-rs` (not mentioning other `parity-dapps-*-rs`.

I wouldn't mix JS code with Rust code (hence don't like an idea of merging ui stuff into parity repo).
Also I wouldn't mix "compiled" JS code + Rust wrappers with source JS code (hence existence of `*-rs` repos).

IMHO the perfect setup would be:
- `parity`
- `parity-dapps-rs` (link between `parity` and `dapps`, could be merged to main repo, but compiling dapps would require whole parity to be downloaded)
- `parity-dapps-builtins-rs` (compiled JS and rust wrappers for Home, TopBar, Status, Wallet)
- `parity-ui` - non-compiled JS for Home, TopBar, Status, Wallet, Components, SysUI, Chrome Extension.

Although it's not possible to develop most of the stuff at the same time (servers / ports / setups are different for all of those) - this is the reason why initially we had separate repos for dapps.

**Comment by gavofyork** [comment]
IMO anything that is involved in the same build process to the same executable should really be in the same repo. i see no need to create artificial repo barriers based upon language. e.g. you don't use that same argument to state that JS should be kept separately to HTML or that in a Qt project the QML be kept separately to the C++.

extra repos mean extra faff. they come at a very high price in terms of developer time - had it not been for the ridiculously complex and largely undocumented task of setting up and integrating a UI build environment i would likely have contributed substantially more work into the UI and prevented the need for reporting highly detailed, yet in my eyes trivial, UI issues and wasting everyone's time.

i would go further than "not mixing compiled JS code", and not store compiled JS code. rather it should be done via a build script. rather than the process we have now of actually *committing* intermediate results into a repo to be later included by another build process. i don't know of any sensible project which splits the build and requires the devs to place intermediate results into their own set of repos.

**Comment by debris** [comment]
@tomusdrw can we close this one?

**Comment by tomusdrw** [comment]
Yes,  I think it will done as a part of @jacogr parity-js project.
