### ISSUE TITLE
Windows: Node's web3.js fails to connect to parity JSONRPC

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1438]
...but works fine with `geth attach` and in the Chrome browser console using localhost:8080's web3 object.

Also works with `-l hyper=trace`.

**Comment by arkpar** [comment]
For some reason on closing the socket TCP RST instead of TCP FIN is generated after sending all the data.  Browsers normally don't care about the RST as long as all the data is transmitted, but nodejs does.
