### ISSUE TITLE
Build issue with `std` package on ARM7

### ISSUE THREAD

**Issue by corvinux** [ethcore/parity#1443]
ot@Jolla parity]#  cargo build --release
--verbose
Compiling bitflags v0.3.3
Running `rustc /root/.cargo/registry/sr
c/github.com-1ecc6299db9ec823/bitflags-0.3.3
/src/lib.rs --crate-name bitflags --crate-ty
pe lib -C opt-level=3 -g -C metadata=9b3e62f
1670341a1 -C extra-filename=-9b3e62f1670341a
1 --out-dir /root/tmp/parity/target/release/
deps --emit=dep-info,link -L dependency=/roo
t/tmp/parity/target/release/deps -L dependen
cy=/root/tmp/parity/target/release/deps --ca
p-lints allow`
Compiling traitobject v0.0.1
Running `rustc /root/.cargo/registry/sr
c/github.com-1ecc6299db9ec823/traitobject-0.
0.1/src/lib.rs --crate-name traitobject --cr
ate-type lib -C opt-level=3 -g -C metadata=d
b2838e831a57fce -C extra-filename=-db2838e83
1a57fce --out-dir /root/tmp/parity/target/re
lease/deps --emit=dep-info,link -L dependenc
y=/root/tmp/parity/target/release/deps -L de
pendency=/root/tmp/parity/target/release/dep
s --cap-lints allow`
error: can't find crate for `std`error [E046
3]:
can't find crate for `std` [E0463]
error: aborting due to previous error
[root@Jolla parity]#
Build failed, waiting for other jobs to fini
sh...
error: Could not compile `bitflags`.

Caused by:
Process didn't exit successfully: `rustc /
root/.cargo/registry/src/github.com-1ecc6299
db9ec823/bitflags-0.3.3/src/lib.rs --crate-n
ame bitflags --crate-type lib -C opt-level=3
-g -C metadata=9b3e62f1670341a1 -C extra-fi
lename=-9b3e62f1670341a1 --out-dir /root/tmp
/parity/target/release/deps --emit=dep-info,
link -L dependency=/root/tmp/parity/target/r
elease/deps -L dependency=/root/tmp/parity/t
arget/release/deps --cap-lints allow` (exit
code: 101)ot@Jolla parity]#  cargo build --release
--verbose
Compiling bitflags v0.3.3
Running `rustc /root/.cargo/registry/sr
c/github.com-1ecc6299db9ec823/bitflags-0.3.3
/src/lib.rs --crate-name bitflags --crate-ty
pe lib -C opt-level=3 -g -C metadata=9b3e62f
1670341a1 -C extra-filename=-9b3e62f1670341a
1 --out-dir /root/tmp/parity/target/release/
deps --emit=dep-info,link -L dependency=/roo
t/tmp/parity/target/release/deps -L dependen
cy=/root/tmp/parity/target/release/deps --ca
p-lints allow`
Compiling traitobject v0.0.1
Running `rustc /root/.cargo/registry/sr
c/github.com-1ecc6299db9ec823/traitobject-0.
0.1/src/lib.rs --crate-name traitobject --cr
ate-type lib -C opt-level=3 -g -C metadata=d
b2838e831a57fce -C extra-filename=-db2838e83
1a57fce --out-dir /root/tmp/parity/target/re
lease/deps --emit=dep-info,link -L dependenc
y=/root/tmp/parity/target/release/deps -L de
pendency=/root/tmp/parity/target/release/dep
s --cap-lints allow`
error: can't find crate for `std`error [E046
3]:
can't find crate for `std` [E0463]
error: aborting due to previous error
[root@Jolla parity]#
Build failed, waiting for other jobs to fini
sh...
error: Could not compile `bitflags`.

Caused by:
Process didn't exit successfully: `rustc /
root/.cargo/registry/src/github.com-1ecc6299
db9ec823/bitflags-0.3.3/src/lib.rs --crate-n
ame bitflags --crate-type lib -C opt-level=3
-g -C metadata=9b3e62f1670341a1 -C extra-fi
lename=-9b3e62f1670341a1 --out-dir /root/tmp
/parity/target/release/deps --emit=dep-info,
link -L dependency=/root/tmp/parity/target/r
elease/deps -L dependency=/root/tmp/parity/t
arget/release/deps --cap-lints allow` (exit
code: 101)ot@Jolla parity]#  cargo build --release
--verbose
Compiling bitflags v0.3.3
Running `rustc /root/.cargo/registry/sr
c/github.com-1ecc6299db9ec823/bitflags-0.3.3
/src/lib.rs --crate-name bitflags --crate-ty
pe lib -C opt-level=3 -g -C metadata=9b3e62f
1670341a1 -C extra-filename=-9b3e62f1670341a
1 --out-dir /root/tmp/parity/target/release/
deps --emit=dep-info,link -L dependency=/roo
t/tmp/parity/target/release/deps -L dependen
cy=/root/tmp/parity/target/release/deps --ca
p-lints allow`
Compiling traitobject v0.0.1
Running `rustc /root/.cargo/registry/sr
c/github.com-1ecc6299db9ec823/traitobject-0.
0.1/src/lib.rs --crate-name traitobject --cr
ate-type lib -C opt-level=3 -g -C metadata=d
b2838e831a57fce -C extra-filename=-db2838e83
1a57fce --out-dir /root/tmp/parity/target/re
lease/deps --emit=dep-info,link -L dependenc
y=/root/tmp/parity/target/release/deps -L de
pendency=/root/tmp/parity/target/release/dep
s --cap-lints allow`
error: can't find crate for `std`error [E046
3]:
can't find crate for `std` [E0463]
error: aborting due to previous error
[root@Jolla parity]#
Build failed, waiting for other jobs to fini
sh...
error: Could not compile `bitflags`.

Caused by:
Process didn't exit successfully: `rustc /
root/.cargo/registry/src/github.com-1ecc6299
db9ec823/bitflags-0.3.3/src/lib.rs --crate-n
ame bitflags --crate-type lib -C opt-level=3
-g -C metadata=9b3e62f1670341a1 -C extra-fi
lename=-9b3e62f1670341a1 --out-dir /root/tmp
/parity/target/release/deps --emit=dep-info,
link -L dependency=/root/tmp/parity/target/r
elease/deps -L dependency=/root/tmp/parity/t
arget/release/deps --cap-lints allow` (exit
code: 101)

**Comment by gavofyork** [comment]
looks like an issue with `cargo`. try removing `~/.cargo` and retrying. @General-Beck any ideas?

**Comment by corvinux** [comment]
I've removed `~/.cargo` and tried build again with `cargo build --release --verbose`on `commit 2ef929dcbd6739188165fcc5cc8405d5f762a124`
.
.
.
cargo build --release --verbose
   Compiling void v1.0.2
     Running `rustc /root/.cargo/registry/src/github.com-1ecc6299db9ec823/void-1.0.2/src/lib.rs --crate-name void --crate-type lib -C opt-level=3 -g --cfg feature=\"std\" --cfg feature=\"default\" -C metadata=1e8d6565de5fc7d1 -C extra-filename=-1e8d6565de5fc7d1 --out-dir /root/tmp/parity/target/release/deps --emit=dep-info,link -L dependency=/root/tmp/parity/target/release/deps -L dependency=/root/tmp/parity/target/release/deps --cap-lints allow`
   Compiling traitobject v0.0.1
     Running `rustc /root/.cargo/registry/src/github.com-1ecc6299db9ec823/traitobject-0.0.1/src/lib.rs --crate-name traitobject --crate-type lib -C opt-level=3 -g -C metadata=db2838e831a57fce -C extra-filename=-db2838e831a57fce --out-dir /root/tmp/parity/target/release/deps --emit=dep-info,link -L dependency=/root/tmp/parity/target/release/deps -L dependency=/root/tmp/parity/target/release/deps --cap-lints allow`
error: can't find crate for `std` [E0463]
errorerror: aborting due to previous error
: can't find crate for `std` [E0463]
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `traitobject`.

Caused by:
  Process didn't exit successfully: `rustc /root/.cargo/registry/src/github.com-1ecc6299db9ec823/traitobject-0.0.1/src/lib.rs --crate-name traitobject --crate-type lib -C opt-level=3 -g -C metadata=db2838e831a57fce -C extra-filename=-db2838e831a57fce --out-dir /root/tmp/parity/target/release/deps --emit=dep-info,link -L dependency=/root/tmp/parity/target/release/deps -L dependency=/root/tmp/parity/target/release/deps --cap-lints allow` (exit code: 101)

**Comment by rphmeier** [comment]
So this almost certainly is a `rustc` or `cargo` issue -- it seems that you don't have a `libstd`. Could you tell us how you installed rust?

**Comment by General-Beck** [comment]
what system? please show the output from the following commands
`cargo -V` `rustc -V` `rustup show`

**Comment by corvinux** [comment]
I have unofficial build of rustc and cargo, the only build  which i can run on my Sailfish OS  Jolla Phone at the moment. I've cross-compiled rust-std-1.11.0-dev-armv7-unknown-linux-gnueabihf.tar.gz. 
`rustc -Vv`
rustc 1.11.0-dev (623af22b9 2016-05-28)
binary: rustc
commit-hash: 623af22b9af0c31d9797211dca7399418b52ba61
commit-date: 2016-05-28
host: arm-unknown-linux-gnueabihf
release: 1.11.0-dev
`cargo -V`
cargo 0.11.0

**Comment by petevine** [comment]
Hi @corvinux, the error you're seeing is a simple `rustc` installation issue (you probably changed the rustlib directory structure) and you shouldn't even be able to compile a hello world successfully so it's not related to building parity in any way.

Try my last [build](https://www.dropbox.com/s/esfhr8erg8kyhoe/rust-nightly-armv7.tar.xz?dl=0); it's supposed to work simply by uncompressing the archive.

**Comment by corvinux** [comment]
@petevine, Hi,
I already did exactly that, and now I'm compiling, ...waiting what will happen.

**Comment by rphmeier** [comment]
@corvinux Any update?

**Comment by gavofyork** [comment]
assuming fixed due to inactivity.
