### ISSUE TITLE
Support for rocksdb column families

### ISSUE THREAD

**Issue by debris** [ethcore/parity#1455]
docs - https://github.com/facebook/rocksdb/wiki/Column-Families

list of possible usecases (might be incomplete)
- blockchain's extras
- transaction traces
- [archivedb's aux](https://github.com/ethcore/parity/pull/1452#discussion_r68555411)

**Comment by debris** [comment]
@tomusdrw was this one done recently?

**Comment by rphmeier** [comment]
I think it was #1741
