### ISSUE TITLE
Friendly name can't update in webinterface

### ISSUE THREAD

**Issue by kholbekj** [ethcore/parity#1499]
<img width="225" alt="parity_home" src="https://cloud.githubusercontent.com/assets/2786571/16488928/466da002-3ed3-11e6-852a-3307e816f6eb.png">

The "Account 3" Value cannot be changed, as whenever i try to update the value it reverts quickly to "Account 3".

**Comment by kholbekj** [comment]
This only seems to apply when using the cogwheel dropdown.

**Comment by gavofyork** [comment]
Moving to https://github.com/ethcore/parity-ui/issues/20
