### ISSUE TITLE
Set a timeout for ETH price lookup

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1519]
Start can be delayed by 10-15 minutes if there is a firewall blocking access to price lookup URL.

**Comment by rphmeier** [comment]
Don't we base gasPrice on the price info if the user doesn't? If there is no user-specified gas price and this request fails, it should make them specify one.

**Comment by arkpar** [comment]
Price lookup is done by default. And if it fails price is reset to some hardcoded value.

**Comment by NikVolf** [comment]
#1526
