### ISSUE TITLE
update build scripts

### ISSUE THREAD

**Issue by debris** [ethcore/parity#1603]
Since #1566 Node.js is a required dependency. We need to update the following build scripts:

- [x] [brew](https://github.com/ethcore/homebrew-ethcore/)
- [ ] [install-parity.sh](https://github.com/ethcore/parity/blob/master/install-parity.sh)
- [ ] [install-deps.sh](https://github.com/ethcore/parity/blob/master/install-deps.sh)
- [ ] [dockerfiles](https://github.com/ethcore/parity/tree/master/docker)

If I missed anything, please add it here

**Comment by tomusdrw** [comment]
Won't be needed in few days.

**Comment by gavofyork** [comment]
not needed now, i guess.
