### ISSUE TITLE
Build Ethash DAG size table at runtime

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#161]

**Comment by peterjoel** [comment]
May I take this task please?

**Comment by NikVolf** [comment]
sure, Peter, you are welcome

**Comment by peterjoel** [comment]
I presume the best place to implement them would be directly inside the existing `get_data_size` and `get_cache_size` functions of `ethash/compute.rs`.

As for tests, should I compare against the full known 2048 blocks, or just a selection of values?

**Comment by gavofyork** [comment]
tests should run fairly quickly. maybe just a well chosen selection would be sufficient?

**Comment by peterjoel** [comment]
`compute.rs` has tests in the same file. Should I continue that?

**Comment by NikVolf** [comment]
yeah, no standards about it so far

**Comment by gavofyork** [comment]
yes that's pretty much the convention we're following currently.
