### ISSUE TITLE
Backport #1548 to beta

### ISSUE THREAD

**Issue by jmahhh** [ethcore/parity#1617]
Parity/v1.2.2-beta-ef124fa-20160712/x86_64-macos/rustc1.10.0

Just a heads up. 
Trying out `parity --chain` using latest `morden.json`.

Adding `daoRescueSoftFork` back in works.

**Comment by gavofyork** [comment]
thanks; just needs a backport of the DSF removal.

**Comment by gavofyork** [comment]
should be fixed with #1628.
