### ISSUE TITLE
sendTransaction crashes on invalid input

### ISSUE THREAD

**Issue by bas-vk** [ethcore/parity#1673]
I'm working on an EIP which standardizes the RPC error codes and was playing with parity to see how it acts on invalid input. When the `to` field in an transaction object is an empty string parity crashes.

Example request:
`curl -X POST --header 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_sendTransaction", "params": [{"from": "0x05cdaa1c70d4f894c6c8effa7bded4fd7f14ec5f", "to": "", "value": "0x1"}]}' localhost:8545`

It seems to crash when the request is parsed. The from address doesn't have to be in the node.

```
thread '<unnamed>' panicked at 'begin <= end (2 <= 0) when slicing ``', src/libcore/str/mod.rs:1692
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-07-20 09:56:49 Finishing work, please wait...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', src/libcore/result.rs:788
```

```
$ parity -v
Parity
  version Parity/v1.3.0-unstable-d67369a-20160719/x86_64-linux-gnu/rustc1.12.0-dev
```

**Comment by tomusdrw** [comment]
Seems like a regression from https://github.com/ethcore/parity/issues/978 (or just related)
