### ISSUE TITLE
FatDB API

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1692]
- Query a range of account data specified by [min_address, max_addres)
- Query storage key-values for a range of addresses

**Comment by debris** [comment]
I assume, it should be exposed via json-rpc, right? How the method should look like?

**Comment by gavofyork** [comment]
- [ ] `eth_listAccounts(address_from: address, address_to: address)` returns `[address_1: address, address_2: address, ...]` It returns all addresses that have trie entries between `address_from` and `address_to`, inclusive.
- [ ] `eth_listStorageKeys(key_from: h256, key_to: h256)` returns `[key_1, key_2, ...]`  It returns all keys that have non-zero storage entries between `key_from` and `key_to`, inclusive.

**Comment by arkpar** [comment]
#3636
