### ISSUE TITLE
pls double check reported height

### ISSUE THREAD

**Issue by hdiedrich** [ethcore/parity#1713]
We are seeing a problem with *geth* – and are discussing that with the geth team – which might be triggered by parity 1.2.2-beta **reporting a wrong, too old height, that potentially also does not match the concurrently reported total difficulty.**

No hard proof but for all I saw it only ever happened with different instances of parity 1.2.2-beta as peers, while lots of other peers were also around, and it would as a consequence increase parity client's outgoing traffic a lot. Maybe you want to double check, thanks.

**Comment by arkpar** [comment]
@hdiedrich reported how? in the eth/63 protocol? which packet?

**Comment by hdiedrich** [comment]
eth/62+. I have not checked wire level. The symptoms are sufficiently complex, probably caused by more than one error in geth alone, eventually playing out between peers. Maybe you you just want to double check. Geth is being hardened against it at any rate so the superfluous traffic caused by its vulnerability and/or error will go away. The opportunity is to take a look whether parity is involved as long as it creates this obvious additional traffic.

You could see it by running one geth client in mainnet, possibly with maxpeers increased. Pretty quickly it starts to dump ignored stats other than 0. Which mean it pulls block bodies that it doesn't need. What I saw it only happens when connected to parity 1.2.2-beta.

**Comment by arkpar** [comment]
I've checked the code and there should be no cases when Parity reports blocks it does not have or sends something that was not requested. Please reopen if you have further evidence of Parity misbehaving
