### ISSUE TITLE
Using Ethereum Wallet over IPC results in 100% CPU after wallet closed

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1717]
Appears to be specific to IPC.

Reproducible on Mac.

Reported by @derhaskell.

**Comment by derhaskell** [comment]
my parity commandline is:
RUST_LOG=trace,mio=debug,network=debug,trie=info,txqueue=info parity --db-compaction hdd --geth
mio, network, trie and txqueue are really verbose and it is next to impossible to spot something odd in megabytes of scrolling logs.
debug loglevel doesn't show an obvious error

**Comment by arkpar** [comment]
@derhaskell what's your OS?

**Comment by NikVolf** [comment]
@derhaskell please check the latest master, there was a fix there

**Comment by derhaskell** [comment]
unfortunately this didn't fix it. As soon as i quit Ethereum Wallet CPU cpu usage is at 100% (of 1 core out of 8).

**Comment by NikVolf** [comment]
@derhaskell 
ok, finally managed to reproduce and fixed it
thanx for reporting!

**Comment by derhaskell** [comment]
fix confirmed. thanks!
