### ISSUE TITLE
Tracing should include CALLCODE and DELEGATECALL

### ISSUE THREAD

**Issue by ppratscher** [ethcore/parity#1723]
Currently the tracing api only returns traces for the first level of calls.

E.g. the tx 0x280f0cee8e1385e127a4d92881044fb1850d3e1edc8031a9076576f52a02b342 has calls up to 5 levels deep as it can be seen at http://etherscan.io/tx/0x280f0cee8e1385e127a4d92881044fb1850d3e1edc8031a9076576f52a02b342

Yet the tracing api just return one single call:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"trace_transaction","params":["0x280f0cee8e1385e127a4d92881044fb1850d3e1edc8031a9076576f528545 -H "Content-Type: application/json"
{"jsonrpc":"2.0","result":[{"action":{"call":{"from":"0xb834e3edfc1a927bdcecb67a9d0eccbd752a5bb3","gas":"0x213ea8","input":"0x61461954","to":"0x2394d2200903f311222a9b66d89129cbebf929e6","value":"0x00"}},"blockHash":"0x88b56d87e0229dc5360d0ebaa1ad3a28a0df5c71247b79dfb6e3038161b2d13c","blockNumber":"0x0b94b3","result":{"call":{"gasUsed":"0x10bf7d","output":"0x"}},"subtraces":"0x00","traceAddress":[],"transactionHash":"0x280f0cee8e1385e127a4d92881044fb1850d3e1edc8031a9076576f52a02b342","transactionPosition":"0x00"}],"id":1}
```

**Comment by mtbitcoin** [comment]
I can confirm that this is an issue too.

**Comment by gavofyork** [comment]
if you're building parity, you might want to try the `trace-other-calls` branch (it will require a resync, i'm afraid) to see if it has the functionality you require.

**Comment by ppratscher** [comment]
I have been testing the trace-other-calls branch. Parity did stop syncing at block #1831071 after a restart it continued the sync process.

Besides that it looks like CALLCODE and DELEGATECALL are both now traced correctly. One remark to the json format. The type of the call should be given as a value and not as a key with an empty array element:

```
"call": {
        "callType": {
          "callcode": [
            
          ]
        },
        "from": "0x2394d2200903f311222a9b66d89129cbebf929e6",
        "gas": "0x213ae8",
        "input": "0x0bd295e60000000000000000000000000000000000000000000000000000000000000003000000000000000000000000b834e3edfc1a927bdcecb67a9d0eccbd752a5bb300000000000000000000000000000000000000000000000000000000000b94b3",
        "to": "0x2394d2200903f311222a9b66d89129cbebf929e6",
        "value": "0x00"
      }
```

**Comment by ppratscher** [comment]
Edit: The new branch fails to export the traces for block 931272. Parity crashes with the following error:

```
thread '<unnamed>' panicked at 'DecodeError: RlpIsTooShort', util/src/rlp/rlpin.rs:119
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-07-27 15:10:36 Finishing work, please wait...
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', ../src/libcore/result.rs:785
```

**Comment by mtbitcoin** [comment]
I am also seeing the stopped sync on windows.
