### ISSUE TITLE
Undefined behavior in state.rs

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#1740]
`fn get` involves a transmute from `Ref` to a reference. Fixing this led to immediate errors on runtime borrow-checking violations.

There are two issues here:
  - undefined behavior on non-`#[repr(C)]` transmute
  - pointer aliasing

**Comment by rphmeier** [comment]
#1776 will fix this completely -- there was one other function with UB.

**Comment by mtbitcoin** [comment]
might be unrelated but would this cause the node to just stop synching? I am running the following build and have noticed it would just stop synching (first node) or looping at the same block (second node)

2016-07-31 21:30:27 Starting Parity/v1.3.0-unstable-dbfc5cd-20160731/x86_64-windows-msvc/rustc1.10.0
