### ISSUE TITLE
Unclean node shutdown causes crash on future startups

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#1760]
I've seen this on two different nodes (on windows with latest nightly build)

```
C:\>"C:\Program Files\Ethcore\Parity\parity.exe" --tracing on --port 30305 --jsonrpc-port
8546
2016-07-29 02:35:26 UTCStarting Parity/v1.3.0-unstable-e4f0c0b-20160728/x86_64-windows-msv
c/rustc1.10.0
2016-07-29 02:35:26 UTCUsing state DB journalling strategy fast
2016-07-29 02:35:26 UTCImport geth accounts failed. The system cannot find the path specif
ied. (os error 3)
2016-07-29 02:35:27 UTCConfigured for Frontier/Homestead using Ethash engine
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\
option.rs:325
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This occurred directly on startup, there were no background RPC calls occuring

**Comment by mtbitcoin** [comment]
I've reproduced this on 4 different nodes, it crashes at block around 800 - 900K.

**Comment by mtbitcoin** [comment]
I was able to consistently produce the issue. It looks like its due an unclean shutdown. If the node is terminated forcefully or an exception occurs midway (i.e out of memory), the next time around the node crashes upon startup

**Comment by gavofyork** [comment]
could you run with `RUST_BACKTRACE=1` set in the environment?

**Comment by mtbitcoin** [comment]
how do you set this up "RUST_BACKTRACE=1" on windows?

**Comment by mtbitcoin** [comment]
@gavofyork here you go, the issue requires one continually resync because the only way to get it running again is to start clean or use a back up

C:\Users\MT4\.cargo\bin>C:\Users\MT4\.cargo\bin\parity.exe
2016-07-29 15:58:42 Starting Parity/v1.3.0-unstable-e4f0c0b-20160728/x86_64-windows-msvc/rustc1.10.0
2016-07-29 15:58:42 Using state DB journalling strategy fast
2016-07-29 15:58:42 Import geth accounts failed. The filename, directory name, or volume label syntax is incorrect. (os error 123)
2016-07-29 15:58:43 Configured for Frontier/Homestead using Ethash engine
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:325
stack backtrace:
   0:     0x7ff65786e782 - <unknown>
   1:     0x7ff65786dd6d - <unknown>
   2:     0x7ff65784db9d - <unknown>
   3:     0x7ff657870b2b - <unknown>
   4:     0x7ff65784efff - <unknown>
   5:     0x7ff65787076c - <unknown>
   6:     0x7ff6578749a5 - <unknown>
   7:     0x7ff657874ca0 - <unknown>
   8:     0x7ff65734fbe0 - <unknown>
   9:     0x7ff6573c89be - <unknown>
  10:     0x7ff656effca7 - <unknown>
  11:     0x7ff656ef1b2f - <unknown>
  12:     0x7ff656f72bc2 - <unknown>
  13:     0x7ff65786d74c - <unknown>
  14:     0x7ff657873ee1 - <unknown>
  15:     0x7ff65786d484 - <unknown>
  16:     0x7ff657a17e27 - secp256k1_schnorr_verify
  17:     0x7ffa5b548101 - BaseThreadInitThunk

**Comment by gavofyork** [comment]
fixed (as much as we can do) in #1765.

**Comment by mtbitcoin** [comment]
noted with thanks. Will wait till the merge is completed to test

**Comment by mtbitcoin** [comment]
tested, confirmed fixed.
