### ISSUE TITLE
Standard + return format for eth_getStorageAt needs changing

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#1761]
If I issue the following command on testnet it returns only the bytes that are set, where as Geth returns all 32 hex encoded bytes.

Other getStorageAt calls in Parity return all 32 bytes..

The storage variables at this address are 3 bools tightly packed.

bool bool1
bool bool2
bool bool3

The request
```
curl http://127.0.0.1:8545/api -H "Content-Type: application/json" -X POST --data '{"id":"1","jsonrpc":"2.0","method":"eth_getStorageAt","params":["0xf0f59f3e53099272a0f69dd7653bd5f788ebc252","0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f868","latest"]}'
```
Response in Parity
```
{"jsonrpc":"2.0","result":"0x0101","id":1}
```
Response in Geth
```
{"jsonrpc":"2.0","id":"1","result":"0x0000000000000000000000000000000000000000000000000000000000000101"}
```

**Comment by gavofyork** [comment]
the [Ethereum JSONRPC Standard Specification](https://github.com/ethcore/parity/wiki/JSONRPC#eth_getstorageat) for this call states that the output should be unsized data.

the example given on the page shows a return value of a single byte:

```
{
  "id":1,
  "jsonrpc": "2.0",
  "result": "0x03"
}
```

as such i guess parity actually has the standard-compliant implementation and geth is non-standard.

that said, i'm happy to consider a proposal to alter the standard.

**Comment by slothbag** [comment]
Thank Gav, happy to raise this with the geth team, however in terms of usability for geth I can just chop up the hex string into the variables sizes (so 3x 1 byte bools) and then convert each into byte to get the value.  However with parity there is no 3rd byte, only two which makes the above approach a bit tricky.

Even though parity is not padding with zero's I would still expect the 3rd bool/byte to be present in the result?

**Comment by gavofyork** [comment]
at this level there's no distinction between the 3rd byte being zero and the 4th (unused) byte being zero. it's all just zeroes, which apparently, should be dropped.

however, i'm inclined to agree that the full 32 bytes is more useful than just the right-most non-zero bytes.
