### ISSUE TITLE
Invalid State Root Error while importing new block

### ISSUE THREAD

**Issue by ppratscher** [ethcore/parity#1785]
Latest Master (v1.3.0-unstable-7c015f0-20160731) crashes routinely with the following error:

```
thread 'IO Worker #2' panicked at 'State root of best block header always valid.: InvalidStateRoot', ../src/libcore/result.rs:785
```

Edit: Parity was synced with archive and tracing on. OS is Ubuntu.

**Comment by rphmeier** [comment]
probably related to the single DB migration

**Comment by arkpar** [comment]
Confirmed with `--pruning archive only`
Race condition on a best block which is updated before the commit to the DB. This is not an issue with `OverayRecentDB` because of the shared memory overlay
