### ISSUE TITLE
Trusted signer hangs on transaction confirm

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1796]
looks like the trusted signer module can hang when confirming a transaction on windows. Ctrl-c fails to work after confirming a transaction with the correct password.

Running master branch 1.3.0-9e5e57f.

**Comment by tomusdrw** [comment]
Having troubles to reproduce this, could it be related to large `--keys-iterations` + debug build?

**Comment by gavofyork** [comment]
i thought the same, but it was definitely a windows release build; the key file was created on geth.

**Comment by tomusdrw** [comment]
Were you using extension or `127.0.0.1:8180`? Was the transaction propagated?

Being unable to Ctrl+c might be cause by huge amount of requests coming to RPC, maybe Signer UI was spinning with fetching transactions.

**Comment by gavofyork** [comment]
i don't believe the transaction was propagated, though can't be sure because eventually tried it with signer disabled and it got through. was using 127.0.0.1:8180.

**Comment by gavofyork** [comment]
will push for later since it can't be replicated.
