### ISSUE TITLE
--datadir seems does not work with ~/path/to

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#1799]
I tried to start parity with `parity --datadir ~/path/to` and it seems option was ignored, only `.parity` dir appeared in my home directory.

During my play with parity I found that it does not expand such path correctly.

**Comment by keorn** [comment]
I am guessing latest master the same as last issue. Might be OSX, works fine on Ubuntu.

**Comment by sammy007** [comment]
This is 1.2.3 on ubuntu, will try `master` later.

**Comment by arkpar** [comment]
special symbols like "~" are expanded by shell, not parity. What shell do you use? bash?

**Comment by sammy007** [comment]
Bash.

**Comment by sammy007** [comment]
Well, I am sorry, tested 1.2.3 again on Linux it works as expected.
