### ISSUE TITLE
Console commands often throw "Parse error" (parity --geth, geth attach)

### ISSUE THREAD

**Issue by jase1981** [ethcore/parity#1805]
I have a problem with Geth attaching to Parity on Windows. When I type the commands, like eth.getBlock("latest"), it sometimes returns the correct values and other times throws "Parse Error". I created a video of the error here:

https://drive.google.com/file/d/0B6tUAs6SHb5JVEdHT0NaVG0tLWM/view

Parity v1.2.0 worked OK, the problem was introduced with Parity v1.2.1 and remains in the latest Parity v1.2.3. When I connect to v1.2.0, I get something like this:
```
D:\Programs\Ethcore\Parity120>geth attach
instance: Parity//v1.2.0-unstable-a6f7957-20160624/x86_64-windows-msvc/rustc1.9.0
coinbase: 0x0037a6b811ffeb6e072da21179d11b1406371c63
at block: 75960 (Wed, 12 Aug 2015 22:48:37 CEST)
> eth.getBlock("latest")
{
  author: "0x580992b51e3925e23280efb93d3047c82f17e038",
  difficulty: 2287719502339,
  extraData: "0x476574682f76312e302e312f6c696e75782f676f312e342e32",
  gasLimit: 3141592,
```

With v1.2.1 and newer versions, there is no info at the beginning (instance, coinbase, etc...) and the exception is thrown on command:
```
D:\Programs\Ethcore\Parity121>geth attach
> eth.getBlock("latest")
Parse error
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
```

**Comment by tomusdrw** [comment]
@NikVolf was it fixed in master?

**Comment by tomusdrw** [comment]
Confirmed (latest master + Win7)
![screenshot from 2016-08-04 10 39 23](https://cloud.githubusercontent.com/assets/581548/17395633/ce6c8e4c-5a2f-11e6-98bc-d3bd72a00c3d.png)

**Comment by NikVolf** [comment]
reproduced with the @tomusdrw help and fixed in https://github.com/ethcore/parity/pull/1839

**Comment by NikVolf** [comment]
@jase1981 
will you be so kind and perform independent check on your setup?

**Comment by jase1981** [comment]
The bug is resolved, no more "Parse errors" on my side. Thank you guys, big fan of your work!
