### ISSUE TITLE
Provided Host header is not whitelisted.

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#1812]
Is it possible to disable it completely? It only leads to pain.

**Comment by sammy007** [comment]
I tried to specify "*" and it does not work. I have several remote deployments on client machines pointed to a mining node and it's impossible for me to switch clients to parity without full whitelist.

**Comment by sammy007** [comment]
Ok, sorted out with `--jsonrpc-hosts="all"`.

**Comment by NikVolf** [comment]
related #2509
