### ISSUE TITLE
RPC eth_getBlockByNumber returns invalid block hash ocassionally

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#1815]
I've seen this happen lately, occasionally the eth_getBlockByNumber would return an incorrect block hash most likely due to a chain reorg. But even after the chain reorg has taken place the correct blockhash is still not returned by eth_getBlockByNumber. To fix this the daemon has to be restarted and only then does it return the correct values

One of the blocks i've seen this was at block #2001702 (which was also one of the blocks when there was a chain reorg/fork)

I am not able to consistently reproduce this however, as it happens randomly and  even then only during the reorgs.  

-- running--
Parity   version Parity/v1.3.0-unstable-0c7ab34-20160802/x86_64-windows-msvc/rustc1.10c

**Comment by arkpar** [comment]
Thanks for reporting, should be fixed in #1816

**Comment by gavofyork** [comment]
please check on the latest master and reopen if it is not fixed.

**Comment by mtbitcoin** [comment]
testing, its holding up so far but will further test. Will reopen if the issue persist
