### ISSUE TITLE
eth_sign is slow to respond with error on locked account and blocks RPC

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#1831]
I tried to perform `eth_sign` on locked account and it takes a lot of time to return zero hash. Not sure this is supposed behaviour.

During this time parity effectively blocks all RPC requests.

Steps to reproduce:

```
curl -X POST http://127.0.0.1:8545 --data '{"jsonrpc":"2.0","method":"eth_sign","params":["0x8a3106a3e50576d4b6794a0e74d3bb5f8c9acaab", "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"],"id":1}' -H'Content-Type:application/json'
```

in 2nd console concurrently

```
curl -X POST http://127.0.0.1:8545 --data '{"id":0,"jsonrpc":"2.0","method":"eth_getWork"}' -H'Content-Type:application/json'
```

last commit `7093651d702c90d2ec1963cc377b81dc037ff898`

OSX. Not sure about other OS.

**Comment by sammy007** [comment]
Looks like the reason is an attempt to perform `eth_sign` on locked account.

**Comment by tomusdrw** [comment]
Can you try running with `--no-signer`? `eth_sign` with Signer will block RPC until you confirm the transaction (or timeout is reached).
Are you manually confirming those `eth_sign` requests or would you rather prefer them being ignored?

**Comment by sammy007** [comment]
Yep it's fast with `--no-signer`. I have no idea what signer is tbh but I think default must not block whole RPC server.

**Comment by sammy007** [comment]
> Are you manually confirming those eth_sign requests or would you rather prefer them being ignored?

I don't understand, I just use this call to check if account is unlocked before sending any payouts.

**Comment by tomusdrw** [comment]
So you should be using `--no-signer` then. With Signer `eth_sign` will wait until you manually confirm/unlock account using interface at `http://127.0.0.1:8180` or [Chrome Extension](https://chrome.google.com/webstore/detail/parity-ethereum-integrati/fgodinogimdopkigkcoelpfkbnpngalc)

Signer is disabled when using `--unlock` or `--geth` flag (or `--no-signer` obviously).

**Comment by sammy007** [comment]
Ok but why it blocks whole rpc server calls like `eth_getWork`?

**Comment by tomusdrw** [comment]
RPC server is currently single threaded (using `async` hyper), `eth_sign` and `eth_sendTransaction` are blocking the thread waiting for a confirmation to maintain backward compatibility with dapps relying on those requests to have account unlocked. 
The issue has been raised internally couple of times, we're thinking about a better solution.

**Comment by arkpar** [comment]
@tomusdrw Is there a way to check if the account is unlocked using RPC only and you don't know in advance what combination of flags the node is running with?

**Comment by sammy007** [comment]
@arkpar I did a research of rpc calls available in geth before I ended up with `eth_sign` trick, there is no way, if there is a way only in parity it does not make sense because solution must be common.

**Comment by tomusdrw** [comment]
AFAIK `eth_sign` is the only way. We may introduce a method like this (to detect permanently unlocked accounts) and perhaps submit PR to geth as well.

**Comment by sammy007** [comment]
It's better to disable signer by default maybe cuz it's unusual feature and no one actually knows what is it.

**Comment by gavofyork** [comment]
if you want the equivalent (substandard, insecure) broken behaviour that geth offers, please run with `--geth`.
