### ISSUE TITLE
eth_call does not support block numbers

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1835]
Explicit panic at `impls/eth.rs#660`

**Comment by AlexeyAkhunov** [comment]
To reproduce, I ran parity in one terminal like this:
`parity --tracing on'`
then, in another terminal, I executed this:
`url -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xbb9bc244d798123fde783fcc1c72d3bb8c189413","data":"0x70a08231000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c189413"},"0x01d4c00"], "id":0}' -H "Content-Type: application/json" localhost:8545`
The should return the amount of DAO tokens owned by DAO itself at the moment of the hard-fork (block 1920000). Instead, parity panics and produces this backtrace:

`thread '<unnamed>' panicked at 'Num(1920000)', rpc/src/v1/impls/eth.rs:545
stack backtrace:
   1:        0x1038c590b - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:        0x1038ca625 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:        0x1038ca25e - std::panicking::default_hook::hf3839060ccbb8764
   4:        0x1038b2327 - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:        0x1038cabe6 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:        0x1038b3198 - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:        0x102f7830a - _<jsonrpc_core..io..DelegateMethod<T, F> as jsonrpc_core..commander..MethodCommand>::execute::h67589b6ccd768b02
   8:        0x103869a55 - jsonrpc_core::commander::Commander::execute_method::h9e25657bf724b799
   9:        0x10386b406 - jsonrpc_core::request_handler::RequestHandler::handle_call::ha8bf31e8ef70469a
  10:        0x10386a689 - jsonrpc_core::request_handler::RequestHandler::handle_request::ha314c4384c33c6b4
  11:        0x1038915a0 - jsonrpc_core::io::IoHandler::handle_request::heef9a05d15d04550
  12:        0x1031f3732 - _<ServerHandler as hyper..server..Handler<hyper..net..HttpStream>>::on_request_readable::h6c488bd2eecafc35
  13:        0x10320c438 - _<hyper..http..conn..ConnInner<K, T, H>>::read::h32941cc7e236b298
  14:        0x10320ca05 - _<hyper..http..conn..ConnInner<K, T, H>>::read::h32941cc7e236b298
  15:        0x10320cfe1 - _<hyper..http..conn..ConnInner<K, T, H>>::read::h32941cc7e236b298
  16:        0x10320c1e3 - _<hyper..http..conn..ConnInner<K, T, H>>::on_readable::h77f5af1168587579
  17:        0x10320926f - _<hyper..http..conn..Conn<K, T, H>>::ready::hfe4708f0700e09b8
  18:        0x103200643 - _<mio..event_loop..EventLoop<H>>::run_once::hde99fd0ac0bf9605
  19:        0x1031ff32a - hyper..server..ServerLoop<hyper..net..HttpListener, [closure@.brew_home$u2f$.multirust$u2f$toolchains$u2f$stable$u2f$cargo$u2f$git$u2f$checkouts$u2f$jsonrpc.http.server.67dcc044a40796d0$u2f$master$u2f$src$u2f$lib.rs.259.62.$u20$262.4$u20$panic_for_server.std..sync..Arc$LT$std..sync..Mutex$LT$std..option..Option$LT$Box$LT$std..ops..Fn$LP$$RP$$u20$$u2b$$u20$Send$u20$$u2b$$u20$$u27$static$GT$$GT$$GT$$GT$$C$$u20$jsonrpc_handler.std..sync..Arc$LT$jsonrpc..IoHandler$GT$$C$$u20$cors_domains.std..vec..Vec$LT$hyper..header..AccessControlAllowOrigin$GT$$u5d$$GT$::drop.15733::hb81bb0cea8afbf4c
  20:        0x10321ac0b - std::panicking::try::call::h3957905f38ee45c3
  21:        0x1038cd74b - __rust_try
  22:        0x1038cd6e5 - __rust_maybe_catch_panic
  23:        0x10321ae9a - _<F as std..boxed..FnBox<A>>::call_box::h3bd98e8f1867207f
  24:        0x1038c9648 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  25:     0x7fff94ee099c - _pthread_body
  26:     0x7fff94ee0919 - _pthread_start
2016-08-04 00:16:26 Finishing work, please wait...
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', ../src/libcore/result.rs:785
stack backtrace:
   1:        0x1038c590b - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:        0x1038ca625 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:        0x1038ca25e - std::panicking::default_hook::hf3839060ccbb8764
   4:        0x1038b2327 - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:        0x1038cabe6 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:        0x1038b3198 - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:        0x1038ca83f - rust_begin_unwind
   8:        0x1038f1180 - core::panicking::panic_fmt::h93df64e7370b5253
   9:        0x103519e59 - core::result::unwrap_failed::h8e265df2c0afe9c7
  10:        0x103519d80 - hyper::server::Listening::close::h1a0fcc9c4be9b0a2
  11:        0x10321b2c8 - _<Server as std..ops..Drop>::drop::he2b73f53910e2763
  12:        0x102f0cca6 - parity::execute_client::h564143ec7aba606a
  13:        0x102ef7541 - parity::execute::h4228f2b3aef67c46
  14:        0x102ef3ccf - parity::main::hc0b8b9a4c77213f8
  15:        0x1038c9e2d - std::panicking::try::call::hbbf4746cba890ca7
  16:        0x1038cd74b - __rust_try
  17:        0x1038cd6e5 - __rust_maybe_catch_panic
  18:        0x1038c9c51 - std::rt::lang_start::hbcefdc316c2fbd45
`

**Comment by tomusdrw** [comment]
I'm working on this. Please note that the call will be possible only when running with `--pruning=archive` otherwise it's not possible to re-create state for blocks over >1k distant from latest block (because of state pruning).

**Comment by AlexeyAkhunov** [comment]
Ok, thank you very much. I will add --pruning=archive next time I run it

**Comment by gavofyork** [comment]
@tomusdrw while you're at it, probably worth putting in historical block support for nonce, storage, balance & code. You might find `Client::state_at_beginning`/`Client::state_at` helpful.

**Comment by tomusdrw** [comment]
Sure, but it seems it's already implemented by @rphmeier afair. It's just eth_call that's left.

**Comment by gavofyork** [comment]
ahh cool
