### ISSUE TITLE
Spec loading incorrect json results in the SIGILL: illegal instruction

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#1840]
example would be 
```
Spec::load(&vec![])
```

**Comment by rphmeier** [comment]
i only observed this in testing mode, unfortunately. i have no idea what leads to it.

**Comment by NikVolf** [comment]
So the problem actually is in the test setup, yep
Probably caused by panichandler there
failed to reproduce in tests dedicated to spec itself 
Not worse putting it it in 1.3 or whatever
