### ISSUE TITLE
Wrong version on status page

### ISSUE THREAD

**Issue by nerdralph** [ethcore/parity#1860]
http://127.0.0.1:8080/home/ says:
"Status Page for Parity 0.6.0"
I'm running v1.2.3-beta

**Comment by rphmeier** [comment]
This is the version of the status page itself: https://github.com/ethcore/parity-ui/blob/master/status/Cargo.toml#L4

**Comment by nerdralph** [comment]
It's bad user interface design if you are exposing internal component versions.

**Comment by gavofyork** [comment]
agreed.

**Comment by rphmeier** [comment]
The page shows the version in a much less visible font color than the issue here would imply; I agree it's a UI design issue but not a particularly severe one. Probably just a simple rephrase will provide the desired clarity.

**Comment by gavofyork** [comment]
internal versions shouldn't be exposed in the user interface.
