### ISSUE TITLE
gas price mining times wrong/misleading

### ISSUE THREAD

**Issue by nerdralph** [ethcore/parity#1864]
This is in the send funds screen. It looks like someone copied the interface from something for bitcoin.  In Eth, there is no competition for transactions being included in blocks, so the majority of transactions use .00042 eth for gas, and it has no impact on the mining time.
http://etherscan.io/txs?block=2028626

I'd get rid of that part of the interface altogether, and just use the minimum gas for all transactions.

**Comment by nerdralph** [comment]
It seems the tx fee is dynamic.  The first time I went to the "send funds" screen the slider wouldn't let me go any lower than 0.00069 eth.  The second time I can go down to .00026.

**Comment by gavofyork** [comment]
i presume you're referring to the prepackaged mist wallet software. i'm afraid we don't maintain or support it ourselves. we do try to keep the mist software up to date with the foundation's releases - i suggest you forward the issue to them.

parity does indeed provide the wallet with a "default" gas price derived from recent transactions, which would lead to your dynamic information.
