### ISSUE TITLE
Parity trusted signer issues

### ISSUE THREAD

**Issue by nerdralph** [ethcore/parity#1865]
The trusted signer interface needs improvement and integration with the send transaction interface.  Sending should have a link to the Signer UI (:8081), so sending can be done in one sequence.
The wiki says, "To ensure this is enabled run Parity with the --signer flag (or use parity ui, which enables it by default)"  This seems to be a red herring at least for the windows version, as the installed shortcut launches parity with the single arg 'ui'.  Just in case, I added the '--signer' flag and restarted it.
https://github.com/ethcore/parity/wiki/Secure-Transaction-Signer

Upon startup I got the following message:
This key code will authorise your System Signer UI: ?[1;37ms6qq-FPlp-zdyP-6Gr3?[
0m
I tried pasting the code into the parity trusted signer, but it stayed in the "not authorized" state.  I then realized the code is just 4x 4 characters separated by dashes, and the extra characters are escape codes (VT100 color codes?).  I copied the code with the escapes, and was still in the "not authorized" state.  
I then ran "parity signer new-token" from the command line, and tried the new code; still not authorized.  I tried yet another code, and still was not authorized.  I then tried going back to the Signer UI home (http://127.0.0.1:8180), and got the message, "There are no transactions requiring your confirmation."

**Comment by nerdralph** [comment]
The signer UI doesn't even seem to work after it is authorized.  Neither reject nor confirm transaction works.  For confirm transaction, after entering my password, it stays "CONFIRMING..."  I've tried with both Firefox 43 and Chrome 51.0.2704.103 under Win 7/64.

**Comment by gavofyork** [comment]
what version of Parity are you using?

there were several updates in the latest development branch of Parity - please retry with Parity 1.3.0 once release in the next few hours.

**Comment by nerdralph** [comment]
V1.2.3beta as previously mentioned:
https://github.com/ethcore/parity/issues/1860

**Comment by gavofyork** [comment]
@tomusdrw perhaps you could help diagnosing here?

**Comment by tomusdrw** [comment]
@nerdralph is there anything in the log apart from standard syncing messages?

**Comment by nerdralph** [comment]
@tomusdrw No errors/warnings in the log:
2016-08-08 10:59:48 Starting Parity/v1.2.3-beta-a9a41a0-20160731/x86_64-windows-
msvc/rustc1.9.0
2016-08-08 10:59:48 Using a conversion rate of ?1 = US$10.97 (21704215000 wei/ga
s)
2016-08-08 10:59:48 Configured for Frontier/Homestead using Ethash engine
2016-08-08 10:59:48 Public node URL: enode://5bd40835c07c29a13b333c926e7969403a1
1713c66658637174982d021512b582369083f0df750eb2c35cc147d8becd5a7cbe36231b534f5b3e
ab98e240d3194@0.0.0.0:30303
#2030520 151e.1921      0 blk/s    0 tx/s   0 Mgas/s    0/ 1 peers   #2030520
  0+    0 Qed     33 MiB db   22 KiB chain    2 KiB queue    8 KiB sync

**Comment by rphmeier** [comment]
will leave this open until @nerdralph confirms the fix.

**Comment by nerdralph** [comment]
@rphmeier Is there a new Windows binary built with this fix?  1.2.3 is still the latest I see in releases.

**Comment by rphmeier** [comment]
@nerdralph Here's the installer produced by our appveyor build for that fix: https://ci.appveyor.com/api/buildjobs/wid3mwja9hwjnyqa/artifacts/nsis/installer.exe

I've never tried those installers personally, so if that doesn't work you may need to build from source.

**Comment by nerdralph** [comment]
@rphmeier 
 Tested w/Parity/1.2.4/1.9.0/wi (release). The escape characters are still around the trusted signer token. When I do a transaction, it shows up in the Signer UI, and when I enter the account password I get a transaction ID.  If I view the tx on etherscan.io, I see it (and the # of confirmations), but it doesn't show up in the recent transactions in the wallet.

**Comment by tomusdrw** [comment]
We will be deprecating wallet pretty soon. The list of transactions for an account is a bit misleading anyway - it's a volatile state that will be removed when you clear your browser settings (or use different browser for instance) and it displays only transactions created on this particular instance of wallet.

**Comment by gavofyork** [comment]
we'll be deprecating the ethereum wallet by the time 1.4 is out. if a signer issue remains, please properly describe in a new issue and we'll get to it.
