### ISSUE TITLE
--password file contents should have whitespace trimmed

### ISSUE THREAD

**Issue by nerdralph** [ethcore/parity#1866]
Since the UI signer isn't working, I'm trying to run parity --unlock.  When I tried that I got the error "No password given..."  I then supplied my password on the cli with the --pasword flag, and got a "unable to read password file".  So I created a file with one line containing my password, and now get the "No password given..." error.  I searched the wiki for information on the format of the password file, but can't find anything.

**Comment by gavofyork** [comment]
it is perhaps not made wholly explicit by the `--help` information:

```
 --password FILE          Provide a file containing a password for unlocking
                           an account.
```

but the password file should quite literally just contain a password. the means of unlocking an account involves running:

```
parity --unlock 0xTHE_ADDRESS_HERE --password PATH_TO_FILE_CONTAINING_PASSWORD
```

if this still doesn't work, please check the password and ensure it is indeed correct for the given supplied account.

**Comment by nerdralph** [comment]
I had created the file with "echo PASSWORD > pw" from the command prompt.  @gavofyork After reading your response, and knowing that parity is developed on Linux, I thought the CR before LF might be the problem, so I checked with od -c, and found a space before the CR.  After removing the space it worked.

**Comment by gavofyork** [comment]
thanks for that - will rename the issue accordingly.

**Comment by nerdralph** [comment]
I just checked, and mist seems to let you use passphrases, so probably only trailing whitespace should be stripped.

**Comment by arkpar** [comment]
Not sure this is a good idea at all. Any character can be actually used in the password.
`echo PASSWORD>pw` should create a file with no spaces and no CR/LF

**Comment by keorn** [comment]
Apparently on Windows it [works differently](http://stackoverflow.com/questions/7105433/windows-batch-echo-without-new-line). I agree its not nice to restrict passwords but it might save some confusion to majority of people.
