### ISSUE TITLE
I can't send any ETH from Parity wallet - "Confirming..." forever

### ISSUE THREAD

**Issue by oktaryn** [ethcore/parity#1867]
Hi,
I need help with Parity wallet, using Windows version. I deposited some ETH to my wallet some time ago. Today wanted to send it from there to another address but I can't ! Parity is causing problems.

First all my attempts of sending ETH had been refusing because of some security token which I finally generated by running cmd.exe and launching parity with following syntax: parity signer new-token

I pasted that token into the form on http://127.0.0.1:8180/

And I finally saw the transaction, it's asking for the password and there is a "confirm" button. I pasted the parity password, clicked on the button, which changed to "confirming..." and that's it. Nothing happens, transfer is not starting, it stays as "confirming" forever which is very frustrating.

Which such basic thing like sending crypto is so complicated? How to retrieve my ETH ?

**Comment by nerdralph** [comment]
@oktaryn I had problems with the trusted signer function, and had to use the --unlock and --pasword options.
https://github.com/ethcore/parity/issues/1865
https://github.com/ethcore/parity/issues/1866

My transactions still aren't getting sent (though my password does get accepted in the integrated mist wallet).  I opened an issue for this since ethcore doesn't maintain mist.
https://github.com/ethereum/mist/issues/1075

**Comment by oktaryn** [comment]
@nerdralph 
I used --unlock and --pasword and my password gets accepted when truster signer interface is disabled but I still can't send anywhere my ETH :(
Transaction created as sent but it isn't and doesn't get confirmed at all.

**Comment by tomusdrw** [comment]
What Windows version are you guys running?
Were the key files created using Parity interface or were they automatically imported from Geth? If keys were imported what Geth version are you using?

As a workaround you can always try running parity without Signer support `parity.exe --no-signer`.

**Comment by gavofyork** [comment]
possibly related to #1796 .

**Comment by gavofyork** [comment]
note that it seems to be on windows in all cases.

**Comment by nerdralph** [comment]
@tomusdrw I'm running it on Win7E/64.  Keys generated by parity (don't think I've ever run geth on this machine).
Will try --no-signer.

**Comment by nerdralph** [comment]
@tomusdrw Just tried with --no-signer --unlock ... and it worked.  All my old transactions also went through (but they don't show up in latest transactions, just the last transaction is listed).  There still seems to be a UI glitch in that it doesn't refresh the transaction list in the wallet to show that it confirmed.  Going back to the status page, and then to the wallet again refreshed the list and showed the tx as confirmed.

**Comment by rphmeier** [comment]
will leave this open until @oktaryn confirms the fix.

**Comment by oktaryn** [comment]
confirmed thanks
