### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Anthony-Tatowicz** [ethcore/parity#1868]
Getting connection refused when trying to connect to dapp server, even with "--jsonrpc-hosts all" set

**Comment by tomusdrw** [comment]
Are you opening the browser at `http://localhost:8080`?
Is there anything specific in the log?
What Parity version and what platform are you using?

**Comment by Anthony-Tatowicz** [comment]
running docker container, v 1.3 beta and no trying to access it on local network I thought the accepted hosts was configurable.

**Comment by tomusdrw** [comment]
Are you trying to access RPC (:8545) or Dapps server (:8080) from host? I'm not sure if ports are exposed by default.

`--jsonrpc-hosts all` will just disable Host headers validation (without it you should be still able to access server though, but you will get `403 Forbidden`)

Perhaps you need to set `--jsonrpc-interface all` also to listen on non-local IPs?

Can you write some more details about the setup? I think I still don't fully understand what's the issue - Connection Refused usually means that nothing is listening on address/port.

**Comment by Anthony-Tatowicz** [comment]
Dapp server :8080. Yeah sure, it is the docker hub image running trusty which pulls the beta from github and builds it, I have port 8080 mapped to container 8080 and `--jsonrpc-interface all`, but I get a connection refused when trying to connect from local network computer, ie the node is running on another local computer. No critical logs, but then again the log setting is very verbose if I have up the verbosity or there is another location for the logs I need I can do that.

**Comment by tomusdrw** [comment]
If you would like to access :8080 we should focus on `--dapps-*` options (`--jsonrpc-*` are for :8545).

I think our Dockerfiles doesn't expose any ports by default (just host-container mapping is not sufficient: [docs](https://docs.docker.com/engine/reference/builder/#/expose)).

So to fix this it might be required to modify Dockerfiles to expose some ports by default.
@General-Beck does it make sense?

**Comment by Anthony-Tatowicz** [comment]
Wouldn't both 8080 and 8545 need to be accessible in order to use anything that requires a node ie like a wallet?

**Comment by Anthony-Tatowicz** [comment]
It appears the ability to enable outside connections to the dapp sever has been removed?

**Comment by tomusdrw** [comment]
As a security measure dapp server is accepting requests only to IP/hostname it's listening on.

So if you run `parity --dapps-interface local` you can only connect to `http://localhost:8080` (server is validating `Host` headers), if you run `parity --dapps-interface 192.168.0.1` you will be only allowed to access server at `http://192.168.0.1:8080`.

For RPC there is `--jsonrpc-hosts` CLI option, but we don't have similar thing for Dapps (cause we didn't find a use case).
It is fairly easy to implement such feature though, could you elaborate more on your use case?

**Comment by Anthony-Tatowicz** [comment]
Okay I understand now, the options changed a bit in an update, but this clears it up and allowed me to fix the problem, so I will close the issue. Essentially my problem was I have a computer running as local network server that has parity always in sync, that way I take the burden off my laptop and when I'm on my home network I can just open up my browser to interact with my wallet/contracts. I had this setup working, but when I updated to 1.3 things stopped working, because one of the dapps options changed.

**Comment by SinErgy84** [comment]
@Anthony-Tatowicz facing the same problem using docker-container. 
setting `--dapps-interface 0.0.0.0` but no way to connect, always 403 forbidden by browser request on docker-host machine. tried to modify browser host header by extension, but still a 403.
easiest way would be setting a mdns hostname, but facing another problem: [https://github.com/ethcore/parity/issues/1880](url)
what's your solution?
