### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by brenzi** [ethcore/parity#1869]
After running parity and syncing for a while, I repeatedly get this:
`
>RUST_BACKTRACE=1 parity
2016-08-08 07:20:20 Starting Parity/v1.3.0-unstable-e72fc53-20160805/x86-linux-gnu/rustc1.10.0
2016-08-08 07:20:20 Using state DB journalling strategy fast
2016-08-08 07:20:21 Configured for Frontier/Homestead using Ethash engine
2016-08-08 07:20:22 NAT mapped to external address 185.45.236.16:54437
2016-08-08 07:20:22 Public node URL: enode://2de406e94b3297237abf712cac9ac739c31dcea47960d0ce663562acc9c940ea11900c733ce3c132919fc165c391b0a5efbe33b1e1bbf557a9c238ad9f4f1203@185.45.236.16:54437+39761
thread 'IO Worker #1' panicked at 'index out of bounds: the len is 128 but the index is 128', ../src/libcollections/vec.rs:1176
stack backtrace:
   1: 0xb63d28c4 - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2: 0xb63d8a81 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3: 0xb63d86c1 - std::panicking::default_hook::hf3839060ccbb8764
   4: 0xb63bcc6a - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5: 0xb63d8d53 - std::panicking::begin_panic::h9bf160aee246b9f6
   6: 0xb63bdf6b - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7: 0xb63d8cdb - rust_begin_unwind
   8: 0xb6410604 - core::panicking::panic_fmt::h93df64e7370b5253
   9: 0xb64107b3 - core::panicking::panic_bounds_check::h1956babe18380ff8
  10: 0xb5f125ff - _<evm..interpreter..Interpreter<Cost>>::copy_data_to_memory::h9c3b8e7165b25dc9
2016-08-08 07:20:27 Syncing  #262834 597b…80f7      0 blk/s    0 tx/s   0 Mgas/s    1277+  245 Qed    #264358    3/ 4/25 peers     10 MiB db  177 KiB chain    1 MiB queue   23 KiB sync
2016-08-08 07:20:32 Syncing  #262834 597b…80f7      0 blk/s    0 tx/s   0 Mgas/s    4660+ 1053 Qed    #268549    3/ 4/25 peers     10 MiB db  177 KiB chain    7 MiB queue  112 KiB sync
                at ../src/libcollections/vec.rs:1176
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/evm/interpreter/memory.rs:91
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/evm/interpreter/mod.rs:541
  11: 0xb5f0e381 - _<evm..interpreter..Interpreter<Cost>>::exec_instruction::hbedecf4a2c8450dc
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/evm/interpreter/mod.rs:478
  12: 0xb5f0a68c - _<evm..interpreter..Interpreter<Cost> as evm..evm..Evm>::exec::h3bcfc0aec4a73edc
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/evm/interpreter/mod.rs:144
  13: 0xb5f4e751 - ethcore::executive::Executive::exec_vm::h4322f931bf1ae398
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/executive.rs:218
  14: 0xb5f51aaa - ethcore::executive::Executive::call::h32672a8be506f205
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/executive.rs:307
  15: 0xb5d3fe9a - ethcore::executive::Executive::transact::h433e8af3fc1eae02
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/executive.rs:197
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/executive.rs:107
  16: 0xb5cd8ed0 - ethcore::state::State::apply::hd8d501e0ab616501
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/state.rs:238
  17: 0xb5cd7f3b - ethcore::block::OpenBlock::push_transaction::h957a742b76ba92fc
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/block.rs:335
  18: 0xb5cdf19e - ethcore::block::enact::hac9457661af0b38c
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/block.rs:521
  19: 0xb5ce0288 - ethcore::block::enact_verified::h2d7e62120ff4c0b7
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/block.rs:556
  20: 0xb5d0b7fe - ethcore::client::client::Client::import_verified_blocks::h755cdff8e00d1b9d
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/client/client.rs:303
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/client/client.rs:364
  21: 0xb5d8f4a0 - _<service..ClientIoHandler as io..IoHandler<service..ClientIoMessage>>::message::h25d59d9397600ecb
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/ethcore/src/service.rs:160
  22: 0xb5d8767a - std::panicking::try::call::h0bdd9d7383ad2613
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/util/io/src/worker.rs:117
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/util/io/src/worker.rs:97
                at .cargo/git/checkouts/parity-6ba620efeffb2216/master/util/io/src/panics.rs:86
                at ../src/libstd/panic.rs:284
                at ../src/libstd/panicking.rs:272
  23: 0xb63e18b7 - __rust_try
  24: 0xb63e184d - __rust_maybe_catch_panic
  25: 0xb5d88c5b - _<F as std..boxed..FnBox<A>>::call_box::h7510a5dd1ee5649c
                at ../src/libstd/thread/local.rs:211
                at ../src/libstd/panicking.rs:235
                at ../src/libstd/panic.rs:387
                at ../src/liballoc/boxed.rs:543
  26: 0xb63d7089 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  27: 0xb550df71 - start_thread
  28: 0xb5701f8d - clone
  29:        0x0 - <unknown>
2016-08-08 07:20:36 Stage 3 block verification failed for #262836 (ba76…e0de)
Error: Block(UnknownParent(a7a653547d6210246cd978fc3efe83c57987916c65aaa6f7afb9f9955ccb9d51))
2016-08-08 07:20:36 Finishing work, please wait...

`

**Comment by tomusdrw** [comment]
Such out of bounds should be rejected earlier by gas validation or bound checking in `copy_data_to_memory`.
Seems it might be related with 32-bit system (probably some usize casting?)
