### ISSUE TITLE
parity .deb install fails on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by nerdralph** [ethcore/parity#1878]
I tried installing the .deb:
 2027  wget https://github.com/ethcore/parity/releases/download/v1.2.3/parity_linux_1.2.3-0_amd64.deb
 2029  sudo dpkg -i parity_linux_1.2.3-0_amd64.deb
 2031  sudo apt-get install -f . > install.log 2>&1

there is a surprisingly huge amount of dependencies checked, and then errors:
<pre>
[...]
parity is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 389-ds-base : Conflicts: slapd but 2.4.31-1+nmu2ubuntu8.3 is to be installed
 aide : Conflicts: aide-dynamic but 0.16~a2.git20130520-2ubuntu0.1 is to be inst
alled
        Conflicts: aide-xen but 0.16~a2.git20130520-2ubuntu0.1 is to be installe
d
 aide-dynamic : Conflicts: aide but 0.16~a2.git20130520-2ubuntu0.1 is to be installed
                Conflicts: aide-xen but 0.16~a2.git20130520-2ubuntu0.1 is to be installed
[...]
</pre>

egrep Conflicts: install.log | wc -l
reports 2297 conflicts.

**Comment by gavofyork** [comment]
not sure if we're supporting 14.04 - @arkpar ?

**Comment by arkpar** [comment]
@nerdralph Why do you think all the broken packages on your system are caused by parity? Parity's packages does not have any dependencies actually. Do you still have broken packages if you uninstall it?
I can see from the log message that `dpkg -i` succeeds with `parity is already the newest version.` There's no need to call `apt-get` after that, the package is already installed.

**Comment by nerdralph** [comment]
@arkpar Seems you are right, and I only needed to run dpkg -i.  Guess I should no better than to blindly follow instructions off stackexchange:
http://unix.stackexchange.com/questions/159094/install-from-a-deb-file-by-dpkg-i-or-by-apt
