### ISSUE TITLE
dozens of unneccessary dependencies

### ISSUE THREAD

**Issue by nerdralph** [ethcore/parity#1879]
I'm trying to build parity from source on Ubuntu 14.04 following the build instructions (cargo install --git https://github.com/ethcore/parity.git parity)  I see dozens (maybe even hundreds) of dependencies getting compiled like "Compiling winapi v0.2.6"
I'm not interested in cross-compilation, so none of the windows libs should be required on Linux.  And I suspect there are other "dependencies" being built that aren't necessary.  I don't know rust, but if it is anything like C/C++, poor coders often #include things that they don't need, or change code so that a header is no longer needed but don't delete the #include.

**Comment by rphmeier** [comment]
Most of these dependencies are transitive; an unfortunate reality of the cargo ecosystem is that lots of functionality is fragmented across dozens of tiny crates. Parity itself includes only a dozen or so dependencies directly, but most of these pull in other projects as well. A lot of these come from projects like [hyper](https://github.com/hyperium/hyper/), which we would rather not have to re-implement ourselves. 

This is beyond the scope of Parity's development, but I'm sure the other projects might be receptive to a PR that configures the `winapi` crate only to be pulled in on a windows build.

As far as "micro-crates" go, this seems to be unavoidable -- it's more of an idealogical conflict than an issue with Parity per se; I'd appreciate it if there weren't so many transitive dependencies, but most of the folks who create these tiny dependencies find it useful for their workflow.

**Comment by arkpar** [comment]
Cargo's support for per-platform dependencies is a recent addition. Not all of our dependencies use this feature yet, but it should improve eventually.
