### ISSUE TITLE
Trie node Not found panic

### ISSUE THREAD

**Issue by boehla** [ethcore/parity#1884]
Parity stopped block syncing today...
My version:
`version Parity/v1.3.0-unstable-21c65a9-20160801/x86_64-linux-gnu/rustc1.10.0`

Errorlog:
> 2016-08-09 05:07:35 Imported #2035729 7839…d14a (1 txs, 0.03 Mgas, 2.37 ms, 1.24 KiB)
> 2016-08-09 05:07:42     0/49/50 peers     25 MiB db    5 MiB chain    2 KiB queue   21 KiB sync
> 2016-08-09 05:07:52 Imported #2035730 d826…93ef (0 txs, 0.00 Mgas, 0.73 ms, 0.53 KiB)
> thread 'IO Worker #0' panicked at 'Not found! a0f530381d5fc459b1904c50baed0d4034f4b36512a9331ebf83f0ebc9849ba7', util/src/trie/triedb.rs:215
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 2016-08-09 05:07:57 Finishing work, please wait...
> 2016-08-09 05:07:57 Imported #2035731 393b…0687 (1 txs, 0.02 Mgas, 93.44 ms, 0.63 KiB) + another 1 block(s)

**Comment by boehla** [comment]
I start partiy with:
`./target/release/parity --chain=classic --author=0x123456789ABCDF`

**Comment by gavofyork** [comment]
how long was parity running before it stopped?

**Comment by boehla** [comment]
About 1 week. I compiled and started it. running fine until today.

**Comment by gavofyork** [comment]
we believe this bug has been identified and fixed in the latest codebase. please let us know if it happens again.

**Comment by boehla** [comment]
Ok,
I have done: `git pull origin master`
then comile: `cargo build --release`
Now I have the version: `Parity/v1.3.0-unstable-2f1ade8-20160808/x86_64-linux-gnu/rustc1.10.0`

Is this right?

**Comment by gavofyork** [comment]
looks good.

**Comment by boehla** [comment]
OK, Thanks very much for your fast help :+1:
