### ISSUE TITLE
Parity instability after about a week

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#1900]
I'm running Parity on testnet for testing and hitting it pretty regularly with new transactions and getStorageAt calls.  It seems after about a week something in Parity trips and it starts acting strangely, not syncing properly, slow in returning RPC calls, and Ctrl-C doesn't shutdown but instead Core dumps after a few minutes.

It seems like the "trip" is pretty quick, rather than a slow gradual decline.

Sorry I don't have any more details than this, probably makes it hard to debug.  If you have any suggestions on how to debug it further i'll try them out.

**Comment by arkpar** [comment]
@slothbag Did you happen to notice memory usage when this happens?

**Comment by slothbag** [comment]
@arkpar unfortunately I did not check the memory usage.. i'll have to check it in 7 days :)  its done it pretty reliably 3 times now.

**Comment by keorn** [comment]
@slothbag Did you experience the same effect again or can we close the issue?

**Comment by slothbag** [comment]
I haven't been able to test this recently with the attacks etc.  So much has changed in Parity has changed recently, happy to close this issue and open a new one if need be.
