### ISSUE TITLE
Documentation on the snapshot format

### ISSUE THREAD

**Issue by wanderer** [ethcore/parity#1925]
It might be nice it the snapshot was in a easily digestible and documented format

**Comment by rphmeier** [comment]
The snapshot format is still a work-in-progress as we are continuing to work on compressing and refining it further.

The rough format consists of two types of ~4MB chunks. One type contains state data (addresses, balances, contract storage and code) and the other type contains the last 30,000 blocks along with their corresponding sets of transaction receipts. Each of these chunks is compressed using specially-tailored methods as well as snappy, and is then hashed to produce a unique identifier. A manifest contains a list of all chunks, along with the block number, block hash, and state root of the snapshot. 

The single-file snapshot format consists of all chunks concatenated together, along with a modified manifest which stores offsets and lengths of each chunk in the file. This allows the snapshot file to be streamed to disk as it is produced.

We will prepare a wiki page to formalize the format once it is in a more complete and tested state.
