### ISSUE TITLE
eth_getBlockByNumber size is not a QUANTITY

### ISSUE THREAD

**Issue by keorn** [ethcore/parity#1932]
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b4", true],"id":1}' localhost:8545
```
returns size as `INT`, instead of `QUANTITY` as described [here](https://github.com/ethcore/parity/wiki/JSONRPC-eth-module#eth_getblockbynumber).

**Comment by keorn** [comment]
relevant: https://github.com/ethcore/parity/pull/1668/files

**Comment by sammy007** [comment]
Funny fact, in geth this property is `"int"` (int as string).
