### ISSUE TITLE
Renamed binary breaks start-up

### ISSUE THREAD

**Issue by petevine** [ethcore/parity#1950]
Trying to start a renamed parity binary fails:

````
thread 'main' panicked at 'Hypervisor cannot start binary ("/home/odroid/parity"): No such file or directory (os error 2)', ipc/hypervisor/src/lib.rs:155
````

Probably caused by `-C panic=abort`, never happened before.

**Comment by arkpar** [comment]
@NikVolf hypervisor should not hardcode binary name, Use the current executing instead.

**Comment by petevine** [comment]
Well, even though the hard-coded binary name is the main problem, `panic=abort` seems to play a part.

Running a regular `unwind` binary, e.g. `/path/parity-foo` instead of `./parity-foo`, doesn't crash like it should (it does when run from the current directory), instead printing this:

`ERROR: sync: Invalid node address format given for a boot node.`

**Comment by NikVolf** [comment]
@petevine about `ERROR: sync: Invalid node address format given for a boot node.`
Are you sure you sure you have no older executables named `parity` in this folder?

**Comment by petevine** [comment]
You're so right! It should've never mattered but I got confused by differently built binaries in those locations.
