### ISSUE TITLE
docker image: rpc calls for transactions, --no-signer, no execution

### ISSUE THREAD

**Issue by SinErgy84** [ethcore/parity#1952]
both rpc calls (personal_signAndSendTransaction & eth_sendTransaction) for executing transactions doesn't end in expected result: transfer of funds

both calls returns transaction hashes but they never show up on blockchain, wallet balance isn't decreased also

my docker-config:
`/build/parity/target/release/parity
       --chain
       "morden"
       --no-ipc
       --jsonrpc-interface
       "0.0.0.0"
       --jsonrpc-hosts
       "all"
       --no-dapps
       --no-signer`

tested on versions:
Parity/v1.3.0-beta-425e1ce-20160812/x86_64-linux-gnu/rustc1.10.0 (your docker build)
Parity/v1.4.0-unstable-0620a03-20160818/x86_64-linux-gnu/rustc1.10.0 (replaced git branch from beta to master)

cause of docker there is no possibility to access the signer-ui websocket endpoint by missing --signer-interface option, like --dapps-interface, to check the queue.
Unlocking a single wallet by --unlock "address" and --password "file" and executing rpc-call also ends in an transaction hash but no transfer.

**Comment by tomusdrw** [comment]
How many peers do you have? If hash is returned it means that transaction successfully got to the queue and will be propagated to other peers, and will eventually be included in mined block.

Could you also run with `-lown_tx=trace,rpc=trace` to see exactly what happens with the transaction?
(please run your node with `--unlock` option, otherwise your password might be visible in the log)

**Comment by SinErgy84** [comment]
@tomusdrw 
peers: 0/1/25 (default)
after using --peers "200" option: 0/2/200

debug response (i used `signAndSendTransaction`, but removed password from output)
`
ethereum_parity_testnet_1 | 2016-08-18 13:42:28 UTC TRACE rpc  Request: {"jsonrpc":"2.0","id":1,"method":"personal_signAndSendTransaction","params":[{"from":"0x6c637709f5ba4c1cdf758fb46b30ea4940db5d44","to":"0x25045234b17e022ba219a04031b327b0eecb2729","gas":"0x5208","value":"0x28ead22dbfc30000"},"xxxmypasswordxxx"]}

ethereum_parity_testnet_1 | 2016-08-18 13:42:30 UTC TRACE own_tx  Importing transaction: SignedTransaction { unsigned: Transaction { nonce: 1048820, gas_price: 20000000000, gas: 21000, action: Call(25045234b17e022ba219a04031b327b0eecb2729), value: 2948400000000000000, data: [] }, v: 27, r: 89102252614638569718880980131575441187131583727479414125572393476188485652962, s: 21998742262807835455112858032700903254868744009694122943286018400209828090341, hash: Cell { value: Some(ed420644794d15dfd11c3839ae73d5b67e7867d515be96ac58f023219d25eb8d) }, sender: Cell { value: None } }

ethereum_parity_testnet_1 | 2016-08-18 13:42:30 UTC TRACE own_tx  Imported transaction to Current (hash: ed420644794d15dfd11c3839ae73d5b67e7867d515be96ac58f023219d25eb8d)

ethereum_parity_testnet_1 | 2016-08-18 13:42:30 UTC TRACE own_tx  Status: TransactionQueueStatus { pending: 3, future: 0 }

ethereum_parity_testnet_1 | 2016-08-18 13:42:30 UTC DEBUG rpc  Response: Some("{\"jsonrpc\":\"2.0\",\"result\":\"0xed420644794d15dfd11c3839ae73d5b67e7867d515be96ac58f023219d25eb8d\",\"id\":1}")`

**Comment by tomusdrw** [comment]
So everything seems fine here. I think the problem might be too few connected peers (1 or 2) - you may try removing `~/.parity/network/nodes.json` if you have been connected to main network before - this should help to get more peers.

Let me know if it worked.

**Comment by SinErgy84** [comment]
@tomusdrw no improvement

1. docker pull current docker image `ethcore/parity:latest`
2. I deleted the whole mounted volume including chain / db data and started the docker container from scratch, never been connected to mainnet.
3. new transaction -> no execution
During chain sync I noticed a decrease of peers from 3/3/25 to 0/1/25 after ~160k blocks

Your current docker container from docker hub is based on v1.3.0-beta-d9d506d-20160819, so there is no `~/.parity/network/nodes.js` (screenshot 1)

Restarted same procedure with own docker container build based on v1.4.0-unstable-0620a03-20160818

Found the nodes.js (screenshot 2), there were 2 entries, one of them had a lots of failures ~765.
Unfortunately I didn't took a screenshot of the enodes.
1. new transaction -> no execution
2. deleted the nodes.json and restarted the docker container
3. new transaction -> no execution
4. peers stats increased between 0/2/25 and 0/3/25

but after deletion and restart I notice that no new `~/.parity/network/nodes.js` was created.

Comparison between ethereum clients after 10 minutes connected to morden testnet:
parity: `net_peerCount()` returns 2
eth-go-client: `net_peerCount()` returns 7, all transactions are executed immediately 

so an internal (inhouse) network problem is out of question

**Comment by tomusdrw** [comment]
Since #1996 have landed could you test if it solves the problem for you?

**Comment by SinErgy84** [comment]
@tomusdrw #1996 seems to be the fix for this problem. 

After 8 minutes `net_peerCount()` returns 10 peers, after 15 minutes even 18 peers, transactions are executed within a short time period. *thumbs up*

It would be nice if you change your dockerfile [from](https://hub.docker.com/r/ethcore/parity/~/dockerfile/) from github beta branch to master and push newer image to prevent new users facing same (already fixed) problem.

**Comment by tomusdrw** [comment]
Thanks for reporting. We're backporting changes to `beta` branch periodically - it's part of our release cycle. It should be fixed shortly.
