### ISSUE TITLE
trace_transaction failed call not reported (edge case)

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#1958]
Doing trace in geth shows a failed call http://etherscan.io/vmtrace?txhash=0xb8c08ceff57335ad2ce894aa8f83c35152431da6ea308eae94a733d689f0c05c  : invalid jump destination (PUSH1) 2 

However, tracing the same transaction hash in parity does not produce any failed calls

curl http://localhost:8546 -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"trace_transaction\",\"params\":[\"0xb8c08ceff57335ad2ce894aa8f83c35152431da6ea308eae94a733d689f0c05c\"],\"id\":1}" -H "Content-Type: application/json"

**Comment by gavofyork** [comment]
it does for me...

![image](https://cloud.githubusercontent.com/assets/138296/17815605/5cf01240-6635-11e6-86a5-ee4e53097fe7.png)

Note particularly:

![image](https://cloud.githubusercontent.com/assets/138296/17815620/6ba55ea8-6635-11e6-9d6f-025bfb7f3de7.png)

**Comment by gavofyork** [comment]
@debris could this be an issue with the trace database? i don't have a synced `--tracing` node to confirm.

**Comment by mtbitcoin** [comment]
deleting and re syncing resolved the issye
