### ISSUE TITLE
Crash on startup after restore

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#1962]
I did a `parity restore` to get the blockchain sync'd quickly and then ran `parity --fast-and-loose --db-compaction hdd` to sync up to the current block.

I then quit using ctrl-c which it said "finishing work" and then exited.

When I went to run parity again with `parity --fast-and-loose --db-compaction hdd` it panics with this error:

```
2016-08-19 12:44:14 Starting Parity/v1.3.0-beta-425e1ce-20160812/x86_64-windows-msvc/rustc1.10.0
2016-08-19 12:44:14 Using state DB journalling strategy fast
2016-08-19 12:44:14 Configured for Frontier/Homestead using Ethash engine
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:325
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

And I just saw the 'BACKTRACE' note.. i'll remember that for next time.

I'm trying to sync again without the `fast-and-loose` flag

**Comment by rphmeier** [comment]
So the first sync after the snapshot worked, but the second didn't? The backtrace will help diagnose here; but in general once you are 1000 or so blocks beyond a restoration it should have no noticeable effect on DB state.

**Comment by gavofyork** [comment]
@slothbag did the sync without `--fast-and-loose` work?

**Comment by slothbag** [comment]
Yup, I deleted the data directory and did the restore again.  then I let it sync up using just `--db-compaction hdd` and not fast-and-loose..  no problems this time.

**Comment by gavofyork** [comment]
ok - closing since it appears to be resolved.
