### ISSUE TITLE
Comprehensive tests for snapshot service and io

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#2001]
Currently missing, will need to be added as we start to expose snapshot functionality externally.

**Comment by gavofyork** [comment]
@rphmeier close this? or postpone to 1.6?

**Comment by rphmeier** [comment]
@gavofyork Can probably postpone safely and could probably be closed, snapshot creation and restoration is well tested via unit tests already. Specific usages of the snapshot service structure aren't well tested but it's relatively minor as it's not a hugely complicated piece of code.
