### ISSUE TITLE
Parity with Mist: mkr.market gas price appears as 0.0 in tx confimation window.

### ISSUE THREAD

**Issue by ferni** [ethcore/parity#2004]
I asked in Maker forums and was told to report here. In mkr.market Dapp, when depositing Eth, the window appears like this, and upon entering the password it gets stuck on "confirming...". After I cancel the window and restart Mist, I see the deposit actually went through.

After I cancel I see this error in mkr.market UI: Error: Method 'eth_sendTransaction' not allowed. But upon restarting Mist, the transaction goes through. I also tried other actions, like buying MKR with an order, and the same thing happens. Maybe it's a bug in mkr.market?

I tried with Geth and that doesn't happen.

![clipboard](https://cloud.githubusercontent.com/assets/653586/17957438/13f0bde2-6a68-11e6-8b52-eda003201305.png)

Parity/v1.3.0-beta/x86_64-linux-gnu/rustc1.10.0
Mist 0.8.2

**Comment by tomusdrw** [comment]
Most probably fixed by #2036. Please re-open if the problem persists.
