### ISSUE TITLE
Returning string from a call doesn't work correctly

### ISSUE THREAD

**Issue by karalabe** [ethcore/parity#2007]
I've added Parity to [`hive`](https://github.com/karalabe/hive) yesterday and it found a few issues out of the box. One of them is that returning strings from a contract call doesn't get passed back correctly.

The contract is as trivial as it gets:

```
contract HelloWorld {
    function Greet() constant returns (string) {
        return "Hello, World!";
    }
}
```

The tests consists of starting a Parity node, loading a pre-generated chain with the above contract already deployed and then the `Greet()` method is invoked via an RPC call.

The expected result is:

```
0000000000000000000000000000000000000000000000000000000000000020
000000000000000000000000000000000000000000000000000000000000000d
48656c6c6f2c20576f726c642100000000000000000000000000000000000000
```

The actual result is:

```
0000000000000000000000000000000000000000000000000000000000000020
000000000000000000000000000000000000000000000000000000000000000d
0000000000000000000000000000000000000000000000000000000000000000
```

You can find the full test suite at https://github.com/karalabe/hive/tree/master/validators/issues/go-ethereum-2796 .

You can also run it via `hive` with `hive --clients=parity:master --test=issues/go-ethereum-2796 --loglevel=6` (it needs [hive installed](https://github.com/karalabe/hive#installing-the-hive-validator) and building Parity takes 15 mins).

**Comment by arkpar** [comment]
Parity requires built-in contracts to be part of the genesis block spec:
https://github.com/ethcore/parity/blob/master/ethcore/res/ethereum/frontier_like_test.json#L157-L160
