### ISSUE TITLE
The eth_blockNumber RPC call seem to always return 0x00

### ISSUE THREAD

**Issue by karalabe** [ethcore/parity#2008]
This issue was found by [`hive`](https://github.com/karalabe/hive) as well, causing simulations to run indefinitely as progress isn't reported properly.

The setup is as follows: I start up one or more Parity nodes, cross connected between them, and have a few of them mine blocks. Then I poll all the nodes for their current block heights and stop when they reach a certain height (the test does a lot of extra, but that's beyod the point). However, Parity nodes always report block heights at zero.

You can find the full test suite at https://github.com/karalabe/hive/tree/master/simulators/dao-hard-fork/extradata . I'll try and prep a custom suite that targets this specific issue only as a regression suite. Will update this issue with it afterwards.

You can also run it via hive with hive --clients=parity:master --test=NONE --sim=dao-hard-fork/extradata --loglevel=6 (it needs hive installed and building Parity takes 15 mins).

**Comment by karalabe** [comment]
Seems it might be some ethminer issue. I'll close down this ticket and reopen if I figure out where th exact issue lies.

**Comment by arkpar** [comment]
ethminer thats comes with cpp-ethereum ubuntu package is known to be broken. Try building from source (works for me) or a 3rd party ppa, such as this: https://launchpad.net/~nerdralph/+archive/ubuntu/ethminer
