### ISSUE TITLE
localhost:8080/ no longer resolves

### ISSUE THREAD

**Issue by nipunn1313** [ethcore/parity#2015]
I believe the issue was caused by #1964 
I verified by checkout out before/after `124a5da75eae85aa8f6470a5cbf9e39fe0001477`
You need to clear cookies/cache in your browser to repro (I was using chrome)

`localhost:8080` does not resolve
`localhost:8080/` does not resolve
`localhost:8080/home` does not resolves
`localhost:8080/home/` resolves
`home.parity/` resolves (when set up correctly)

Trying to dig into the root of the issue. @tomusdrw

**Comment by nipunn1313** [comment]
I printed out some information for each of the cases pointing to the issue, but I haven't figured out exactly where the regression happened in the code.

```
2016-08-28 13:31:45
ENDPOINT: (None, None)
URL: Some(Url { raw: "http://localhost:8080/home", host: Domain("localhost"), port: 8080, path: ["home"], username: None, password: None })
REQ:  Request { method: Get, uri: AbsolutePath("/home"), version: Http11, headers: Headers { Host: localhost:8080, Connection: keep-alive, Cache-Control: max-age=0, Upgrade-Insecure-Requests: 1, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, Accept-Encoding: gzip, deflate, sdch, Accept-Language: en-US,en;q=0.8, } }
```

```
2016-08-28 13:30:14
ENDPOINT: (None, None)
URL: Some(Url { raw: "http://localhost:8080/", host: Domain("localhost"), port: 8080, path: [""], username: None, password: None })
REQ:  Request { method: Get, uri: AbsolutePath("/"), version: Http11, headers: Headers { Host: localhost:8080, Connection: keep-alive, Cache-Control: max-age=0, Upgrade-Insecure-Requests: 1, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, Accept-Encoding: gzip, deflate, sdch, Accept-Language: en-US,en;q=0.8, } }
```

Both of these are causing a fallthrough to "RPC by default" rather than redirecting to /home/ in https://github.com/ethcore/parity/blob/master/dapps/src/router/mod.rs#L96

Unclear what's supposed to happen. I think the path has length 1 which skips this arm
https://github.com/ethcore/parity/blob/master/dapps/src/router/mod.rs#L173

However, that arm did not change its condition in the commit which caused the regression, so there's something upstream from there changing the way the url is parsed.

**Comment by tomusdrw** [comment]
Good catch. Thanks for detailed description, I'll look into it.

**Comment by tomusdrw** [comment]
Actually there was a change in the `match` - it was expecting a path and before it was redirecting any `GET` requests.
