### ISSUE TITLE
`Err` value: "PoisonError

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#2029]
Running:
2016-09-01 02:26:26 Starting Parity/v1.4.0-unstable-e159b5f-20160901/x86_64-windows-msvc/rustc1.10.0

Error encountered:

Io(Error { repr: Custom(Custom { kind: TimedOut, error: StringError("Timed out")
 }) })', ../src/libcore\result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'IO Worker #12016-09-01 09:05:11 UTCFinishing work, please wait...' panic
ked at '
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../sr
c/libcore\result.rs:785
thread 'IO Worker #0' panicked at 'called `Result::unwrap()` on an `Err` value:
"PoisonError { inner: .. }"', ../src/libcore\result.rs:785
thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value:
"PoisonError { inner: .. }"', ../src/libcore\result.rs:785

**Comment by debris** [comment]
same as #2027
