### ISSUE TITLE
Cannot launch parity.exe, because api-ms-win-crt-runtime-l1-1-0.dll is missing

### ISSUE THREAD

**Issue by bingjiw** [ethcore/parity#2067]
After the install is completed.
Cannot launch parity.exe, because **api-ms-win-crt-runtime-l1-1-0.dll** is missing
On Windows 7 64bit Professional SP1.

> ---------------------------
> parity.exe - 系统错误
> ---------------------------
> 无法启动此程序，因为计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll。尝试重新安装该程序以解决此问题。 
> ---------------------------
> 确定   
> ---------------------------

**Comment by arkpar** [comment]
Please try installing the following windows update:
https://support.microsoft.com/en-us/kb/2999226
