### ISSUE TITLE
Owning views of blockchain data

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#2079]
Currently we have the `ethcore::views` module, for borrowing headers, blocks, transactions, etc. and decoding it partially from RLP without decoding the whole thing -- this is desirable as it requires less work and oftentimes, less space.

We also have the in-memory representations of `Header`, `Block`, `SignedTransaction`, `Uncle`, which are fully decoded. However, as we don't want to do full decoding on `BlockChain`/`Client` queries, they often return very weakly-typed `Bytes`.

I propose that we add strong, owning "view" types which wrap an internal set of bytes while not allowing access to it, and defer queries to a borrowing view. This will give us more confidence in the correctness of our blockchain-interacting code.

**Comment by tomusdrw** [comment]
:+1: It could be at least an enum for a start.

**Comment by tomusdrw** [comment]
NVM, It will be much better with `structs` :)
