### ISSUE TITLE
Ability to select & save the visible views/tabs

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2130]
Allow configuration of the UI, i.e. what will be displayed. This lays the groundwork for things like the developer pages which we (possibly) don't want on by default. Operation -

- [x] menu where the active/inactive views can be shown
- [x] user can toggle items to be visible/invisible
- [x] some items should not be selectable, e.g. signer
- [x] view settings should be saved between sessions

In action - https://youtu.be/xPSrHKB3VqU

**Comment by derhuerst** [comment]
Redgarding UX: The gears icon implies to me that there's some advanced preference panel behind this, but it's "just" showing menu items. I propose to use [the vertical ellipsis icon](https://design.google.com/icons/#ic_more_vert) here. It is commonly used for menu items that are not as important but still need to be accessible.
