### ISSUE TITLE
global & event subscriptions api, Promise-based

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2134]
As discussed in https://github.com/ethcore/parity/pull/2104 for both the `api.[subscribe|unsubscribe]` and `contract.[subscribe|unsubscribe]` endpoints, implement -

- [x] subscriptions return a Promise, success returns the subscriptionId
- [x] unsubscriptions does the same (events currently don't handle error conditions)
- [x] expand tests (actually do them)

Depends on https://github.com/ethcore/parity/pull/2104 (base to work from)

**Comment by derhuerst** [comment]
[disclaimer: streams fanboy here, just putting this here as an impulse]

I think [streams](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_readable_streams) really fit to subscriptions. In the end, afaik a subscription is just a *stream* of events, which

- may be closed/stopped
- may emit one or more errors
- hopefully emits events that happened
