### ISSUE TITLE
eth_call to builtin does not work properly

### ISSUE THREAD

**Issue by debris** [ethcore/parity#2138]
`eth_call` returns empty output (`0x`) when calling builtin. I haven't checked if it's also broken for calling contracts. It's caused by empty `&mut slice` passed as an argument to `Builtin::execute` method.

Quickfix: https://github.com/ethcore/parity/commit/fbe4a1b6fe68ae597382c0fa9ed6de0a6f894adc

**Comment by marhel** [comment]
I used this json;

    {
        "jsonrpc": "2.0",
        "method": "eth_call",
        "params": [{
            "from": "0xca807a90fd64deed760fb98bf0869b475c469348",
            "to": "0x00000000000000000000000000000000000109a0",
            "value": "0x10",
            "gas": "0x123",
            "gasPrice": "0x123",
            "data": "0x414141"
        }, "latest"],
        "id": 2
    }

and removing value, gas, and gasPrice, it started working.

**Comment by marhel** [comment]
So response with additional fields was;

    {"jsonrpc":"2.0","result":"0x","id":2}

but without, was 

{"jsonrpc":"2.0","result":"0x4140430000000000000000000000000000000000000000000000000000000000","id":2}
