### ISSUE TITLE
sending should allow graphical gasPrice selection

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2142]
- when sending, instead of putting in a price, do it graphically
- curve based on previous values available via eth_gasPriceStatistics
- needs to be intuitive

(Split from https://github.com/ethcore/parity/issues/2114)

**Comment by ngotchac** [comment]
Is `eth_gasPriceStatistics` implemented yet ?

**Comment by derhuerst** [comment]
I think we also need a beginner-friendly explanation of the gas system.

**Comment by ngotchac** [comment]
(method is `ethcore_gasPriceStatistics`)
