### ISSUE TITLE
Connection status should show in the Status & dapp overlay

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2149]
- Connected
- Disconnected

Signer has logic to determine if we are actually online with Parity. (Should be in addition to actually connected to the network)

(Split from https://github.com/ethcore/parity/issues/2117)

**Comment by ngotchac** [comment]
@jacogr Is this still relevant ? When disconnected, an overlay is displayed explaining that it's disconnected from Parity. Thus it becomes quite obvious when we're connected or not...

**Comment by jacogr** [comment]
100%, not sure it is relevant anymore with the current state of things. Closing.
