### ISSUE TITLE
On Windows, put application data in the correct locations.

### ISSUE THREAD

**Issue by Zoltu** [ethcore/parity#2159]
When in ~~Rome~~ Windows, do as the ~~Romans~~ Windows Users Do.

On Windows, putting files into the user's home directory is considered "rude".  That directory is meant to be the location where the user puts files that they directly interact with.  There are clear guidelines provided by Microsoft that outline where the correct place to store data on Windows is, but the summary is one of these folders:  `%APPDATA%`, `%LOCALAPPDATA%` or `%PROGRAMDATA%`

`APPDATA`: Per-user configuration data.  The contents of this folder may roam across the network so it should only consist of small user-specific data like configuration, keys, etc.
`LOCALAPPDATA`: Per-user big-data.  This folder is similar to `APPDATA` in that it is user specific, but it does *not* roam across the network which means it is a good place to put per-user caches.
`PROGRAMDATA`: Machine-wide data.  This folder should not contain user configuration and care should be taken relying on information in this folder as multiple users on a machine have access to it.  Anything stored here should be assumed to be compromised and accessed opportunistically or in ways that are not required to be secure.  This can be a good place to store validatable caches.  The blockchain could be stored here as long as there is a mechanism for users to validate its state easily using data in `APPDATA` or `LOCALAPPDATA`

The current solution (home folder) can wreak havoc on a corporate network because it is synced over the network on every login/logout and it appears that the entire blockchain is being stored here.  This means that on every login/logout GBs of data are being transferred over the network, and possibly over the internet if logging in remotely (e.g., over a VPN).

----

On Linux it is my understanding that using `$HOME` is going out of style in favor of something like https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html.  I am out of my realm of expertise so I won't comment on it, but figured it was relevant.  Also, on MacOS X I believe $HOME is also not the correct place to store data, though it isn't as terribly bad as it is on Windows.

**Comment by arkpar** [comment]
Thanks for reporting, we already have plans for this. See #1648
