### ISSUE TITLE
Better address already in use message

### ISSUE THREAD

**Issue by keorn** [ethcore/parity#2164]
Show which port is unavailable.

**Comment by 3esmit** [comment]
For now there is no message, just the windows error message, that is only possible to read if opening parity in a cmd.exe. Opening parity.exe directly just open a terminal and closes, making difficult to debug the error. Add also some kind of pause & press any key to continue, so the user can read the error message. This would be desirable for any parity crash/error/die, unless running in a "silent mode", important for calling from scripts.

**Comment by paulperegud** [comment]
For others who encountered this cryptic message:

`$ strace -f -e trace=bind parity`

**Comment by tomusdrw** [comment]
Would be good to propose which CLI argument to use in error message too.

**Comment by keorn** [comment]
Closed by #2859
