### ISSUE TITLE
Fix Webpack config to allow /api/ping

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2177]

**Comment by ngotchac** [comment]
Should be fixed with https://github.com/ethcore/parity/pull/2178 (see: https://github.com/ethcore/parity/blob/js/js/webpack.config.js#L208)

**Comment by jacogr** [comment]
Prefer this -

https://github.com/ethcore/parity/pull/2175/files

There are other methods there as well. (Got it from ethcore/parity-ui - working and more extended than ours atm)
