### ISSUE TITLE
TokenReg - check address for valid ECR20 before trying to use it

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2193]
Use the ECR20 interface to attach to the supplied address -

1. getCode on address - needs to be a contract, i.e. result !== 0x
2. do a query on totalSupply - needs to be >0

We only want valid addresses in there.

**Comment by ngotchac** [comment]
@see: a6a8616ba6519ab879d8593b650fd94d6fafcce8 and e4c3f4ead024e5d3529e7acf0f7aac9296a06349
