### ISSUE TITLE
Post-consolidation migrations are not being run.

### ISSUE THREAD

**Issue by chtat12** [ethcore/parity#2201]
So I'm trying to use Ethereum Wallet with Parity instead of Geth.  I followed the instruction on this page:
https://github.com/ethcore/parity/wiki/Using-Parity-with-Mist

Once I launched the Parity --geth, a prompt window popped up and it started syncing the blockchain. Now I don't know what exactly happened, but the Parity window just closed itself. When I tried to run the parity --geth again, the prompt window just flashed up some text and closed. Restarting/reinstalling doesn't help.

Here is what I could capture using print screen.
![1](https://cloud.githubusercontent.com/assets/22314105/18660103/492867fa-7ed4-11e6-8045-ebadb46ea5d8.png)

![0](https://cloud.githubusercontent.com/assets/22314105/18660110/546a3c42-7ed4-11e6-97d1-97b4cef87c57.PNG)

**Comment by tomusdrw** [comment]
Have you been running a newer version of Parity on the same machine?

**Comment by rphmeier** [comment]
I think this is actually a bug with how we handle corrupted databases: after performing DB repair we don't open with column families. See https://github.com/ethcore/parity/blob/master/util/src/kvdb.rs#L285

Probably your database became corrupted either as a cause or result of your Parity closing suddenly, and now it is failing to repair the db.

**Comment by chtat12** [comment]
@rphmeier I think you were right. My database was corrupted. I deleted the blockchain data and re-synced Parity again, and now it's working.
