### ISSUE TITLE
Signer - display decoded transaction parameters using 4byte.directory

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#2208]
https://www.4byte.directory/docs/

**Comment by jacogr** [comment]
Great idea. I am honestly not sure that I like the centralised nature of this (yes, we use some centralised services and yes we want to get rid of them). Apart from that, really cool.

**Comment by tomusdrw** [comment]
Yup, we can also just include the DB in the app - it will be updated with each commit, or we could use `name -> contenthash -> content` addressing in namereg.

**Comment by jacogr** [comment]
Initial stab, visible on the transaction list -

transaction expansion - https://youtu.be/BM3lL6hQhdo
dapp for sig. mgmt - https://www.youtube.com/watch?v=Z8z4qdxnSn0

Need to get the layouts right somewhat before thinking signer - needs to be everywhere where we deal with transactions, so rendering should be a shared component for at least these 2 places

**Comment by jacogr** [comment]
Implemented for tx list, signer will need a bit more work - backlogging - https://github.com/ethcore/parity/issues/2407
