### ISSUE TITLE
Sent issues

### ISSUE THREAD

**Issue by behazin** [ethcore/parity#2224]
How to sent ETH via parity?

I get message below:

Parity Trusted Signer
Not Authorized

Connections used by Trusted Signer are secured. You need to authorize this app.

Make sure Parity is running, generate authorization token:

$ parity signer new-token and paste the token below:

**Comment by rphmeier** [comment]
You need to generate a new token for the trusted signer (running at https://localhost:8180) by running the command  `parity signer new-token` as it suggests. Then paste the token into the signer UI to authorize it to sign your transactions. 

You can also run parity with the `--no-signer` flag to disable the signer.

**Comment by rphmeier** [comment]
(resolved in gitter)
