### ISSUE TITLE
Background for application/signer to be derived from token

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2228]
Procedurally generated, user choice.

**Comment by derhuerst** [comment]
e.g. using [geopattern](http://btmills.github.io/geopattern/). It uses SHA1, so we could generate it from a hash of the private key, right?

**Comment by jacogr** [comment]
In this case we want to tie it to the signer, so it will probably be using `sha3(<signerToken>)` - but the idea is exactly the same, just the input values may be gotten from a different place.

**Comment by tomusdrw** [comment]
IMHO We should use the same pattern instead of indenticon too.
