### ISSUE TITLE
No ctrl+c handled on windows

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#2241]
Parity does not even show `"Finishing work..."` when interrupted with ctrl+c

With this behavior, discovered peers will never be saved and will be discovered again on the next launch

**Comment by petevine** [comment]
It seems parity is currently broken:
- never shuts down after Ctrl-C
- eats memory until killed irrespective of cache setting
- doesn't compile on nightly

**Comment by 5chdn** [comment]
duplicate of #2027
