### ISSUE TITLE
moving from geth

### ISSUE THREAD

**Issue by daniel-lucio** [ethcore/parity#2261]
Is it a directory something i need to move from geth in order to keep my wallet address and main stuff? (moving from cpp to go I just copy the directory where the wallet address is, and thats it), in parity is there something like that? how?

Thanks

**Comment by keorn** [comment]
The keys should get imported automatically, did you check? `parity account list` shows the list of accounts. The keys are stored at `$HOME/.parity/keys`.

**Comment by daniel-lucio** [comment]
thanks,  i only run once parity and review the new directories, i dont recal to seee .parity/keys created, thats why my question. I will review again.

**Comment by tomusdrw** [comment]
Please re-open if you feel that the problem is not solved.
