### ISSUE TITLE
eth_signTransaction

### ISSUE THREAD

**Issue by mongrim** [ethcore/parity#2265]
Hi, guys

Any plans on implementing this API?
https://github.com/ethereum/go-ethereum/pull/1666

It would be nice to have this feature in your client so I could switch to it from geth

**Comment by tomusdrw** [comment]
Sholdn't be too hard. Will require additional Trusted Signer support though.

**Comment by mongrim** [comment]
Any news? It's almost impossible to stay on geth with all these attacks, but we can't use parity without this simple feature
