### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by aspirecoin** [ethcore/parity#2269]
parity in local network, ethminer in other home.
pc where stay parity have 192.168.1.12 ip. 
i try use `parity --jsonrpc-interface 0.0.0.0 --max-peers 100 --cache 3062 --extra-data "your mark" --author 0037a6b811ffeb6e072da21179d11b1406371c63 --identity "you node info" --dapps-interface 0.0.0.0 --dapps-user "admin" --dapps-pass "password"`
but cant connect ethminer to parity.. how open rpc(8545) to internet network?

**Comment by tomusdrw** [comment]
Parity is validating `Host` headers - so you can only connect using the same address Parity is listening on.
Try:
`$ parity --jsonrpc-interface 192.168.1.12 ...` (to allow connections to that IP)
or `$ parity --jsonrpc-interface 0.0.0.0 --jsonrpc-hosts all` to open up your interface for any connections

**Comment by aspirecoin** [comment]
work! thanks!
