### ISSUE TITLE
Add pre-push hook that runs eslint & tests

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2291]
... it is fast enough, no reason not to. js/scripts/pre-push.sh

**Comment by tomusdrw** [comment]
https://www.npmjs.com/package/pre-git :)

**Comment by jacogr** [comment]
Good point. I'm not opposed to move package.json (only) to root like we have Cargo.toml there, however you have just got me thinking - this needs to be conditional to js changes, don't need the rest of the Core devs to run this. (They may not even have the tools to do so)

**Comment by derhuerst** [comment]
Pretty hacky, but this should work: http://stackoverflow.com/questions/7351551/writing-a-git-post-receive-hook-to-deal-with-a-specific-branch#13057643
