### ISSUE TITLE
How to import geth/Ethereum wallet account if not automatic?

### ISSUE THREAD

**Issue by m-thomson** [ethcore/parity#2309]
How can I import my previous geth/Ethereuem wallet account into parity? I have a backup of the keystore folder.

The docs say parity will automatically import geth accounts but if I restore this folder to it's correct location (~/Library/Ethereum) and re-start parity nothing happens.

Any help would greatly be appreciated. Thank you.

**Comment by m-thomson** [comment]
Found the solution:

Copy the keystore file (starts with `UTC--*`) from `~/Library/Ethereum/keystore/` to `~/.parity/keys/`

**Comment by lumicon** [comment]
works great! thank you!

**Comment by peterfig** [comment]
`parity --import-geth-keys`

BOOM chacalaca BOOM
