### ISSUE TITLE
missing 'nonce' value in eth_getBlockByNumber and eth_getUncleByBlockNumberAndIndex

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#2316]
Running 2016-09-25 22:57:10 Starting Parity/v1.4.0-unstable-abcdc81-20160924/x86_64-windows-msvc/rustc1.10.0

missing 'nonce' value when calling the 'eth_getBlockByNumber' and 'eth_getUncleByBlockNumberAndIndex'

**Comment by tomusdrw** [comment]
There is an engine-agnostic `sealFields` field, containing `nonce` in case of Ethash.
