### ISSUE TITLE
Check if JIT works correctly with DelegateCall

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#2341]
And check if our fork of JIT EVM even supports DelegateCall.
https://github.com/ethcore/evmjit
(at first glance seems that it does)

See:
https://github.com/ethcore/parity/pull/2310/files#diff-23bb5e4e60116556bf691850bc184f9bR212

**Comment by gavofyork** [comment]
presume this is addressed in https://github.com/ethcore/parity/pull/2378
