### ISSUE TITLE
Signer/Transaction list should show health/number confirmations of each transaction

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2345]
Currently in other software there is a little bar that counts from 0 to 12 confirmation, suggesting that at 12 a re-org may not mess things up, or rather, chances are much greater that the transaction will "stick".

We need some visual indication here that has a little bar filling up (or something along those lines), where the greater number of confirmations are better for the overall health.

(As requested by @gavofyork)

**Comment by derhuerst** [comment]
What about indicating this using colors or with opacity? Something like this:

![bitcoin wallet](https://lh3.googleusercontent.com/jhDecSzB8OBl8u3RFhge8Vs3WtmNDCzAhsLr-Hhkc12EApRmYvwhoJfNmWA6IWtghETP=h900)
