### ISSUE TITLE
Broken Windows Build (v1.3.1)

### ISSUE THREAD

**Issue by jtesta** [ethcore/parity#2347]
I installed v1.3.1 on a Windows 8.1 system, but when I ran the program, I got the message "api-ms-win-crt-math-l1-1-0.dll is missing from your computer.  Try reinstalling the program to fix this problem."

See attached screen shot.
![parity_error](https://cloud.githubusercontent.com/assets/2982011/18855854/1d3b2c22-8424-11e6-8329-1dbe5edf6a5a.png)

**Comment by arkpar** [comment]
Please try installing the following windows update:
https://support.microsoft.com/en-us/kb/2999226

**Comment by jtesta** [comment]
Yep, updating my VM using Windows Update solved this problem for me.  Still, you may want to fix the installer so that it automatically downloads that update, or tells the user to do it manually.

**Comment by gavofyork** [comment]
added to FAQ.
