### ISSUE TITLE
signAndSendTransaction yields big difference between estimated gas and used gas

### ISSUE THREAD

**Issue by nvtaveras** [ethcore/parity#2348]
I was trying to execute a token transfer on the Morden testnet, using the contract provided on [Ethereum's site](https://www.ethereum.org/token), so I had to send a small amout of Ether to the sender address to pay for the gas price. 

After using the personal_SignAndSendTransaction method, I got the following error from the JSON RPC (using the NEthereum Client):

`Nethereum.JsonRpc.Client.RpcResponseException: Insufficient funds. Account you try to send transaction from does not have enough funds. Required 18800000000000000 and got: 1800000000000000.`

This caused the transaction to fail on the testnet:
https://testnet.etherscan.io/tx/0xdc7c29bfca86c750f0aac65231dd007fab5701ac3e89faba9192a747ffbf10d8

I send more ether to be able to execute it, and to my surprise the transaction went through, but with a way smaller gas usage than the estimated:

https://testnet.etherscan.io/tx/0x8d49529387ef469a3905640647a97bebeff2fe156fa4fdac4c84a9b1efd36d69

I tried this method on GETH and it does return the correct estimated gas price. I tried on the main net transferring some DAO tokens and had the same results.

Let me know if there's any additional information I can provide to help reproducing this or if anyone has experience something similar.

Note: I'm running **Parity 1.3.1** on **Ubuntu**.

**Comment by tomusdrw** [comment]
If you don't specify `gas` limit in your transaction "sensible default" is used for you, currently it's `gas_floor_target/5`.
If you require better approximation you can always call `eth_estimateGas` before doing a transaction (if it's a contract call) or just specify constant value (21k) if you know it's a simple transaction.

**Comment by gavofyork** [comment]
question answered.
