### ISSUE TITLE
about synchronize block data & node usage

### ISSUE THREAD

**Issue by lushwang** [ethcore/parity#2350]
**1, can not synchronize block data**
We build the mining pool Ethereum with parity, but when in use, it often appears that it is unable to synchronize the latest blocks from the network and about falls behind more than 40 blocks, it can not synchronize.

**2, Running in the wrong chain**
After normal work for a period of time with parity, the local block is generated in its own particular chain, and completely separates from the real Ethereum network data, it is running in the wrong chain.

**3, Static node list use**
We want to be able to know how to write static nodes list for parity to facilitate data synchronization. At the same time, we want to be able to get nodes list that is published on ethstats.net.

**4, How to specify the height of synchronization**
Please guide us how to specify the re-synchronization of data from some block height, when the block data synchronization mistakes, we do not need to synchronize data to avoid mining loss.

**Comment by arkpar** [comment]
Please specify the version you are using (`parity --version`)
Run with the following flags `-l miner=trace,sync=trace 2>parity.log` and attach the log file for the case when it stops syncing or goes on the wrong chain.

For static peers you can youse `--reserved-peers` option. 
```
--reserved-peers FILE    Provide a file containing enodes, one per line.
                           These nodes will always have a reserved slot on top
```
The nodes in the file must be in the enode format: `enode://<key>@<ip>:<port`
There's no option to sync or reset to specific block, but we might add that in the future. Syncing should recover from being on the wrong fork automatically however.

**Comment by lushwang** [comment]
@arkpar 
we use parity 1.3.10 for a mining pool as these options following. 
parity --cache-size-db 1024 --gas-floor-target 1000000 --gasprice 5000000000000 --no-dapps --port 30303 --min-peers 25 --max-peers 50 --jsonrpc-port 18545 --jsonrpc-interface all --jsonrpc-hosts all   --rpcapi "eth" --signer-no-validation 

when it suddenly stops syncing,  it shows no errors.
when it goes on the wrong fork chain, it only reports that our pool import one and one new block.

I'm sorry that we donot save the logs.

**Comment by keorn** [comment]
Hi @lushwang,
have you been running into any issues recently, is the issue still relevant?
To help us debug:
 - There is no Parity 1.3.10, could you first let us know the version displayed with `parity -v`.
 - If you run into issues, you will have to provide us with some log output: preferably `-l miner=trace,sync=trace 2>parity.log` as arkpar mentioned or even just regular Parity logging.

**Comment by gavofyork** [comment]
stale.

@lushwang please reopen if still an issue.
