### ISSUE TITLE
Dropdown menus/select fields should be styled to fit in with the rest of the UI

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2351]
Uses the standard MUI overlay colours, unfortunately doesn't fit in with what we have for the rest

**Comment by derhuerst** [comment]
This could be done with a more general approach than creating a wrapper for each UI component. [Material UI allows for theming](http://www.material-ui.com/#/customization/themes) and [the default dark theme contains a lot of pink](https://github.com/callemall/material-ui/blob/master/src/styles/baseThemes/darkBaseTheme.js), which doesn't really fit in.
