### ISSUE TITLE
registry dapp: lookup gives returns wrong data

### ISSUE THREAD

**Issue by derhuerst** [ethcore/parity#2354]
From https://github.com/ethcore/parity/pull/2323#issuecomment-249832530:

> The name lookup in the registry dapp seems to have a bug however. I registered `foobaz` and set `A` to `0x1010101010101010101010101010101010101010`. Later, looking `A` of `foobaz` up yields `0x1010101010101010000000000000000000000000`.

**Comment by jacogr** [comment]
Seems to be invalid or a dapp issue. Works for me via the contract interface via the execute & query functionality.

1. Added ABI to contracts interface
2. Registered 0xecf69634885f27a8f78161e530f15a8d3b57d39e755c222c92cf297b6e25a123
3. setAddress for 0x63Cf90D3f0410092FC0fca41846f596223979195
4. getAddress returns 0x63Cf90D3f0410092FC0fca41846f596223979195

**Comment by jacogr** [comment]
In addition, when using set to set, get returns the correct value. The issue starts when using set & getAddress mixed.

**Comment by jacogr** [comment]
Underlying the issues is the following - when setting something that is not bytes32 you need to use the correct get/set pair. e.g. an address is encoded as bytes32 as follows (note the leading 0's) - `0x000000000000000000000000c26da87880e1428e9a2d976e51fc290a0058206d`

Updated the code to actually use setAddress for setting the address
