### ISSUE TITLE
Incorrect traceAddress from parity trace

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#2371]
As a follow up from the gitter chat with @gavofyork , see transaction  https://etherscan.io/tx/0xa238ee46e4cd5aed9f785e68ccebc6f57105e4d2f6a03d2ad64f7114bd56bb2c#internal . The trace address [create_1_5_1_0_0] and others are missing the parent traceAddress.

Here is another call with an incorrect traceAddresses https://etherscan.io/tx/0x4895fa3e71e213963ffacd3ae689f3e143cf57b5a70834e8d1ea6e43f025e132#internal [call_1_3_0] is missing parent traceAddress [call_1_3]

--- proposed workaround by gavin -----
function processTraceRec(traces, index, trace) {
    trace.subtraces = parseInt(trace.subtraces);
    trace.children = [];
    for (var i = 0; i < trace.subtraces; ++i) {
        var t = traces[index++];
        index = processTraceRec(traces, index, t);
        trace.children.push(t);
    }
    return index;
}
export function processTrace(trace) {
    var t = trace[0];
    processTraceRec(trace, 1, t);
    return t;
}

**Comment by gavofyork** [comment]
Fixed in #2373
