### ISSUE TITLE
parameter --keys-path is not honored / maybe other --path related parameters too.

### ISSUE THREAD

**Issue by gituser** [ethcore/parity#2374]
Hi.

I'm using parity version Parity/v1.3.1-beta-2a82fa0-20160911/x86_64-linux-gnu/rustc1.11.0

It seems there is a bug, db-keys always defaults either to ~/.parity/keys or ~/.parity/testnet_keys (if --testnet parameter was specified).

It doesn't matter what you specify on command line for --db-keys parity always uses one of these paths for some reason.

I've also tried specifying paths without = (e.g. --keys-path /home/ethereum/.parity_testnet/keys) still same issue.

Here is my cmdline I run parity:

`/home/ethereum/parity daemon /var/run/parity_testnet.pid --chain=testnet --db-path=/home/ethereum/.parity_testnet --keys-path=/home/ethereum/.parity_testnet/keys --signer-path=/home/ethereum/.parity_testnet/signer --dapps-path=/home/ethereum/.parity_testnet/dapps --mode=active --mode-timeout 30 --mode-alarm 300 --cache-size 1024 -l 3 --log-file /home/ethereum/.parity_testnet/testnet.log --identity parity_testnet --jsonrpc-interface 192.168.70.4 --jsonrpc-port 8110 --jsonrpc-apis web3,eth,net,ethcore,personal,traces,rpc --ipc-path /home/ethereum/.parity_testnet/parity.ipc --tx-gas-limit 1500000`

```
ethereum@ethereum-testnet-dev:~$ ls .parity/keys|wc -l
0
ethereum@ethereum-testnet-dev:~$ ls .parity_testnet/keys|wc -l
117
ethereum@ethereum-testnet-dev:~$ ./parity account list
[]
```

**Comment by NikVolf** [comment]
in your last line you run `./parity account list`
it should be `./parity --keys-path=/home/ethereum/.parity_testnet/keys account list` instead for proper check

**Comment by NikVolf** [comment]
due to the large amount of keys probably related to https://github.com/ethcore/parity/issues/2263

**Comment by gituser** [comment]
@NikVolf the thing is when I run parity as I specified it always creates ~/.parity/keys for some reason, why?

**Comment by gavofyork** [comment]
we can probably support a `--data-dir` cli arg. will need another issue though.

**Comment by gituser** [comment]
@gavofyork done - https://github.com/ethcore/parity/issues/2383
