### ISSUE TITLE
parity doesn't start if used both --testnet --geth parameters

### ISSUE THREAD

**Issue by gituser** [ethcore/parity#2382]
Start parity with:

Parity version Parity/v1.3.1-beta-2a82fa0-20160911/x86_64-linux-gnu/rustc1.11.0

`parity --testnet --geth`

If there is no ~/.ethereum/testnet directory created before start it will fail with:

`RPC io error: No such file or directory (os error 2)`

**Comment by gavofyork** [comment]
this is because it isn't creating the `~/.ethereum/testnet` path prior to using it for the IPC file.
