### ISSUE TITLE
Use datadir as a base directory for all other parameter paths

### ISSUE THREAD

**Issue by gituser** [ethcore/parity#2383]
#1221 is related.

In geth it's very useful to set --data-dir to some directory and have all other things reside in that directory in subdirectories, e.g. keys, dapps, chain, etc.

So my propose is to do the same for parity?

E.g. if user specified --datadir /tmp/.parity_testnet assign --keys-path to /tmp/.parity_testnet/keys --dapps to /tmp/.parity_testnet/dapps etc

**Comment by fanatid** [comment]
Please, resolve this (maybe `--base-dir`).
It's crazy pass 4 (!) arguments instead one.

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/20224475/e42b9720-a83e-11e6-9d64-1ff2b0728569.png)

looks like @rphmeier just volunteered.

**Comment by rphmeier** [comment]
Guess I did :)

**Comment by rphmeier** [comment]
I like the suggestion of `--base-dir`. Will implement as such unless anyone has a better idea
