### ISSUE TITLE
Key import fails on address_book.json (master swap to beta)

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2410]
Reported by @KenKappler on the beta branch, may be catered for on master and eventually make it back. (i.e. may be an issue only when swapping from current master + UI to beta, hence unconfirmed as an issue) -
## 

I’m guessing the stuff we did to better parse wallets is running into problems when it encounters `address_book.json` in my key folder.

Could not open keys directory: Invalid key file: "/Users/KenKappler/.parity/keys/address_book.json": Unknown field: '0x102e61f5d8f9bc71d0ad4a084df4e65e05ce0e1c' at line 1 column 45

**Comment by gavofyork** [comment]
gone now.
