### ISSUE TITLE
Parity/v1.3.0-beta/x86_64-linux-gnu/rustc1.10.0 Panics from time to time

### ISSUE THREAD

**Issue by LeChuckDE** [ethcore/parity#2422]
thread 'IO Worker #2' panicked at 'chain.tree_route and chain.find_uncles only return hahses of blocks that are in the blockchain. qed.', ../src/libcore/option.rs:699
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by rphmeier** [comment]
This is a known issue, patched in 1.3.2. See #2400.
