### ISSUE TITLE
failure installing Parity with cargo run

### ISSUE THREAD

**Issue by jmiehau** [ethcore/parity#2425]
Trying to install parity, once I run:
`sudo cargo run --release --verbose
`

It gets stuck with this error on the console:
```
warning: struct is never used: `Headers`, #[warn(dead_code)] on by default
   --> ethcore/src/verification/queue/kind.rs:167:2
    |
167 | 	pub struct Headers;
    | 	^^^^^^^^^^^^^^^^^^^

```

OS X and Runstup.

**Comment by tomusdrw** [comment]
It's just a warning. Are you sure the compilation is stuck? How long is it stuck? What's your hardware spec?
It can take up to 20 minutes to compile Parity from scratch on a decent hardware.

**Comment by jmiehau** [comment]
I'm running a Macbook Air, I will run again the process to check if it is pass after 30 minutes.

Thanks!

**Comment by jmiehau** [comment]
Resolved, I'm sync.

Thanks!
