### ISSUE TITLE
Not possible to compile with 2GB RAM

### ISSUE THREAD

**Issue by daniel-lucio** [ethcore/parity#2429]
in a 2GB appliance with 2GB of SWAP (total 4GB of virtual memory), the compiller shows out of memory messages.  Any clue?

**Comment by arkpar** [comment]
try setting build jobs to 1
`export CARGO_BUILD_JOBS=1`

**Comment by daniel-lucio** [comment]
Thanks, I will try in next release. I did compile on a bigger computer and copied the binary

**Comment by JP-Ellis** [comment]
I believe this is an issue with Rust 1.12.  I recently upgraded, and now cannot compile parity without all my memory being used up before `rustc` ultimately crashing.  I have 8GB ram + 4GB swap.

The error happens during the compilation of the `parity` crate, everything up to then works fine.

**Comment by tomusdrw** [comment]
It's already fixed in `beta` and `nightly` channels of rust compiler. We have disabled debug builds to mitigate that on stable.
