### ISSUE TITLE
Error: The contract code couldn't be stored, please check your gas amount , when creating new contract

### ISSUE THREAD

**Issue by waglik** [ethcore/parity#2434]
Hi guys. 

I can not deploy my contract(estimated gas 84251) on Parity despite having 15ETH on my test account. Same code works fine with testrpc.

Error Message : 

Error: The contract code couldn't be stored, please check your gas amount.

Here is some debugging output : 

```
var balance =  web3.eth.getBalance(accounts[1])
console.log('balance: ' + web3.fromWei(balance));
```
>balance: 15.95038514 

```
var gasPrice = web3.eth.gasPrice;
console.log('gasPrice '+gasPrice.toString(10));
```

>gasPrice 20000000000 

```
var gasEstimate = web3.eth.estimateGas({data: contractData});
console.log('gas Estimate '+gasEstimate);
```

>gas Estimate 84251

```
var total = gasEstimate*gasPrice;
console.log('total: ' + web3.fromWei(total));

```
>total: 0.00168502

Code and Parity log : 
[test.tar.gz](https://github.com/ethcore/parity/files/504978/test.tar.gz)

thanks 

-w

**Comment by tomusdrw** [comment]
Can you check if it works corretly in `--geth` mode? Parity (in default mode) will return transaction receipts also for pending transactions and it seems it might be confusing `web3` contract deployment code.

**Comment by waglik** [comment]
@tomusdrw 

Yep it works with --geth, thanks!. What is plan for the future? Should I always run it with --geth if I want to use web3? Or should I use different library?

**Comment by tomusdrw** [comment]
Yes, to keep full `geth/web3` compatibility it is necessary (actually contract deployment is the only thing that happens to break in web3 when not running in `--geth` mode afaik).

We are working on new promise-based web3-replacement library: You can have a look here: https://github.com/jacogr/ethapi-js
(note: this is older version of the library, most recent one is part of this repo, but there is no docs yet)

**Comment by tomusdrw** [comment]
You could also deploy the contract manually (with different deployment-successful logic) instead of using web3 deployment - this might actually be the best solution for you.

**Comment by waglik** [comment]
I see. Thanks for hints will try that.
