### ISSUE TITLE
getTransactionCount 'pending' returns less than 'latest'

### ISSUE THREAD

**Issue by lastperson** [ethcore/parity#2442]
```
eth.getTransactionCount('0x9cbfcb30e3f53acf708907a7a246d2aec943c003');
> 11
eth.getTransactionCount('0x9cbfcb30e3f53acf708907a7a246d2aec943c003', 'pending');
> 9
```

**Parity/v1.3.2-beta-df61b1b-20160921/x86_64-linux-gnu/rustc1.11.0**

`--jsonrpc-interface all --jsonrpc-hosts="all" --pruning="archive" --datadir /var/parity --geth --max-peers 5000 --gas-floor-target 1500000 --gasprice 20000000000 --gas-cap 1500000 --remove-solved`

Node is **not** used for mining.

This is quite a big problem, because provider-engine uses this request in order to find out what nonce to use next: https://github.com/MetaMask/provider-engine/blob/243af1e9547d1ab653dc1f09117e658e47621bfc/subproviders/hooked-wallet.js#L177

**Comment by tomusdrw** [comment]
Shouldn't `getTransactionCount(_, 'pending')` just use transaction queue directly?
What if there are still some transactions that didn't fit to the block because of gas limit.

If it is not going to the queue there is no easy way to get next available nonce over RPC.
