### ISSUE TITLE
data.size returns different type than geth

### ISSUE THREAD

**Issue by flyswatter** [ethcore/parity#2446]
When calling the method `eth_getBlockByNumber`, parity returns an object whose `data.size` value is a base 10 number, while geth returns a hex value.

I think they should agree, and return the same type.

**Comment by tomusdrw** [comment]
What version are you running?

Latest master (and I believe latest beta too) is returning a hex value, which is correct behaviour (encoded `QUANTITY`).

**Comment by gavofyork** [comment]
seems to be a non-issue. please reopen if @tomusdrw 's assertion is incorrect.
