### ISSUE TITLE
RPC should tolerate unknown keys

### ISSUE THREAD

**Issue by flyswatter** [ethcore/parity#2449]
Right now the RPC is very picky about additional keys in a request, and eagerly throws an `Invalid Params` errors.

I prefer an API that doesn't mind stray keys it doesn't understand, and only objects when known keys are misused.  I think this makes an API easier to work with.

At the very least, if the API is going to be picky, it should thrown descriptive errors about why it's throwing.

Somewhat related to #2448

**Comment by tomusdrw** [comment]
Typos in JSON objects are imho the most annoying mistake one can make - I think it's much better to reject invalid inputs, especially that there are default for some parameters.

More descriptive errors would be nice, I agree. Renamed #2448 to address that in future.
