### ISSUE TITLE
Contract Deployments

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2453]
Contracts -
  - [x] Registry
  - [x] TokenReg
  - [x] GitHubHint
  - [x] GAVcoin
  - [x] SignatureReg
  - [x] DappReg
  - [x] BasicCoin

Parity -
  - [x] Update main network registry address

Token registration & images -
  - [x] GAVcoin
  - [x] Unicorn, (UNI 🦄, `0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7`, 10^0)
  - [x] Augur (REP, `0x48c80F1f4D53D5951e5D5438B54Cba84f29F32a5`, 10^18)
  - [x] Digix (DGD, `0xe0b7927c4af23765cb51314a0e0521a9645f0e2a`, 10^9)
  - [x] Beercoin (ALE 🍺, `0x74c1e4b8cae59269ec1d85d3d4f324396048f4ac `, 10^0)
  - [x] Maker (MKR, `0xc66ea802717bfb9833400264dd12c2bceaa34a6d`, 10^18)
  - [x] Nexium (NxC, `0x45e42D659D9f9466cD5DF622506033145a9b89Bc`, 10^3)
  - [x] Pluton, (PLU, `0xD8912C10681D8B21Fd3742244f44658dBA12264E`, 10^18) 
  - [X] SingularDTV, (SNGLS, `0xaec2e87e0a235266d9c5adc9deb4b2e29b54d009`, 10^0)
  - [x] Xaurum (XAUR, `0x4DF812F6064def1e5e029f1ca858777CC98D2D81`, 10^8)
  - [x] Hackergold (HKG, `0xb582baaF5e749d6aA98A22355A9d08B4c4d013C8`, 10^3)
  - [x] Decentralised Capital - https://decentralizedcapital.com/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRlY2VudHJhbGl6ZWRjYXBpdGFsQGdhdndvb2QuY29tIiwidXNlcklkIjo3MSwiaWF0IjoxNDc1NTczMTgzLCJleHAiOjE0NzU1NzY3ODN9.bMGHchoUrJESrzidPFBtXRrXda4p8iwZep8hVxFW61w#/reserves
    - [x] USD (`0x01a7018e6d1fde8a68d12f59b6532fb523b6259d`, 10^8)
    - [x] EUR (`0xdd239298e512427ba98b6602e4c8050c3e21f58b`, 10^8)
    - [x] GBP (`0x45901fa08636c31b647c363fc01a8d4de2a551a1`, 10^8)

**Comment by jacogr** [comment]
Waiting for the HF for a bigger gas limit.

**Comment by romanman** [comment]
@jacogr : can you please update the new HKG address: 

https://etherscan.io/address/0x14f37b574242d366558db61f3335289a5035c506
