### ISSUE TITLE
Parity hammering my server (very weak performance)

### ISSUE THREAD

**Issue by mmitech** [ethcore/parity#2454]
I've switched from geth to parity today in one of my servers and I am experiencing a strange issue, server performance is horrible, it starts lagging in the sense that I experience hangs and slow responses, also blocks are lagging so the amount of orphans and uncles is huge, the moment I stop parity everything returns to normal, resource monitor shows normal usage of CPU and memory.

The server is a bare-metal server HP ProLiant DL580 G5 with a couple of Intel(R) Xeon(R) CPU E7450, 64 GB DDRII and  SSD

The CPU support  :
`x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dt                              s acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx constant_tsc arch_perfmon pebs bts rep_good nopl xtopology aperfmperf pni dtes64                               monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 lahf_lm tpr_shadow vnmi flexpriority dtherm
`

**Edit:** Using Ubuntu server 16.04.1 LTS, tried parity versions 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0 same issue across all version.

**Comment by Eliovp** [comment]
Would like an answer/sollution for this issue as well :+1:

**Comment by NikVolf** [comment]
This must be the case when parity performance is limited by the i/o

**Comment by mmitech** [comment]
How is it possible to be affecting only Parity and how do we fix it ?

**Comment by keorn** [comment]
Im guessing its because Parity fully utilises the available i/o resources. You could try increasing the cache settings or limiting processing power available via os tools (which will hopefully bind the i/o utilisation).

**Comment by mmitech** [comment]
already running with 8GB of cache, but I just don't understand how limiting the processing power will solve this issue ? can you extend a bit on this ?

**Comment by gavofyork** [comment]
try running parity under `nice -n19` to see if it helps. it's quite possible parity is becoming i/o bound.

**Comment by tomusdrw** [comment]
If you have 64GB of RAM I would recommend setting up a ramdisk to store a DB - should speed up everything significantly.
http://www.observium.org/docs/persistent_ramdisk/

**Comment by gavofyork** [comment]
@mmitech / @Eliovp  is this still an issue with parity 

- 1.3.9?

 can we investigate further?

**Comment by mmitech** [comment]
that issue appeared only in that particular server and I don't have access to it anymore, we otherwise switched to parity on all other servers and I couldn't reproduce the same issue.

**Comment by arkpar** [comment]
Please reopen if it resurfaces
