### ISSUE TITLE
RPC support?

### ISSUE THREAD

**Issue by daniel-lucio** [ethcore/parity#2470]
I have been trying to get information using this method:

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash

Just to confirm, is it supported or I am doing something wrong?

**Comment by tomusdrw** [comment]
Definitely supported. What errors are you getting?

**Comment by daniel-lucio** [comment]
Look:
curl http://192.168.7.234:8545 -sSf -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0xd5a7dd309c92382c1f68a86878bbf8e77ca66e82e4612729d192cb95ab8c3d63", true],"id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","result":null,"id":1}


do i need to run with --geth parameter?

**Comment by daniel-lucio** [comment]
even with --geth, I get same results.

**Comment by daniel-lucio** [comment]
Nevermind! :dancing_men:

**Comment by tomusdrw** [comment]
Are you sure `0xd5a7dd309c92382c1f68a86878bbf8e77ca66e82e4612729d192cb95ab8c3d63` is a hash of a block? The response indicates that there is no such block in your blockchain.

There is [a transaction](https://www.etherchain.org/tx/0xd5a7dd309c92382c1f68a86878bbf8e77ca66e82e4612729d192cb95ab8c3d63) with this hash, though.
