### ISSUE TITLE
Configurable state cache size.

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#2481]
Add an option to configure state cache size. The will require tracking memory used in the `LRUHashMap` or a custom `LRUHashMap`

**Comment by rphmeier** [comment]
To really make it configurable and to keep the footprint down there should be 3 separate caches:

1. Accounts (basically just deserialized RLP)
2. Storage (`LruCache<(Address, H256), H256>`?)
3. Code (`LruCache<H256, Arc<Bytes>>` based on code size, not item count). This is superior to the current situation, where we only share code between snapshotted versions of the same account.

There are a couple of edge cases to consider when updating the storage cache
1. Suicide: ought to clear all cached storage for the given address.
2. Deploying a contract to an existing address. Needs to clear all globally cached storage for the given address when propagating local changes to the global cache, and then cache any necessary storage from the new contract.

The main issue here is that removing all storage for a given address from the `LruCache` is inefficient as it's backed by a hashmap and iteration is in random order. We could also maintain a `BTreeSet<(Address, H256)>` which would allow efficient removal of all entries for a given account easily at the cost of some extra bookkeeping:

```
let to_remove: Vec<_> = key_set.iter().skip_while(|&(a, _)| a < addr).take_while(|&(a, _)| a == addr).cloned().collect();

for item in to_remove {
    key_set.remove(&item);
    storage_cache.remove(&item);
}
```

Is the overhead worthwhile for the O(logn) vs O(n) complexity?

**Comment by arkpar** [comment]
I'd got for `LruCache<Address, LruCache<H256, H256>>` probably. And have a custom eviction function that would find least recently used key of the least recently used account and remove it

**Comment by 5chdn** [comment]
Just passing by: labelled with _asap_ for 5 months. Is this still in progress?

**Comment by arkpar** [comment]
Already implemented.

**Comment by rphmeier** [comment]
Not everything described was implemented, but it's safe to say the ASAP portions were done ASAP.
