### ISSUE TITLE
Parity 1.3.3 crashes on Ubuntu Linux

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#2484]
I just updated my parity client to the latest 1.3.3, running on Ubuntu Linux 64 bit.  It crashed after running for less than 24 hours.

Error:
```
thread 'IO Worker #3' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-10-06 11:50:15  Finishing work, please wait...
```

**Comment by gavofyork** [comment]
could you describe what you were doing at that time?

please run with `RUST_BACKTRACE=1` in your environment. the information should allow us to debug the issue should it happen again.

**Comment by slothbag** [comment]
I wasn't doing anything that i'm aware of.  It was just connected to the p2p network and processing blocks as per normal.

**Comment by daniel-lucio** [comment]
2016-10-05 23:27:11  Imported #2388268 670e…1408 (0 txs, 0.00 Mgas, 0.49 ms, 0.52 KiB)
thread 'IO Worker #0' panicked at 'assertion failed: `(left == right)` (left: `2046`, right: `2047`)', ethcore/src/miner/transaction_queue.rs:514
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'IO Worker #1' panicked at 'assertion failed: `(left == right)` (left: `2047`, right: `2048`)', ethcore/src/miner/transaction_queue.rs:514
thread 'IO Worker #3' panicked at 'assertion failed: `(left == right)` (left: `2047`, right: `2048`)', ethcore/src/miner/transaction_queue.rs:514
thread 'IO Worker #2' panicked at 'assertion failed: `(left == right)` (left: `2047`, right: `2048`)', ethcore/src/miner/transaction_queue.rs:514
2016-10-05 23:27:12  Finishing work, please wait...


Maybe related? Not using ubuntu, please take out that ugly label. 
I was mining, and using 1.3.3 release

**Comment by cneklason** [comment]
Ubuntu 14.04 16gig RAM 4 Radeon GPUs Parity 1.3.3
Won't stay running > 24 hours. 
Backtrace below:
2016-10-07 12:58:44  Syncing #2398056 e253…2005      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398056    1/ 4/25 peers     42 MiB db    6 MiB chain    2 KiB queue   25 KiB sync
2016-10-07 12:59:14  Syncing #2398064 4e4e…2ae2      0 blk/s    4 tx/s   0 Mgas/s       0+    0 Qed   #2398064    1/ 2/25 peers     42 MiB db    3 MiB chain    2 KiB queue   22 KiB sync
thread 'IO Worker #1' panicked at 'assertion failed: `(left == right)` (left: `1345`, right: `1346`)', ethcore/src/miner/transaction_queue.rs:514
stack backtrace:
   1:     0x55b4606c2b89 - <unknown>
   2:     0x55b4606ca85c - <unknown>
   3:     0x55b4606c9729 - <unknown>
   4:     0x55b4606c9e18 - <unknown>
   5:     0x55b4606c9c72 - <unknown>
   6:     0x55b4606c9be0 - <unknown>
   7:     0x55b46024b192 - <unknown>
   8:     0x55b4602be9e1 - <unknown>
   9:     0x55b4602c0c77 - <unknown>
  10:     0x55b4602782ea - <unknown>
  11:     0x55b460172bf5 - <unknown>
  12:     0x55b4606d2346 - <unknown>
  13:     0x55b4601d882e - <unknown>
  14:     0x55b4606c83c2 - <unknown>
  15:     0x7f02da2d8183 - start_thread
  16:     0x7f02dad0237c - clone
  17:                0x0 - <unknown>
thread 'IO Worker #2' panicked at 'assertion failed: `(left == right)` (left: `1345`, right: `1346`)', ethcore/src/miner/transaction_queue.rs:514
stack backtrace:
   1:     0x55b4606c2b89 - <unknown>
   2:     0x55b4606ca85c - <unknown>
   3:     0x55b4606c9729 - <unknown>
   4:     0x55b4606c9e18 - <unknown>
   5:     0x55b4606c9c72 - <unknown>
   6:     0x55b4606c9be0 - <unknown>
   7:     0x55b46024b192 - <unknown>
   8:     0x55b4602be9e1 - <unknown>
   9:     0x55b4602c0c77 - <unknown>
  10:     0x55b4602782ea - <unknown>
  11:     0x55b460172bf5 - <unknown>
  12:     0x55b4606d2346 - <unknown>
  13:     0x55b4601d882e - <unknown>
  14:     0x55b4606c83c2 - <unknown>
  15:     0x7f02da2d8183 - start_thread
  16:     0x7f02dad0237c - clone
  17:                0x0 - <unknown>
2016-10-07 12:59:14  Finishing work, please wait...
thread 'IO Worker #3' panicked at 'assertion failed: `(left == right)` (left: `1345`, right: `1346`)', ethcore/src/miner/transaction_queue.rs:514
stack backtrace:
   1:     0x55b4606c2b89 - <unknown>
   2:     0x55b4606ca85c - <unknown>
   3:     0x55b4606c9729 - <unknown>
   4:     0x55b4606c9e18 - <unknown>
   5:     0x55b4606c9c72 - <unknown>
   6:     0x55b4606c9be0 - <unknown>
   7:     0x55b46024b192 - <unknown>
   8:     0x55b4602be9e1 - <unknown>
   9:     0x55b4602c0c77 - <unknown>
  10:     0x55b4602782ea - <unknown>
  11:     0x55b460172bf5 - <unknown>
  12:     0x55b4606d2346 - <unknown>
  13:     0x55b4601d882e - <unknown>
  14:     0x55b4606c83c2 - <unknown>
  15:     0x7f02da2d8183 - start_thread
  16:     0x7f02dad0237c - clone
  17:                0x0 - <unknown>
thread 'IO Worker #0' panicked at 'assertion failed: `(left == right)` (left: `1345`, right: `1346`)', ethcore/src/miner/transaction_queue.rs:514
stack backtrace:
   1:     0x55b4606c2b89 - <unknown>
   2:     0x55b4606ca85c - <unknown>
   3:     0x55b4606c9729 - <unknown>
   4:     0x55b4606c9e18 - <unknown>
   5:     0x55b4606c9c72 - <unknown>
   6:     0x55b4606c9be0 - <unknown>
   7:     0x55b46024b192 - <unknown>
   8:     0x55b4602be9e1 - <unknown>
   9:     0x55b4602c0c77 - <unknown>
  10:     0x55b4602782ea - <unknown>
  11:     0x55b460172bf5 - <unknown>
  12:     0x55b4606d2346 - <unknown>
  13:     0x55b4601d882e - <unknown>
  14:     0x55b4606c83c2 - <unknown>
  15:     0x7f02da2d8183 - start_thread
  16:     0x7f02dad0237c - clone
  17:                0x0 - <unknown>

**Comment by NikVolf** [comment]
@cneklason 
please update your version to the latest beta 1.3.4, it contains a fix for this issue

**Comment by daniel-lucio** [comment]
thread 'IO Worker #1' panicked at 'assertion failed: `(left == right)` (left: `1241`, right: `1242`)', ethcore/src/miner/transaction_queue.rs:514
stack backtrace:
   1:     0x55af7241acbf - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55af7242165b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55af724212df - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x55af7240665e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55af724218a1 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55af7240730a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55af71f75452 - _<core..iter..Map<I, F> as core..iter..iterator..Iterator>::next::h802e9b33c60c1b13
   8:     0x55af71f7400f - ethcore::miner::miner::Miner::add_transactions_to_queue::h67fe0e84c8858cb6
   9:     0x55af71de00e0 - _<ethcore..miner..miner..Miner as ethcore..miner..MinerService>::import_external_transactions::ha014df68484e5f53
  10:     0x55af71e1832d - ethcore::client::client::Client::import_queued_transactions::h419bc3c6592c476e
  11:     0x55af71e67482 - std::panicking::try::call::h23787d7dabad7220
  12:     0x55af72428ebb - __rust_try
  13:     0x55af72428e5e - __rust_maybe_catch_panic
  14:     0x55af71e68c2c - _<F as alloc..boxed..FnBox<A>>::call_box::h2aeb4c2df3494d39
  15:     0x55af7241fd44 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  16:     0x7f12b3cb25bc - start_thread
  17:     0x7f12b46e262c - __clone
  18:                0x0 - <unknown>
thread 'IO Worker #0' panicked at 'assertion failed: `(left == right)` (left: `1241`, right: `1242`)', ethcore/src/miner/transaction_queue.rs:514
stack backtrace:
   1:     0x55af7241acbf - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55af7242165b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55af724212df - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x55af7240665e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55af724218a1 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55af7240730a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55af71f75452 - _<core..iter..Map<I, F> as core..iter..iterator..Iterator>::next::h802e9b33c60c1b13
   8:     0x55af71f7400f - ethcore::miner::miner::Miner::add_transactions_to_queue::h67fe0e84c8858cb6
   9:     0x55af71de00e0 - _<ethcore..miner..miner..Miner as ethcore..miner..MinerService>::import_external_transactions::ha014df68484e5f53
  10:     0x55af71e1832d - ethcore::client::client::Client::import_queued_transactions::h419bc3c6592c476e
  11:     0x55af71e67482 - std::panicking::try::call::h23787d7dabad7220
  12:     0x55af72428ebb - __rust_try
  13:     0x55af72428e5e - __rust_maybe_catch_panic
  14:     0x55af71e68c2c - _<F as alloc..boxed..FnBox<A>>::call_box::h2aeb4c2df3494d39
  15:     0x55af7241fd44 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  16:     0x7f12b3cb25bc - start_thread
  17:     0x7f12b46e262c - __clone
  18:                0x0 - <unknown>
2016-10-07 12:18:25  Finishing work, please wait...


I will update, thanks

**Comment by celeduc** [comment]
Also with Parity 1.3.3 on Ubuntu 16.04:
`parity --author ... --cache-size-db 1024 --gas-floor-target 1500000 --gasprice 20000000000 --gas-cap 1500000 --geth --relay-set=strict --force-sealing`

> 2016-10-07 22:52:54  Imported #2398299 7284…d97a (0 txs, 0.00 Mgas, 0.81 ms, 0.51 KiB) + another 1 block(s)
> thread 'IO Worker #1' panicked at 'assertion failed: `(left == right)` (left: `419`, right: `427`)', ethcore/src/miner/transaction_queue.rs:514
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 2016-10-07 22:52:54  Finishing work, please wait...
>

**Comment by keorn** [comment]
@celeduc This issue (as mentioned above) should be fixed in the 1.3.4 release and `master`.

**Comment by celeduc** [comment]
@keorn Thanks, I've already upgraded, but I assumed it wasn't definitively fixed because it is still open.

**Comment by keorn** [comment]
I was referring to the issue mentioned by @celeduc, @daniel-lucio and @cneklason. The original issue with `unwrap` is different.

**Comment by keorn** [comment]
@slothbag have encountered the exact same issue since?
```
thread 'IO Worker #3' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-10-06 11:50:15  Finishing work, please wait...
```

**Comment by keorn** [comment]
We will close it for now, since the information provided is not sufficient to debug. There is active work to remove all places that might produce such useless errors and `RUST_BACKTRACE` should be set in the future releases by default.
