### ISSUE TITLE
gas price market

### ISSUE THREAD

**Issue by sch7** [ethcore/parity#2502]
Someone posted it here:
https://www.reddit.com/r/ethereum/comments/56417j/parity_completely_destroyed_gas_price_market/
instead of creating an issue...

**Comment by tomusdrw** [comment]
In upcoming 1.3.4 release there will be additional CLI switch to choose ordering strategy. See: https://github.com/ethcore/parity/pull/2494

Also by default we have enabled a new strategy where priority is calculated according to formula:
`priority = gas_price - gas/2^15 * minimal_gas_price`

It means that heavy transactions have to increase the gas price significantly to have the same priority as light transactions.

**Comment by arkpar** [comment]
See https://gitter.im/ethcore/parity?at=57f62c7bd6251fd126979ab5 for the discussion
