### ISSUE TITLE
Add `txpool` API

### ISSUE THREAD

**Issue by pipermerriam** [ethcore/parity#2506]
The [txpool](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#txpool) API is quite useful.  It would be helpful for it to be available in parity.

**Comment by tomusdrw** [comment]
Yes, it is a part of already created issue #1966

**Comment by hermanjunge** [comment]
+1

**Comment by tomusdrw** [comment]
@hermanjunge for now we have custom `parity_pendingTransactions` in 1.5 and 1.4 releases. Master branch also contains new UI to track local transactions propagations.

Geth-compatible `txpool` API is there on the roadmap, but without ETA.
