### ISSUE TITLE
web3_sha3 is return incorrect hashes

### ISSUE THREAD

**Issue by AdvancedStyle** [ethcore/parity#2507]
When using Parity "web3_sha3" call over RPC it is return hashes that do not match keccak-256 hashes generated by other tools.

For example in Parity:
`curl -s -X POST 127.0.0.1:8545 --data '{"jsonrpc":"2.0","method":"web3_sha3","params":["0x7ee1cc30f12731068b31c440512b8aaa44277ab7"],"id":1}' -H "Content-Type: application/json"`

Returns: 
`0xd1dfd81cc922f8d23d3fc2a9e402eb814d80aca61bc0061838a67404526da305`

In GETH console:
`web3.sha3('0x7ee1cc30f12731068b31c440512b8aaa44277ab7');`

Returns: 
`0x553a9ec495cafcb7c037c18d3afd3a60be1e0cbd5c16fbb13ea3480789328630`

This online hashing tool agrees with GETH:
http://emn178.github.io/online-tools/keccak_256.html

**Comment by tomusdrw** [comment]
Parity is hashing raw bytes not strings. Don't see a point of hashing a string instead of bytes:
```
$ echo -n -e '\x7e\xe1\xcc\x30\xf1\x27\x31\x06\x8b\x31\xc4\x40\x51\x2b\x8a\xaa\x44\x27\x7a\xb7' > file
$ rhash --sha3-256 file
d1dfd81cc922f8d23d3fc2a9e402eb814d80aca61bc0061838a67404526da305  file
```

**Comment by tomusdrw** [comment]
I think you can use `web3.sha3('0x..', { encoding: 'hex' });` to get the same results. Seems that the conversion is done in web3 library - try using geth's API directly - it should return the same results as us.

Also please test with `$ parity --geth` and `geth attach` - the results should be the same.
Re-open if it's not the case.

**Comment by AdvancedStyle** [comment]
sha3 is used for address capitalization, so that for example:
`0x7ee1cc30f12731068b31c440512b8aaa44277ab7`

Capitalized for sumcheck validation is:
`0x7eE1cC30f12731068b31c440512b8AAa44277AB7`

Where the corresponding character in the sha3 hash it used to determine if the character in the address should be upper or lower case.  If using the Parity hash it would result in a different set of uppercase characters.  And the resulting address would appear in invalid.

If you use the Parity hash it will come out with a different result, such a

**Comment by tomusdrw** [comment]
So you need to encode the string `0x7ee1cc30f12731068b31c440512b8aaa44277ab7` to bytes: `0x307837656531636333306631323733313036386233316334343035313262386161613434323737616237`.

Running:
```
$ curl -s -X POST 127.0.0.1:8545 --data '{"jsonrpc":"2.0","method":"web3_sha3","params":["0x307837656531636333306631323733313036386233316334343035313262386161613434323737616237"],"id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","result":"0x553a9ec495cafcb7c037c18d3afd3a60be1e0cbd5c16fbb13ea3480789328630","id":1}
```
results in expected hash.

**Comment by AdvancedStyle** [comment]
Ok great, thanks, got it.
