### ISSUE TITLE
master cargo build failing

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#2508]
Compiling ethcore-io v1.4.0 (https://github.com/ethcore/parity.git#0c7a2877)
Users\xx\.cargo\git\checkouts\parity-6ba620efeffb2216\master\util\io\src\worker.rs:32:2: 32:16 error: no rules expected the token `#`
Users\xxx\.cargo\git\checkouts\parity-6ba620efeffb2216\master\util\io\src\worker.rs:32      /// Stack size
                                                                                                ^~~~~~~~~~~~~~
Build failed, waiting for other jobs to finish...
error: failed to compile `parity v1.4.0 (https://github.com/ethcore/parity.git#0c7a2877)`, intermediate artifacts can be found at `C:\Users\Matthew\AppData\Local\Temp\cargo-install.UNAyHw9rkDCb`

**Comment by arkpar** [comment]
Parity requires rustc 1.12 now. See https://github.com/ethcore/parity/wiki/FAQ#im-getting-build-errors

**Comment by mtbitcoin** [comment]
@arkpar I upgraded to 1.12 but now running into the following issue (this is on Windows)

--
C:\>rustc -V
rustc 1.12.0 (3191fbae9 2016-09-23)
--
...

   Compiling parity v1.4.0 (https://github.com/ethcore/parity.git#533af433)
EH pad must be jumped to via an unwind edge
  %cleanuppad8 = cleanuppad within none []
  br i1 %1245, label %bb110, label %bb113_cleanup_trampoline_bb110
LLVM ERROR: Broken function found, compilation aborted!
error: failed to compile `parity v1.4.0 (https://github.com/ethcore/parity.git#533af433)`, intermediate artifacts can be found at `C:\Users\Matthew\AppData\Local\Temp\cargo-install.jfSIZUT95AIc`

**Comment by tomusdrw** [comment]
I guess it's that issue: https://github.com/rust-lang/rust/issues/36924

**Comment by mtbitcoin** [comment]
yes, was just.... about to post that. looks like an issue with rustc on windows

**Comment by mtbitcoin** [comment]
@tomusdrw where does the "RUSTFLAGS=-Zorbit=off" go?

**Comment by rphmeier** [comment]
@mtbitcoin It should be set as an environment variable while compiling. I think on Windows this is done with `set RUSTFLAGS=-Zorbit=off && cargo build --release` but I'm not completely sure.

**Comment by mtbitcoin** [comment]
@rphmeier thanks, but is the 'cargo build --release' necessary? 

I am currently compiling with 
cargo install --no-default-features --git https://github.com/ethcore/parity.git parity --force

**Comment by rphmeier** [comment]
@mtbitcoin AFAIK `cargo install` from a git repository will build it in release mode under the hood.

**Comment by mtbitcoin** [comment]
@rphmeier thanks! that did it
