### ISSUE TITLE
Provided Host header is not whitelisted.

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#2509]
Please whitelist for gethWork

**Comment by sammy007** [comment]
Its scrwing existing setup

**Comment by tomusdrw** [comment]
You can whitelist hosts for you own using `--jsonrpc-hosts <Hostname>` or even `--jsonrpc-hosts all`

**Comment by sammy007** [comment]
PLEASE DON"T DO TRAT

**Comment by arkpar** [comment]
resolved in gitter

**Comment by NikVolf** [comment]
@arkpar
can you please post the resolution here?
because it is not like we can watch the full gitter log when another user will come into this issue?

**Comment by NikVolf** [comment]
the `--jsonrpc-hosts` should contain full protocol and port specification like
`http://192.168.3.125:8545`

**Comment by wildmolasses** [comment]
I wanted to set up an ssh tunnel that maps my local port 8145 to my remote machine's 8545. With @joshua-mir's help, was directed to this thread and got it working with `--jsonrpc-hosts http://localhost:8145`

Fyi, also takes comma separated values, e.g. `--jsonrpc-hosts http://localhost:8145,http://localhost:8245`
