### ISSUE TITLE
Watch token contract shows wrong value

### ISSUE THREAD

**Issue by githubacc32** [ethcore/parity#2534]
Hello,
I added a watch token contract for Augur (REP) with this contract address:

0x48c80f1f4d53d5951e5d5438b54cba84f29f32a5
(and 18 decimals)

However, it's always showing some strange (and wrong) value which also changes sometimes.
It was something with 6,000 when the address didn't hold any REP yet, now it holds 3.00 REP and the value is "12,072.3161...".

What's wrong with that?
Thanks

**Comment by tomusdrw** [comment]
Ethereum Wallet is no longer part of Parity 1.4. We recommend using our new UI (or connecting Mist to Parity using IPC)
