### ISSUE TITLE
nodes.json freezes sync on chain change

### ISSUE THREAD

**Issue by almindor** [ethcore/parity#2560]
It seems `nodes.json` causes sync stalling when changing chains. I switched from dogmatic to homestead and parity just stood there with 0 peers while it worked on homestead just moments before.

Removing `nodes.json` fixed the issue.

**Comment by rphmeier** [comment]
The solution here ought to be to have a separate `nodes.json` per network (classic, testnet, morden, private) as the sets of valid nodes for each are disjoint.

**Comment by arkpar** [comment]
eth and etc share the same genesis hash. Should be the spec name instead.

**Comment by crazyearner** [comment]
How to fix this sync problem then as cant update and no peers found
