### ISSUE TITLE
SecretStore/KeyManager

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#26]

**Comment by NikVolf** [comment]
this is how i would like to name files, btw
not like geth, account id should not be exposed

when parity first launches (or first request to account manager occurs), it generates 
- random 256 bit salt and puts it in the keys folder with name like `.salt` (`ROOT_SALT`)
- just random 4096 bits (`ROOT_SEQ`)

When user requests to store some key and provides some password, it derives 4096-bit key from `ROOT_SALT` and his password, decrypts `ROOT_SEQ` with this key and gets sequence of 32 ids (4096/128) - any files that exists in this sequence considered as an "account" and should contain 256-bit secret with `[ACCOUNT_ID(128); ACCOUNT_PRIVATE_KEY_SECRET(128)]`

So given the password provided, user will be able to see what accounts he created with this password, and different passwords will produce different sequences of ids for each password

**Comment by gavofyork** [comment]
so cpp has a password-protected key directory which fulfils a similar role. i'm not bothered about introducing either of them now; keys will not generally be managed by the client, but rather in the layer above. we're doing this out of the need for backwards compatibility and little more.

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/pull/497
final part to make it complete

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/pull/509
