### ISSUE TITLE
eth_getTransaction unstable responses

### ISSUE THREAD

**Issue by lastperson** [ethcore/parity#2602]
Illustration of the issue:
```
eth.getTransaction('0xaaa64a6b3c1c6d5bd47fa8c3009484246d037c9802ce4e91bc5aec68d4d5f6fa')
> null
eth.getTransaction('0xaaa64a6b3c1c6d5bd47fa8c3009484246d037c9802ce4e91bc5aec68d4d5f6fa')
> Object {...}
eth.getTransaction('0xaaa64a6b3c1c6d5bd47fa8c3009484246d037c9802ce4e91bc5aec68d4d5f6fa')
> null
eth.getTransaction('0xaaa64a6b3c1c6d5bd47fa8c3009484246d037c9802ce4e91bc5aec68d4d5f6fa')
> Object {...}
```
Requests are done with ~1 second interval, but experimentation revealed that interval doesn't matter.
The node is the same one that was used to broadcast the transaction using `eth_sendRawTransaction`.
There is no pattern in responses, sometimes it can respond correctly for 20 times in a row, sometimes opposite.
Behavior is reproducible while transaction is not mined yet.
To reproduce: submit transaction with 500000+ gas, so it will have hard time propagating, then start polling getTransaction.
Parity versions checked: 1.3.4, 1.3.6, 1.3.7, on Ubuntu machine.

**Comment by tomusdrw** [comment]
What CLI options are you using for 1.3.7 release?

That situation is only possible if there is more transactions than count limit (`--tx-queue-size`) in your local queue. Otherwise we never discard local transactions from the queue because of the limit (which was not the case for <1.3.6 though)

Can you double check that such behaviour still occurs on 1.3.7? The CLI options might also help with debugging.

**Comment by lastperson** [comment]
`--jsonrpc-interface all --jsonrpc-hosts="all" --pruning="archive" --datadir /var/parity --geth --max-peers 500 --gas-floor-target 1500000 --gasprice 20000000000 --gas-cap 1500000 --remove-solved --relay-set strict --force-sealing  --tx-queue-gas 100000000 -l own_tx=trace`

If transaction would have dropped, than why it reappears later? Being broadcasted by other nodes?

**Comment by tomusdrw** [comment]
Yes, it might be dropped from your local queue, but other node can still re-broadcast it to you (but it will have lower priority then).

So because you are using `--relay-set strict` it will only re-broadcast transactions that fits to the block, you may get better results without that option.

**Comment by tomusdrw** [comment]
I think `relay-set` is also affecting this - transaction is in the block, then new block is mined and the priorities in the queue are changed and your transaction is not included in this new pending block any more - this is why it returns `null`.

**Comment by lastperson** [comment]
is there a `relay-set` value that will make sure my own transaction are never dropped?

**Comment by tomusdrw** [comment]
You should use `--relay-set cheap` (default). 1.3.7 also contains a fix that was happened to slow down Parity a lot when it was relaying a large set of huge transactions (currently we only relay up to 2*block gas limit transactions).

**Comment by lastperson** [comment]
@tomusdrw thanks! removing `--relay-set` did the trick. Should be closed?

**Comment by tomusdrw** [comment]
Yes, please re-open if it happens again.
