### ISSUE TITLE
Move tx options into signer confirmation

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2605]
- gas
- gasPrice
- ...

**Comment by subtly** [comment]
Right now, when using the contracts interface there is no way to specify a higher gas-price or gas-cost. This would be great to have so that a higher gas-price can be specified when calling solidity ABI methods.

**Comment by gavofyork** [comment]
in fact, the primary place for setting/modifying those options should be in the signer, not the wallet. this will allow the user (via the signer) to configure different dapps to default to different percentiles of the gas price thereby configuring them with different default priorities.
