### ISSUE TITLE
Account names reset and contract not showing

### ISSUE THREAD

**Issue by lechatnieger** [ethcore/parity#2633]
hi, 
every time i open parity, accounts name, returns back to standard Account(n), and i have to restore every time Watched contract and watched token.

Is there anything i'm doing wrong?

Thank you in advance for any advice.

**Comment by gavofyork** [comment]
if you're referring to the Ethereum Wallet dapp, it is a Foundation project which we provide as a courtesy. following 1.4 it will not be provided and we make no effort to support it.

you might have better luck running Mist itself with Parity already running. see https://www.youtube.com/watch?v=sta-p5d1blQ for an introduction to that.
