### ISSUE TITLE
eth_syncing inconsistent values

### ISSUE THREAD

**Issue by almindor** [ethcore/parity#2639]
I'm getting inconsistent return values from `eth_syncing` while parity is synchronizing.

I don't see sync stalls on parity output, blocks are coming in ok, but the IPC call gets `false` every 2nd or 3rd call, sometimes consistently for a short while.

**Comment by tomusdrw** [comment]
Are you fully synced with a chain or is it still in syncing mode? What kind of output is displayed in the console: `Imported ...` or `Syncing...`?

**Comment by almindor** [comment]
Still syncing, the console output is consistently displaying `Syncing` no `Imported`.

This was on a node that was quite behind somewhere on blocks `20x`

**Comment by keorn** [comment]
In this early stage of syncing your node will not be aware of the actual highest block number on the network, so it might assume to be synced for a second before finding new blocks. Once it gets connected better and starts downloading more blocks then it should not happen again.

**Comment by keorn** [comment]
Mostly addressed by #2699 and #2763 , the RPC should be more reliable and consistent with the console output.
