### ISSUE TITLE
Understanding release notes for hard-fork version

### ISSUE THREAD

**Issue by newmzy** [ethcore/parity#2641]
> Upgrading private chain specification files.
> 
> All the chain specification files now have EIP-150 rules enabled by default. To continue using the chain add the eip150Transition key under Engine/ethash/params and set it to a future transition block as shown in this example.
> 
> The key related to homestead transition has been renamed from frontierCompatibilityModeLimit to homesteadTransition.

I'm not a developer, I just use Parity as the node for my Mist wallet in --geth mode, because it has lately been a much more reliable option. I don't understand the quote above at all, i.e. whether it applies to me in the use case I described. Does this mean that I need to "add the eip150Transition key under Engine/ethash/params" if I DON'T want to go with the hard-fork? Or if I DO? Does this not apply to me at all? To continue to use Parity as I have been, and follow the hard-fork do I actually have to change anything?

**Comment by keorn** [comment]
This section refers only to private chains, while the chain you use is the official public Ethereum blockchain. Please ignore this section and simply run Parity as usual.

**Comment by newmzy** [comment]
Thankyou very much! That was what I suspected but wanted to be sure.


________________________________
