### ISSUE TITLE
OS X User Who Upgraded to Beta (1.3.8)

### ISSUE THREAD

**Issue by murraci** [ethcore/parity#2642]
I've gotten this error message when starting Parity:

Migrating database from version 6 to 9
Database migration unexpectedly failed

**Comment by tomusdrw** [comment]
Can you make sure you have enough disk space? It should be at least double the size of your current database.
To check disk space:
`$ df --si`
To see how large is a db (mainnet):
`$ du --si ~/.parity/90* --summarize`

**Comment by murraci** [comment]
I've got 330GB to play with buddy according to "About my Mac". 

When I typed thos commands into Terminal I was told "command not found".

**Comment by tomusdrw** [comment]
Is this error consistent? When you run `parity` again are you getting the same message?
Could you post a screenshot with exact output or paste the exact output of terminal here?

**Comment by murraci** [comment]
<img width="572" alt="screen shot 2016-10-17 at 19 28 33" src="https://cloud.githubusercontent.com/assets/15641569/19437530/f2b5384e-949f-11e6-8a15-a258700932ad.png">

**Comment by murraci** [comment]
As you can see, the "migrating database from version 6 to 9" sentence has stopped showing now.

**Comment by tomusdrw** [comment]
I'm afraid your DB is already corrupted at this point - you will have to remove the database and re-sync the chain:
```
$ rm -rf ~/.parity/906a34e69aec8c0d/` #copy without $
```

I've backported more descriptive migration errors to better debug such issues in the future.

**Comment by murraci** [comment]
God darn! OK mate, will start again :) Thanks for your assistance.

**Comment by murraci** [comment]
Sorry to return to this but I've ran that command, then tried to run parity and nothing. Tried to re-install parity --beta and nothing. Any insights? 
<img width="572" alt="screen shot 2016-10-18 at 14 46 37" src="https://cloud.githubusercontent.com/assets/15641569/19468646/c7c7a14c-9541-11e6-97e4-a7dfc20f1d04.png">

**Comment by murraci** [comment]
Restarted whole process again (as if it had never been installed) and this happened.

<img width="784" alt="screen shot 2016-10-18 at 15 42 16" src="https://cloud.githubusercontent.com/assets/15641569/19470399/968f5388-9549-11e6-81c7-23d608e6ae50.png">

**Comment by tomusdrw** [comment]
In original command the was a superfluous ` symbol (note the first character in subsequent lines is `>`).

I'm not an OSX expert but I think you need to run `brew uninstall parity` first and the try installing again with `brew install parity --beta`

**Comment by tomusdrw** [comment]
You can also join our Gitter https://gitter.im/ethcore/parity to get more direct help :)

**Comment by murraci** [comment]
It's a single line command to install. Have done it before. I'll throw it out to Gitter, thanks for your help.

**Comment by murraci** [comment]
Noooo!!! So I uninstalled and tried to re-install. It stalled. Then I used the --force command you told me about on Gitter and this is what I got again. 
<img width="810" alt="screen shot 2016-10-19 at 00 05 57" src="https://cloud.githubusercontent.com/assets/15641569/19488204/0cc46c14-9590-11e6-93b1-ffd7a5186531.png">

**Comment by murraci** [comment]
Tried the uninstall method too :(

<img width="601" alt="screen shot 2016-10-19 at 00 51 37" src="https://cloud.githubusercontent.com/assets/15641569/19489653/4b1bcc9a-9596-11e6-979a-82bfa7fb867e.png">

This is killing me at this stage! :)

**Comment by tomusdrw** [comment]
Your DB is already corrupted you need to remove blockchain data:
`$ rm -rf ~/.parity/906a34e69aec8c0d/ #copy without $`

**Comment by murraci** [comment]
Tried the uninstall method too :(

<img width="601" alt="screen shot 2016-10-19 at 00 51 37" src="https://cloud.githubusercontent.com/assets/15641569/19489653/4b1bcc9a-9596-11e6-979a-82bfa7fb867e.png">

This is killing me at this stage! :)

**Comment by murraci** [comment]
<img width="571" alt="screen shot 2016-10-19 at 00 57 01" src="https://cloud.githubusercontent.com/assets/15641569/19489823/fd2c90b8-9596-11e6-9a75-86fb1420f8b1.png">

Where is the DB located? I could maybe just manually drop it into trash?

**Comment by tomusdrw** [comment]
Don't copy `$` symbol from the commands: `rm -rf ~/.parity/906a34e69aec8c0d`

**Comment by murraci** [comment]
sorry you must really be fed up of me at this stage :)

<img width="969" alt="screen shot 2016-10-19 at 01 19 59" src="https://cloud.githubusercontent.com/assets/15641569/19490660/392575f0-959a-11e6-90c0-c034dc3f7bc3.png">

**Comment by tomusdrw** [comment]
It's fine :) First error you encountered can indicate that other instance of Parity or Geth is already running, please close that instance or modify run parity using `parity --port 30305 --jsonrpc-port 8645 --dapps-port 8081`

Second error (the one from brew) seems to be spurious - just try again.

**Comment by murraci** [comment]
OK first error doesn't apply anymore as I uninstalled again. Try to reinstall once more. Although this is tedious, it's still way better than waiting a century for geth to download :)

**Comment by tomusdrw** [comment]
You don't need to re-install that often. Just when you're upgrading to new version.

Clearing blockchain data using: `rm -rf ~/.parity/906a34e69aec8c0d` should suffice.

**Comment by murraci** [comment]
<img width="883" alt="screen shot 2016-10-19 at 02 02 40" src="https://cloud.githubusercontent.com/assets/15641569/19492261/295422c4-95a0-11e6-93fd-bc3f314863a7.png">

**Comment by tomusdrw** [comment]
I forgot about one more port that needs to be specified when running Parity twice:
`parity --port 30305 --jsonrpc-port 8645 --dapps-port 8081 --signer-port 8181`
But still you cannot run Parity twice with the same DB/Chain (and it seems that it's what you are trying to do).

You should stop Parity running as a service:
`brew services stop parity`
Then clear your database:
`rm -rf ~/.parity/906a34e69aec8c0d && rm -rf ~/.parity/c3295826d7c9904c`
And start Parity:
`parity`

**Comment by murraci** [comment]
We got there!! Thank you!
