### ISSUE TITLE
Autodetect backing store speed for --db-compaction in Mac and Windows

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#2648]
One major support burden is asking users if they have an HDD and if so telling them to run with `--db-compaction=hdd`. Figure it out automatically.

Nice to have for 1.4 but not a blocker.

**Comment by keorn** [comment]
Looks hard for Windows: https://stackoverflow.com/questions/24061519/batch-check-if-someone-is-using-a-hdd-or-a-ssd

**Comment by gavofyork** [comment]
looks like we've done as good a job on this a possible. shelving for now.
