### ISSUE TITLE
Request: improve tagging of docker builds pushed to hub.docker.com

### ISSUE THREAD

**Issue by benjaminion** [ethcore/parity#2649]
I've been in the habit of periodically running

```
docker pull ethcore/parity:latest
```

Apparently this does not track releases only, but also includes experimental commits that might get reverted. For example, I recently picked up a version of 1.3.7 that included something to do with Bloom filtering that was later reverted. This caused some issues.

Since all versions on https://hub.docker.com/r/ethcore/parity/builds/ look the same (there's no release info attached) it's hard to tell what each one's status is.

Could the build process be enhanced to only tag official releases ( as per https://github.com/ethcore/parity/releases) with "latest", and tag non-release versions otherwise?

**Comment by jesuscript** [comment]
note: create a cron job to merge master into a branch (e.g. nightly) once a day and point docker hub at that branch
