### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#266]

**Comment by petevine** [comment]
A fully functional parity can now be built on ARM. 

What's needed are these changes:
`nix 0.5`
`mio patch https://github.com/thkaw/mio/commit/8add138f57b3c4e520a1054498d84bf999da2e8a`
`fixed [Makefile](https://github.com/ethcore/parity/issues/566#issuecomment-191189069)`

**Comment by petevine** [comment]
Why does it need rustc to start? Shurely shome mishtake!

**Comment by gavofyork** [comment]
cool - any chance we could get PRs for the required alterations?

**Comment by petevine** [comment]
The `nix/mio` issue will probably solve itself over the coming days. If it drags on, however, or you wanted to have it compile right now, we'd have to use an "official" fork of `mio` in Cargo.toml

As for the `rocksdb` Makefile bug, I'll open an issue with https://github.com/arkpar/rust-rocksdb/ as I'm not sure about the cleanest way to backport the change.

**Comment by petevine** [comment]
Or rather I'd do it if the repo allowed issues :)

**Comment by arkpar** [comment]
rocksdb is sorted now

**Comment by petevine** [comment]
Indeed, builds out of the box.

-original message-
Subject: Re: [parity] ARM build (#266)
From: Arkadiy Paronyan <notifications@github.com>
Date: 16.03.2016 16:29

rocksdb is sorted now

---

**Comment by petevine** [comment]
Someone has tried cross-compilation targeting ARM:

https://github.com/rust-lang/rust/issues/32272#issuecomment-197349899#issuecomment-197379488

I suspect rocksdb must have been built natively.

-original message-
Subject: Re: [parity] ARM build (#266)
From: Arkadiy Paronyan <notifications@github.com>
Date: 16.03.2016 16:29

rocksdb is sorted now

---

**Comment by phonikg** [comment]
This is all a little over my head as it is my first time in Rust-land, and I am very much a beginner developer.  I have been able to install Multirust on a RasPi3, and indeed I no longer have any rocksdb issues, however I am also(obviously) running into the [308] Could not compile `nix` issue.

@petevine Am I best off to wait for it to sort itself out?  Or would you be so kind as to post a step-by-step to replacing old_nix with new_nix?

**Comment by petevine** [comment]
Luckily for you, I already did that :)

https://github.com/rust-lang/rust/issues/32272#issuecomment-197281592

**Comment by petevine** [comment]
Don't forget to add your benchmark results [here.](https://github.com/ethcore/parity/issues/596)

**Comment by tomusdrw** [comment]
Recently #629 has been merged to master (and I believe to beta also). @petevine could you try to re-run the benchmarks to compare the results?

**Comment by phonikg** [comment]
@petevine Thanks for this, I will play around with it. Would you be opposed to me using your binary to create a Raspberry Pi image a distribute on www.ethembedded.com?  Credit will be given of course...

**Comment by petevine** [comment]
Sure, go ahead if you the binary works for you.

**Comment by phonikg** [comment]
its syncing now... block # 163,000 ...ill ensure it fully syncs without issue before releasing into the wild.  Also Ill add benchmark.

**Comment by General-Beck** [comment]
started this build on Rasp p2 B (Ubuntu Core ). syncing now
"parity Pi 2 B" on ethstats

**Comment by phonikg** [comment]
So other than the fact that I had to start re-syncing fresh due to a power outage(parity --pruning --fast would not just continue) Both my RasPi2 & RasPi3 have been getting hung up often on blocks due to 0/0 peers... syncing for over 24hrs now and getting there, but.

![image](https://cloud.githubusercontent.com/assets/7241066/14097184/a0d6630c-f53c-11e5-8e58-11a3ed41c84e.png)

@General-Beck I'm curious how are you making out with yours? I cannot find a "parity Pi 2 B" on ethstats...

**Comment by General-Beck** [comment]
@phonikg ethstats periodically disappears, the client statistics on an external server
http://screencloud.net/v/4NWV
use direct run `./parity-armv7 --rpc --rpcaddr "0.0.0.0" --cache "500" --port "30304"`

**Comment by petevine** [comment]
@phonikg I'd updated the build maybe a day or two later, and that's the one @General-Beck is using judging from ethstats. In case you're actually bumping into some old bugs, I advise using the later build too.

**Comment by phonikg** [comment]
@petevine I think I have the latest as well... not buggy so much as drops peers. Restart parity and off it goes.  More likely lack of resources(see `free` stats below), and the fact that I normally have 2GB of swap, but forgot to `apt-get install dphys-swapfile`

![image](https://cloud.githubusercontent.com/assets/7241066/14128785/0f68bf08-f5f2-11e5-91d9-35590ac91129.png)

I am at block #1184890... getting close:)

**Comment by phonikg** [comment]
@General-Beck Yeah `ethstats` is memory intensive as well... historically when I was posting my devices to stats.ethdev.com I would let the Pi sync first before running ethstats. Greatly reduced the time-to-full-sync.  Also see message above re: swap... doesn't hurt to have a little.

**Comment by petevine** [comment]
@phonikg You mentioned owning a XU3 - you seem to have no problem using rust tools, so maybe you could run a little [benchmark](https://llvm.org/bugs/show_bug.cgi?id=26106#c8) on it to help llvm ARM guys tweak some unrolling settings? That could benefit code generation, with parity in mind, as unrolling is currently off during autovectorization.

**Comment by phonikg** [comment]
@petevine For sure... Ill give it a go, with zram installed;)

**Comment by phonikg** [comment]
@petevine how do I adjust for this:

main.rs:16:9: 16:15 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
main.rs:16     let mut dq: VecDeque<_> = (0..1024).collect();
                   ^~~~~~
main.rs:37:9: 37:15 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
main.rs:37     let mut dq: VecDeque<_> = (0..1024).collect();

**Comment by phonikg** [comment]
I believe I correctly used this attachment:

https://llvm.org/bugs/attachment.cgi?id=15605&action=edit

**Comment by phonikg** [comment]
More info:  `cargo bench` returns:

`     Running target/release/vectorize-f20fd5b44037c8d3

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured`

**Comment by phonikg** [comment]
OK NVM... ignore warnings RIGHT?

n=1

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 38)
test sum_deque_2 ... bench:         400 ns/iter (+/- 3)

N=2

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 42)
test sum_deque_2 ... bench:         259 ns/iter (+/- 4)

N=4

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 38)
test sum_deque_2 ... bench:         238 ns/iter (+/- 3)

N=8

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 37)
test sum_deque_2 ... bench:         238 ns/iter (+/- 3)

**Comment by petevine** [comment]
Thanks! I'll repost the result in the LLVM bugtracker then. 

-original message-
Subject: Re: [ethcore/parity] ARM build (#266)
From: John Gerryts <notifications@github.com>
Date: 31.03.2016 05:03

OK NVM... ignore warnings RIGHT?

n=1

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 38)
test sum_deque_2 ... bench:         400 ns/iter (+/- 3)

N=2

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 42)
test sum_deque_2 ... bench:         259 ns/iter (+/- 4)

N=4

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 38)
test sum_deque_2 ... bench:         238 ns/iter (+/- 3)

N=8

running 2 tests
test sum_deque   ... bench:       3,133 ns/iter (+/- 37)
test sum_deque_2 ... bench:         238 ns/iter (+/- 3)



---

**Comment by petevine** [comment]
https://github.com/rust-lang/rust/pull/33189

**Comment by arkpar** [comment]
There is an ARM docker build image, so closing this. There is separate issue for musl/static build (#999)

**Comment by petevine** [comment]
From a purely Rust/Cargo perspective it still doesn't build cleanly but at least the nix/mio situation should get fixed soon in the ecosystem.

-original message-
Subject: Re: [ethcore/parity] ARM build (#266)
From: Arkadiy Paronyan <notifications@github.com>
Date: 27.04.2016 16:57

There is an ARM docker build image, so closing this. There is separate issue for musl/static build (#999) 

---
