### ISSUE TITLE
Missing HTTP header in dapp: "Web Browser XSS Protection"

### ISSUE THREAD

**Issue by sebs** [ethcore/parity#2680]
"Web Browser XSS Protection is not enabled, or is disabled by the configuration of the 'X-XSS-Protection' HTTP response header on the web server"

> The X-XSS-Protection HTTP response header allows the web server to enable or disable the web browser's XSS protection mechanism. The following values would attempt to enable it: 
X-XSS-Protection: 1; mode=block

>Ensure that the web browser's XSS filter is enabled, by setting the X-XSS-Protection HTTP response header to '1'.

Following routes are concerned

* /contracts
* /deploy-contract
* /home
* /
* /send
* /parity 
* /status
* /wallet

**Comment by tomusdrw** [comment]
Thanks for the report.
Because JSON-RPC API is used for any interaction with backend server I think it's not vulnerable to XSS (perhaps URL injection could work for some of the non-standard dapps).

That said - it won't hurt to include that header in response. Thanks again!

**Comment by sebs** [comment]
The application is using and displaying user input, I think, in some cases, errornous contract code, showed in the "binary" tab (or how it was named). I was not able to reproduce, but take into consideration: This is a standard test, but a tailored approach will get you further.
