### ISSUE TITLE
--notify-work explanation

### ISSUE THREAD

**Issue by daniel-lucio** [ethcore/parity#2695]
could you elaborate when/how to use this parameter?

**Comment by NikVolf** [comment]
@daniel-lucio 
when provided with url, parity will make a `HTTP POST` request each time new mining job is available. The payload will be json-encoded parameters of the mining job. 

using
`--notify-work http://your-mining-service1.com`

**Comment by daniel-lucio** [comment]
Nice!,     like a proxy,    all my ethminer points to my parity, and my parity points to the pool :)
