### ISSUE TITLE
Adding accounts bloom (one-time upgrade)

### ISSUE THREAD

**Issue by vladann93** [ethcore/parity#2696]
Wasnt able to make the trusted signer to work, win10.

Decided to download the latest parity version.

First thing happening was, updating from version 9 from 10, stared at that for a while.

Now it's stuck at Adding accounts bloom (one-time upgrade).

How do I go about fixing this? read somewhere I could delete .ethhash, .parity from c/users, but If I do that will I lose my wallet too? How do I get it back?

Thanks for any help.

**Comment by NikVolf** [comment]
to clear chain database, remove `%HOME%/.parity/906a34e69aec8c0d` directory only, all you wallets will not be deleted
but better just wait until the bloom is updated, it is a heavy operation and it will not stuck

**Comment by vladann93** [comment]
Ah crap.. I already deleted both folders and started syncing from the start...

Would you explain to me how I can get my wallet back?
I backed up the key folder and I know my password.

**Comment by NikVolf** [comment]
@vladann93 
it is easy - just put `keys` folder inside your new `%HOME%/.parity`
