### ISSUE TITLE
DAPP: Resource interpreted as Stylesheet but transferred with MIME type text/html

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#2701]
I copied a DAPP into the `dapps`folder of parity. It fails loading with the following error when visiting the Dapp:
`Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://127.0.0.1:8080/home/"`

```
<!DOCTYPE html><html><head><meta charset=utf-8><title>Some Title</title><link href=/static/css/app.c6eb2c354f022879ebf446874ecf957e.css rel=stylesheet></head><body><div id=app></div><script type=text/javascript src=/static/js/manifest.0791f35c0d77f1b1e6f9.js></script><script type=text/javascript src=/static/js/vendor.d31c0356074fbeb2bc20.js></script><script type=text/javascript src=/static/js/app.5f7b63732838d2d04bb0.js></script></body></html>
```

**Comment by tomusdrw** [comment]
So it seems that you are trying to load some non-existing file (like `<link rel="stylesheet" href="/styles.css" />`) and it's redirecting you to the homepage instead.

Can you show us `index.html` of your dapp?

**Comment by chevdor** [comment]
Hi @tomusdrw, you again 😄 

the index.html is what I pasted above. Let me make look nicer:
```
<!DOCTYPE html>
<html>

<head>
    <meta charset=utf-8>
    <title>Some Title</title>
    <link href=/static/css/app.c6eb2c354f022879ebf446874ecf957e.css rel=stylesheet>
</head>

<body>
    <div id=app></div>
    <script type=text/javascript src=/static/js/manifest.0791f35c0d77f1b1e6f9.js></script>
    <script type=text/javascript src=/static/js/vendor.d31c0356074fbeb2bc20.js></script>
    <script type=text/javascript src=/static/js/app.5f7b63732838d2d04bb0.js></script>
</body>
</html>
```

I double checked the 4 dependencies (css and js) and they all exist and are reachable.

I tried serving this dapp with a local http server (http-server) and the dapp loads fine in Chrome (with assistance from Metamask for web3).

Additionnally, I tried loadin the dapp in Mist (still using the same http-server) and the dapp loads fine there as well.

**Comment by tomusdrw** [comment]
So this will only work if you are using `http://<dappid>.parity/` address.
Otherwise your dapp is loaded under:
`http://localhost:8080/<dappid>/` and `/static/css/file.css` will be resolved to: `http://localhost:8080/static/css/file.css` which is incorrect.
It should fetch the file from `http://localhost:8080/<dappid>/static/css/file.css`.

So you should use relative paths in imports (i.e. `static/css/app.*.css`) to make it work correctly for both cases.

**Comment by chevdor** [comment]
Oh indeed, I did not think about that. Totally correct. Problem solved.
