### ISSUE TITLE
master release synching issue

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#2705]
Running Parityv1.4.0-unstable-487dfb0-20161018x86_64-windows-msvcrustc1.12.0

Every so often the client nodes fails to keep up with the latest blocks and has to be restarted. This was not an issue with the 20161008 build, so most likely it was changes introduced after this commit

**Comment by tomusdrw** [comment]
Logs with `-lsync=trace` would be helpful (or at least standard Parity log)

**Comment by tomusdrw** [comment]
Logs: https://gist.github.com/mtbitcoin/3346d5fc842e48ba4ea2163dce734754

**Comment by mtbitcoin** [comment]
This is a second gist of the logs for a node which is about 10 minutes back

https://gist.github.com/mtbitcoin/50ea4f40dcb5f2114081994abf47d542

**Comment by mtbitcoin** [comment]
might be related to https://github.com/ethcore/parity/commit/7db42df1db64c1de4d66817f20e6bba619ec2368

**Comment by mtbitcoin** [comment]
fixed by the above.
