### ISSUE TITLE
Trace for DelegateCall shows same value transferred twice

### ISSUE THREAD

**Issue by shihao-guo** [ethcore/parity#2706]
Parity/v1.4.0-unstable-487dfb0-20161018/x86_64-linux-gnu/rustc1.12.0

When a transaction initiated a delegate call, how should the transfer of value be interpreted? I've found out that the trace for transaction 

~~~~
0x069ba3c00acf351b6ac4a6d6a585859e353e31a62bfccf19adab98f789d85711
~~~~

is 

~~~~
{
    "action": {
      "callType": "call",
      "from": "0xa42af2c70d316684e57aefcc6e393fecb1c7e84e",
      "gas": "0x2ee0",
      "input": "0x",
      "to": "0xa471e72088497a885a88375328ede9d1f4873f55",
      "value": "0xe65a2d88498a800"
    },
    "blockHash": "0x02cec47bf87e71934682a76d232eb0050eba4603570d4707b9cadd54386eb0e8",
    "blockNumber": 2429013,
    "result": {
      "gasUsed": "0x606",
      "output": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "subtraces": 1,
    "traceAddress": [],
    "transactionHash": "0x069ba3c00acf351b6ac4a6d6a585859e353e31a62bfccf19adab98f789d85711",
    "transactionPosition": 56,
    "type": "call"
  },
  {
    "action": {
      "callType": "delegatecall",
      "from": "0xa42af2c70d316684e57aefcc6e393fecb1c7e84e",
      "gas": "0x2e90",
      "input": "0x",
      "to": "0xa471e72088497a885a88375328ede9d1f4873f55",
      "value": "0xe65a2d88498a800"
    },
    "blockHash": "0x02cec47bf87e71934682a76d232eb0050eba4603570d4707b9cadd54386eb0e8",
    "blockNumber": 2429013,
    "result": {
      "gasUsed": "0x5a4",
      "output": "0x"
    },
    "subtraces": 0,
    "traceAddress": [
      0
    ],
    "transactionHash": "0x069ba3c00acf351b6ac4a6d6a585859e353e31a62bfccf19adab98f789d85711",
    "transactionPosition": 56,
    "type": "call"
  }
~~~~

While only one of those transactions has actually transferred value (both transfer the same amount so I don't know which one is considered valid)

This led to some confusion because even it appears both the normal and internal transaction transferred value, the value is only actually transferred once. 

Is this a bug and may get fixed in the future (for example, set the value to be 0 at the initial tx or the delegate call tx), or is it expected result?

**Comment by shihao-guo** [comment]
Sample transaction can also be seen here https://etherscan.io/tx/0x069ba3c00acf351b6ac4a6d6a585859e353e31a62bfccf19adab98f789d85711

**Comment by tomusdrw** [comment]
I think the second trace is actually a subtrace of the first one (note: `subtraces: 1` and `traceAddress: [0]`)
@debris could you confirm?

**Comment by tomusdrw** [comment]
Also afaik `DELEGATECALL` is never transfering a value, perhaps it shouldn't be in the trace in a first place?

**Comment by shihao-guo** [comment]
I'm running version Parity/v1.4.0-unstable-487dfb0-20161018/x86_64-linux-gnu/rustc1.12.0

The second trace is the subtrace of the first one.

**Comment by gavofyork** [comment]
this is the correct result. `DELEGATECALL`, like `CALL`, `CALLCODE` and `CREATE` has a *value* associated with it. however, that value is propagated from the parent `CALL`: there is no *transfer* associated with it.

please note: these traces are not meant to be "user-level" - they require some substantial knowledge of the ethereum protocol.
