### ISSUE TITLE
Change in Account balance without transaction 

### ISSUE THREAD

**Issue by shihao-guo** [ethcore/parity#2707]
The account 0xa42af2c70d316684e57aefcc6e393fecb1c7e84e has a balance of "0x1cdd8f8969f72c2735" , or  532.4739643561305 eth at block 1964223 according to the eth_getBalance call.
At block 1964224, the account balance becomes "0x1d1a46a8bbf381a735", or 536.8489643561306 eth. 

However, there is no transaction that involves 0xa42af2c70d316684e57aefcc6e393fecb1c7e84e between those 2 blocks, as you can see from 
http://api.etherscan.io/api?module=account&action=txlist&address=0xa42af2c70d316684e57aefcc6e393fecb1c7e84e&startblock=1964220&endblock=1964225&sort=asc&apikey=YourApiKeyToken

I'm guessing this is an parsing error? 

--- edit
Uncle payoff at 1964224 is what's causing the difference.

**Comment by tomusdrw** [comment]
What version are you running?

**Comment by shihao-guo** [comment]
version Parity/v1.4.0-unstable-487dfb0-20161018/x86_64-linux-gnu/rustc1.12.0

**Comment by gavofyork** [comment]
could have been an uncle-block payout?

**Comment by shihao-guo** [comment]
@gavofyork  You're right I must've overlooked that there's a uncle payoff at block 1964224.
