### ISSUE TITLE
Trace Filter is not working properly (filtering fromAddress)

### ISSUE THREAD

**Issue by ngotchac** [ethcore/parity#2751]
When trying to use the `trace_filter` call with the `fromAddress` filter, some unrelated transactions are returned.

Eg. for address `0xe1a1531a6667fa8ba694692362fc679105ff2677` on Testnet.

There should be only one **IN** transaction : https://testnet.etherscan.io/address/0xe1a1531a6667fa8ba694692362fc679105ff2677

However, running 
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"0x0","fromAddress":["0xE1A1531A6667FA8ba694692362Fc679105ff2677"]}],"id":74}' localhost:8545 | python -mjson.tool
```
will return 2 contract creation transactions unrelated to the account `0xe1a1531a6667fa8ba694692362fc679105ff2677` ([0xdf92bf2](http://testnet.etherscan.io/tx/0xdf92bf2be3547fc456e51db27450c8ac1accfc85e2a5618ef880a215d7fc6046) and [0x85893ad](http://testnet.etherscan.io/tx/0x85893ad8ce27faaa2bf27ae05139618630d9f755254b9cf042804014152aff09)).

It seems that it returns every contract creation transactions ([filter.rs#L130](https://github.com/ethcore/parity/blob/master/ethcore/src/types/trace_types/filter.rs#L130) with no `to_address` filter), in blocks matching the `toAddress` filter...

**Comment by ngotchac** [comment]
This seems to fix the issue...

```diff
diff --git a/ethcore/src/types/trace_types/filter.rs b/ethcore/src/types/trace_types/filter.rs
index 2d35718..7eba18c 100644
--- a/ethcore/src/types/trace_types/filter.rs
+++ b/ethcore/src/types/trace_types/filter.rs
@@ -42,7 +42,12 @@ impl From<Vec<Address>> for AddressesFilter {
 impl AddressesFilter {
 	/// Returns true if address matches one of the searched addresses.
 	pub fn matches(&self, address: &Address) -> bool {
-		self.matches_all() || self.list.contains(address)
+		self.matches_all() || self.stricly_matches(address)
+	}
+
+	/// Returns true if address matches at least one of the searched addresses.
+	pub fn stricly_matches(&self, address: &Address) -> bool {
+		self.list.contains(address)
 	}
 
 	/// Returns true if this address filter matches everything.
@@ -127,7 +132,7 @@ impl Filter {
 		};
 
 		action || match trace.result {
-			Res::Create(ref create) => self.to_address.matches(&create.address),
+			Res::Create(ref create) => self.to_address.stricly_matches(&create.address),
 			_ => false
 		}
 	}
```

**Comment by jacogr** [comment]
Make a PR :)
