### ISSUE TITLE
Not a block mined for almost 2 weeks

### ISSUE THREAD

**Issue by daniel-lucio** [ethcore/parity#2770]
just wondering, if this is something broken in parity or just my issue. I have 48 MH/s, and in 2 weeks i have not mined a block. Before switching to parity, with geth i mined 1 block and 1 uncle in 2 weeks.

and yes, im using 1.3.8.

my parity command line options are: 
parity --keys-path=/var/lib/ethereum/keys --db-path=/var/lib/ethereum --max-peers=256 --jsonrpc-interface=all --author=0xXXXXXXXXXXXXXXX --jsonrpc-hosts=all --ipc-path=/var/lib/ethereum/jsonrpc.ipc --dapps-hosts=all --dapps-interface=0.0.0.0 --dapps-path=/var/lib/ethereum/dapps --cache-size-db 512 --dapps-user=xxx --dapps-pass=xxxxx --min-peers=128 --nat=extip:X.X.X.X --geth --db-compaction=hdd --tx-gas-limit=2000000

is it something wrong? or just, bad luck?

**Comment by tomusdrw** [comment]
There is a lot of factors that may affect this fact, but most importantly:
There were couple attacks on the network, causing significant delays in block processing (and therefore the time you could start mining), this also caused higher uncle rate and more re-orgs. Depending on your settings at that time you could be significantly behind the network while mining (or mining could be often interrupted when new block was coming).
Logs from `-lminer=trace` would be helpful for debugging.


BTW 1.3.9 is out.

**Comment by gavofyork** [comment]
With 48MH/s, you have around 1/100,000th of the total network hashing power (which stands at around 4.8TH/s) and as such can expect to mine a block roughly once every 17 days, so the expected number of blocks in 2 weeks (14 days) would be 14/17 blocks = 0.82.

To work out the probability of mining no blocks in two weeks, we can model your mining as a Poisson distribution:

![image](https://cloud.githubusercontent.com/assets/138296/19893906/37db28e6-a04b-11e6-9a3e-877c0cafe213.png)

So we end up with P(0 blocks mined) = (0.82^0 * e^-0.82 / 0!) = 0.44, or a 44% probability. So while this is strictly improbable (it's below 50%), it's still only slightly less likely than an unfavourable coin toss. Mining at least two blocks in two weeks works out as a probability of 20%: substantially less likely. You appeared to have gotten rather lucky in your time of using Geth.
