### ISSUE TITLE
Creating an account should ask for a repetition of the passphrase

### ISSUE THREAD

**Issue by knocte** [ethcore/parity#2774]
Just downloaded version 1.3.8 and when creating an account through the http://localhost:8080/ UI, I have been asked a passphrase, but I haven't been asked to confirm my password (repeat it in a second textbox), which I think should be a very important security feature.

**Comment by rphmeier** [comment]
cc @ethcore/ui-devs -- is this fixed in the new version of the UI?

**Comment by jacogr** [comment]
Yes. This is not an issue for 1.4, the old UI is completely removed. 

In addition to double-password entry and length checking (no strength checking atm, it is slated for 1.5), you have a recovery phrase for each account you create as well as password hint.

**Comment by jacogr** [comment]
Sample from 1.4 (this is for the case where you create a brand-new account, importing from alternative clients and/or recovery via phrase is similar) -

![parity 2016-10-21 23-09-47](https://cloud.githubusercontent.com/assets/1424473/19611802/af130c3c-97e3-11e6-8664-b3e583d28344.png)

**Comment by jacogr** [comment]
Closing, the offending UI has been deprecated and removed.

**Comment by knocte** [comment]
Great thanks. What version of parity will include this new UI?

**Comment by derhuerst** [comment]
@knocte v1.4
