### ISSUE TITLE
Wallet: Renaming an account resets the names of other accounts

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#2782]
Issue: Account names are not saved/loaded properly.

To reproduce:
- name/rename an account
- reload the page, check that the change is effective
- now rename another account
- reload the page

You will see that your last change is there but you lost the first name.

**Comment by chevdor** [comment]
Current Workaround: edit the data directly from local storage

**Comment by tomusdrw** [comment]
Current wallet is going to be removed in next version in favour of our own UI, where this problem is not existent.
