### ISSUE TITLE
No matter what I do I can't sync past block #1,353,830

### ISSUE THREAD

**Issue by naikel** [ethcore/parity#2787]
My time is _exact_.  I've deleted the datadir several times, and then start Parity and it starts sync'ing.  But always it get stuck at block #1,353,830 for hours downloading hundreds of Gigabytes.

Running with -l sync=trace all I see is errors like this:

```
2016-10-21 08:57:53  IO Worker #1 TRACE sync  26: Fork mismatch
2016-10-21 08:57:58  IO Worker #2 TRACE sync  86: Fork mismatch
```

What can I do?  It's always the same very block #1,353,830.

**Comment by keorn** [comment]
What is your Parity version (`parity -v` output)?

**Comment by rphmeier** [comment]
interestingly enough, this is pretty close to (and might be) the block where my `meta_db` branch fails. maybe a consensus issue caused by the bloom filter change?

**Comment by naikel** [comment]
Sorry I forgot to add that information:

Parity/v1.3.8-beta-e0778fc-20161015/x86_64-windows-msvc/rustc1.12.0

**Comment by gavofyork** [comment]
is this still a problem? could you try with parity 1.3.9?

**Comment by naikel** [comment]
No, I will close this issue.  I upgraded to 1.3.9 and it sync'd fine.

Thanks!
