### ISSUE TITLE
Peercount dropping

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#2829]
Running Parity/v1.4.0-unstable-cf9ad99-20161022/x86_64-windows-msvc/

Starts out with more than 20 connected peers, but eventually keeps dropping till around 10

**Comment by mtbitcoin** [comment]
setting min-peers solves this

**Comment by mtbitcoin** [comment]
Problem still persists, only restarting the node helps

**Comment by mtbitcoin** [comment]
Might be related to https://github.com/ethcore/parity/issues/2737

**Comment by arkpar** [comment]
How long it has been running for before dropping from 20 to 10 peers?

**Comment by mtbitcoin** [comment]
Normally after 12 hours, but it's really random. Different nodes have different results but I eventually have to restart the nodes when it drops close to zero

**Comment by arkpar** [comment]
Should be fixed in latest master. @mtbitcoin could you give it another test?

**Comment by mtbitcoin** [comment]
@arkpar I have compiled the latest master, but its throwing a lot of errors upon startup

2016-10-29 12:46:03  Starting Parity/v1.4.0-unstable-0d5a57c-20161016/x86_64-windows-msvc/rustc1.12.0
2016-10-29 12:46:03  State DB configuation: fast +Trace
2016-10-29 12:46:03  Configured for Frontier/Homestead using Ethash engine
thread 'IO Worker #2' panicked at 'Could not get module handle for ntdll.dll', Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot-0.2.6\src\thread_parker/windows.rs:73
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'IO Worker #3' panicked at 'Could not get module handle for ntdll.dll', Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot-0.2.6\src\thread_parker/windows.rs:73
thread 'IO Worker #1' panicked at 'Could not get module handle for ntdll.dll', Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot-0.2.6\src\thread_parker/windows.rs:73
thread '<unnamed>' panicked at 'Could not get module handle for ntdll.dll', Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot-0.2.6\src\thread_parker/windows.rs:73
2016-10-29 12:46:11  Public node URL: enode://ff53fc65a168b77ba1eae26dba1ccbd67f4d61bbadeaa14a28a6b996ecbb78ea44e05fce856fa1de5f78fd0318c55d8d77d453b8ccb7174424dbad5471fa1688@127.0.0.1:30305
2016-10-29 12:46:35      0/ 0/25 peers      2 MiB db    7 KiB chain    2 KiB queue    4 KiB sync
2016-10-29 12:47:06      0/ 0/25 peers      2 MiB db    7 KiB chain    2 KiB queue    4 KiB sync

**Comment by mtbitcoin** [comment]
fixed with latest
