### ISSUE TITLE
No password found to unlock account af29…xx. Make sure valid password is present in files passed using `--password`.

### ISSUE THREAD

**Issue by zz0412** [ethcore/parity#2835]
hi, Guys:
parity version:1.3.9
cmd:parity --unlock "af2xxxx"  --password /usr/xxxx/parity-payout/password --db-path /usr/xxxx/parity-payout  --pruning fast --no-dapps --no-signer

parity note me :No password found to unlock account af29…xx. Make sure valid password is present in files passed using `--password`.

when i copy /usr/xxxx/parity-payout/keys to ~/.parity/keys , it`s ok.
so it`s a issue, when i use  --db-path ,parity can`t find right keys.

**Comment by tomusdrw** [comment]
You should be using `--keys-path` option.

**Comment by zz0412** [comment]
@tomusdrw ok,thanks.
if i use parity miner , config `--author "xxxxxx"`  option and  not put the key to `--keys-path`.can it ?

**Comment by rphmeier** [comment]
@zz0412 correct, you don't need the account's key for block rewards to be paid out.

**Comment by zz0412** [comment]
@rphmeier thanks
