### ISSUE TITLE
crashing with state root not found after freshly resynching blockchain

### ISSUE THREAD

**Issue by brenzi** [ethcore/parity#2849]
I got this

```
2016-10-24 20:36:36  Starting Parity/v1.4.0-unstable-6c7af57-20161017/x86-linux-gnu/rustc1.12.0
2016-10-24 20:36:36  State DB configuation: fast
2016-10-24 20:36:36  Configured for Frontier/Homestead using Ethash engine
2016-10-24 20:36:44  State root not found for block #2421559 (8487c9e4b1bf3baff1419197cf4c904d8fb0841dcd84cb73fc5c5d7365162bde)
2016-10-24 20:36:45  NAT mapped to external address 213.160.36.45:35645
2016-10-24 20:36:45  Public node URL: enode://2de406e94b3297237abf712cac9ac739c31dcea47960d0ce663562acc9c940ea11900c733ce3c132919fc165c391b0a5efbe33b1e1bbf557a9c238ad9f4f1203@213.160.36.45:35645+46475
thread 'IO Worker #2' panicked at 'State root of best block header always valid.: InvalidStateRoot(43f75539013285d2e2f933a95d35326851e15c8978d8dcbdcacd007c6f751b1f)', ../src/libcore/result.rs:788
stack backtrace:
   1: 0xb5b6f6c1 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2: 0xb5b77f0e - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3: 0xb5b76aa9 - std::panicking::default_hook::h41cf296f654245d7
   4: 0xb5b77243 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5: 0xb5b7707d - std::panicking::begin_panic::h93672d0313d5e8e9
   6: 0xb5b76fde - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7: 0xb5b76f3e - rust_begin_unwind
   8: 0xb5bb6d44 - core::panicking::panic_fmt::hbfc935564d134c1b
   9: 0xb5483a88 - core::result::unwrap_failed::hd4001bee4b7169dc
  10: 0xb5589c91 - ethcore::client::client::Client::state::h28fd428ca9aa034f
  11: 0xb558917a - ethcore::client::client::Client::state_at::h1ccdbf0787d2dc2e
  12: 0xb55a0247 - ethcore::client::traits::BlockChainClient::latest_nonce::h65c0879985361ab3
  13: 0xb555018a - _<core..iter..Map<I, F> as core..iter..iterator..Iterator>::next::h0012ab8940dec1d1
  14: 0xb561ff9a - ethcore::miner::miner::Miner::add_transactions_to_queue::hb880a0456beaf26e
  15: 0xb5622b6e - _<ethcore..miner..miner..Miner as ethcore..miner..MinerService>::import_external_transactions::hc2ab640672e5c9e2
  16: 0xb5588af2 - ethcore::client::client::Client::import_queued_transactions::h27225f7840e407e7
  17: 0xb55f9c2e - _<ethcore..service..ClientIoHandler as ethcore_io..IoHandler<ethcore..service..ClientIoMessage>>::message::he9bb167282e9cb30
  18: 0xb5465b23 - std::panicking::try::do_call::hd5a8ce6a40209461
  19: 0xb5b7f667 - __rust_maybe_catch_panic
  20: 0xb54944df - _<F as alloc..boxed..FnBox<A>>::call_box::h1ac3152400e4279d
  21: 0xb5b7578d - std::sys::thread::Thread::new::thread_start::h4c0ad33b336bc6ea
  22: 0xb4a6b2b4 - start_thread
  23: 0xb4cea16d - __clone
  24:        0x0 - <unknown>
2016-10-24 20:36:54  Finishing work, please wait...

```

resynching the entire blockchain didn't help.

**Comment by rphmeier** [comment]
I think this is exactly what @arkpar's flush lock changes were supposed to do.

**Comment by keorn** [comment]
Yes, @brenzi please build the latest master it should be fixed there.

**Comment by gavofyork** [comment]
will assume fixed in #2603.

**Comment by brenzi** [comment]
confirmed

**Comment by segovro** [comment]
2016-11-14 11:24:46  Starting Parity/v1.4.2-beta-b14aed7-20161110/x86_64-linux-gnu/rustc1.12.1
2016-11-14 11:24:46  State DB configuation: fast
2016-11-14 11:24:46  Operating mode: active
2016-11-14 11:24:46  Configured for Frontier/Homestead using Ethash engine
....
2016-11-14 11:25:45  Syncing #2044800 d9bf…3d5f     16 blk/s   94 tx/s   3 Mgas/s     700+    0 Qed   #2045501    1/ 1/25 peers      4 MiB db  351 KiB chain    3 MiB queue  128 KiB sync
thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x556ef681c4f9 - <unknown>
   2:     0x556ef6824f6c - <unknown>
   3:     0x556ef6823e39 - <unknown>
   4:     0x556ef6824528 - <unknown>
   5:     0x556ef6824382 - <unknown>
   6:     0x556ef68242f0 - <unknown>
   7:     0x556ef6824271 - <unknown>
   8:     0x556ef686196f - <unknown>
   9:     0x556ef6240d88 - <unknown>
  10:     0x556ef635f584 - <unknown>
  11:     0x556ef6221880 - <unknown>
  12:     0x556ef682ca56 - <unknown>
  13:     0x556ef6253b88 - <unknown>
  14:     0x556ef6822ad2 - <unknown>
  15:     0x7f29c52bd709 - start_thread
  16:     0x7f29c5d6382c - clone
  17:                0x0 - <unknown>
2016-11-14 11:25:45  Finishing work, please wait...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:788

**Comment by arkpar** [comment]
@segovro this does not look related. Please file a new issue.

**Comment by segovro** [comment]
ok
