### ISSUE TITLE
IPC not accepting sendTransaction

### ISSUE THREAD

**Issue by wighawag** [ethcore/parity#2852]
parity does not seem to accept "eth_sendTransation" via IPC
"eth_call" seems to works fine

This has been seen using ```parity --pruning fast --geth --testnet```

Notes:
 the issue is not present when using jsonrpc
 the transaction tested was one of contract creation

using -l ipc=trace I get 
```
016-10-25 09:10:45 UTC  TRACE ipc  Accepted connection with token Token(1)
```

nothing more.

Using web3, the callback never get called (so no tx hash neither)

**Comment by tomusdrw** [comment]
Are you using `geth attach` or some kind of nodejs script?
@NikVolf any ideas?

**Comment by wighawag** [comment]
nodejs script that works with geth IPC/JSONRPC and parity JSONRPC
the nodejs script is actually javascript generated from another language

**Comment by tomusdrw** [comment]
What nodejs version are you running?

**Comment by wighawag** [comment]
5.12.0

**Comment by gavofyork** [comment]
`eth_sendTransaction` requires you to use the trusted signer. If you want it to work without, ensure you use `--no-signer`, `--unlock` and `--password` on the CLI. This is insecure.

**Comment by wighawag** [comment]
Sorry I forgot to mention I am using ```--unlock <account> --password <pasword file path>```
this works with jsonrpc

**Comment by wighawag** [comment]
do I need --no-signer with IPC ?

**Comment by gavofyork** [comment]
i believe so. @tomusdrw ?

**Comment by wighawag** [comment]
adding ```--no-signer``` does not solve it
I still only get 
```
2016-10-25 10:29:39 UTC  TRACE ipc  Accepted connection with token Token(1)
```
in the log with ```-l ipc=trace```

**Comment by wighawag** [comment]
Note that I am using ```--geth ```

**Comment by tomusdrw** [comment]
I think the problem is that the request is not even received while on IPC (@wighawag mentions that it works fine when using RPC over HTTP).
So it seems to be some issue with IPC or client.

**Comment by gavofyork** [comment]
ok - guess we need @NikVolf to weigh in, then

**Comment by NikVolf** [comment]
@wighawag what is your parity version?

**Comment by wighawag** [comment]
tested on both 1.3.8-beta and 1.3.9 (from deb packages)

**Comment by NikVolf** [comment]
@wighawag 
cool
can you share actual js code with the call being made?

**Comment by wighawag** [comment]
The js script has been generated by the haxe compiler but is still readable: https://gist.github.com/wighawag/8e1a1bd0605f30e45bca1fbd35303d40

this is using web3 version 0.16.0

**Comment by NikVolf** [comment]
@wighawag 
thanx for reporting, we successfully identified and fixed the issue in the above pr

**Comment by wighawag** [comment]
welcome and thanks for fixing it that quick.
