### ISSUE TITLE
Gas price calculation

### ISSUE THREAD

**Issue by iFA88** [ethcore/parity#2854]
Parity/v1.3.9-beta-e9987c4-20161021/x86_64-windows-msvc/rustc1.12.0

The client has defined invalid gas price (`0x0`) when in the last 100 block was no transaction and the eth-usd price was not fetched.
The maybe eth-usd price was not fetched because I'm on private net with 2 peers and every peer think that we are not full synced.

**Comment by gavofyork** [comment]
Addressed in #2856.
