### ISSUE TITLE
Signer is throwing errors when a new Transaction is added

### ISSUE THREAD

**Issue by ngotchac** [ethcore/parity#2867]
```
VM24446:1 Uncaught SyntaxError: Unexpected token e in JSON at position 1
```
Cause: `new_message` sent by Parity WS

```
Error: <circle> attribute r: A negative value is not valid. ("-1.25")
```
Cause: [changes](https://github.com/callemall/material-ui/issues/5277) in Material UI

**Comment by jacogr** [comment]
The first one is "known", but ugly and if fixable, should be fixed.

The second is new after the material upgrade
