### ISSUE TITLE
parity ui to launch token setter interface

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2874]
gavofyork [11:03 PM]  
so would be nice to have `parity ui` open a page like `http://127.0.0.1:8080/?token=singleusetokenhere` which the UI can either use (it it doesn't have a token already) or throw away (if it does) (edited)

jacogr [11:05 PM]  
It does beat copy-and-pasting tokens.

gavofyork [11:05 PM]  
the ui should check whether `http://home.parity/?token=ourtoken` works - if so then redirect; if not, then bug the user to install the extension which manages the proxy
end result is that dapp devs know that if their users are running parity, then they'll probably be able to tell them to go to "mydapp.parity" and it'll just work

**Comment by tomusdrw** [comment]
I would change `?` to `#` to prevent sending the token with a HTTP request to the server (Parity) - imho if it can stay on the client side it should stay there.
