### ISSUE TITLE
Account Edit: Empty tag

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#2888]
If such issue bothers you (I am referring to a build from master), just let me know. I don´t want to generate noise in the issue list.

I noticed that when editing an account, when you start typing in the optional tags field, an empty tag is immediately created (just as the user hits the first key).

**Comment by ngotchac** [comment]
It has been fixed there #2882 :)

**Comment by chevdor** [comment]
Confirmed, works fine now.
