### ISSUE TITLE
Config fat_db expects a string

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#2897]
I am using this config:
https://github.com/ethcore/parity/blob/27d30fca229d0065a748b80cfe33d29fd4c4b0d1/parity/cli/config.full.toml#L85

I get the following error:
`expected a value of type `string`, but found a value of type `boolean` for the key `footprint.fat_db``

**Comment by tomusdrw** [comment]
https://github.com/ethcore/parity/blob/master/parity/cli/config.full.toml#L93 Latest version is using `String` here. Values are `auto`, `on`, `off`.
