### ISSUE TITLE
Gavcoin doesn't load in dev mode

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2900]
vendor.js:3169 Uncaught TypeError: Cannot use 'in' operator to search for 'undefined' in 
gavcoin.js:3378Uncaught TypeError: Cannot read property 'api' of undefined(anonymous function)

**Comment by ngotchac** [comment]
Should be fixed on `master` : must reload Webpack (stop and start `npm start`)

**Comment by jacogr** [comment]
Indeed. Updated, restarted, fixed.
