### ISSUE TITLE
Address 0x0000... doesn't work

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2901]
![image](https://cloud.githubusercontent.com/assets/1424473/19736517/e8a7d94e-9baf-11e6-9b33-fc68cb091d55.png)

Reported by @KenKappler

**Comment by jacogr** [comment]
Umm... cannot replicate atm.

![parity 2016-10-26 19-36-02](https://cloud.githubusercontent.com/assets/1424473/19737385/844d3f62-9bb3-11e6-9848-0dd9790da46f.png)

**Comment by derhuerst** [comment]
Cannot replicate as well.

**Comment by ngotchac** [comment]
Me neither. Should close this one
