### ISSUE TITLE
Add ICONOMI token to live TokenReg

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2903]
https://etherscan.io/token/ICONOMI

via @General-Beck

**Comment by jacogr** [comment]
- [ ] Deploy token
- [ ] Add image

**Comment by General-Beck** [comment]
![2016-10-27 02-15-30](https://cloud.githubusercontent.com/assets/818533/19741832/81f2df40-9bec-11e6-8ee2-d8d308f5d2f9.png)
