### ISSUE TITLE
TokenReg TLA issue

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2904]
From @General-Beck: "TLA in first I paste word with >3 char, after change - red"

![image](https://cloud.githubusercontent.com/assets/1424473/19738099/64c854b2-9bb6-11e6-9618-c41d6b44d4b1.png)

![image](https://cloud.githubusercontent.com/assets/1424473/19738151/9469cce6-9bb6-11e6-842d-4b5f8f4fb67a.png)

**Comment by ngotchac** [comment]
I cannot reproduce it

**Comment by ngotchac** [comment]
This is working fine ; closing for now
