### ISSUE TITLE
Import RAW private key in UI

### ISSUE THREAD

**Issue by iFA88** [ethcore/parity#2911]
Parity/v1.3.9-beta-e9987c4-20161021/x86_64-windows-msvc/rustc1.12.0

I do not find out how can I import private key into keystore.

**Comment by tomusdrw** [comment]
It's a planned feature for 1.4 UI (afaict). @jacogr can you confirm that it is possible in 1.4?

There is `personal_newAccountFromWallet` RPC available.

**Comment by iFA88** [comment]
For `personal_newAccountFromPhrase`
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":null},"id":22}

**Comment by iFA88** [comment]
`personal_newAccountFromWallet`
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":null},"id":22}

**Comment by jacogr** [comment]
In 1.4 with the UI we currently don't allow/handle raw key imports. We currently only allow imports from .json files, from Geth, via secure phrase (as generated by Parity) or pre-sale wallets.

**Comment by tomusdrw** [comment]
You can also use `ethstore` binary to import an account from secret: https://github.com/ethcore/parity/tree/master/ethstore

**Comment by gavofyork** [comment]
@jacogr let's add it to the list - should be an easy one, no?

**Comment by androlo** [comment]
Noticed issue is closed, but just want to say this is great. No longer have to go through geth. 

Been experimenting with secure sockets integration, mainly for "off chain resolution of on-chain promises", through a secure identity registration and lookup system. Ideally Eth could be used for establishing identities (pubaddress-host coupling) rather then certificates, and certificate authorities and all that stuff. Couple this with a dns contract and web 3 here we come.
