### ISSUE TITLE
Error: no such file or directory

### ISSUE THREAD

**Issue by Manidos** [ethcore/parity#2914]
OS: Windows 8, 64 bit
PARITY: 1.3.9
This is what I'm getting in console:
![1](https://cloud.githubusercontent.com/assets/16019131/19765087/bf086204-9c70-11e6-9bb6-71d038e96227.png)
I've just checked, the folder exists, what might be the problem? Does it have to do anything with the presense in the path non-latin characters?

**Comment by tomusdrw** [comment]
It's a known issue: https://github.com/ethcore/parity/issues/2215 Our RocksDB wrapper does not support UTF8 paths.
As a workaround please point a database to a different (non-utf8) directory using `--db-path` flag.
Example: `parity.exe --db-path C:\DbPath`
