### ISSUE TITLE
trace_call ignores gasLimit

### ISSUE THREAD

**Issue by kvhnuke** [ethcore/parity#2927]
Parity trace_call api seems to ignore the gasLimit input.
for example `{"jsonrpc":"2.0","method":"trace_call","params":[{"gasLimit":"0x1A", "data":"0x0f2c93290000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a8000000000000000000000000a7deff12461661212734db35ade9ae7d987d648c","to": "0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444", "from": "0xa7deff12461661212734db35ade9ae7d987d648c", "value": "0x06f05b59d3b20000", "gasPrice": "0x01"},["stateDiff"]],"id":74}` 
and 
`{"jsonrpc":"2.0","method":"trace_call","params":[{"data":"0x0f2c93290000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a8000000000000000000000000a7deff12461661212734db35ade9ae7d987d648c","to": "0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444", "from": "0xa7deff12461661212734db35ade9ae7d987d648c", "value": "0x06f05b59d3b20000", "gasPrice": "0x01"},["stateDiff"]],"id":74}`

has the same output. It'll be useful if it can use the provided gasLimit instead of using default `50000000`. This way user will be able to execute and read the state changes based on a specific gas limit and verify whether provided limit is enough or not. It seems like `trace_rawTransaction` takes gasLimit into consideration when doing the trace but you have to sign the tx everytime to use `trace_rawTransaction`

**Comment by tomusdrw** [comment]
Can you try with `gas` instead of `gasLimit`?

**Comment by kvhnuke** [comment]
awesome that did the trick! Thanks again!
