### ISSUE TITLE
Gavcoin page wider than display

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2953]
via @rphmeier 

```
rob [11:37 PM]  
page for gavcoin dapp is too wide
can scroll horizontally to see just white on the right side
about an extra 5% of the screen width
```

**Comment by jacogr** [comment]
Struggling to replicate on my side. Tried Chrome & FF

**Comment by ngotchac** [comment]
Could reproduce it by changing window's size.

**Comment by chevdor** [comment]
I tested with Chrome, there is a vertical scrollbar but no horizontal one unless you go below 723px. I don´t see any issue/horizontal scrollbar (tested up to 2500+px)

**Comment by rphmeier** [comment]
if it helps, I had another monitor (1920x1200) hooked up while viewing the UI on the main screen (1920x1080).
