### ISSUE TITLE
Parity not syncing

### ISSUE THREAD

**Issue by MaxBinnewies** [ethcore/parity#2967]
Hello,

I am very frustrated with Parity. It simply isn't working anymore. It was working like a month ago, but then suddenly stopped. I dont keep it running 24/7, only turn it on for development. The sync is extremely slow, slower than new blocks being generated...
I updated to the newest version -> same problem.
I switched to Windows with the newest version of Parity for Windows yesterday -> same problem
It downloaded the first two million(actually a bit more I think) blocks within a few hours and then simply drops to near zero.
Now its always the same pattern. It connects, finds peers, but doesn't really import anything. Than loses peers and stays at zero peers. The block number occasionally jumps up a few blocks, but the output for "blk/s" is almost always zero, sometimes 1 or 2. The strange thing is, that the block number goes up slightly higher than the number of blocks it claims it has found.

This is a pretty representative screenshot:
![image](https://cloud.githubusercontent.com/assets/22887963/19830237/bb6abb7c-9df3-11e6-8f7e-00ae798f8e8a.png)
Please help! What can I do, to get Parity to sync again?

Max

**Comment by gavofyork** [comment]
looks like you're syncing through the blocks that were polluted with the recent attacks.

this was a protocol fault and the blocks are *extremely* slow to import. this is not the fault of parity but of the underlying network protocol. if you are on a HDD, ensure you are running parity with `--db-compaction=hdd`. you might also try increasing the cache to around 1024 (see the `--help` for more information there). in general you have three options:

- be patient - they'll import eventually.
- sync from a recent snapshot - ask in our [gitter](https://gitter.im/ethcore/parity) for one.
- update to the experimental 1.4.0 and use `--warp` sync. this requires building from source. you can find instructions on our [wiki](https://github.com/ethcore/parity/wiki).
