### ISSUE TITLE
Account balance does not show when using private chain

### ISSUE THREAD

**Issue by catageek** [ethcore/parity#2975]
I set up a private chain with two accounts. Geth show the balances but parity does not show them.

I noticed that some calls were made to the (inexistent) registrar to resolve account names, and get an error. I could see that on Morden the registrar solve account names to address and then get the balance.

So I deployed a Registrar on the chain and provided the address in the json file of the chain, but unfortunately parity is ignoring it.

So what should I do to get the UI works on a private chain ?

My parity version is at commit 3e3230a

**Comment by jacogr** [comment]
Sorry about that, will put in a fix.
