### ISSUE TITLE
ethcore_pendingTransactions broken in master

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#2981]
ethcore_pendingTransactions appears not be working in the latest master (v1.4.0-unstable-222b2b7-20161029). It is not picking up any pending transactions ("result":[]). Used to work a few commits ago

**Comment by tomusdrw** [comment]
Thanks for report! Fixed in #2984

**Comment by mtbitcoin** [comment]
thanks, that worked. But getting this issue https://github.com/ethcore/parity/issues/2992 , not sure if its related
