### ISSUE TITLE
Address inputs on contract executions should be empty at the start

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3006]
I suppose that the issue is in a 'address' react component.

I saw the issue in the UI while calling a function on a contract I watch.

The function I called requires an address. So the address component shows up with the default "0x" content. This default content ('0x') seems to be set as value for the input. That means that the user has to delete it before pasting an address (otherwise he would get 0x0x1234.....).

Instead of setting 0x as value, setting it as placeholder would improve the experience greatly.

Definitely NO blocker.

**Comment by chevdor** [comment]
Checking out the UI, this seems to be a common issue for a few components.
Value/uint fields are also affected, the default value being '0'. This is also less of an issue as 0123 == 123

**Comment by derhuerst** [comment]
In this specific case, [the problem seems to be in `<ExecuteContract>`](https://github.com/ethcore/parity/blob/1e6a2cb/js/src/modals/ExecuteContract/executeContract.js#L149-L150), `0x` is set as a default value of addresses.

**Comment by chevdor** [comment]
Here is a rendered example:

Instead of
```
<input type="text" autocomplete="off" name=" " value="0x" id=" " style="padding: 0px; position: relative; width: 100%; border: none; outline: none; background-color: rgba(0, 0, 0, 0); color: rgb(255, 255, 255); cursor: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); height: 100%; box-sizing: border-box; margin-top: 14px; -webkit-appearance: textfield;">
```

it should be:
```
<input type="text" autocomplete="off" name=" "  placeholder="0x" id=" " style="padding: 0px; position: relative; width: 100%; border: none; outline: none; background-color: rgba(0, 0, 0, 0); color: rgb(255, 255, 255); cursor: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); height: 100%; box-sizing: border-box; margin-top: 14px; -webkit-appearance: textfield;">
```

**Comment by derhuerst** [comment]
I will put a check inside if the input contains `0x`, otherwise prepend it. Having a default value of `0x` is still a good idea, because we want hex-encoded values to be easily recognisable (so the an address without `0x` will be invalid).

**Comment by chevdor** [comment]
You can, it don´t think it would hurt but I would prepend 0x only if what the user typed in is a valid address once 0x is prepended. If not, I would not push a 0x that may end up being more confusing.

Think about 0x123456789..... By mistake, the user copies 23456789.... to his clipboard and pastes it in the input. You would see no 0x and prepend it, making a 0x23456789 which looks a little more like a valid address but will ends up confusing the user even more.

Having 0x as placebolder (placeholder as in html attribute) already strongly tells the user what the expectation is and the placeholder will vanish when the user brings data in so that it is not on  the way as it is today.

**Comment by derhuerst** [comment]
> Think about 0x123456789..... By mistake, the user copies 23456789.... to his clipboard and pastes it in the input. You would see no 0x and prepend it, making a 0x23456789 which looks a little more like a valid address but will ends up confusing the user even more.

We try to show addresses in the UI with `0x` consistently to avoid confusion.

The "execute function on contract" modal should actually render `23456789` as an invalid address.

**Comment by derhuerst** [comment]
@chevdor #3013 contains address validation, so the input will immediately go red if `0x` is missing.

**Comment by derhuerst** [comment]
Please reopen if you think this is still a major UX problem.

**Comment by chevdor** [comment]
Hi @derhuerst,

Sorry but I would indeed reopen this issue if I could. While you may have fixed the critical issue of 0x0 being passed silently to the contract, I think the current user experience is still confusing and will lead to errors.

For instance, if you are in 'search' mode and type in a valid address then press <TAB>, the input will switch to a random (or maybe the first, last, ...) address in the list but not the one the user entered. Sure the user should pay attention but the current implementation is a guaranty for issues.

I think the component should work as:

**EDIT MODE**
* the user types in a valid unknown address => OK, the address stays
* the user types in an invalid address (no 0x, checksum fails, etc...) => as done today, the input shows some red and is invalid. Under no circumstances invalid input should be considered as being 0x0  
* the user types in a valid address that is known => OK, the name of the account is shown. Your pick if you want to switch to search mode for this case.

**SEARCH MODE**
* the user makes a search and clicks an entry => OK, we show the name
* the user enters a valid known address => we resolve the address and behave as the previous case
* the user enters a valid address that is unknown => we switch to EDIT mode and leave the address as entered. Edit mode rules apply
* the user enters an invalid address => if the user entry starts with 0x, I would switch to edit mode and apply the rules there. If the user entry does not start with 0x, we keep the current behaviour: filtering the list based on the string.

I know such controls are a pain to implement right but the address component is used in many places and should feel right and totally UN-surprising to the user.

What are your thoughts?

**Comment by derhuerst** [comment]
@chevdor

I can understand this is not a good solution, I'm not happy with it either. But as we try to release `1.4`, will only do cleanup changes right now. Fixing the address input/search properly will be more work than a quick fix.

I imagine both mode being combined, so you don't have to switch (the "edit" caption is confusing anyways).

- name entered -> autocompletion from address book
- no match, valid address -> proposes to take that address
- no match, invalid address -> marked red.

**Comment by chevdor** [comment]
@derhuerst 
I totally understand and would not bother (yet) unless I would see still an issue which is the one I mentioned: currently, if you type an address (in search mode) and hit the tab key, without a warning of any sort, your random address is transformed into a random address from the address book. At least, if this case would return a 'no match' that would be OK for 1.4 IMHO.

I really did not look at the code for this component but I am thinking that it may be more convenient to use a 'magnifier/search' button instead of the current mode toggle. I guess this is what you describe with 'mode being combined'.

So concretely for now (ie 1.4), do you think you can find a way that the search does NOT return a  default hit when the user types in a string (it does not even has to by an address) and hits tab?

As an example, I have in my address book some accounts called Bob and Max but none called Peter. In search mode, I type in Peter then TAB, the control resolves to Max and life goes on as if everything would be fine.... Not good.

**Comment by derhuerst** [comment]
> I totally understand and would not bother (yet) unless I would see still an issue which is the one I mentioned: currently, if you type an address (in search mode) and hit the tab key, without a warning of any sort, your random address is transformed into a random address from the address book. At least, if this case would return a 'no match' that would be OK for 1.4 IMHO.

Will look into this, but the component is not the cleanest.

> I really did not look at the code for this component but I am thinking that it may be more convenient to use a 'magnifier/search' button instead of the current mode toggle. I guess this is what you describe with 'mode being combined'.

I imagine it without any search button, just integrated into one text field.
