### ISSUE TITLE
Address inputs in non edit mode should accept addresses

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3008]
Warning: The following issue can lead to disasters for normal users.
Disaster = unexpected replacement of the address they typed by 0x0 and of contracts with 0x0 instead of the address they intended.

The address input has 2 modes:
- edit (we can type 0x124...)
- search (we can type Bob and search for the account called Bob...)

In various places, I noticed that the mode is set by default to either edit or search depending on the context. That´s fine.

I would propose the following:
- if the address input component is in 'search' mode
- and if the user type in a valid address that is not matching a known account
- then switch for the user to the 'edit' mode

Not doing so is confusing for the user who types a valid address.
The user would see the following:
![screen shot 2016-10-31 at 13 04 17](https://cloud.githubusercontent.com/assets/738724/19853716/45b9f4d2-9f6b-11e6-9422-7d7d900bcd14.png)
which looks OK for normal users.

However, since we are in 'search' mode and the address is a good one but not in the list of know addresses, the address that will be used when calling the contract **will not** be the one the user sees, but 0x0 instead.

**Comment by gavofyork** [comment]
...or just ensure that if the name isn't found in search mode then the action cannot happen.

**Comment by derhuerst** [comment]
> ...or just ensure that if the name isn't found in search mode then the action cannot happen.

and (in search mode) mark it as invalid input.

**Comment by derhuerst** [comment]
An invalid name is already being rejected, *if you selected a name before*. If you didn't it doesn't invalidate.

**Comment by chevdor** [comment]
I just tested the current version and I find it totally confusing. If this is in progress, ignore my comment.

Don´t get me wrong, I do understand the difference between the edit and search mode but the visual difference is small for a regular user and the current implementation will lead to friction.

Currently, I am in search mode, I type a valid address, it can see it, and things fail with the message "A recipient network address...."

The good side of it obviously is that it probably (I did not double check) prevents 0x0 to be silently passed. The down side is that it remains totally confusing for the user: he types a valid address in an address input field and things fail.

**Comment by derhuerst** [comment]
> Currently, I am in search mode, I type a valid address, it can see it, and things fail with the message "A recipient network address...."

Cannot confirm.

What I can confirm though is that typing stuff into the input (in search mode) won't put it into the transaction.
