### ISSUE TITLE
Contract Execution & boolean values

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3023]
Chevdor @chevdor 17:26
I am confused about booleans… In the parity UI, I call a contract that needs a bool. I tried 0, 1, true, false, it all seems to end up as true (that´s wat the ‘queries’ of the contract show as well as the input data of the tx). I do not think the issue is the contract itself. Do I miss some info, should it a string like ‘false’ instead of false? or an hex value like 0x0 instead of 0 ?

Gav Wood @gavofyork 17:30
definitely should accept a JS bool

Jaco Greeff @jacogr 17:31
Ok, that may be an issue - let me check it out. The bool should worj with a JS bool.
so false should be, erm, false 
I'm assuming you are working via the "Execute" modal when it doesn't work for you?

Chevdor @chevdor 17:32
I compared queries and tx data and they match so I would exclude a display issue in the queries.
@jacogr correct. I am using the execute feature your work allows me to abuse now

**Comment by chevdor** [comment]
Here is a call done passing `false`:
https://testnet.etherscan.io/tx/0xbf5559865c5889b152d184e9deb26b7723ee2d0426d03b2478a1c8e64568e454

The input data shows:
`0x58e4e2<truncated...>000000000000c
0000000000000000000000000000000000000000000000000000000000000001`

so my `false` became a `1`.
