### ISSUE TITLE
Periodic snapshot maxing out RAM, interrupting sync

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#3027]
reported by @mtbitcoin on gitter.

**Comment by rphmeier** [comment]
(am unable to reproduce)

**Comment by gavofyork** [comment]
would be nice to have this cleared out before releasing 1.4.0

**Comment by mtbitcoin** [comment]
I've run this with --no-periodic-snapshot and the leak is still there. so this might not be related to the warp synch.

**Comment by mtbitcoin** [comment]
could the memory leak be related to the --pruning=archive ?

**Comment by mtbitcoin** [comment]
The memory leak is looking more of an issue with the "--pruning=archive". I am testing this now ..

**Comment by mtbitcoin** [comment]
closing, memory leak was due to running with --pruning=archive https://github.com/ethcore/parity/issues/3081

**Comment by tomusdrw** [comment]
Closing since new issue has been opened.
