### ISSUE TITLE
eth_call block.blockhash(n) == sendTransaction block.blockhash(n+1)

### ISSUE THREAD

**Issue by wighawag** [ethcore/parity#3035]
parity eth_call's blockhash function is giving the wrong hash. It is giving the hash of the blockNumber +1 provided

Here is a node script to test it out
https://gist.github.com/wighawag/33e404824012c5c2612449b775b2dbf0

Using a recent block (blockNumber 1822012)
the script return the hash of blockNumber 1822013

tested on both parity at commit c24ac577fb2c5feaaac5e7f4223874f1afd01fca
and on 1.3.9
running on ubuntu

**Comment by wighawag** [comment]
the contract code is : https://gist.github.com/anonymous/bc3b3909588c9cfd798067d2ff13a8a9

**Comment by wighawag** [comment]
I originally wrongly thought that it could be a solidity issue and you can find some context here : https://github.com/ethereum/solidity/issues/1305

**Comment by tomusdrw** [comment]
Let me get this straight:
1. We are at block `N` now with hash `H(N)` (latest block)
2. You do `eth_call` with block `N` and you should get `H(N)`
3. Then you send transaction and transactions are appended to a pending block `N+1` and the result you get is `H(N+1)`.

I don't see any misbehaviour here, could you elaborate on what would be the expected behaviour?

**Comment by wighawag** [comment]
this is not that, 

let say N = 1824618 (and not as in your case where N is block.blockNumber)

during an eth_sendTransaction block.blockhash(N) = H1
during an eth_call : block.blockhash(N) = H2
parity result in H1 != H2

we are using the same N in both case, we are NOT using block.blockNumber

H1 turns out to be the correct block hash for N

and H2 turns out to be the block hash for N+1

Hope that is clearer

**Comment by wighawag** [comment]
if using the script with a recent block (testnet : )
``` node blockhashtest.js http://localhost:8545 1824639``` gives me ```0x10c60c19bf564acf22f44bc7949b076563e85551bed5d453b2969533806f221f``` (which is the hash for ```1824640```)

it should have give me ```0x94ba960740ee83066832de3c7ff6475e5a9409a31177f2d5be6322dcb8329831```

**Comment by tomusdrw** [comment]
Confirmed, it's a bug with `eth_call`. Will provide a fix in few minutes.
