### ISSUE TITLE
registry dapp: should check if name is owned when changed records

### ISSUE THREAD

**Issue by derhuerst** [ethcore/parity#3037]
> no error message or anything whenever trying to change the meta data of a not owned entry

@ngotchac

**Comment by ngotchac** [comment]
Waiting for [ethcore/contracts#15](https://github.com/ethcore/contracts/pull/15) to be merged and new contract deployed

**Comment by ngotchac** [comment]
@jacogr The PR has been merged, but will the contract be updated (deployed)?
