### ISSUE TITLE
Inline refresh for background images

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3038]
don't continue growing the list of background images, just generate 20 and replace what is there (excluding current selected version)

Requested by @gavofyork

**Comment by derhuerst** [comment]
cc @gavofyork @jacogr @ngotchac

Right now, text & buttons in the settings section are incredibly hard to see. We're all looking at this, with rather colourful & bright screens, no sunlight and rather good eyes and they're still pretty dim. 

Imagine this being projected onto a wall… you would not see the button. I propose (apart from this PR) to make set the `opacity` of the settings section from `.5` to `.7`.

**Comment by jacogr** [comment]
1. Doesn't preserve current
2. One missing

![parity 2016-11-01 13-08-35](https://cloud.githubusercontent.com/assets/1424473/19889284/60f93216-a034-11e6-9bd3-fb9a5a10b7a1.png)
