### ISSUE TITLE
Batch & parallelise trie updates

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#304]
At present trie updates (new nodes) and commits (determination of root hash) are the same operation. There is potential for optimisation by splitting these and allowing multiple updates for a single commit. The trie nodes would be kept decoded, in memory, (possibly in the current `Node` enum) until commit/hash is requested, at which point they'd be hashed and inserted into the DB (when required).

Following this, the commit process itself can be parallelised:

> 1. split the trie into N sub-tries by key (should take O(N * log(trie nodes)) time);
> 2. update sub-tries in parallel;
> 3. re-merge (once again O(N * log(trie nodes)) time).

See also https://eprint.iacr.org/2012/144.pdf .

**Comment by rphmeier** [comment]
batching shows performance gains, parallelization does not in my experiments

**Comment by gavofyork** [comment]
i guess that's in then.
