### ISSUE TITLE
Synchronization halts at block #2283415

### ISSUE THREAD

**Issue by martindederer** [ethcore/parity#3042]
The synchronization halts at block #2283415. It has been like this for days. This behavior occurs with Parity/v1.3.9-beta-e9987c4-20161021/arm-linux-gnu/rustc1.12.0. Is this related to [this bug in geth](https://blog.ethereum.org/2016/09/18/security-alert-geth-nodes-crash-due-memory-bug/)?

[This issue in mist](https://github.com/ethereum/mist/issues/1165) is probably related.

**Comment by tomusdrw** [comment]
Could you post a Parity log for a start?
Those blocks may take a long time to process.

**Comment by rphmeier** [comment]
I thought the attacks only started at around block 2,306,000 -- after the stalling here. The log will help us diagnose.

**Comment by gavofyork** [comment]
attack block began prior to 2283416

**Comment by martindederer** [comment]
Sorry for not providing the logs earlier. After several days of no progress the block has finally been cleared. I run parity with the db-compaction mode "hdd". The disk is attached via a slow USB 2.0 connection. So i guess that and my impatience are to blame. Thanks for the advice though.
