### ISSUE TITLE
Client mode should be persistent 

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3049]
- [x] `--mode=off` should work.
- [x] mode should be saved between parity invocations.
- [ ] ~~RPCs for current sleep status.~~

**Comment by rphmeier** [comment]
point 3 is a bit touchy -- some of these operating modes will wake on RPC. is the querying function precluded from activating sync? if so, it will make refactoring the `self.active()` calls out into something like a middleware a bit trickier.

**Comment by gavofyork** [comment]
true; i guess it's not urgent. we can always put it in its own module of stuff that doesn't imply `active()`.

**Comment by gavofyork** [comment]
point 2 is fare more important

**Comment by tomusdrw** [comment]
AFAIK works correctly now (`user_defaults.json`)
