### ISSUE TITLE
Make recovery phrase copy/pastable

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3066]
Currently, the user cannot select/copy/paste the recovery phrase when creating an account.
That is not convenient at all!

**Comment by jacogr** [comment]
@ngotchac Is it possible to have a generic solution for this one -

- Add copy-to-clipboard prop on Input field
- When set render & copy (as per your existing logic)
- Where required, set prop, copy ability is available

**Comment by ngotchac** [comment]
So what about changing in some places the `disabled` attribute on those inputs to `readonly`. This would make them selectable on Windows (at least it should), and the style and UI can be preserved.

**Comment by ngotchac** [comment]
(Plus, it is more semantically correct than the disabled attribute)
