### ISSUE TITLE
Handling of boolean value during contract deployment

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3067]
This is exactly the same issue than #3024 but in another place.

You will need a contract with a ctor containing a boolean value. @jacogr has all in stock :)

* From the Parity UI
* Contracts
* Deploy Contracts
* Select your account, Abi, provide code 
* Once the ABI is provided, the list of arguments of the ctor will appear. The Boolean values will contain 0x by default (as it was the case in #3024)

The same fix as #3024 should do here as well.

![screen shot 2016-11-01 at 19 31 12](https://cloud.githubusercontent.com/assets/738724/19902277/5b2cc45c-a06a-11e6-8c62-b73546fb50ed.png)

PS: @jacogr I am sooo sorry 😄

**Comment by jacogr** [comment]
Good catch, this one will be quick. Actually let me prepare a fix for it right now since it needs to be in 1.4.
