### ISSUE TITLE
Expand accounts list when clicking on the account icon

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3069]
In the address input component, in search mode, the list of accounts expand when the user clicks in the input field. Naturally, users will click on the biggest item: the icon representing the address.

Currently, this does nothing.
 It would be nice to expand the list as well when the user click on the address unique icon.
![screen_shot_2016-11-01_at_19_46_34](https://cloud.githubusercontent.com/assets/738724/19902712/1bbf2de4-a06c-11e6-8657-69a1f8db76f9.png)

**Comment by chevdor** [comment]
I keep clicking on those identycons... don´t you? :)

**Comment by ngotchac** [comment]
The Address Selector now pops up when clicking on the Identity Icon :+1:
