### ISSUE TITLE
Include contracts into the list of account for the address input component

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3073]
Currently, when a user tries to send Ether (or other) to another account, this is done through the `address input component`. This component has an `edit` and a `search`mode.

In `search`mode, the user can search though his own accounts or all the accounts listed in his address book.

It is currently NOT possible to select a Contract (watched or deployed) from this list.
As a workaround, I tried adding my contract in my address book. As a result, the contract was added to the address book as expected BUT removed from the list of contracts.

Adding the contract back (using watch contract) adds it back to the contract list and removes it from the address book :)

I propose either one of the following:
* a user should be able to have a contract listed in BOTH his contract list and his address book
* or the `address input component` should also list the contracts the users deployed or is watching.

I have no opinion yet on which solution would be better and what the current technical limitations may be (depending on the discussion here, feel free to rename this issue). My needs (as typical user I guess) are:
* ability to interact with a contract (using execute)
* ability to send funds to this contract (without juggling with addresses copy/paste)

If the solution ends up to add all the known contracts to the address input component list, I would recommend also adding a way for the user to visually easily identify accounts between:
1. his own accounts
2. accounts from his address book
3. accounts that are contracts
4. optionally make a difference between watched contracts and deployed contracts

I could think about adding a coloured css border of a few pixels on the left side of the account unique icon with a color code to identify the categories as mentioned above. 

![screen_shot_2016-11-01_at_20_58_16](https://cloud.githubusercontent.com/assets/738724/19905312/78798f84-a076-11e6-8729-bb877d28a339.png)

**Comment by gavofyork** [comment]
i like it!

**Comment by jacogr** [comment]
Umm, I think this is actually a regression - it used to include accounts, addresses & contracts. (In that order) Good catch, very valid.
