### ISSUE TITLE
Address input component should not generate identityicon unless the address is valid

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3093]
Discussed (partlyx) with @derhuerst 

If the user types in `0xHelloWorld` or `0x1234` or even `0xabc456789012345678901234567890123456789Z`, this should not generate an identityicon but show clearly that this is not a valid address.

I propose the following:
- valid address w/ checksum => identityicon
- valid address w/o checksum  => identityicon
- invalid address => big red X

I am not sure yet what would be the best option to provide user feedback about checksums but I think it would be nice to have a way to display it without much clutter.

We have the following cases:
- no checksum `0xabbb6bebfa05aa13e908eaa492bd7a8343760477`
- check OK `0xaBbb6bEbFA05aA13e908EaA492Bd7a8343760477`
- checksum NOK `0xaBBB6bEbFA05aA13e908EaA492Bd7a8343760477`

For those 3 cases, I would display the identityicon in any case but add a little symbol in a corner or a coloured border around it. 

Feedback wanted (but not about my drawing skills 😄  obviously some CSS will do a better job )! Note that I did not regenerate the identityicon to match the following, in a real case, the icons below would differ.
![screen_shot_2016-11-02_at_13_14_27_redcross](https://cloud.githubusercontent.com/assets/738724/19928478/e2140da6-a0fe-11e6-8267-ad9ef5dfba1b.png) ![screen_shot_2016-11-02_at_13_14_27_tick](https://cloud.githubusercontent.com/assets/738724/19928479/e2161466-a0fe-11e6-8962-65e7b5a4f72d.png) ![screen_shot_2016-11-02_at_13_14_27_question](https://cloud.githubusercontent.com/assets/738724/19928480/e21853de-a0fe-11e6-9221-13b0d685b197.png)

![screen_shot_2016-11-02_at_13_14_27_red](https://cloud.githubusercontent.com/assets/738724/19928483/ea19edea-a0fe-11e6-89ca-d03e004c8239.png) ![screen_shot_2016-11-02_at_13_14_27_green](https://cloud.githubusercontent.com/assets/738724/19928484/ea1c7416-a0fe-11e6-9d5e-1a12ead837ab.png) ![screen_shot_2016-11-02_at_13_14_27_yellow](https://cloud.githubusercontent.com/assets/738724/19928485/ea2d0f60-a0fe-11e6-9f22-85b64911b9a2.png)

I kinda prefer the outline option best, it can also be disabled very quickly from the CSS by setting the border width to 0...

The drawback I can think of regarding the 'color only' solution is for color blind people who may not distinguish some of the state. For the 'no checksum' case, we could use a dashed line. To differentiate between OK and NOT OK, we may need an extra visual clue.

**Comment by derhuerst** [comment]
> I kinda prefer the outline option best, it can also be disabled very quickly from the CSS by setting the border width to 0...
>
> The drawback I can think of regarding the 'color only' solution is for color blind people who may not distinguish some of the state. For the 'no checksum' case, we could use a dashed line. To differentiate between OK and NOT OK, we may need an extra visual clue.

Prefer the icon option, as the outline option seems to colourful. 😄

**Comment by chevdor** [comment]
@derhuerst If you go the icon option, you solve also the color blind issue. Keeping accessibility in mind is always nice...

**Comment by jacogr** [comment]
1. This took care of the invalid IdentityIcon - https://github.com/ethcore/parity/pull/3065

2. We currently don't have the fine-grained capabilities to determine for the 3 cases of failures - it is all-or-nothing. (There is an issue logged to address this at the API level, which includes the actual errors as displayed on the UI).
