### ISSUE TITLE
RPCs for deleting accounts

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3105]
(May be slightly controversial or a "won't do", so not logged together with https://github.com/ethcore/parity/issues/3104)

The ability to delete accounts via the UI would be beneficial as opposed to having to clean the folder manually when you want to get rid of "toy" account. (Obviously with the correct warnings, flags & confirmations)

Currently there is no such functionality either in RPCs, and neither on the UI. (And will only be done if correct RPCs are available)

Originally requested by @bjornwgnr

**Comment by chevdor** [comment]
I totally agree. 
I would propose the following additionally for the UI:
- show the DELETE option in the UI only in the case of account that have no balance of any kind 
- ask for user´s confirmation with all appropriate warnings before effectively deleting

Asking for the account´s password / recovery phrase could be good to ensure that the user will be later able to reimport the account however, in the case of toy accounts (typically on testnet), the user may not even have all of that.
