### ISSUE TITLE
Allow a set of standard ABIs (e.g. EIP20, etc) for contract watch

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3126]
... user can still copy ABI or select from a pre-populated list.

**Comment by ngotchac** [comment]
Wouldn't it be better if it were code snippets that can be included in the code editor ? :)

**Comment by jacogr** [comment]
Not convinced about code - we are trying to reach the non-technical users. It is much easier to -

- Watch Contract
- Select "it is a token contract" (or multisig wallet)
- Add the address

Developers love code, however we are trying to reach the other 99% (which still providing a kick-ass experience for the 1%)
