### ISSUE TITLE
Copy button missing at contract creation

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3134]
I know there are big changes in progress on the topic so this will likely fixed in an existing PR but I keep it separated to handle it easier.

During the contract creation, if a contract ctor requires an address, the address input field does not seem to be the one that is being worked on at the moment by @derhuerst. The current control does not list the accounts, we can only type an address in.

Also when the contract has been deployed, its address is displayed but without a "copy to clipboard" button, that would be rather convenient there.

**Comment by jacogr** [comment]
1. Not sure this is valid - checked both contract execution & contract creation modals, both use the InputAddressSelect components. (Which basically allows for either manual inputs of selecting from a list.)

2. Copy is available when the contract was added to the list, can't hurt having it there, but nice-to-have atm.

**Comment by chevdor** [comment]
Ok, I checked again. I think it IS the new component indeed. I was just surprised by the fact that (at least in the version I have), you no longer get a full list when clicking the input field. It seems now to be mandatory to type something in :(

The second 'issue' is there but I agree this should be low prio or even postponed after 1.4
![screen_shot_2016-11-03_at_17_37_01](https://cloud.githubusercontent.com/assets/738724/19975548/b013a08e-a1ec-11e6-9014-12d5904ad038.png)

**Comment by jacogr** [comment]
Yes, type to search :( However when I click on my field it does pop up the list. What happens when you Transfer - the recipient is the same component, does that one open when clicked?

**Comment by chevdor** [comment]
I currently cannot say. See #3146

**Comment by chevdor** [comment]
I could see it in Contract/Execute as well as in Contract/Deploy. So the listing of account is back on track. The only remaining would be to have this copy button to copy the address of created contracts. It should be no brainer since the new address input component as now a readOnly mode.

This is used already in the events:
![screen shot 2016-11-03 at 18 31 37](https://cloud.githubusercontent.com/assets/738724/19977428/cfeddb66-a1f3-11e6-95fe-39c44fd9a0bd.png)

Users can copy, select, not edit, see the identityicon... rather perfect!
