### ISSUE TITLE
Address input requires mouse click

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3136]
I think this is @derhuerst baby :)

Currently, the user MUST use his mouse to select an account from the list.
Naturally, some users will want to use keyboard only and type the name then hit tab or enter. If the list contained a single entry, the expectation is that this account is taken.

Alternatively, users may start typing a few letters, see a short list of N accounts and attempt using the down arrow key to pick an item from the list. 
Currently that *almost* works, but an extra down arrow key is required.

**Comment by derhuerst** [comment]
In which way is another down arrow key required? Remember that I want to be able to type a custom input and submit using the return key, without selecting the first item in the autocompletion list. Right now, its behaviour is like e.g. at Google.

**Comment by chevdor** [comment]
There are 2 cases. Let´s consider that the account list is (for the sake of discussion):
- Bob
- Bobby
- Max
- Peter

If the user starts typing in 'ma' or 'pe', there will be a single match. That´s probably the case you are describing. In that case indeed, with a single TAB or ENTER, we want to pick that account.

If the user starts typing in 'bo', there will be 2 matches: Bob and Bobby. While TAB/ENTER should pick the first item in the list, the user should be able to use the down arrow key once to reach Bob (the 1st match) or twice to reach Bobby (the 2n match), etc...

Currently, if you test the component for the first time, it seems to work as expected. But after selecting an account this way, try again, the second attempt will require 2 times arrow down.

To reproduce: 
- type a string to get a single match
- press the down arrow, you should indeed see the account highlighted (good). Do NOT validate at that point
- change your text to get another single match, try again as above, you will need to hit the down arrow twice to get the match highlighted

**Comment by jacogr** [comment]
@ngotchac Can you please take a look, would like to get these type of enhancements in the queue for 1.4.1

**Comment by ngotchac** [comment]
Closing this with the new Address Selector supporting keyboard navigation/input.
