### ISSUE TITLE
Expanding extra data in the signer produces a wild expansion

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3138]
The best is to reproduce the issue:
- call a contract that needs data (any...)
- in the signer, at that point, we can see a summary of the tx in a rather nice and compact way
![screen_shot_2016-11-03_at_15_19_38](https://cloud.githubusercontent.com/assets/738724/19969593/7b4f7cbe-a1d9-11e6-930a-cf646d47484c.png)

- click on the button "Extra Data... click to expand"
![screen_shot_2016-11-03_at_15_19_56](https://cloud.githubusercontent.com/assets/738724/19969598/7f753838-a1d9-11e6-950d-9b3d9bff5957.png)

=> Doing so, the extra data is displayed in a single line. Not only this is rather unreadable but it also means extensively using both vert. and horiz. scrollbars to see the tx.

**Comment by jacogr** [comment]
Will keep it in mind for post 1.4 when we re-do the Signer UIs.
