### ISSUE TITLE
sendTransaction hangs when sending contract data in PoA mode

### ISSUE THREAD

**Issue by tomconte** [ethcore/parity#3140]
Hi there,

I am trying to create a smart contract, originally using Truffle, connecting to a private PoA chain.

Here is the chain.json: https://gist.github.com/tomconte/00260418fcd4eecdd6e89078f15bd015

When running `truffle migrate`, it just hangs after sending the contract data transaction:

```
  Deploying Migrations...
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_sendTransaction",
   >   "params": [
   >     {
   >       "from": "0x133e5245e3e5ab3f65e73120b34cc29f0f7ba504",
   >       "gas": "0x47e7c4",
   >       "gasPrice": "0x174876e800",
   >       "data": "0x6060<snip>190f3"
   >     }
   >   ],
   >   "id": 1
   > }
```

Using Web3.js on the local host, and sending the transaction manually, it hangs too:

```
> web3.eth.sendTransaction({"from": "0x133e5245e3e5ab3f65e73120b34cc29f0f7ba504", "data": "0x6060<snip>90f3"})
```

The truffle debug log does not show anything useful.

Any help appreciated!

**Comment by keorn** [comment]
You might need to confirm the transaction through the [Trusted Signer](https://github.com/ethcore/parity/wiki/Secure-Transaction-Signer) which should let it through.

**Comment by tomconte** [comment]
Interesting! In a development environment, is there a way to disable the Trusted Signer, or sign using the command line?

**Comment by keorn** [comment]
Command line interface is not yet ready afaik, but you can use `personal_signAndSendTransaction`. `--no-signer` should disable the signer.

**Comment by tomconte** [comment]
Thanks! It works when using --no-signer (together with --unlock & --author)

**Comment by tomconte** [comment]
Sorry, spoke too fast :)

Now Truffle hangs differently, and I do see the transaction in the logs:

```
2016-11-03 16:18:24 UTC  DEBUG txqueue  Imported transaction to current: d6b53bfbfa763a270ab328e9e357a27b9a30093ea58daf3b1058806211d46909
2016-11-03 16:18:24 UTC  DEBUG txqueue  status: TransactionQueueStatus { pending: 1, future: 0 }
2016-11-03 16:18:24 UTC  DEBUG miner  Skipping adding transaction to block because of gas limit: d6b53bfbfa763a270ab328e9e357a27b9a30093ea58daf3b1058806211d46909 (limit: 3144658, used: 0, gas: 4712388)
```

Truffle does send 0x47e7c4 (4712388) worth of gas, however I am not sure where the limit (3144658 or 0x‭2FFBD2‬) comes from... The genesis chain.json has:

```
"gasLimit": "0x2fefd8"
```

Is this where the limit comes from?

**Comment by keorn** [comment]
By default the gas limit can adjust (determined by the "gasLimitBoundDivisor" engine param) so if the previous block was full it will go up.

**Comment by tomconte** [comment]
OK, I bumped up the gasLimit in the genesis and re-created the chain, which solved the problem. Thanks!

**Comment by rstormsf** [comment]
`Unknown flag: '--no-signer'`

**Comment by rphmeier** [comment]
@rstormsf Try `--no-ui`
