### ISSUE TITLE
Invalid number formatting on Transfer gas selection

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3171]
Sending ETH from Account A to account B works fine.
However, when turning ON 'advanced' mode and picking a gas price, the tx fails.

![screen shot 2016-11-04 at 11 27 02](https://cloud.githubusercontent.com/assets/738724/20002583/dc0923cc-a281-11e6-9c82-811b59f3ab15.png)

![screen shot 2016-11-04 at 11 26 27](https://cloud.githubusercontent.com/assets/738724/20002591/e07cdf5c-a281-11e6-87b9-d92e0b495a84.png)

![screen shot 2016-11-04 at 11 26 40](https://cloud.githubusercontent.com/assets/738724/20002594/e44fc838-a281-11e6-9e63-e91df85d8289.png)

![screen shot 2016-11-04 at 11 26 46](https://cloud.githubusercontent.com/assets/738724/20002598/e82cb556-a281-11e6-8b23-2b43ae346ce7.png)

**Comment by jacogr** [comment]
@ngotchac Need a fix and backport to beta ASAP - the number includes decimal places. (use toFixed(0) to format)
