### ISSUE TITLE
testing & building PRs is important but there is *no need* to test on every platform. make tests work on linux, but only build on windows and mac.

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3181]

**Comment by General-Beck** [comment]
Builds only  beta, stable, tags from https://github.com/ethcore/parity/commit/72a1db8d01d794cd8a80fad19b7998c9e1cd08c6
Remove darwin and windows test from https://github.com/ethcore/parity/commit/52ce4f9bc1ba567770aab22a4d98ae2aeb196e1e
