### ISSUE TITLE
 a full test and artefacts build of master *once* per day ("nightly") is needed.

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3184]

**Comment by General-Beck** [comment]
https://github.com/ethcore/parity/commit/3ae5ad1beadb47f2a0d92a6dc92c63356f8075d2
now in the process of developing

**Comment by General-Beck** [comment]
"Nightly" triggers enabled for master. Will run every night at 4.00 CET.
https://gitlab.ethcore.io/Mirrors/ethcore-parity/pipelines/3921
