### ISSUE TITLE
a simple script can be used to identify PRs that only alter files in the `/js/` path. in this case, don't do any rust compilation/testing.

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3185]

**Comment by General-Beck** [comment]
I need to specify the exact condition. in the development

**Comment by rphmeier** [comment]
This snippet will do the job: ```[[ `git diff master | grep ^diff | grep -v a/js/ | wc -l` -gt 0 ]] && echo Need to cargo test and build || echo Just Javascript tests and build```

**Comment by General-Beck** [comment]
crossed with this https://github.com/ethcore/parity/issues/3186

**Comment by General-Beck** [comment]
@arkpar @jacogr need review and test
from https://github.com/ethcore/parity/commit/86522c8f71e15797e06758c6989fe4f5bd668a35 in `master` and https://github.com/ethcore/parity/commit/db5f33510c603419cae878bbc8d524fd895173ab in `beta`
