### ISSUE TITLE
The gitlab CI should give success only when all components succeed (currently some components can fail and you'll still get a tick)

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3187]

**Comment by jesuscript** [comment]
made the context include the name of the build stage (build,test etc.), so there should be multiple ticks coming from gitlab per PR. Will look something like:
continuous-integration/gitlab-build
continuous-integration/gitlab-test 

Will leave it running for some time to see how it goes. If everyone is happy, will close this ticket.

**Comment by jesuscript** [comment]
replaced build stage with build name in the tick context

**Comment by jesuscript** [comment]
I think everyone is (still) happy. Closing :)

**Comment by rphmeier** [comment]
Yep, that's much nicer :)
