### ISSUE TITLE
Add 32-bit linux (i686) binary

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#3201]

**Comment by General-Beck** [comment]
ok, i prepare docker image and try build 
@arkpar Ubuntu 14.04 or 16.04 based?

**Comment by arkpar** [comment]
14.04 for maximum compatibility

**Comment by General-Beck** [comment]
https://gitlab.ethcore.io/Mirrors/ethcore-parity/builds/18147

**Comment by General-Beck** [comment]
add in beta and master
