### ISSUE TITLE
Where to get checksum from snapshot?

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3206]
Where to get checksum from snapshot magnet:?xt=urn:btih:E9B318B15016AAD261E925FF19AE14B30D1BACA3&dn=mainnet-2021235.snapshot ?

How to check validity of this snapshot?

**Comment by rphmeier** [comment]
I believe the magnet link contains the hash of the content and your bittorrent client will perform the validation for you.

**Comment by keuge** [comment]
But what is the right checksum of this snapshot with what i can recheck it? And is this sha256 or md5 or sha1. Why are you closing the question no matter the answer were not full?
