### ISSUE TITLE
Tagging contracts fails on first attempt

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3215]
I noticed the issue on the contracts tabs. It may apply in other places but it is harder to reproduce.

Symptom: If you add (watch) a new contract and set a single tag on it, it will be ignored. It you try again, then the tag is correctly applied.

To reproduce:
- Watch a new contract (The Multisig Wallet does the trick very well)
- Click on the contract in the list
- Type in some text for your tag
- Press ENTER
- Click SAVE

This is not a recent regression. I saw it already a while back but doubted if I really set the tag in the first place :)

**Comment by jacogr** [comment]
@ngotchac Could you please take a look?

**Comment by chevdor** [comment]
I just tested and it occurs as well when you deploy a contract.
