### ISSUE TITLE
Parity does not start:  Unknown api: ethcore

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3220]
I updated to d172c83 and I get the following message at start:
` Unknown api: ethcore`

**Comment by jacogr** [comment]
Just built latest - definitely works here. What are you doing when you get these errors? For master we have moved all ethcore.* API endpoints to parity.* to line up with the core product name.

**Comment by chevdor** [comment]
- pull master
- rebuilt
- started as usual as `target/release/parity --testnet ui``

and I get the message immediately. Nothing starts at all so I don´t even get the chance to click anywhere.

**Comment by chevdor** [comment]
The issue was an improper config for the IPC section.

I changed from:
```
[ipc]
disable = false
# path = "$HOME/.parity/jsonrpc.ipc"
apis = ["web3", "eth", "net", "personal", "ethcore", "traces", "rpc"]
```

to 
```
[ipc]
disable = false
# path = "$HOME/.parity/jsonrpc.ipc"
apis = ["web3", "eth", "net", "personal", "parity", "traces", "rpc"]
```

and the issue was solved.

**Comment by rphmeier** [comment]
@chevdor Good catch, glad you were able to solve it but many other users might have a little more difficulty pinpointing the issue.

@ethcore/core-devs 
Seems that we broke pre-existing config files -- once those are out in the wild we might have to be a bit more careful with changing CLI options.

**Comment by chevdor** [comment]
@rphmeier hey sure, no problem. Documenting the issue here (and the solution) is also good for the people who may experience similar issues in the future.

**Comment by jpritikin** [comment]
I got `Unknown api: rpcpersonal`. Where is the config file?

**Comment by chevdor** [comment]
@jpritikin on OS X, the file is located at:
`~/.parity/config.toml
`
I may be wrong but I don´t think Parity does create the file automagically. So unless you created this file, it should not be there. As I said, things may change/have changed in this regards.

**Comment by jpritikin** [comment]
Yeah, I don't have that file, but I still get the error.

**Comment by rphmeier** [comment]
@jpritikin Are you running with the `--geth` flag?

**Comment by jpritikin** [comment]
Yeah, is the `--geth` flag a problem?

**Comment by chevdor** [comment]
@rphmeier I tested as well and indeed, `--geth' causes the issue. see #3263
