### ISSUE TITLE
http://home.parity/ requests signer token

### ISSUE THREAD

**Issue by bjornwgnr** [ethcore/parity#3223]
Even though home.parity is being forwarded to 127.0.0.1:8180 it leads to a different UI instance.

_Chromium Version 52.0.2743.116 Built on Ubuntu, running on Ubuntu 16.04 (64-bit)_

> function FindProxyForURL(url, host) {
> 	if (shExpMatch(host, "home.parity"))
> 	{
> 		return "PROXY 127.0.0.1:8180";
> 	}
> 
> 	if (shExpMatch(host, "*.parity"))
> 	{
> 		return "PROXY 127.0.0.1:8080";
> 	}
> 
> 	return "DIRECT";
> }

**Comment by rphmeier** [comment]
I think this is because local storage is different, but not 100% sure.

**Comment by jacogr** [comment]
Th domains & localStore is different. We have an issue open to allow config of one domain from another trusted domain, so we can simplify this process. At the moment the same goes when you open a new browser, you need to re-auth.

It needs to and will get better.
