### ISSUE TITLE
UI doesn't accept signer tokens w/o dashes

### ISSUE THREAD

**Issue by bjornwgnr** [ethcore/parity#3224]
The UI (unlike the chrome extension) doesn't accept signer tokens w/o dashes.

Tokens are saved w/o dashes in 'authcodes' file.

**Comment by gavofyork** [comment]
rather than adding more complexity here, i'd prefer to focus on functionality which will mean the user never needs to interact with `parity signer new-token` or `authcodes`.

in the meantime, it's not too difficult to insert a few `-` characters.

**Comment by jacogr** [comment]
Fixed in master already a while ago (however https://github.com/ethcore/parity/pull/3945 fixes current issues)
