### ISSUE TITLE
Problem with simple one-line installer

### ISSUE THREAD

**Issue by sandakersmann** [ethcore/parity#3225]
I installed with entering this in terminal on Linux Mint 17.3:

`bash <(curl https://get.parity.io -Lk)`

It installs just fine, but I get this when I try to run Parity:

```
$ parity
parity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by parity)
parity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by parity)
parity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by parity)
```

**Comment by rphmeier** [comment]
Possibly related to a rocksdb version upgrade? The binaries we distribute should be built on relatively old distros for max compatibility. Something like the holy build box (http://phusion.github.io/holy-build-box/) might be useful here.

**Comment by arkpar** [comment]
Should work now. The link in the one-line script was pointing to a package compiled for Ubuntu Xenial. This is now changed to Trusty which should be compatible with Mint

**Comment by gavofyork** [comment]
please reopen if it's not now working.

**Comment by sandakersmann** [comment]
It is working now on 1.4.0 :)

**Comment by canadadennischen** [comment]
Hi all,
Unfortunately, I saw these 2 error when I just installed Parity now (in Ubuntu 14.04).
Please help. Thanks in advance

-------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0    175      0 --:--:-- --:--:-- --:--:--   175
100  2990  100  2990    0     0   2667      0  0:00:01  0:00:01 --:--:--  2667
Release selected is: beta
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   400  100   400    0     0    376      0  0:00:01  0:00:01 --:--:--   377
parity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by parity)
parity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by parity)
Upgrading parity from  to 1.8.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.1M  100 10.1M    0     0  26.6M      0 --:--:-- --:--:-- --:--:-- 26.6M
sudo: unable to resolve host 150-95-141-161
(Reading database ... 92703 files and directories currently installed.)
Preparing to unpack .../parity_1.8.2_amd64.deb ...
Unpacking parity (1.8.2) over (1.8.2) ...
Setting up parity (1.8.2) ...

**Comment by 5chdn** [comment]
@canadadennischen please consider building from source.

**Comment by canadadennischen** [comment]
Hi,
Thanks.
I solve it by using Ubuntu 16.04 (but not 14.04 on a cloud service which may have issue on their image).
Thanks anyway.
rgds,
Dennis
