### ISSUE TITLE
Status page HTML encodig

### ISSUE THREAD

**Issue by aleixmorgadas** [ethcore/parity#3228]
At Status page, there is an encoding issue with _Extradata_ field

Image attached:
![parity status page](https://cloud.githubusercontent.com/assets/5518197/20057188/8258856e-a4ea-11e6-83de-7b907f315755.png)

```
$> parity --version
  version Parity/v1.3.9-beta/x86_64-linux-gnu/rustc1.12.1
```

**Comment by rphmeier** [comment]
This problem doesn't appear to exist in the new UI.

We've deprecated the UI which is present in our 1.3.x series, and it will be replaced by our new, much shinier UI in the 1.4.x series, which will be released later today if all goes well.

**Comment by aleixmorgadas** [comment]
Perfect! :ok_hand:
