### ISSUE TITLE
CI should build mac installer

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3250]
Use file `mac/Parity.pkgproj` with instructions:
http://s.sudre.free.fr/Software/documentation/Packages/en/Project_Building.html#4

**Comment by General-Beck** [comment]
what is the file name format should we use?

**Comment by General-Beck** [comment]
https://vanity-service.ethcore.io/parity-binaries?version=beta&architecture=x86_64&os=darwin
https://gitlab.ethcore.io/Mirrors/ethcore-parity/builds/18628
build passed
