### ISSUE TITLE
Parity 1.4.0 restore snapshot crashes

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#3251]
Partiy 1.4.0 on Ubuntu linux 64 bit crashes after it completes the State Chunks and before it starts the Block Chunks.

I can't sync normally because of the DoS attacks from a few weeks ago so I attempted to restore from snapshot instead, I created a snapshot from latest block on Windows 1.4.0 parity, then attempted to restore that snapshot into linux Parity 1.4.0 with crash/core dump as mentioned above.

**Comment by slothbag** [comment]
I tried it again and this time in managed to do the block chunks as well but then crashed with `pure virtual method called`

I then started up Parity like normal and it appears to have successfully continued on from the point of the snapshot.

**Comment by gavofyork** [comment]
could you post the full logs please?

**Comment by slothbag** [comment]
Sorry, I didn't copy it, it didn't actually say very much.. just pure virtual method called and program aborted and then it went to command prompt.  The node seems pretty stable now so the error must have been in some housekeeping routine.   If I see it again i'll add any logs.

Feel free to close this until then

**Comment by rphmeier** [comment]
@arkpar maybe something's wrong with the `DBRestore` implementation; sounds like the old DB might be getting dropped twice somehow.

**Comment by rphmeier** [comment]
The underlying cause was addressed in https://github.com/ethcore/parity/pull/3286 I believe. Please reopen if the issue persists.
