### ISSUE TITLE
Parity 1.4.0: Windows installation fails: VCRUNTIME140.dll missed

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethcore/parity#3253]
I believe the following happens: The installer does not install the needed runtime VCRUNTIME140.dll. That leads to a system error of ptray.exe during start. 

After looking for the DLL I found it in C:\Windows\System32. It seems that the used Parity start script does not include this directory in the loader path ...? Although the PATH variable as set on my PC does include the directory!

**Comment by arkpar** [comment]
Windows installer hotfix has been uploaded. Please uninstall, download and run the installer again.

**Comment by SteffenIvanhoe** [comment]
Parity has not installed an "unistall" method or script. It is not shown in the Windows list of installed programs. How do I uninstall it?

**Comment by SteffenIvanhoe** [comment]
Let me know when you "really" update the installer!

**Comment by arkpar** [comment]
The link has been updated. Sorry for the confusion. There should be an entry in the list of installed programs named "Ethcore - Parity..." that allows to uninstall from control panel.

**Comment by SteffenIvanhoe** [comment]
It works now. Although it is not a good idea to start a process in the background which creates a heavy load on the system without letting the user know about all that. I was surprised what is going on and had to use system tools to find out.
