### ISSUE TITLE
Checksum on Windows didnt match

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3256]
On git ef66696508fe6aeeb399a088c93438c4
On machine MD5 B870AE9B276A4C7B78657F8207A35C40

**Comment by derhuerst** [comment]
I assume you checked the `md5`-Checksum of [`InstallParity.exe` from the latest beta release](http://d1h4xl4cr1h0mo.cloudfront.net/v1.4.0/x86_64-pc-windows-msvc/InstallParity.exe)?

I can confirm that, the hash is wrong.

```shell
curl 'http://d1h4xl4cr1h0mo.cloudfront.net/v1.4.0/x86_64-pc-windows-msvc/InstallParity.exe' | md5
```

```
b870ae9b276a4c7b78657f8207a35c40
```

**Comment by keuge** [comment]
Yes thats correct!

**Comment by keorn** [comment]
Updated, there was a Windows installer hotfix and it was not updated.
