### ISSUE TITLE
Insecure link between Parity 1.4.0 client and server in Windows 10

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethcore/parity#3262]
After installing Parity 1.4.0 on Windows 10 I was surprised that nothing visible got started but the system immediately created a huge load in the background. Not a good idea!

I looked for and found the newly created "Parity Ethereum" link in the startup menu. To my surprise, it points to an insecure web server (no HTTPS) and asks for an important password. This does not make any sense at all. Users get preached all the time to never put something private or critical into an insecure web page. I assume that the implemented logic is all local but how should I or any other user check that? HTTPS is a must for such a web page!

**Comment by derhuerst** [comment]
Parity serves the UI *locally* over HTTP. The preaching no to send any credentials over HTTP (unencrypted) is correct, but is only valid for *remote* servers like e.g. `wikipedia.org`.

Serving over HTTPS *locally* is in fact not possible with the SSL certificate system currently in place, without putting the private key into the source code of Parity. One way would be to generate a self-signed certificate and add it to the operating systems list of trusted certificates, that however is considered a bad practice as well.

This problem should probably be addressed by a proper explanation that parity runs locally and therefore using HTTP is fine.

Side note:

> In following releases, we will continue to extend HTTP warnings, for example, by labelling HTTP pages as “not secure” in Incognito mode, where users may have higher expectations of privacy. Eventually, we plan to label all HTTP pages as non-secure, and change the HTTP security indicator to the red triangle that we use for broken HTTPS.

["Moving towards a more secure web" – Google Online Security Blog](https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html)

**Comment by rphmeier** [comment]
@SteffenIvanhoe The installer starts parity in the background with the `--passive` mode. This is designed to use practically zero system resources. I suppose it might have also started warp syncing right away, in which case you might have to give it a few minutes to finish doing that. It definitely isn't perfect yet, which is why the installers/system service features are still experimental -- by our next release we should have ironed out all the UX issues here.
