### ISSUE TITLE
2nd use of "Parity Ethereum" client (V1.4.0) on Windows 10 fails

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethcore/parity#3265]
I created a test account. Closing the web page and opening it again delivers "Unable to make a connection to the Parity Secure API. To update your secure token or to generate a new one, run parity signer new-token and supply the token below".

Makes no sense or should it be that (unusable) way?

I use Chrome, latest version. I did not restart the browser, only closed and re-opened the Parity tab. Restarting the browser made no difference.

**Comment by tomusdrw** [comment]
Fixed in #3289
