### ISSUE TITLE
crash Parity/v1.4.0-beta-170bd03-20161107/x86_64-linux-gnu/rustc1.12.1parity on json call

### ISSUE THREAD

**Issue by jo-tud** [ethcore/parity#3267]
When I call `getBlockByNumber` with a block as parameter and transactions included on a parity node, it crashes. The node was not yet fully synced, but it had already synced the requested block. 
This was the command to start parity:
`parity --tracing on --mode active --pruning archive`
For me this is reproducible.

`2016-11-08 13:27:39 UTC Syncing #2370963 797b…9ec1      6 blk/s   65 tx/s   6 Mgas/s       0+ 5958 Qed   #2376924    0/ 8/25 peers    179 KiB db  875 KiB chain   52 MiB queue    2 MiB sync
thread '<unnamed>' panicked at 'DecodeError: RlpExpectedToBeList, a0d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3', util/rlp/src/rlpin.rs:120
stack backtrace:
   1:     0x560bad64df19 - <unknown>
   2:     0x560bad65698c - <unknown>
   3:     0x560bad655859 - <unknown>
   4:     0x560bad655f48 - <unknown>
   5:     0x560bad655da2 - <unknown>
   6:     0x560bad655d10 - <unknown>
   7:     0x560bad04e159 - <unknown>
   8:     0x560bad1a8388 - <unknown>
   9:     0x560bacc9da2e - <unknown>
  10:     0x560bacb7978b - <unknown>
  11:     0x560bacb1983c - <unknown>
  12:     0x560bacf6a159 - <unknown>
  13:     0x560bacf6b45f - <unknown>
  14:     0x560bacf6a829 - <unknown>
  15:     0x560bacf6d88c - <unknown>
  16:     0x560bacf48d3e - <unknown>
  17:     0x560bacf40f35 - <unknown>
  18:     0x560bacf410a0 - <unknown>
  19:     0x560bacf40df5 - <unknown>
  20:     0x560bacf3ee6c - <unknown>
  21:     0x560bacf3d0c6 - <unknown>
  22:     0x560bacf3063d - <unknown>
  23:     0x560bacf385cf - <unknown>
  24:     0x560bacf2fed7 - <unknown>
  25:     0x560bad65e476 - <unknown>
  26:     0x560bacf3a761 - <unknown>
  27:     0x560bad6544f2 - <unknown>
  28:     0x7fca246cd709 - start_thread
  29:     0x7fca2517382c - clone
  30:                0x0 - <unknown>
2016-11-08 13:27:43 UTC Finishing work, please wait...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x560bad64df19 - <unknown>
   2:     0x560bad65698c - <unknown>
   3:     0x560bad655859 - <unknown>
   4:     0x560bad655f48 - <unknown>
   5:     0x560bad655da2 - <unknown>
   6:     0x560bad655d10 - <unknown>
   7:     0x560bad655c91 - <unknown>
   8:     0x560bad69338f - <unknown>
   9:     0x560bad325155 - <unknown>
  10:     0x560bad33b0fd - <unknown>
  11:     0x560bacf51f49 - <unknown>
  12:     0x560bacd022ab - <unknown>
  13:     0x560bacd0dac5 - <unknown>
  14:     0x560bacd1852d - <unknown>
  15:     0x560bad65e476 - <unknown>
  16:     0x560bad654fd2 - <unknown>
  17:     0x7fca2508d82f - __libc_start_main
  18:     0x560bacadf4ad - <unknown>
  19:                0x0 - <unknown>

`

**Comment by arkpar** [comment]
What was the block number you were requesting?

**Comment by mtbitcoin** [comment]
I can confirm this issue with beta

2016-11-08 23:24:32 UTC Starting Parity/v1.4.0-beta-170bd03-20161107/x86_64-windows-msvc/rustc1.12.0
2016-11-08 23:24:32 UTC State DB configuation: fast +Trace
2016-11-08 23:24:32 UTC Operating mode: active
2016-11-08 23:24:32 UTC Configured for Frontier/Homestead using Ethash engine
2016-11-08 23:24:39 UTC Public node URL: enode://920a46addf49e477344e6745d3f0a31
897e3a35f7034d793bcc4413d011db6e287a2d6dc3795d18573bc01f92f5d09f433fc40b38e07db3
1f57d3410e9338b2e@127.0.0.1:30305
thread '2016-11-08 23:24:41 UTC Imported #2591958 59b8.c7e2 (9 txs, 0.19 Mgas, 5
.63 ms, 1.53 KiB) + another 1 block(s) containing 2 tx(s)<unnamed>
' panicked at 'DecodeError: RlpExpectedToBeList, a07c928482751358f67a1dbbc79902f
5daf206697e1fa6512a5e20dfabe5e8949b2016-11-08 23:25:03 UTC     0/11/25 peers
  2 MiB db    4 MiB chain  0 bytes queue   22 KiB sync',
util\rlp\src\rlpin.rs:120
2016-11-08 23:28:19 UTC     0/16/25 peers      2 MiB db    7 MiB chain  0 bytes
queue   22 KiB sync
2016-11-08 23:28:19 UTC Syncing #2591963 d0cb.7615      0 blk/s    0 tx/s   0 Mg
as/s       4+    0 Qed   #2591871    1/23/25 peers      2 MiB db    7 MiB chain
  10 KiB queue   22 KiB sync
2016-11-08 23:28:19 UTC Syncing #2591963 d0cb.7615      0 blk/s    0 tx/s   0 Mg
as/s       5+    0 Qed   #2591827    1/23/25 peers      2 MiB db    7 MiB chain
  11 KiB queue   22 KiB sync
stack backtrace:

**Comment by tomusdrw** [comment]
Have you synced on new version from scratch or did you use some older DB?

**Comment by arkpar** [comment]
Reproduced in master

**Comment by mtbitcoin** [comment]
@arkpar Issue still persists in Master. Is a resync required ?

2016-11-10 01:45:07  Starting Parity/v1.5.0-unstable-29add4e-20161109/x86_64-windows-msvc/rustc1.12.0
2016-11-10 01:45:07  State DB configuation: fast +Trace
2016-11-10 01:45:07  Operating mode: active
2016-11-10 01:45:07  Configured for Frontier/Homestead using Ethash engine
2016-11-10 01:45:08  Public node URL: enode://7c81c7305c075e81399897e500099565e733cfb67e7c2034c7b52fc73b769bd832f6c29d31c07541c57d083b8d1f01228a01257fa794c87bea36a7c2bf99a771@127.0.0.1:30305
2016-11-10 01:45:17  Imported #2596515 da4d…86fd (10 txs, 0.21 Mgas, 4.92 ms, 1.64 KiB)
thread '<unnamed>' panicked at 'DecodeError: RlpExpectedToBeList, a02b29bd3fd44b44f5499b3bbdfa918a3d3c48836a5fbcd1c024a979a89bac25e6', Users\Matthew\.cargo\git\checkouts\parity-6ba620efeffb2216\master\util\rlp\src\rlpin.rs:120
stack backtrace:

**Comment by arkpar** [comment]
@mtbitcoin commit 29add4e from your version number is a bit old and does not have the fix. Please try rebuilding the latest.

**Comment by mtbitcoin** [comment]
@arkpar that worked, thanks!
