### ISSUE TITLE
Unknown api: rpcpersonal

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#3270]
`parity --geth --jsonrpc-hosts="all" --rpcaddr=0.0.0.0 --dapps-interface 192.168.0.1`

Unknown api: rpcpersonal

**Comment by sammy007** [comment]
an you already properly test CLI args parser? This coin is a big PITA and every upgrade of parity seems like even bigger PITA.

**Comment by keorn** [comment]
Its not a bug with arg parsing, it should be fixed [here](https://github.com/ethcore/parity/pull/3260/files#diff-95a85c2b131cc7f0d6efba3d6bbcb211L551). There are tests for parsing present if something slips through, we will add more.

**Comment by rphmeier** [comment]
Duplicate of #3263
