### ISSUE TITLE
How to create contract with several owners in Parity 1.4 GUI?

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3273]
How to create contract with several owners in Parity 1.4 GUI?

**Comment by jacogr** [comment]
When you deploy a contract, you specify the account that the contract is to be deployed from. Assuming that the contract has a function to call to add addresses, you can make a call to that in subsequent executions.

**Comment by keuge** [comment]
Can i do that with Parity UI?

**Comment by derhuerst** [comment]
@keuge Sure! You can deploy a new contract in the "contracts" section. On any deployed contract, you can call static & non-static functions in the "individual contract" view.

**Comment by keuge** [comment]
How can i choose owners of the contract?

**Comment by derhuerst** [comment]
In the Ethereum blockchain, users can create arbitrary contracts by issuing special transactions.

These contracts may have (and typically have) an `owner` field. In your contract, you may adapt that field or add more fields to hold multiple owners. With most contracts, you're the owner by default, as the sender of the contract creation transaction (see [e.g. `Registry.sol`](https://github.com/ethcore/contracts/blob/df32dce/Registry.sol#L13)).

**Comment by keuge** [comment]
I need to make 3 owners for 1 contract. Can i do that with Parity 1.4.1 GUI?

**Comment by derhuerst** [comment]
As I said, that depends on the contract code. Parity as well as its GUI doesn't directly have the notion of one or more owners, it can just call functions on contracts. Check the [Solidity introduction](https://solidity.readthedocs.io/en/develop/) for more information.

**Comment by derhuerst** [comment]
What you would typically do:

- Write a contract that has one or more fields to store the addresses of those 3 owners.
- Deploy it using the Parity GUI.
- Put the other two owners in place by calling the appropriate contract function(s), using the Parity GUI.

**Comment by derhuerst** [comment]
Please reopen this issue if you come across issues that are related to Parity UI & calling contracts.

**Comment by keuge** [comment]
I cant create Contract in Parity UI like it creates in Mist UI when you creating contracts with several owners and set the maximum amount that can be sendede without contract owners.

I dont see how to do that on Parity UI.

**Comment by derhuerst** [comment]
I don't have experience with deploying contracts using Mist. Maybe @ngotchac can help.

**Comment by jacogr** [comment]
Ok, I have compiled the `wallet.col` file locally and tried deploying via the UI. We definitely have an enhancement here. The issue in this case is that for the constructor parameters we don't handle the array of owner addresses correctly. So while easy to watch, we are falling down a bit deploying these kinds of contracts - mostly since our constructor parameters have been simple types.

We need an enhancement for that. Logged it at https://github.com/ethcore/parity/issues/3314

The good news is that proper multisig support is on the cards (https://github.com/ethcore/parity/issues/3282), so you won't need to fiddle with contracts yourself.

**Comment by ngotchac** [comment]
Plus, if we have contract snippets in the _Write Contract_ section, we could easily load `wallet.sol`, compile it, deploy, profit.
