### ISSUE TITLE
One-line installer on mac fails

### ISSUE THREAD

**Issue by tjsaw** [ethcore/parity#3277]
Following error after running the one line installer: bash <(curl https://get.parity.io -Lk)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: No such keg: /usr/local/Cellar/parity

==> Parity is missing

==> Installation failed

**Comment by 5chdn** [comment]
Some issue with installing homebrew, closing as dupe of #2474
