### ISSUE TITLE
Brew - trouble installing

### ISSUE THREAD

**Issue by tjsaw** [ethcore/parity#3278]
Following error encountered after using: `brew uninstall --force parity && brew install parity —beta`
```
Error: /usr/local is not writable. You should change the ownership
and permissions of /usr/local back to your user account:
  sudo chown -R $(whoami) /usr/local
Error: No available formula with the name "—beta" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
==> You haven't updated Homebrew in a while.
A formula for —beta might have been added recently.
Run `brew update` to get the latest Homebrew updates!
```

**Comment by rphmeier** [comment]
(this is more of a local configuration or brew error than parity issue)

**Comment by rphmeier** [comment]
This thread might have your answer: https://github.com/Homebrew/legacy-homebrew/issues/49895

**Comment by derhuerst** [comment]
@tjsaw Where did you copy this from? Actually it may be our issue.

**Comment by keorn** [comment]
@derhuerst chevdor in Gitter was posting that as a solution

**Comment by derhuerst** [comment]
@keorn No, that's a different and very common issue. Usually `brew doctor` will tell you how to fix it.

I am talking about the fact that in the copy-pasted command above, `—beta` is actually not an option, because instead of `--`, `—` is used.

**Comment by keorn** [comment]
True, solved either way.

**Comment by rphmeier** [comment]
@derhuerst Good eye :) didn't see that earlier.

**Comment by derhuerst** [comment]
We just have to make sure there's no auto-corrected `–` in our docs or chat posts. Such a tiny detail will confuse users a lot.

**Comment by tjsaw** [comment]
Soz my bad
