### ISSUE TITLE
Client service error: Client(Database("Invalid argument

### ISSUE THREAD

**Issue by mhaythem** [ethcore/parity#3280]
can anyone help me , I get this message when I try to open parity ( I try uninstall )
![screenshot_2](https://cloud.githubusercontent.com/assets/20526117/20106201/9d697fe4-a5d4-11e6-8ee6-47269d1d9b63.png)

**Comment by rphmeier** [comment]
This is a symptom of database corruption; you can try deleting your chain data (located in `Users\Username\.parity\906...` for mainnet) and see if it helps.

**Comment by mhaythem** [comment]
thanks I manged to sync 
but I get this message in browser 
![screenshot_2](https://cloud.githubusercontent.com/assets/20526117/20107114/a3c65512-a5d7-11e6-97d3-2cc5f6425c4a.png)

**Comment by rphmeier** [comment]
Yep, this message is tailored a bit to Darwin/Linux -- on Windows you will need to run `parity.exe signer new-token`. This will output a token which the UI requires to establish a secure connection with the node.

**Comment by rphmeier** [comment]
(assuming fixed; reopen if the issue persists)
