### ISSUE TITLE
OS X installer fails with user-defaults file missing mode.timeout

### ISSUE THREAD

**Issue by davebryson** [ethcore/parity#3285]
Installed with the new 1.4 OS X installer.   Node doesn't start.  ~/.parity/log.err shows:

invalid/missing mode.timeout value at line 1 column 66

the user_defaults file contains the following information:

{"fat_db":false,"mode":"passive","pruning":"fast","tracing":false}

Looks like the user_defaults serializer is not adding the requires 'mode.timeout' key

NOTE: manually fixing this, then causes:

invalid/missing mode.alarm value at line 1 column 87

**Comment by rphmeier** [comment]
This has been fixed in #3260
