### ISSUE TITLE
invalid/missing mode.timeout value - beta 1.4.0 / macos sierra

### ISSUE THREAD

**Issue by kayagoban** [ethcore/parity#3287]
After building from the beta branch, with cargo build --release

```
sente:parity cthomas$ target/release/parity
invalid/missing mode.timeout value at line 1 column 66
```

**Comment by rphmeier** [comment]
Did you by chance install using the installer previously? This is similar to #3258, which is addressed in #3260.

**Comment by kayagoban** [comment]
Yes, I did

**Comment by rphmeier** [comment]
Try deleting your `user_defaults` file -- it should be located in `~/.parity/906.../`.

**Comment by kayagoban** [comment]
I applied the changes in  https://github.com/ethcore/parity/pull/3260/commits/f049b4a5963a21f28bbf2baf04165d7b02c610d7

and everything just started working.

**Comment by rphmeier** [comment]
That works too!
