### ISSUE TITLE
Import of ancient block causes syncing to stall indefinitely

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#3288]
Reported by @boysie123

![Captured logs](https://files.gitter.im/ethcore/parity/KtGH/image.png)

**Comment by rphmeier** [comment]
(this may be more severe -- could be that it stops syncing as well, but the higher numbers in the reorg message lead me to believe it's just a broken informant)

**Comment by rachyandco** [comment]
![screenshot from 2016-11-15 02-13-42](https://cloud.githubusercontent.com/assets/2358699/20289257/29e49676-aad9-11e6-8ef3-f74af6472792.png)

we are experiencing the same issue. We are running  Parity//v1.4.3-beta-08a4220-20161114/x86_64-linux-gnu/rustc1.13.0 (it was acting the same way on 1.4.2-beta)

**Comment by gavofyork** [comment]
also reported on gitter recently. terminal dump clearly showing that a restart began from the block immediately after the attempted ancient block import: https://files.gitter.im/ethcore/parity/xfpQ/Terminal-Saved-Output .

**Comment by arkpar** [comment]
Fixed by #3519
