### ISSUE TITLE
eth_sign(address, sha3(msg)) should be eth_sign(address, msg)

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3297]
Hashing should be done internally to prevent chosen plaintext attacks.

See discussions here:
https://github.com/ethereum/go-ethereum/pull/2940

**Comment by gavofyork** [comment]
happy enough with this, but not sure if it's really a badass attack strategy since it all has to go through the trusted signer anyway.

**Comment by gavofyork** [comment]
@tomusdrw is this done already?

**Comment by tomusdrw** [comment]
Nope, not yet. Will do today.
