### ISSUE TITLE
UI is always accessing `127.0.0.1:8080`

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3301]
Use case:
`parity --dapps-interface 192.168.0.1 --dapps-port 8000 --signer-interface 192.168.0.1`

Should serve secure UI on `http://192.168.0.1:8180` and UI should be accessing `http://192.168.0.1:8000/` for dapps/content.

**Comment by jacogr** [comment]
Additional use-cases split into https://github.com/ethcore/parity/issues/3337
