### ISSUE TITLE
Deserializing empty string as empty bytes.

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3309]
Got error when trying to send eth from one wallet to another with paryty 1.4.1

`parity --geth`

got

> Deserializing empty string as empty bytes. This is a non-standart behavior that will be removed in future versions. Please update your code to sent @0x" instead.

**Comment by keuge** [comment]
Restart solved the issue. But what was that?

**Comment by rphmeier** [comment]
The `--geth` flag allows for more lenient byte serialization to support non-standard behavior in Mist. If you're using the Parity Wallet you should not be using `--geth`.

Note: you might find [our gitter room](https://gitter.im/ethcore/parity) useful for answering these kinds of questions.
