### ISSUE TITLE
Make sure TokenReg addresses are indeed ECR20 tokens before registering

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3320]
i.e. a user could register the TokenReg address, as has hapenned

**Comment by ngotchac** [comment]
Ok so what happens is that there is no way (as far as I know) to check if a method exists. The only thing I can think of is to check that the balance is actually > 0. Is that ok ?

**Comment by jacogr** [comment]
Well, if we could call/trace e.g. transfer or just get the value from `totalSupply` (i.e. things that are available in the public interface and returns info that is valid)

**Comment by ngotchac** [comment]
So `totalSupply` would return `0` even if the method doesn't exist in the contract.
