### ISSUE TITLE
Ubuntu 14.01 with Rust 1.12.1 build fails.

### ISSUE THREAD

**Issue by davembg** [ethcore/parity#3327]
rpc/src/v1/helpers/auto_args.rs:67:20: 67:22 error: expected type, found `&`
rpc/src/v1/helpers/auto_args.rs:67 				fn $m_name ( $($p)* ) $( -> Result<$out, Error> )* ;

**Comment by rphmeier** [comment]
@davembg I am currently running ubuntu `16.10` and do several builds daily using rustc `1.12.1` with no issues. Our CI as well uses rustc `1.12.1`, on `14.04` so i'm very surprised to hear this.

**Comment by tomusdrw** [comment]
Looks like an issue with old `rustc` version, could you double check rust version in `parity` directory (perhaps an override?)?

**Comment by davembg** [comment]
Yeah, that's likely - cargo -V is 0.12.0.
oops - close it. thanks a bunch for the help:)
