### ISSUE TITLE
Optimise dapps loading, content display as soon as avilable

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3339]
Chevdor @chevdor 12:01
Are you aware of the regression in parity that makes the DAPPS list load very slowly if at all? (I built using —debug this time). I have 18 dapps and 12 visible. It looks to me that dapps loading is no longer done at start but when the tab is activated while not caching the data. If there is issue yet, I will open a ticket. Just let me know.

Jaco Greeff @jacogr 12:49
The dapps list loading was always done when opening the tab. With loading external network manifests we quite probably slowed things down a bit to simplify the logic - can definitely look to optimise it, we have some additional things that we need to add there so dove-tailing that would be good.
I'll log an issue to see how we can do more things in parallel and not wait for external resources before displaying what we do have and know about.

**Comment by chevdor** [comment]
Oh I see, then you may want to test the case when one or more manifests are missing (which is my case). The first load is really much longer than before. It used to fee instant, now it is around 7~10s on a good machine. After a few loads, it goes down to 1~4s which is still very visible.

**Comment by jacogr** [comment]
I actually have some "broken on purpose" dapps in my ~/.parity/dapps as well - missing images, missing manifests.
