### ISSUE TITLE
Missing OSX installer

### ISSUE THREAD

**Issue by ramvi** [ethcore/parity#3343]
[The website](https://ethcore.io/parity.html) says Sample Parity on OSX: Brew or [Installer, but there is no OSX installer](https://github.com/ethcore/parity/releases). 

When I'm first in here and reporting an issue; it's now called MacOS, not OSX.

**Comment by derhuerst** [comment]
Thanks for reporting this!

The (mac)OS (X) installer is still considered experimental. You can get the current build from http://d1h4xl4cr1h0mo.cloudfront.net/v1.4.1/x86_64-apple-darwin/parity-1.4.0-osx-installer-EXPERIMENTAL.pkg however.

We will release `1.4.2` very soon, which will include the installer. Then, there will also be a link in the release page.

**Comment by ramvi** [comment]
That WAS very soon!

tor. 10. nov. 2016 kl. 15.31 skrev Jannis Redmann <notifications@github.com
