### ISSUE TITLE
Dropping name in Name registry address app

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3349]
Registered name in global name registry address app for 1 ETH. Then dropped name. So this means right now the name that i registered is now avaliable for network again? Also will my ETH get back after i make drop name?

**Comment by derhuerst** [comment]
> Registered name in global name registry address app for 1 ETH. Then dropped name. So this means right now the name that i registered is now avaliable for network again?

[Should be, yes](https://github.com/ethcore/contracts/blob/df32dce/Registry.sol#L48-L52).

> Also will my ETH get back after i make drop name?

Right now, this is not part of the contract.

**Comment by keuge** [comment]
How can i get back my ETH?)

**Comment by derhuerst** [comment]
@keuge

You can't. The current deployment of the `Registry.sol` contract only let's the `owner` drain the ETH.

If you're talking about the Testnet (Morden), there's an easy way to get new Ether: Open `http://icarus.parity.io/rain/<your-testnet-address>`.

**Comment by derhuerst** [comment]
I will put a message into the Registry dapp to inform users about the implications of registering & dropping names.

**Comment by keuge** [comment]
No, its not test net.

How can i register name again with that ETH? I dont want to spend 2 ETH on it.)

**Comment by gavofyork** [comment]
you'd normally need to pay the fee again. however we might take pity on you just this once :-P

**Comment by keuge** [comment]
answered in gitter)

**Comment by keuge** [comment]
Thanks! Questions resolved.
