### ISSUE TITLE
DAPP: Handle missing manifest.json

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3350]
Currently, the name and version for DAPPs missing a manifest default to usable values expect the DAPP logo. Using a default DAPP logo and avoiding the 404 error due to the missing logo would be good.

Knowing that the `.app` seems to be a convention, I would also propose to strip it out for the display.

![screen shot 2016-11-10 at 17 26 44](https://cloud.githubusercontent.com/assets/738724/20185041/e4ce8338-a76a-11e6-93c0-ec0bed2d42ba.png)

**Comment by jacogr** [comment]
We have addressed this while fixing the slow loading - should go in today.
