### ISSUE TITLE
Mismatched ID in response to invalid RPC request

### ISSUE THREAD

**Issue by kumavis** [ethcore/parity#3353]
if you forget to set the `"jsonrpc": "2.0"` parameter in the RPC request body, the response error is slightly broken:
1) response has null id
2) response error has null data field (?)
3) response error is not clear

failure example (try it!):
```
curl -H "Content-Type: application/json" -X POST --data '{"id":120,"method":"eth_getStorageAt","params":["0x37d65ca0754f12c7eec1c86b0915fba9fcbda131","0x68fb8e7cad479ccc9244a179d64897454189fd25db04e15d3a5135327a17597f","0x27b7c1"]}' https://mainnet.infura.io

{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request","data":null},"id":null}
```

success example
```
curl -H "Content-Type: application/json" -X POST --data '{"id":120,"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0x37d65ca0754f12c7eec1c86b0915fba9fcbda131","0x68fb8e7cad479ccc9244a179d64897454189fd25db04e15d3a5135327a17597f","0x27b7c1"]}' https://mainnet.infura.io

{"jsonrpc":"2.0","result":"0x000000000000000000000001446fa0c8ead753c7abf0b821f90d4338e72de380","id":120}
```

**Comment by rphmeier** [comment]
I think only the mismatched `id` is an issue.

As specified here: http://www.jsonrpc.org/specification#request_object

**Comment by kumavis** [comment]
`error.data`
> This may be omitted.

no reason to add it if theres no data for it

**Comment by rphmeier** [comment]
@kumavis while true, it's simpler with the serialization framework we use to have it be present and null.
