### ISSUE TITLE
Latest Parity 1.4.2 excessive bandwidth usage

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#3358]
Latest Parity is using a sustained 2MiB/sec download even on a fully sync'd node.  Each peer connections is using 50Kb-100Kb-200Kb+ downloads!

This is not right.

**Comment by tomusdrw** [comment]
Did you use `--warp` sync?

**Comment by slothbag** [comment]
Nope

**Comment by arkpar** [comment]
Could you post console output?

**Comment by slothbag** [comment]
I didn't save the output, but it was no different to normal.. just showing each new block every 15 seconds

**Comment by arkpar** [comment]
Normally Parity shows each new block as soon as it arrives and not every 15 seconds. It is hard to diagnose this without any additional information. Have you used warp sync or restored from a snapshot before? What is your OS and what method did you use to install Parity?

**Comment by slothbag** [comment]
Windows, No warp sync.  Cant remember if I used snapshot or not.

If I get more info i'll post it.

**Comment by arkpar** [comment]
Have you used the windows installer?  It uses warp sync automatically. After the sync is complete Parity still downloads the historical blocks in the background. That might take a few hours, but after it is over bandwidth and CPU usage should be back to minimum.

**Comment by slothbag** [comment]
Ahh, it could be something like that. I did use the new installer. I'll check it out
