### ISSUE TITLE
Address in book doesn't refresh the balance while syncing

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3360]
```
Christoph @cniemann 10:51
Checking out the new 1.4 UI, it looks much better, and the warp sync is really great. 
I imported an address into the address book that has some ether in it. However, the addressbook shows it with the message: There are no balances associated with this account. Is that the intended behavior?

Tomasz Drwięga @tomusdrw
@cniemann Are you fully synced (to the right network?)? Does it show your balance correctly after refresh?

Christoph @cniemann 11:09
@tomusdrw Ah, the refresh was missing on my part. Thanks.

Christoph @cniemann 11:14
@tomusdrw I might not have been synced fully when I navigated to the parity UI at first. However, I certainly was a bit later. There was no such thing like an automatic refresh on the UI side.
```

**Comment by jacogr** [comment]
Ok, this shouldn't happen - balances should update automatically. There is probably an issue with the new address not being added to the list of those that balances are retrieved for.

**Comment by derhuerst** [comment]
Cannot confirm using `ropsten`, on `master`.

**Comment by derhuerst** [comment]
Can confirm on `ropsten` with `0x00fbB1695f789E71760e9C7F97c08f6f19bFd7a4`, having e0f6f8f97ecebed1a6e58e0f8ae53564c0d8e7bd checked out.

**Comment by derhuerst** [comment]
In fact none of `const list = [].concat(accounts, addresses, contracts)` get updates. This is because the `fetchBalances` doesn't fetch if `list` is deeply equal to the last `list`.

**Comment by derhuerst** [comment]
I see two solutions

1. Introduce a `noCache` parameter in `fetchBalances`.
2. Check if the node is syncing in `fetchBalances`.

Both solutions introduce more complexity. It would be nice to refactor the balances (including tokens) & badges system.
