### ISSUE TITLE
Signer confirming takes very long

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3362]
This is a new issue. I cannot tell about yesterday but it was not showing up 2d ago.
I am calling the setMeta function on the DappReg contract.

The signer shows up. I type in the password and hit the CONFIRM button.
The button turns to CONFIRMING....

I measured one attempt, it took ~1:52 min until the tx hash appeared.
In the end the tx goes thru 

The confirmation used to be almost instant.

**Comment by jacogr** [comment]
Morden?

**Comment by tomusdrw** [comment]
Are you running in `debug` mode? You need to compile parity with `--release` otherwise it may take quite a while.

**Comment by chevdor** [comment]
@tomusdrw you are totally right.
I compiled in release and indeed, it was then as instant as I expected.

@jacogr yes morden. So there is a major drawback about not building in --release.

@tomusdrw do you know why a debug version takes that much longer? I would understand a few seconds more but here we go from instant to 2 minutes.

Closing here anyway.
