### ISSUE TITLE
Send failures returns 50M gas, show error in UI (transfer & execute)

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3366]
Currently the UI helpfully converts this 50M number to ETH, however when number > gasLimit display that the transaction cannot be executed. It should display that it is an exception, not take everything at face-value.

**Comment by derhuerst** [comment]
There is [`util/check-if-tx-failed.js`, part of #3336](https://github.com/ethcore/parity/blob/3f0053f884248b00eb123d70941f256dacb58dee/js/src/util/check-if-tx-failed.js#L17).

**Comment by jacogr** [comment]
This is pre-send, not post-send. Warn user up-front -

1. estimated gas will exceed block limit
2. estimate gas indicates an error
