### ISSUE TITLE
Dapp Authentication

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3382]
Should allow dapps to be identified by core RPC. This allows:

- a dapp's to be given elevated privileges for RPC calls;
- a dapp's transactions to be streamlined through the signer;
- the user to configure which of their identities a dapp sees.

Dapp (actually it can be topbar) generates a random GUID and sends it to RPC (+ dapp name/desc).

**Comment by tomusdrw** [comment]
1. Extract `id=hash` from `Origin` of the request (if origin is missing use defaults/empty)
2. Alter `id=hash` resolution (when serving content to)
   2.1. check if `hash` resolves in namereg to a content hash
   2.2. check if it resolves to a dapp
   2.3. check if it resolves to a content

So basically accessing `http://sha3(dappname).parity` should resolve to latest version of the dapp and the unique id when handling requests should be `id = sha3(dappname)`

**Comment by gavofyork** [comment]
How is this one doing, @tomusdrw ?

**Comment by tomusdrw** [comment]
The first part is finished, better implementation for metadata handling is pending in #3859.

We have two issues left (logged separately):
1. Referer is not reliable/can be spoofed: #3673
2. Using new version of the dapp requires you to expose accounts once again: #3989

We need to figure out first how to identify the dapp securely (#3673) to start implementing elevated privileges.

**Comment by rphmeier** [comment]
#3859 is onice until post-1.5 but this issue is part of the 1.5 milestone.
One has to give. I think the futures-based RPC is fine but it might be about time to a feature freeze on 1.5 anyway given that we're a bit overdue already.

**Comment by tomusdrw** [comment]
#3859 is just a nicer way of doing what is already done using Rpc Middleware (https://github.com/ethcore/parity/blob/master/dapps/src/rpc.rs#L73) so it is not necessary for 1.5

**Comment by tomusdrw** [comment]
Splitted into #4105 #3673 #3989
