### ISSUE TITLE
Parity everytime defaults ui settings when starting it again.

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3386]
Contract, status, signer is switching off to default.
Background is randomized everytime.

debian-8.6.0-amd64-netinst
Parity 1.4.2
Firefox browser set up with "not remember anything after exiting" options.

**Comment by rphmeier** [comment]
Parity UI stores its configuration in browser localStorage; there's nowhere else it really can, since webpages aren't given access to the filesystem. If you configure your browser to delete localStorage, then it should be expected that nothing is saved.
