### ISSUE TITLE
Can't transfer ETH from multisig contract. 

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3388]
Parity just simply does not have that buttons and features to do that. I have to swith to --geth interface to accomplish that.

**Comment by jacogr** [comment]
Could you please expand on the features you require?

**Comment by keuge** [comment]
I created a contract in Mist with 3 multisig wallets. I want to send ETH from that miltisig wallet to another wallet.

**Comment by jacogr** [comment]
Thanks for the feedback. Closing as duplicate.

We do have multisig contract support planned and in the queue for the 1.5 series (i.e. acting as first-class citizens in the interface), tracking at https://github.com/ethcore/parity/issues/3282. 

For now advanced users can add the contract and interact with it (there are some from-scratch deployment issues, tracked in https://github.com/ethcore/parity/issues/3314 which will address technical uses, however #3282 aims to not have users resort to low-level interfaces)
