### ISSUE TITLE
Better memory and bandwidth management

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3390]
1.5.0 is eating up as much bandwidth as it can find - 2-3 MByte/s sustained with ~40 peers, but up to 12 MB/s. Pretty much all TCP incoming to port 30303, coming from across the peers, not just one or two as far as I can tell.

Memory usage seems to be 2-3GB, sometimes up to 6GB.

> Can confirm that reverting to 1.3.10 (running while building 1.3.11) has restored normality: <50KB/s d/l rate; 500MB memory footprint

Possibly to do with warp sync, but then this guy wasn't running with `--warp`.

**Comment by benjaminion** [comment]
> 1.5.0 is eating up as much bandwidth as it can find
Assuming that this refers to my issue mentioned on gitter, it was v1.4.2 that caused the problems reported (not 1.5.0).
I've reverted for now to 1.3.11 which is running smoothly.
I'll post sync trace output as and when I see the issue again.

**Comment by benjaminion** [comment]
# First Run - parity consumes high network bandwidth

I've attached a log from 1.4.2 with `-l sync=trace`. It captures about 5 minutes worth from a near synced chain (only a couple of blocks to catch up).

[parity_sync_log_161113.txt.gz](https://github.com/ethcore/parity/files/587817/parity_sync_log_161113.txt.gz)

Complete command line is
```
docker run my/parity_beta --pruning fast -l sync=trace > parity_sync_log_161113.txt 2>&1
```

Observations
* Sustained bandwidth was not as high as yesterday (which ran at ~10MByte/s with 40 peers). I did not specify --min-peers on this run.
* Nonetheless bandwith usage was often > 2MB/s, sometimes up to 5MB/s and generally an order of magnitude higher than with 1.3.x
* CPU usage was also much higher than 1.3.x and more often, generally sitting between 75%-100% throughout (four cores) . Again, an order of magnitude more that 1.3.x.
* Memory footprint remained low on this short run.

# Second run - parity terminates prematurely

As above with more peers and more cache assigned.

[parity_sync_log_2_161113.txt.gz](https://github.com/ethcore/parity/files/587826/parity_sync_log_2_161113.txt.gz)

```
docker run my/parity_beta --pruning fast --min-peers 40 --cache-size-db 1024 -l sync=trace > parity_sync_log_2_161113.txt 2>&1
```

Observations:

* This run terminated prematurely after about 2 minutes: the docker container stopped with no error message. No crash dump in the Parity logs. It's as if Parity just exited cleanly (for no apparent reason). I also saw this happen twice yesterday.
* Other observations on network and CPU and memory usage are as above.

**Comment by benjaminion** [comment]
I've attached a log from 1.4.2 with `-l sync=trace`. It captures a few minutes' worth from a near synced chain (only a couple of blocks to catch up).

[sync_log_1_161113.txt.gz](https://github.com/ethcore/parity/files/587857/sync_log_1_161113.txt.gz)

Complete command line is
```
docker run -v /share/CACHEDEV2_DATA/parity_debug:/root/.parity my/parity_beta --pruning fast -l sync=trace > sync_log_1_161113.txt 2>&1
```
So, for clarity, the only specific parity options are `--pruning fast` and `-l sync=trace`.

Platform is 
```
Linux 3.19.8 #1 SMP Fri Oct 21 05:15:25 CST 2016 x86_64 unknown
```

Observations
* Throughout the run the download network b/w was between 2 and 12 MBytes/s for the most part. 12MB/s is pretty much the maximum on my line.
* Upload b/w seems reasonable - 5-10% of download anyway.
* Memory footprint started at <500MB, but grew rapidly to over 1GB and still growing rapidly when I terminated. A longer run suggests that the memory footprint keeps growing indefinitely at about ~150 MB/minute.

As mentioned above, v1.3.11 is running very nicely for me on the same platform with bandwidth usage of less than 10% of this.

**Comment by arkpar** [comment]
@benjaminion So it appears you've used warp sync or restored from a snapshot at some point before. This means that your blockchain is missing some of the older blocks. Parity is now trying to download these old blocks in the background to make sure you end up with the full blockchain. That's a new feature introduced in 1.4. You can see the progress of the download in these messages:
`2016-11-13 16:08:37  import     #1949995   20/20/25 peers      4 MiB db    6 MiB chain  0 bytes queue   14 MiB sync`
Once the block number gets from 1949995 to ~2620000 bandwidth usage should get back to normal.
How do you measure memory usage?

**Comment by benjaminion** [comment]
I see. Yes, this chain was restored from a snapshot previously - a few weeks ago. I suspected warp sync, but since I hadn't specified `--warp` it was surprising.

Memory usage is provided by Docker in various ways, but `top` on the host OS is pretty reliable as well.

I'll try letting it run and see what happens. Some bandwidth cap would be handy, but may be impractical I guess.

Thanks for your help.

**Comment by gavofyork** [comment]
assuming this is fixed for now. @benjaminion please reopen if there's still trouble here.
