### ISSUE TITLE
Contract information doesn't update automatically

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3391]
If you execute a method on a contract, the information displays do not update. They should update whenever a new event has been emitted or it is otherwise known that a transaction to the contract has been executed.

**Comment by jacogr** [comment]
It should update, the logic is there. Possible regression.

**Comment by gavofyork** [comment]
yeah - it's not an easy one to reproduce. put it on the backburner for now.

**Comment by derhuerst** [comment]
Just tried simply with `setOwner` and the contract "queries" changed had been mined.

**Comment by ngotchac** [comment]
Might be that the transaction didn't succeed, which could be the case if running out of gas (happened a lot especially using these Wallets contracts). Works fine otherwise.
