### ISSUE TITLE
Parity UI: Desktop Icon - Tray Icon

### ISSUE THREAD

**Issue by pikos-apikos** [ethcore/parity#3404]
I am sorry but i really don't like it at all! It looks terrible and totally unprofessional. 

Here are my proposals: 
![parity-desktop-logos](https://cloud.githubusercontent.com/assets/941416/20239521/6930f390-a90a-11e6-80ac-e7e0af28dd32.png)

1)  Classic icon
2 - 3) Ethcore & The Rusty Parity 
4 - 5) Zoomed Parity 

Anyone you like ?

**Comment by 5chdn** [comment]
I like 4 and 5, however, how do they look on light backgrounds?

**Comment by 5chdn** [comment]
fixed with #4804
