### ISSUE TITLE
Logs are sometimes not shown on contract view

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3407]
I came across an issue whereby all of the event from one of my contracts became no longer visible.

They originally showed up in the contract's UI, but now it's ~3000 blocks later, they don't. A quick check reveals they do exist:

![image](https://cloud.githubusercontent.com/assets/138296/20244994/f7ef7e4a-a995-11e6-9b18-542154bf5655.png)

Yet they don't show up on the contract page.

**Comment by gavofyork** [comment]
UPDATE: When I deleted the contract from the view, it left a message "error: Cannot read field filterId of undefined" (or something similar).

**Comment by ngotchac** [comment]
@gavofyork Could you give us which Contract you used?

**Comment by derhuerst** [comment]
> I came across an issue whereby all of the event from one of my contracts became no longer visible.

I guess it's not a contract of those in `js/src/contracts/abi`? Because with these, the events won't be shown if the signature doesn't match with the stored abi.

**Comment by ngotchac** [comment]
Well he did write _no longer_ so it guess they used to display

**Comment by gavofyork** [comment]
don't remember. haven't seen it since, so i'll close for now.
