### ISSUE TITLE
Parity 1.4.2: Interaction with contracts stuck.

### ISSUE THREAD

**Issue by ChristophSiegenthaler** [ethcore/parity#3411]
Playing around with parity 1.4.2, good work folks.
Ran into an issue however: added the BeerCoin contract with the json interface according to https://www.reddit.com/r/ethereum/comments/4v7opj/introducing_beercoin/?st=ivgnov56&sh=fe75bf8a

The contract shows up (even with the BeerCoin icon), I can't interact with the contract though.
When I select or paste an address in the balanceOf field and hit "Query", the status bar above the Query button is the only things that shows any action. What's going on here? (..or what do I do wrong?)

**Comment by jacogr** [comment]
Replicated & verified as an issue. (Also on master) Thanks for the report.

**Comment by ChristophSiegenthaler** [comment]
Can confirm, queries to contracts work with parity-git-1.5.0.6252. Thanks!
