### ISSUE TITLE
Missing 'ethcore_pendingTransactions' in beta

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#3416]
The method 'ethcore_pendingTransactions' is not available anymore in the both beta 1.4.2 and also latest master.

Tested with beta: 2016-11-14 11:45:14  Starting Parity/v1.4.2-beta-b14aed7-20161110/x86_64-win
Tested with master: 2016-11-14 11:59:21  Starting Parity/v1.5.0-unstable-d184811-20161113/x86_64-win

C:\>curl http://localhost:8546 -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"ethcore_pendingTransactions\",\"id\":1}"  -H "Content-Type: application/json"
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":null},"id":1}

**Comment by tomusdrw** [comment]
`ethcore_*` methods were renamed to `parity_*` in `beta` and `master`.
