### ISSUE TITLE
Host not getting whitelisted when using --jsonrpc-hosts

### ISSUE THREAD

**Issue by nvtaveras** [ethcore/parity#3418]
Hello,

I'm running parity v1.4.1-beta with the following parameters:
`parity --jsonrpc-interface all --jsonrpc-hosts localhost`

However when I try to query the jsonrpc:
`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}' localhost:8545`

 I get the "**Provided Host header is not whitelisted.**" error. It only works when passing all as the --jsonpc-hosts parameter.

Has anyone experienced a similar issue?

**Comment by tomusdrw** [comment]
Can you try `--jsonrpc-hosts localhost:8545`?

**Comment by nvtaveras** [comment]
@tomusdrw It does work! Any particular reason why the port is needed?

**Comment by tomusdrw** [comment]
Yes, it validates the whole `hostname:port` part of the `Host` header.
Actually in your case it might be easier to just run `parity --jsonrpc-interface localhost` or `parity --jsonrpc-interface 127.0.0.1` afair we add `localhost` to allowed Hosts by default in such case.

**Comment by tomusdrw** [comment]
Closing since it appears to be solved, please reopen in case of further questions.
