### ISSUE TITLE
Your Homepage is NOT Available When Trusted Signer is DISABLED.

### ISSUE THREAD

**Issue by kenzaka07** [ethcore/parity#3429]
Hi.

I would like to ask help regarding my Signer issue. Yesterday, I successfully encode my Signer Parity New Token, and I was able to open my new Parity UI using the Parity 1.4.2.

Then, I shutdown my PC so I can leave home for the day. When I get back home, and open back my PC, and run parity, however, I can no longer view the Parity wallet, and a message appears stating:

``` 

YOUR HOMEPAGE IS NOT AVAILABLE WHEN TRUSTED SIGNER IS DISABLED.

You can still access dapps by writing a correct address, though. Re-enabled Signer to get your homepage back.

**Comment by rphmeier** [comment]
@kenzaka07 What flags are you running parity with? Some of them will disable the trusted signer.

**Comment by kenzaka07** [comment]
@rphmeier Sorry, I'm not sure what flags you mean, but I'm using the parity with --geth.

**Comment by rphmeier** [comment]
@kenzaka07 The `--geth` flag disables the trusted signer. You can force the ui back on with `--force-ui`.

**Comment by kenzaka07** [comment]
@rphmeier Thank you so much... It works

**Comment by AndreyNag** [comment]
--force-ui is not helped for me. : (
 sudo netstat -natp |grep parity
tcp        0      0 0.0.0.0:30303           0.0.0.0:*               LISTEN      8910/parity
tcp        0      0 192.168.1.111:8545      0.0.0.0:*               LISTEN      8910/parity
tcp        0      0 192.168.1.111:8546      0.0.0.0:*               LISTEN      8910/parity
There is no 8180. --force-ui hangs up daemon with error 
` --force-ui
Loading config file from /home/andrey/parity/config.toml
2017-10-04 15:58:23  Starting Parity/v1.7.2-beta-9f47909-20170918/x86_64-linux-gnu/rustc1.19.0
2017-10-04 15:58:23  Keys path /home/andrey/.local/share/io.parity.ethereum/keys/Ethereum Classic
2017-10-04 15:58:23  DB path /home/andrey/.local/share/io.parity.ethereum/chains/classic/db/906a34e69aec8c0d
2017-10-04 15:58:23  Path to dapps /home/andrey/.local/share/io.parity.ethereum/dapps
2017-10-04 15:58:23  State DB configuration: fast
2017-10-04 15:58:23  Operating mode: passive
2017-10-04 15:58:24  Configured for Ethereum Classic using Ethash engine
2017-10-04 15:58:39  Removed existing file '/home/andrey/.local/share/io.parity.ethereum/jsonrpc.ipc'.
Invalid UI WALLET listen host/port given: 192.168.111:8180
andrey@server:~$
`
Help me please. Let me path.

**Comment by 5chdn** [comment]
How are you running parity? What does your config look like?

**Comment by tomusdrw** [comment]
The `[wallet] interface` in your config file is invalid. `192.168.111` is not a valid IP address.
