### ISSUE TITLE
panicked at 'DB flush failed.: "Corruption: block checksum mismatch"

### ISSUE THREAD

**Issue by segovro** [ethcore/parity#3432]
I have tried almost all recommended procedures to sync ...

2016-11-14 11:24:46 Starting Parity/v1.4.2-beta-b14aed7-20161110/x86_64-linux-gnu/rustc1.12.1
2016-11-14 11:24:46 State DB configuation: fast
2016-11-14 11:24:46 Operating mode: active
2016-11-14 11:24:46 Configured for Frontier/Homestead using Ethash engine
....
2016-11-14 11:25:45 Syncing #2044800 d9bf…3d5f 16 blk/s 94 tx/s 3 Mgas/s 700+ 0 Qed #2045501 1/ 1/25 peers 4 MiB db 351 KiB chain 3 MiB queue 128 KiB sync
thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', ../src/libcore/result.rs:788
stack backtrace:
1: 0x556ef681c4f9 - 
2: 0x556ef6824f6c - 
3: 0x556ef6823e39 - 
4: 0x556ef6824528 - 
5: 0x556ef6824382 - 
6: 0x556ef68242f0 - 
7: 0x556ef6824271 - 
8: 0x556ef686196f - 
9: 0x556ef6240d88 - 
10: 0x556ef635f584 - 
11: 0x556ef6221880 - 
12: 0x556ef682ca56 - 
13: 0x556ef6253b88 - 
14: 0x556ef6822ad2 - 
15: 0x7f29c52bd709 - start_thread
16: 0x7f29c5d6382c - clone
17: 0x0 - 
2016-11-14 11:25:45 Finishing work, please wait...
thread 'main' panicked at 'called Result::unwrap() on an Err value: Any', ../src/libcore/result.rs:788

**Comment by arkpar** [comment]
Does it continue normally after restart? Could it be that you are running out of disk space or memory?

**Comment by segovro** [comment]
Disk analyser says I have 488,2 GB free space  
**parity** does not even start   
rebooted the computer, nothing  
ubuntu 16.04 LTS  
3,6 GiB
64 bits
AMDE-350 * 2

**Comment by arkpar** [comment]
This looks like a file system corruption. What is your filesystem?
1. Check your RAM with memtest
2. Check the FS with fsck
3. Consider using ext4

**Comment by segovro** [comment]
fsck util-linux 2.27.1
e2fsck 1.42.13 (17-May-2015)
/dev/sda1 mounted

**Comment by segovro** [comment]
I am running memtest overnight. Will report on outcome. Thanks

**Comment by benjaminion** [comment]
Just to add that I was experiencing exactly this issue.  I ran a full diagnostic on my SSD which came up clean; I'm running ext4.  However, a Memtest86+ memory test showed errors. I've swapped back to some DIMMs with no errors and all now seems to be well (so far).

So, yes - could well be hardware related.

**Comment by segovro** [comment]
thanks all of you. I will change the RAM
