### ISSUE TITLE
Incorrect report of "Executed an unknown/unregistered method on the contract"

### ISSUE THREAD

**Issue by tjayrush** [ethcore/parity#3434]
On the account screen, where the transactions for a given account are displayed, Parity reports incorrectly, that the transaction tried to "Execute an unknown/unregistered method on the contract." 

This is incorrect. I didn't try to execute a method. I sent myself a message through the input field.

As I do with many of my transactions, I entered hexadecimal data into the input field with a message reminding me what the transaction was for. In my own work analyzing transactions, if I encounter an input field that does not correspond to on the function signatures in the ABI of a contract (or I'm dealing with a regular account), I check the hex to see if it has only characters from a-zA-Z0-9 and punctuation and only report unknown method if the input field contains something that doesn't scan.

Not a serious problem, just annoying.

If you go to that transaction on etherscan and translate the input field, it shows the legit message: https://etherscan.io/tx/0xa81ef1da02e6e063034b47e8ae8f7fa2b5f2e6130c317a4891d882bfa6e551c7

Here's a screen shot:

<img width="1616" alt="screen shot 2016-11-14 at 2 23 28 pm" src="https://cloud.githubusercontent.com/assets/5417918/20279322/221b9510-aa76-11e6-8fa5-2f6aaf90e8d8.png">

**Comment by b-f-** [comment]
ERC20 token balance not displayed in account details in Parity 1.8.3-beta. Wallet is synced.

Install contract:
https://etherscan.io/tx/0x49d9592992c34f780a183af558a22835259c0aae20d91002ac698d105ee1192e

Token acquisition:
https://etherscan.io/tx/0x55a9212b112eba2f5bca47cc75629a3a984d6b5d9c46318d210985fcbb30dad4

![image](https://user-images.githubusercontent.com/2358754/33146744-bd716f1a-cfc5-11e7-932b-0e970cebdf7c.png)
