### ISSUE TITLE
the supplied amount exceeds the allowed decimals

### ISSUE THREAD

**Issue by ferni** [ethcore/parity#3437]
I'm trying to send 4999 tokens (no decimals) and I'm getting this error from the form validator: "the supplied amount exceeds the allowed decimals"

![decimals](https://cloud.githubusercontent.com/assets/653586/20281918/338da2f0-aa91-11e6-9adb-c95f6ea299bb.png)

I've tried sending with and without the ".0" at the end, same error appears.

**Comment by jacogr** [comment]
Thanks for the issue report. Will test, verify & get it in the queue.

**Comment by jacogr** [comment]
Confirmed. Happens when the total amount = available amount. (Smaller amounts are fine.)
