### ISSUE TITLE
Checksums in the release page don't match, or its kind should be explicitly stated

### ISSUE THREAD

**Issue by knocte** [ethcore/parity#3449]
What kind of checksum is the one used in the release page? I've tried to compare the one used for the Linux amd64 (v1.3.11) binary using SHA256 and MD5 and none of them match.

Is this checksum wrong? If not, please state the algorithm used in the release page. Thanks

**Comment by rphmeier** [comment]
Our CI system goes crazy sometimes and overwrites the pre-existing binaries...will be addressed shortly.

**Comment by jesuscript** [comment]
fixed in #3455. closing
