### ISSUE TITLE
Binaries in S3 should NEVER get overwritten

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3455]
Gitlab currently randomly rebuilds tags (e.g. v1.3.11, v1.4.2) and overwrites the binaries in corresponding S3 buckets. This is a **very big problem**, because the build tables generated by vanity-service.ethcore.io/parity-binaries which we publish on github are static. As a result, upon a rebuild, the binaries get overwritten but checksums stay the same (and wrong!)

I propose that we 

1. As a matter of **MAXIMUM** priority, make it impossible to automatically overwrite the published binaries
2. (somewhat less urgently) stop these, random tag re-builds

**Comment by jesuscript** [comment]
as for 1: one idea would be to leave everything as is, create a new bucket, e.g. `parity-builds-published` (in addition to the existing `parity-builds`), point the existing CDN at `parity-builds-published` and write a script that, given a list of tags/branches, simply copies the directories from `parity-builds` to `parity-builds-published`. This way spontaneous rebuilds stop being such a problem as we'll now have full control over the published versions.

thoughts?

**Comment by rphmeier** [comment]
Cause of #3449 

Sounds like a good first step, best thing would be to prevent the spurious rebuilds but the first step has got to be making sure that we aren't hurt by this happening again.

**Comment by jesuscript** [comment]
OK, I'll take care of the S3 stuff. @General-Beck the spurious rebuilds are all yours  ;)

**Comment by jesuscript** [comment]
created a new bucket called `builds-parity-published`. From now on CDN will point to that instead of the "live" `builds-parity` bucket and Vanity will be listing its directories too. Our release now will have to include an extra step:
```bash
aws s3 sync s3://builds-parity/<tag directory> s3://builds-parity-published/<tag directory>
aws s3 sync s3://builds-parity/master s3://builds-parity-published/master
aws s3 sync s3://builds-parity/beta s3://builds-parity-published/beta
aws s3 sync s3://builds-parity/stable s3://builds-parity-published/stable
```

You can also list the s3 buckets, e.g.:
```bash
aws s3 ls s3://builds-parity/
```

Speak to me if you need the S3 credentials. @arkpar @rphmeier
