### ISSUE TITLE
trace_replayTransaction and stateDiff

### ISSUE THREAD

**Issue by alesl** [ethcore/parity#3467]
Not sure if this is a bug or my lack of understanding, but it seems stateDiff does not return balance diffs correctly in some cases.

Assumption: when balance in stateDiff is returned as `* {from:v1, to:v2}`, the change in balance on this address equals to `v2 - v1`.

Parity version: `Parity//v1.4.2-beta-b14aed7-20161110/x86_64-macos/rustc1.13.0`

Example [0xed70a970323faa1d80689a2f6d55ba77966cf309a3c1c11c4b1324ccb8af907d](https://etherscan.io/tx/0xed70a970323faa1d80689a2f6d55ba77966cf309a3c1c11c4b1324ccb8af907d)

Balance state diff for `0x37510df5b825f93d256713c1aac947ff145ee937` is reported as `-196224823995530` weis
```json
"0x37510df5b825f93d256713c1aac947ff145ee937": {
    "balance": {
        "*": {
            "from": "0xb86dc1231d5000",
            "to": "0xb7bb49fc2f2376"
        }
    },
    "code": "=",
    "nonce": {
        "*": {
            "from": "0x6",
            "to": "0x7"
        }
    },
    "storage": {}
}
```

Trace shows two relevant calls, where mentioned address is ether recipient or sender, where only last one has non-zero value of `18460057597123142` weis:
```json
{
    "action": {
        "callType": "call",
        "from": "0x96e423291765c60e0fbc2cfb2bc538fb6ccdadd9",
        "gas": "0x1af56",
        "input": "0x",
        "to": "0x37510df5b825f93d256713c1aac947ff145ee937",
        "value": "0x419553179c1a46"
    },
    "result": {
        "gasUsed": "0x0",
        "output": "0x"
    },
    "subtraces": 0,
    "traceAddress": [
        200,
        1
    ],
    "type": "call"
}
```

This value matches one that can be derived from parsing geth trace and the one reported by [etherscan](https://etherscan.io/tx/0xed70a970323faa1d80689a2f6d55ba77966cf309a3c1c11c4b1324ccb8af907d#internal).

**Comment by gavofyork** [comment]
you're not taking into account the fee paid by that account as the original sender.

fee_paid = `
web3.eth.getTransactionReceipt('0xed70a970323faa1d80689a2f6d55ba77966cf309a3c1c11c4b1324ccb8af907d').gasUsed * web3.eth.getTransaction('0xed70a970323faa1d80689a2f6d55ba77966cf309a3c1c11c4b1324ccb8af907d').gasPrice` = 18656282421118670 wei

value received in the internal tx = 0x419553179c1a46 = 18460057597123144 wei

change = value_received - fee_paid = 18460057597123144 - 18656282421118670 = -196224823995530.
