### ISSUE TITLE
Connect Private chains on MAC OS

### ISSUE THREAD

**Issue by jwter** [ethcore/parity#3468]
i install parity on mac os with this "parity-osx-installer-EXPERIMENTAL.pkg"
auto open "http://127.0.0.1:8180/" when completed. this default open common chains and show
common chains accounts.
now , i want connect Private chains use parity . so how to config  or do something.
i find install url on computer "/Users/jwter/.parity"

**Comment by tomusdrw** [comment]
Experimental installers are making it smooth to connect to main network.

For more advanced scenarios you will either like to run Parity manually using CLI.
You can also use config files to automatically connect to your private chain:
https://ethcore.github.io/parity-config-generator/

Generate the file and save it to `/Users/jwter/.parity/config.toml`, next time you'll run Parity it will pick up the settings from there.
To connect to private chain use:
```
[parity]
chain = "/Location/To/ChainSpec.json"
```

**Comment by arkpar** [comment]
Also see https://github.com/ethcore/parity/wiki/Private%20Chains for private chain guide
