### ISSUE TITLE
eth_signTransaction output format

### ISSUE THREAD

**Issue by mongrim** [ethcore/parity#3472]
Hi again

I saw, you implemented my request #2265.
Thank you for that.

Is it possible to make output format of this call the same as in geth? 
To return 
```

{
  "raw": "0x....",
  "tx": {
    "hash": "0x..",
    "from": "..",
    "to": "..",
    ..
  }
}
```

instead of simple raw transaction string?
I'm mostly interested tx hash part, but it's always nice to have fully compatible API to switch between clients painlessly.
Thanks in advance.

**Comment by tomusdrw** [comment]
Sure, it should be implemented that way in a first place. Sorry, I haven't look carefully enough into linked PR.

**Comment by mongrim** [comment]
Great, thanks for the answer. 

Could you also provide some ETA for this feature to be included to a release (as implemented now or with improved format)? Week/month/two months/more?
And is it safe to take current 1.3/1.4 latest release, merge those 2 commits manually and start using it right away? Or it will break something else?

**Comment by tomusdrw** [comment]
For now it will be part of 1.5 release (we try to keep 6-8 weeks release schedule).
It might be difficult to backport it to 1.4 and 1.3 since that part of RPC was also refactored in the meantime. PM me on Gitter I can help you with the merges.
