### ISSUE TITLE
Parity Icon not displaying correctly after upgrade on Mac OS

### ISSUE THREAD

**Issue by bamos01** [ethcore/parity#3480]
The parity icon is lost after upgrading from 1.4 to 1.4.3-  it just has a generic text/script icon for the parity app.

**Comment by tomusdrw** [comment]
@arkpar was it just icon rename?

**Comment by arkpar** [comment]
The icon was not committed to git properly. @gavofyork fixed it in 75c92e935622090d34c9bd91a6b385856d451c48
