### ISSUE TITLE
web3 expects eth_getTransactionReceipt to return null when transaction is pending

### ISSUE THREAD

**Issue by thebalaa** [ethcore/parity#3482]
I'm using web3.js to deploy a contract via the json rpc call to `eth_sendTransaction`.

As far as I can tell, web3 expects calls to `eth_getTransactionReceipt` to return null (according to [here](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt ) until the block has been mined; however, parity is returning the following:

```
{"blockHash":null,"blockNumber":null,"contractAddress":"0x01ce8d92c5713b996f318c1f271aadd6e5d663e3","cumulativeGasUsed":331535,"gasUsed":331535,"logs":[],"transactionHash":"0xc04a2e0193d7922b2073d3d32aad91f7d6e250cf23bb79832a46c5d6415b7ce5","transactionIndex":0}
```

This causes the following error callback to fire prematurely:

https://github.com/ethereum/web3.js/blob/develop/dist/web3.js#L2932

**Comment by tomusdrw** [comment]
You can use `--geth` flag to bring back geth-compatible behaviour. AFAIR the spec says that receipts should be available also for pending transactions, might be a good idea to file a bug in `web3` repo.
