### ISSUE TITLE
Bunch of personal_* RPC methods unknown

### ISSUE THREAD

**Issue by SinErgy84** [ethcore/parity#3485]
Client: Parity/v1.4.3-beta-a1a03a6-20161116/x86_64-linux-gnu/rustc1.13.0
Run-options: - --jsonrpc-apis "web3,eth,net,personal,rpc"

I've tried some functions like
- personal_newAccountFromPhrase
- personal_newAccountFromWallet
- personal_accountsInfo

mentioned in https://github.com/ethcore/parity/wiki/JSONRPC-personal-module
but they all results in error that the method is not found / unknown.

Counter-sample: personal_signAndSendTransaction works like expected

Please provide also compatibility with geth-client-method [personal_importRawKey](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_importrawkey) to use same api calls.

**Comment by tomusdrw** [comment]
We've recently moved all Parity-specific methods out of "standarized" namespaces and most of the methods are now part of `parity_*` namespace #3143 . Seems that the docs are not updated, I will update the docs, but in the meantime you can have a look at the code to see what methods are supported:
Personal:
https://github.com/ethcore/parity/blob/master/rpc/src/v1/traits/personal.rs#L25
Parity:
https://github.com/ethcore/parity/blob/master/rpc/src/v1/traits/parity_accounts.rs#L26

**Comment by SinErgy84** [comment]
@tomusdrw Thank you!
It's kinda hard sometimes to differentiate in the release-notes /-changelog between important major changes concerning usage and minor changes concerning cosmetic refactoring.

Some time ago I also experienced that the personal-module was disabled from default-loaded-jsonrpc-modules in 1.3.?? and re-enabled by next version-change, but it needed some investigation of commits to find the clue.

You're doing great work *thumb up*, but it would be nice if you provide more details on your release-notes and "improve communication / documentation".

**Comment by tomusdrw** [comment]
Thanks, yes we have now a new label to mark PRs with significant changes that should be included in release notes.

The `personal` module should be disabled by default in all versions now (it contains some unsafe methods) - I'll verify that too.
