### ISSUE TITLE
Include other trace_ RPCs in parity.js

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3487]
Currently missing:

- `trace_call` (like `eth_call` but takes an extra `what_trace` arg)
- `trace_rawTransaction` (like `eth_sendRawTransaction` but takes an extra `what_trace` arg and doesn't actually send it)
- `trace_replayTransaction` (takes a transaction hash and `what_trace` arg)

`what_trace` is an array that should contain one or more of `vmTrace`, `trace` and `stateDiff`, depending on what kind of trace you want to make.

**Comment by jacogr** [comment]
Any preferences and/or would sane defaults make sense in this case -

For eth.call (i.e. when blockNumber is not specified, it defaults to `latest`

```
call (options, blockNumber = 'latest') ...
```

For eth.trace (and the others with the `whatTrace` parameter, is there a sane default -

```
call (options, blockNumber = 'latest', whatTrace = ['vmTrace']) ...
```

Or don't try and specify most-used `whatTrace` defaults for these at all.
