### ISSUE TITLE
eth_protocolVersion RPC does not return hex string

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#3502]
All other rpc values return as hex strings, but this appears to be a plain int.  Checked geth and it returns a hex string.

**Comment by tomusdrw** [comment]
The example in spec displays a number:
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_protocolversion

Also the return type is defined as `String` not `QUANTITY`, I don't see a reason to change the output.
