### ISSUE TITLE
Contract execute should allows for gasPrice selection & gas setting

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3510]
... as we have in the Transfer dialog

**Comment by knocte** [comment]
Is there a workaround for this? I mean, can I add a flag to parity when launching it in the command line, to increase the gas?

My problem is that I'm getting "out of gas" when calling a contract and I wanted to try increasing the gas limit or the gas price, to see if that fixes it (if it doesn't then maybe it's a parity bug?).

If you're interested in the details, they are here: http://ethereum.stackexchange.com/questions/10310/trying-to-get-a-refund-from-my-dao-results-in-out-of-gas
