### ISSUE TITLE
SMS process failed: all gas used up

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3514]
I went thru the process on testnet: https://testnet.etherscan.io/tx/0x6ed045aeaaa8d0815d44d98e534655874969dfa144bfefa97f8e80729bce2c28

It failed after I signed the tx that sends back the puzzle magic sentence.

`Failed to send the verification code: Transaction failed, all gas used up.`

**Comment by derhuerst** [comment]
Will look into this today. Will also setup sms verification for mainnet.

**Comment by derhuerst** [comment]
@chevdor I cannot look at your `morden` tx on etherscan.io, because they switched to `ropsten`.

Will update the client code to match [the changes made on the server](https://github.com/ethcore/sms-verification/commits/11923ff0274d5394a55d6523209f908f42a3c330).

**Comment by chevdor** [comment]
Hi. I will access my data again on wednesday. If you still need the tx, let
me know and I will bring you a fresh one to ropsten.

**Comment by chevdor** [comment]
@derhuerst you can still look at morden tx on etherscan: https://morden.etherscan.io/tx/0x6ed045aeaaa8d0815d44d98e534655874969dfa144bfefa97f8e80729bce2c28

**Comment by derhuerst** [comment]
22e1384d45864c0fda7cec07d94c6eaceddae896 may fix it. Will also make it verify the typed code up front.

**Comment by chevdor** [comment]
I also will test on ropsten on my side and let you know.

**Comment by chevdor** [comment]
I currently cannot test as it fails earlier in the process:
![screen shot 2016-11-23 at 12 33 11](https://cloud.githubusercontent.com/assets/738724/20560328/1074e046-b179-11e6-9bb6-aacda9d67532.png)

I built at commit a969c008d172697b786b2e545930a88b0df42d60
A tx was sent though: https://testnet.etherscan.io/tx/0x0b60f6cf49f1b944032715ed3cd3992c38754d868e4b2f857839522023ba882d

**Comment by chevdor** [comment]
Closing this issue as I could test it with @derhuerst with jr-update-sms-verification
It works atm as long as the chain is selected using `--chain ropsten` and not `--chain path-to-file.json`

@jacogr is on it so no need for another issue. Thank you @derhuerst for your time.

**Comment by chevdor** [comment]
For reference: #3578
