### ISSUE TITLE
Master, beta and stable artifacts should be uploaded to the builds-parity-published bucket directly

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3515]
We're currently writing these into builds-parity, which requires a manual step to make them obtainable. This is over-protective - publishing these automatically is fine.

**Comment by rphmeier** [comment]
Doesn't this defeat the purpose? Then if the CI decides to rebuild it will be able to overwrite the published builds bucket entries.

**Comment by jesuscript** [comment]
The two-step mechanism makes sense for the tagged builds as we're actually putting these out on github and other places. AFAIK, we don't do that with master/beta/stable. Master was always meant to be frequently updated.Same goes for beta I think. Stable is a weird one, not sure why it exists.

@arkpar could you comment?

**Comment by rphmeier** [comment]
@jesuscript Fair enough, but we don't really publish those builds so I'm not sure if they belong in the published builds bucket.

**Comment by jesuscript** [comment]
"published" only means they become downloadable through our CDN. This is highly desirable, especially for master, which we use on our bootnodes

also, can't believe I misspelt "artefact" lol

**Comment by arkpar** [comment]
Right, we only really "publish" tag builds. Branch builds are expected to be volatile

**Comment by jesuscript** [comment]
gotcha. updating the gitlab-ci config to push branch builds directly into the "published" bucket
