### ISSUE TITLE
Blocks stop around 2.4 million

### ISSUE THREAD

**Issue by 23452nick** [ethcore/parity#3529]
I followed the terminal steps to download parity [here](https://github.com/ethcore/parity/blob/master/README.md) in my whonix virtual machine two days ago.

In the .parity folder, there is a text file named "ver.lock". The text file says 1.5.0.

Is the issue that whonix without qubes is 32 bit, and parity only comes in 64 bit?

Parity worked fine until around 2.4 million blocks, every time I restart it, it restarts at like 2.384 million and then gets stuck on a block around 2.4 million, but its always a different block number.

**Comment by tomusdrw** [comment]
A log output would be helpful. There are plenty possible explanations, maybe your node is just slowing down processing the blocks?

**Comment by tomusdrw** [comment]
Impossible to figure out what could be wrong without additional details. Assuming it's just a block import slowdown. @23452nick please reopen if the problem persists.
