### ISSUE TITLE
Keep transactionIndex and logIndex returned by RPC consistent with RPC docs (and therefor 'geth')

### ISSUE THREAD

**Issue by tjayrush** [ethcore/parity#3537]
Please see this bug report on geth: https://github.com/ethereum/go-ethereum/issues/2028.

It is a discussion of the **transactionIndex** and **logIndex** being returned by the RPC call eth_getTransactionByHash and eth_getFilterChanges respectively. The RPC wiki document says that both of the transactionIndex and logIndex are 'integer[s] of the...index position in the block. null when its pending'

Parity correctly returns a transactionIndex _per block_ starting with '0'. Inconsistent with the documentation, but consistent with the recommended fix described in the geth bug report, Parity returns a logIndex _per transaction_ also starting with '0'.

I think Parity does things correctly, but then the documentation should be corrected. If the documentation does not get corrected, then I think Parity should change the way it numbers the **logIndex**.

The reason why I think this is important is to promote switching between Parity and Geth as the RPC provider. The way things stand now, if one wants to use the values in 'dapp' code, one must make custom code depending on the client one is interacting with. Needless complication that should be easily fixed in all clients and correctly documented.

**Comment by tomusdrw** [comment]
I'm pretty sure that `log_index` is unique within a block not within a transaction.

Here is a relevant test case:
https://github.com/ethcore/parity/blob/master/ethcore/src/blockchain/blockchain.rs#L1943

Could you send an example of duplicated `log_index` in a single block?

**Comment by tomusdrw** [comment]
Hmm, it seems that `log_index` is actually different when using `eth_filterChanges` and `eth_getTransactionReceipt`, we should probably make it consistent.

**Comment by tjayrush** [comment]
I am doing eth_getTransactionReceipt through RPC.

I actually think Parity gets this right. To me, the logs seem to be a data member of the transaction receipt. Indexing per transaction (as does Parity) makes sense. Indexing logs per block doesn't seem to make sense to me, but there may be a reason for that. The documentation says it should be indexed per block. This is what 'geth' does, but the above referenced 'geth' bug discusses changing it. Perhaps the bug is in the documentation.

**Comment by tjayrush** [comment]
I've tested more than 1,000 randomly chosen blocks between 0 and 2,500,000. This appears to happen with any block with more than one transaction receipt with one or more logs, which makes sense since 'geth' numbers receipts per block and Parity numbers then per transaction.

**Comment by tomusdrw** [comment]
We will most probably fix the behaviour of `logIndex` of transaction receipt to return "index in block", but will add another field `logIndexInTransaction`

**Comment by fjl** [comment]
My take on these issues and the resolution I'd like to see below. If we can agree on a resolution,
I can update the spec to match.

> 1) 'geth' returns nonce field from eth_getBlockByNumber(x,true), Parity does not
> According to the documentation (https://github.com/ethereum/wiki/blob/master/JSON-RPC.md#eth_getblockbyhash), nonce should be returned by getBlockNumber.

> 2) 'geth' returns the fields from, to, and root from eth_getTransactionReceipt(addr), Parity does not

We need these values so the full receipt can be reconstructed on the client side.
This is something you might interested in as well.

> 2) Both clients return 'r', 's', and 'v' fields in the transaction from eth_getNumberByBlock(x,true) call
 
We already kind of agree on this one.

4) 'geth' removes leading zeros from a transaction's r and s fields, Parity does not.

RLP encoding of transactions treats these fields as a number so I thought they should
encode as quantities in JSON.

6) 'geth' and Parity disagree on the value of the transaction's v field.

Similar to receipts, I'd like to be able to reconstruct the transaction as used by
consensus. Since the exact v value is now meaningful for EIP155 purposes, I'd like to
see it returned as-is.

> 7) Parity numbers the logIndex field of the receipts logs per transaction. 'geth' numbers the logs per block.

You already said you'd change it to block index and I agree.

**Comment by tomusdrw** [comment]
Closed via #3995
