### ISSUE TITLE
UI: Ropsten/custom chain considered as Mainnet

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3578]
I am running parity using --chain ropsten.json

In the UI, parity shows a green label that usually means MAIN net.
In the contracts and accounts tab, I can now see a mix of accounts/contracts from Homestead and Ropsten => the Ropsten accounts/contracts do show up, but the Homestead ones as well.

![screen shot 2016-11-23 at 12 20 38](https://cloud.githubusercontent.com/assets/738724/20559959/4eb277bc-b177-11e6-8f68-d8c2d4ba3204.png)

The Network ID should probably be used to identify the network and store/filter the accounts/contracts.

I think the color code for the network is a good idea and I would propose to extend it as follow:

- Homestead / mainnet => green (unchanged)
- Morden / Ropsten / testnet => cyan (red is a contradiction, red = risk, testnet = no risk )
- other / unknown networkd id => yellow

**Comment by jacogr** [comment]
Fixed in master yesterday.

**Comment by jacogr** [comment]
Still happens when using a chain file, but not using `--chain ropsten` (or `--testnet`)
