### ISSUE TITLE
Owner recover phrase creates different account

### ISSUE THREAD

**Issue by NitroMoo** [ethcore/parity#3584]
When you create the new account with "new account manually" option, it shows the recovery phrase in the end.

However, you cannot recreate this initial account with this phrase, it will create a different account with the different address, which then could be recovered with that phrase.

**Comment by gavofyork** [comment]
just tried this and works perfectly for me. are you sure you typed the phrase correctly?

**Comment by NitroMoo** [comment]
I am pretty sure i am typing it correctly, i've tried it over 15 times already with different methods - copy pasting whole phrase, pasting word by word, typing manually. 

I am using the Parity//v1.4.4, synced by using --warp and --pruning fast

**Comment by NitroMoo** [comment]
I broke it down with 3 screenshots, can you please take a look and see if i am doing something wrong?
(a test empty account with 0 bal;ance)

1.https://i.gyazo.com/6a086691c6cee66bcbcb8155a7a5c7fe.png
2. https://i.gyazo.com/71b78b55f904f2616fd4584f105f04d2.png
3. https://i.gyazo.com/c7936ee6140c4ef0e46910b51956af7f.png

**Comment by NitroMoo** [comment]
I am pretty confident that its not a human error, i can recover accounts that were created via "recover from phrase" by re-typing same phrase, but still cant recover any "new" accounts created manually.

**Comment by gavofyork** [comment]
reopening after @3esmit confirms there's an issue lurking somewhere.

**Comment by gavofyork** [comment]
what platform are you running on?

**Comment by tomusdrw** [comment]
Reproduced on Windows, culprit:
```
{
"jsonrpc":"2.0",
"id":1,
  "method": "parity_generateSecretPhrase",
  "params": []
}
{
    "jsonrpc": "2.0",
    "result": "natural\r certified\r cupid\r merely\r hump\r lip\r psych\r devices\r jane\r steak\r asia\r reports\r",
    "id": 1
}
```

**Comment by NitroMoo** [comment]
I was also using Win10

**Comment by gavofyork** [comment]
thanks for reporting - there will be fix allowing you to recover the original account from the phrase in 1.4.5.

**Comment by NitroMoo** [comment]
Nice!
Quick questions:
1) Are the current accounts, created in 1.4.4, any less secure besides the fact that the phrase wont work on them?
2) Are my phrases for all my accounts that i wrote down completely useless and not linked with these accounts in any way?
3) If #2 is true, then do these accounts have any phrases linked to them at all? 

Thank you for your time

**Comment by gavofyork** [comment]
1. they're no less secure (only difference is that the `\t` characters were not stripped from the end of the words).
2. your phrases can all be used to regenerate the accounts that you are using as you would expect
3. n/a

**Comment by NitroMoo** [comment]
Nice.

Thanks for explanation

**Comment by tomusdrw** [comment]
Fixed with #3614 and #3615

**Comment by brucelkp** [comment]
my hardisk crashed after reinstalling windows unable to restore back my account with the phase key; it will create one with another address; any other information i need other then the phrase key?

**Comment by 5chdn** [comment]
@brucelkp which parity version did you use to create that account? and which operating system did you use?
