### ISSUE TITLE
Parity 1.4.4: syncing stopped at some block (actually is very slow)

### ISSUE THREAD

**Issue by resurtm** [ethcore/parity#3606]
Hello!

Not managed to find similar question or something useful with help of Google... I have two Ethereum nodes running based on Parity:

Here's the first one:

```
resurtm@resurtm-thinkpad:~$ screenfetch
                          ./+o+-       resurtm@resurtm-thinkpad
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.4.0-47-generic
           .++ .:/++++++/-.+sss/`      Uptime: 1d 1h 17m
         .:++o:  /++++++++/:--:/-      Packages: 1600
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.46
       .:+o:+o/.          `+sssoo+/    CPU: Intel Core2 Duo CPU T7500 @ 2.201GHz
  .++/+:+oo+o:`             /sssooo.   RAM: 1572MiB / 7910MiB
 /+++//+:`oo+o               /::--:.  
 \+/+o+++`o++o               ++////.  
  .++.o+++oo+:`             /dddhhh.  
       .+.o+oo:.          `oddhhhh+   
        \+.++o+o``-````.:ohdhhhhh+    
         `:o+++ `ohhhhhhhhyo++os:     
           .o:`.syhhhhhhh/.oo++o`     
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.      

resurtm@resurtm-thinkpad:~$ dpkg -l | grep parity
ii  parity                                      1.4.4                                         amd64        Ethereum network client by Ethcore

resurtm@resurtm-thinkpad:~$ apt show parity
Package: parity
Version: 1.4.4
Status: install ok installed
Priority: extra
Section: science
Source: parity
Maintainer: Ethcore <devops@ethcore.io>
Installed-Size: unknown
Homepage: https://ethcore.io
Build-Depends: debhelper (>=9)
Standards-Version: 3.9.5
Vcs-Git: git://github.com/ethcore/parity.git
Vcs-Browser: https://github.com/ethcore/parity
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Ethereum network client by Ethcore
```

Syncing stalled at this state:

http://i.imgur.com/92ThVXj.png

![](http://i.imgur.com/92ThVXj.png)

And here's my second node:

```
resurtm@resurtm-desktop:~$ screenfetch
         _,met$$$$$gg.           resurtm@resurtm-desktop
      ,g$$$$$$$$$$$$$$$P.        OS: Debian testing stretch
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.8.0-1-amd64
   ,$$P'              `$$$.      Uptime: 29m
  ',$$P       ,ggs.     `$$b:    Packages: 1704
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.4.0
   $$P      d$'     ,    $$P     Resolution: 1920x1200
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: Default
   `$$b      "-.__               GTK Theme: Adwaita [GTK2]
    `Y$$                         Icon Theme: Tango
     `Y$$.                       Font: Sans 10
       `$$b.                     CPU: Intel Core i5 CPU 760 @ 2.801GHz
         `Y$$b.                  GPU: GeForce GT 640/PCIe/SSE2
            `"Y$b._              RAM: 3455MiB / 16041MiB
                `""""           


resurtm@resurtm-desktop:~$ dpkg -l | grep parity
ii  parity                                 1.4.4                             amd64        Ethereum network client by Ethcore

resurtm@resurtm-desktop:~$ apt show parity
Package: parity
Version: 1.4.4
Status: install ok installed
Priority: extra
Section: science
Source: parity
Maintainer: Ethcore <devops@ethcore.io>
Installed-Size: unknown
Homepage: https://ethcore.io
Build-Depends: debhelper (>=9)
Standards-Version: 3.9.5
Vcs-Git: git://github.com/ethcore/parity.git
Vcs-Browser: https://github.com/ethcore/parity
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Ethereum network client by Ethcore
```

So far so good on this node:

http://i.imgur.com/TjadT2x.png

![](http://i.imgur.com/TjadT2x.png)

The question is: what can I do to solve the stall issue at my first box? Parity is latest for the moment, cannot imagine what causes that.

I appreciate any help! ;-)

Thanks!

**Comment by tomusdrw** [comment]
It seems that your node is not stalled, it's just taking a lot of time to process those blocks.

Notice that the number is increasing (although it takes around a minute to process the block), also the green number `15591` indicates that there are 15k blocks already downloaded and waiting to be processed.

If you have HDD drive you may consider resyncing with `--db-compaction hdd`, also you may try `--warp` sync to get the latest state in `~15minutes`

**Comment by resurtm** [comment]
@tomusdrw, thank you for quick reply!

Trying both options...

**Comment by resurtm** [comment]
Launched with both options, this is what I've got:

![image](https://cloud.githubusercontent.com/assets/100198/20618562/fa7ffc88-b319-11e6-936c-a1b6926dac25.png)

I know it's not stalled, and is working, but with such speed it will take *forever*. Current block is #2427971, total block count is #2690764 (https://etherscan.io/txs), at the moment of writing this. I'll leave my PC to work a bit, maybe it will become faster... :-(

**Comment by tomusdrw** [comment]
Those are most probably the blocks when state bloat attack was ongoing, they take quite a while to process on HDD.
So if you wish to use `--warp` sync it might be better to actually remove blockchain data and re-sync with `--warp` from scratch. For default location and mainnet:

```bash
# Remove the chain
$ rm -rf ~/.parity/906a34e69aec8c0d
# Start Parity
$ parity -db-compaction hdd --warp
```

**Comment by arkpar** [comment]
Looks like the war sync has been interrupted. You can try stopping, `rm ~/.parity/906a34e69aec8c0d/network/nodes.json` and starting with `--warp` again

**Comment by resurtm** [comment]
@tomusdrw, thanks for help!

**Comment by resurtm** [comment]
Thank you for your help! ;-) I'm finally now with the latest block. Nice!

Parity is just a fresh air comparing with go-ethereum. Took only 24 hours to manage to sync all blockchain. With go-ethereum I was having issues for about 2.5 weeks.
