### ISSUE TITLE
Unconfirmed Transactions

### ISSUE THREAD

**Issue by etherchain-org** [ethcore/parity#3608]
I am sending several thousands of transactions with Parity 1.4.4 on a daily basis. Every day, a small fraction of those transactions (maybe 1-20) do not get included in a block and need to be re-send manually.

Usually the not included transactions appear grouped together so I assume that the issue is that they were included in a block which was not included in the canonical chain for some reason.

**Comment by tomusdrw** [comment]
Indeed might be some kind of issue with retracted transactions, Queue priorities should be double checked.

Could you run with `-ltxqueue=trace`? It will produce a lot of logs, but might be helpful in reproducing the issue.

**Comment by etherchain-org** [comment]
After updating the sending node to Parity 1.4.5 all transaction were mined up to now. I will continue to monitor the situation and update the ticket in case it happens again.

Thanks!

**Comment by tomusdrw** [comment]
Seems solved for now, please re-open if the problem happens again.
