### ISSUE TITLE
rpc: eth_getBlockByNumber fails if block number is data type int

### ISSUE THREAD

**Issue by SinErgy84** [ethcore/parity#3611]
tested versions: 
- Parity/v1.4.3-beta-1b4aca8-20161116/x86_64-linux-gnu/rustc1.13.0
- Parity/v1.4.4-beta-a68d52c-20161118/x86_64-linux-gnu/rustc1.13.0

issue: if method eth_getBlockByNumber is called with block number parameter as data type integer, the call fails.

examples:
- {"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":["0x1",true]} -> OK
- {"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":["1",true]} -> OK
- {"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":[1,true]} -> FAIL with error invalid params

expected behaviour: all representations of a block number (data type string with hex-value, data type string with int value, data type int with int-value) acts the same

for comparison: geth-client handles calls like described expected behaviour

**Comment by keorn** [comment]
The standard is [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding). Geth will become stricter in coming releases.

**Comment by SinErgy84** [comment]
sorry, but this (the so called standard) is implemented inconsequently.
Take [personal_unlockAccount](https://github.com/ethcore/parity/wiki/JSONRPC-personal-module#personal_unlockaccount) for example. If quantity is encoded as hex it fails, if it's numeric everything is ok.

**Comment by keorn** [comment]
Indeed that is a bug, thanks for reporting!
