### ISSUE TITLE
The UI needs a page refresh to start working with no pre-existing authcodes

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3620]
To reproduce:

1. delete `~/.parity/signer/authcodes`
1. start parity as `parity` (note: without the "ui" command, or the bug won't show itself)
1. open `127.0.0.1:8180` in your browser
1. the UI gets stuck at "Connecting to the Parity Secure API" until the page is refreshed

**Comment by keorn** [comment]
I think you need to go to `localhost:8080` which redirects you to `8180`.

**Comment by jesuscript** [comment]
the hostname has to be 127.0.0.1, not localhost. Not sure how this makes a difference anyway, the page still won't update

**Comment by keorn** [comment]
works fine for me every time...

**Comment by derhuerst** [comment]
Cannot confirm. `localhost:8080` and `127.0.0.1:8080` both redirect me to `127.0.0.1:8180`, which connects successfully and then shows "generate a Signer token". Tested on `master`.

**Comment by derhuerst** [comment]
Can confirm actually (on `:3000`), but had to delete restart parity *twice* after deleting `~/.parity/signer/authcodes` for some reason. Will look into it.

**Comment by ngotchac** [comment]
Should be fixed with #3927

**Comment by derhuerst** [comment]
Please reopen if the problem shows up again.
