### ISSUE TITLE
Dropping V62 peers

### ISSUE THREAD

**Issue by zilm13** [ethcore/parity#3624]
Hello, you are currently dropping incoming connections from V62 peers while you supported them some time ago.
I guess, these lines are the reason of it https://github.com/ethcore/parity/blob/master/sync/src/chain.rs#L610-L614
Could you return support for V62 peers?

**Comment by zilm13** [comment]
@arkpar V62 is not deprecated officially and V62 nodes are still useful for you on short sync, for headers, block bodies etc.

**Comment by gavofyork** [comment]
What counts as "officially"? :-)

**Comment by Nashatyrev** [comment]
Hey guys! 
We just want to understand the reasons behind dropping the peer which declares only eth62 supported. It doesn't differ from the scenario when the peer declares eth62,eth63 and uses only eth62 (as far as I know Parity supports eth63 in 'passive' mode only)
