### ISSUE TITLE
unable to scroll to bottom of contract create screen

### ISSUE THREAD

**Issue by david-sg** [ethcore/parity#3629]
I'm unable to get to the create option in the create contract screen - using chrome on a surface4. The options fields are below the screen area and there's no way to scroll or move to the bottom.

![viewcontract](https://cloud.githubusercontent.com/assets/5844023/20645095/8142e35c-b48c-11e6-995e-44e0a8f755db.png)

**Comment by derhuerst** [comment]
Can you tell me which version of Parity you are using?

Neither on `v1.4.5` nor on `master` can I reproduce the UI your screenshot shows. Both query the constructor parameters in a separate step, which is shown in a scrollable modal.

**Comment by derhuerst** [comment]
I can confirm the problem on `beta`.

**Comment by david-sg** [comment]
Parity//v1.4.5-beta-a028d04-20161126/x86_64-windows-msvc/rustc1.13.0

**Comment by derhuerst** [comment]
On `beta`, this should be fixed now.
