### ISSUE TITLE
UI Bug when enabling or disabling views in web UI

### ISSUE THREAD

**Issue by LogvinovLeon** [ethcore/parity#3631]
When you disable a view it's actually disabled, but it still shows it's icon in a view pannel in place of a next view.

<img width="1278" alt="screen shot 2016-11-27 at 13 12 37" src="https://cloud.githubusercontent.com/assets/6204356/20648303/618e88ec-b4a3-11e6-8dd5-acf68b6fa13f.png">
Here i disable Address Book and click on Accounts.
<img width="1280" alt="screen shot 2016-11-27 at 13 12 48" src="https://cloud.githubusercontent.com/assets/6204356/20648304/619853ea-b4a3-11e6-9e0a-d3ebd358e811.png">
But it's still showing Address Book icon.
<img width="1280" alt="screen shot 2016-11-27 at 13 12 56" src="https://cloud.githubusercontent.com/assets/6204356/20648305/6198bace-b4a3-11e6-83f6-d9b69b4ca850.png">
If you click on this icon it brings you to Applications and now the application icon is duplicated.

The similar bug also appears if you enable views.

**Comment by gavofyork** [comment]
it does eventually prune down the icons to the right ones, but it's hit an miss for a few clicks, for sure.
