### ISSUE TITLE
Please release versioned docker images

### ISSUE THREAD

**Issue by Levino** [ethcore/parity#3632]
Could you please tag docker images with versions? Just using "stable" is kinda unsexy.

**Comment by jesuscript** [comment]
note: create a new job in gitlab-ci with `only: tags` to create a new image on tag releases and push to docker hub

**Comment by General-Beck** [comment]
https://github.com/ethcore/parity/blob/master/docker/hub/Dockerfile for `latest` build
https://github.com/ethcore/parity/blob/master/.gitlab-ci.yml#L473 for `tags`
