### ISSUE TITLE
JS Precompiled is not updated

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3647]
There are plenty of commits containing JS stuff in master, but there is no `js-precompiled` bump commit.
So the latest changes in UI are not available when compiling Parity.

**Comment by jacogr** [comment]
It seems to have recovered. Seems to be the same issue as we had on beta, i.e. `&` as opposed to `&&` for chaining scripts in the gitlab-ci.yml.

**Comment by General-Beck** [comment]
Yes, it's works
