### ISSUE TITLE
Gitlab should build on Pull Requests rather than new commits in branches

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3670]
See https://github.com/ethcore/parity/pull/3652#issuecomment-263593804 - no Gitlab ticks. The problem is that right now Gitlab builds branches on new commits. We should instead detect pull requests and build the `compare` branches (which might happen to be part of forked repos)

**Comment by rphmeier** [comment]
Every PR gets its own branch in the main repo as seen here: https://help.github.com/articles/checking-out-pull-requests-locally/

Isn't this what the webhooks trigger points to?

**Comment by jesuscript** [comment]
expand?

**Comment by rphmeier** [comment]
I think you can pull the head for any PR (imagine XXXX is a number) to a local branch "BRANCHNAME" with `origin refs/pull/XXXX/head:BRANCHNAME`

I always saw travis do this and I've done it as well a couple of times.

**Comment by jesuscript** [comment]
gotcha. Yeah, I was thinking of having a webhook server that listens for Pull Request events and then clones and builds the forked repo (the remote and branch info can be found in the webhook request data) - this way we can make sure the target builds and passes all tests without creating a redundant branch in our repo. 

My only slight worry I have is, in both cases, we make ourselves open to potentially malicious PRs aimed at messing with our build system. It's not a huge risk, as we can report those who do it, but maybe something to keep in mind?

**Comment by rphmeier** [comment]
The fix for that is just to use something like @bors or @homu to trigger CI post-review by someone with privileges. The Rust project has a two-stage testing pipeline:
  - Test with travis on linux on PR open
  - After signal from a team member the bot will test on all platforms and automatically merge on success or complain on error/merge conflict.

**Comment by jesuscript** [comment]
that would be sick! Although, the 2-step system probably deserves it's own ticket

**Comment by jesuscript** [comment]
decided against this as there are certain advantages to building on new pushes even if they are not PR'ed, especially since the CI currently copes with the load without problems. May revisit this in the future
