### ISSUE TITLE
Fix spontaneous tag rebuilds

### ISSUE THREAD

**Issue by jesuscript** [ethcore/parity#3672]
These completely fuck up our build pipelines, can we please stop this happening?

![gitlab](http://i.imgur.com/v5OqxXp.png)

**Comment by gavofyork** [comment]
it was assigned `dropeverything` 28 days ago. why is this not sorted yet?

**Comment by jesuscript** [comment]
there were multiple causes for the rebuilds. we're now down to fixing the last one

**Comment by jesuscript** [comment]
Currently testing a new GH-GL bridge which should prevent this problem happening again. The project is also moving to a new home on GL. Will complete the switch after the release.

**Comment by jesuscript** [comment]
so, we're done with the migration. rebuilds shouldn't be happening any more
