### ISSUE TITLE
Homestead accounts/contracts displayed while running Ropsten

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3683]
parity started with `--chain ropsten`

I see the Ropsten accounts/contracts but also the Homestead ones.

![screen shot 2016-11-29 at 20 02 37](https://cloud.githubusercontent.com/assets/738724/20724502/cf63c0ea-b66e-11e6-8d34-d44659a9837b.png)

**Comment by jacogr** [comment]
When you run with `--chain` is uses the same database as "normal". (Accounts, addressbook, all shared here - `~./parity/keys`.) `--testnet` loads with data from the `~/.parity/testnet_keys` directory.

**Comment by chevdor** [comment]
I see. This is confusing. Since we know when using --chain ropsten that this is testnet, should not --testnet be applied automatically?
