### ISSUE TITLE
not able to start parity.exe (1.4.5) with --geth

### ISSUE THREAD

**Issue by CaptainSkywave** [ethcore/parity#3690]
I just installed the WIN .exe file (1.4.5)
Not able to start parity.exe with --geth string
CMD window opens briefly and closes immediately - not even able to see any error message

**Comment by arkpar** [comment]
Check the tray icon, perhaps Parity is already running? In such case you need to close it first via the tray menu.

**Comment by CaptainSkywave** [comment]
@arkpar - that was soo true ;) parity was already running - stopped it and now --geth works, thx.
