### ISSUE TITLE
Mac installer: v 1.4.5 failed installation does not show

### ISSUE THREAD

**Issue by tjsaw** [ethcore/parity#3699]
v 1.4.0 installed (via darwin installer) and running in the background.

When the v 1.4.5 installer is used, installation fails.

Failure is not shown and the Parity UI is restarted with the old version. Lay user cannot ascertain why upgrade not possible

To remove v 1.4.0 need to manually key 
`sudo` /usr/local/libexec/uninstall-parity.sh

Desirable to remove v 1.4.0 with new installer, or at least show that installation failed.

**Comment by 5chdn** [comment]
Please try again with the latest installer, and report back if it still does not work.

Also, try to use the update button in the UI.
