### ISSUE TITLE
On detecting a network change, the accounts/balances should refresh completely

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3723]
e.g. stop with `--testnet` start with no chain (`homestead`)

Currently balances are refreshed, however tokens not adjusted, neither are the actual available accounts.

**Comment by derhuerst** [comment]
As discussed with @jacogr, will make a message "You switched the network. Please reload the page." show up.

It would be a lot of work, with dozens of edge cases to remove, to make the UI fully dynamic in this aspect. As switching chains right now is something only advanced users will do, it seems like a reasonable compromise between effort & usability.
