### ISSUE TITLE
Account balance not updated after successful transaction-no further transactions possible

### ISSUE THREAD

**Issue by fonja** [ethcore/parity#3724]
Hi,
I transfered some ETH to exchange, but balance does not change. I tried to make a new transaction but without success. Installed ver 1.4.5
Tnx for support

**Comment by derhuerst** [comment]
Did the transactions get mined? In the Signer, it says "x confirmations" if it has been mined or "waiting for confirmations" it it hasn't yet.

**Comment by fonja** [comment]
It went through even with a delay. Tnx

**Comment by tomusdrw** [comment]
Seems to be solved. Please re-open if the problem persists.
