### ISSUE TITLE
test async web3 ipc transaction, server no reply

### ISSUE THREAD

**Issue by jay411tw** [ethcore/parity#3726]
Hi, I got a problem about I send a lot of transactions (1000) at one time to the node, but node only does reply the first transaction result when I execute this javascript at the first time. Then I try to execute again, the node doesn't give any response until I restart the node. But still only reply the first transaction result. This script works well on go-ethereum.  The node starting through this cmd: parity --chain homestead_test.json (the json definition file I grabbed from parity test genesis). Anyone can tell me is it the node bugs or My code have something wrong? 

my test platform is:
version Parity/v1.4.5-beta-a028d04-20161126/x86_64-linux-gnu/rustc1.13.0

The code:
```
var Web3 = require('web3');
var web3 = new Web3();
var web3HTTP = new Web3();
var web3IPC = new Web3();
var  net = require('net');

web3HTTP.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
var client = new net.Socket();
web3IPC.setProvider(new web3.providers.IpcProvider('/home/jay/.parity/jsonrpc.ipc', client));

var accounts = web3HTTP.eth.accounts;
// set the default account
web3HTTP.eth.defaultAccount = accounts[0];
console.log(web3HTTP.eth.defaultAccount);

var ret = web3HTTP.personal.unlockAccount(accounts[0], "1", 36000);
console.log("unlock account: " + ret);
var start = new Date().getTime();
        while (new Date().getTime() < start + 3000);


var start = Date.now();
for (i=0; i< 10; i++) {

web3IPC.eth.sendTransaction({from:accounts[0],to:accounts[1],value:'0x01',gasPrice:'0x01',gasLimit:'0x01',data:'0x01'}, function(error, addr){
    if(!error) {
        console.log(addr);
        var finish = Date.now();
        var timeDiff = finish - start;
        console.log(timeDiff);
        }
    else
        console.error(error);
});

}
```

**Comment by derhuerst** [comment]
Please format your code [as I told your in the last issue](https://github.com/ethcore/parity/issues/3720#issuecomment-264901119). 😉

**Comment by jay411tw** [comment]
Sorry, I am new user for post code on thread, the icon "<>" seems like no work when I marked my code.

**Comment by derhuerst** [comment]
See the [GitHub help on formatting code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by tomusdrw** [comment]
Unlocking accounts works differently in Parity since it's very unsafe (last parameter is ignored, we only unlock account for single transaction).

Please run with `--geth` (which brings back the unsecure behaviour) or use `personal.signAndSendTransaction(transaction, password, callback)` instead.

**Comment by tomusdrw** [comment]
@jay411tw Is the issue still happening? Does `--geth` solve the problem?
