### ISSUE TITLE
RPC eth_getBalance does not accept QUANTITY

### ISSUE THREAD

**Issue by SinErgy84** [ethcore/parity#3733]
version: `Parity/v1.4.6-beta-5feccf1-20161205/x86_64-linux-gnu/rustc1.13.0`

Like in https://github.com/ethcore/parity/wiki/JSONRPC-eth-module#eth_getbalance specified
the string quantity-parameters ` "latest", "earliest" or "pending"` are not accepted by client while throwing error: `Invalid params`, code: `-32602`
Using a blocknumber has no issues

Some time ago I reported a similar bug (#3637 for v1.4.5, this version had no issues with eth_getBalance calls).

**Comment by SinErgy84** [comment]
Sorry, issue was forced by me while calling eth_getBalance for `0x2488fB14E55211F891a779496114529982693b00\n`
Didn't see the faulty \n at the end of an automated call

**Comment by rphmeier** [comment]
We do have tests for the deserialization of RPC arguments for all methods. Here are the ones for `eth_getBalance`: https://github.com/ethcore/parity/blob/master/rpc/src/v1/tests/mocked/eth.rs#L383

These tests are run on every PR before it can be merged; could you compare your RPC invocation to that in the tests?
