### ISSUE TITLE
Account / Transfer broken in master

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3756]
If this is wip, feel free to ignore. Currently, the transfer button in the accounts tab no longer does anything but raising errors in the (devtools) console.

**Comment by jacogr** [comment]
Didn't see it as part of https://github.com/ethcore/parity/pull/3750 - could be fixed already, to confirm.

**Comment by chevdor** [comment]
I just compiled master, the issue is still there. Since #3750 is not yet merged, I will test again later.

**Comment by chevdor** [comment]
I checked after the merge and I still see the issue.

**Comment by derhuerst** [comment]
Can't confirm. I get an error in the console when adapting the gas price, but i can still send the transaction.

**Comment by chevdor** [comment]
I recompiled again. Here I get no error, just nothing happens when clicking the Transfer button.

**Comment by jacogr** [comment]
Also can't confirm at all. Been in-and-out of Transfer the whole day thus far.

What errors are you seeing in the console?

**Comment by ngotchac** [comment]
I also can confirm I can't confirm... Logs would be ideal yes :)

**Comment by jacogr** [comment]
Saw this with @arkpar

**Comment by chevdor** [comment]
Tested just now and it now looks OK. Thanks for the fix.
