### ISSUE TITLE
Shapeshift integration keeps on defaulting to bitcoin

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3767]
In the shapeshift integration, the user can select to fund an account wih ETH from BTC and a bunch of other currencies.

When a new block comes in, the selected currency is set back to BTC.

To reproduce: select another currency than BTC and wait for a block to come in.

![screen shot 2016-12-09 at 13 13 37](https://cloud.githubusercontent.com/assets/738724/21048787/5e994786-be11-11e6-8879-0912be6226b9.png)

**Comment by jacogr** [comment]
Cannot reproduce, have left it open on a variety of coins for 5-10 min stretches (while syncing & well as retrieving blocks). Have also looked at the code, there is no refresh on block, rather the list is retrieved once and the selected value not changed. 

So really not sure what is up atm.

**Comment by chevdor** [comment]
I can no longer reproduce the issue...
I will keep an eye on that and gather more next time if possible.

**Comment by jacogr** [comment]
Well, if you saw it, there is definitely something up somewhere - just cannot see what it is.
