### ISSUE TITLE
Don't restrict accounts by default

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3771]
Since #3627 is in `eth_accounts` returns empty list by default.
It might be wiser to return a full list if no user action (for compatibility) is taken and have a setting in UI to restrict the default list of accounts (could be part of initial setup, like: "Always expose all account for dapps")

**Comment by gavofyork** [comment]
Prefer for parity to be secure by default. I think if the endpoint has access to the `personal_newAccount` API, then the created account should be visible through `eth_accounts` by default.

**Comment by tomusdrw** [comment]
#3792 makes the behaviour configurable (we can also easily switch default from `AllAccounts` to `Whitelist(vec![])`), pretty much if endpoint has access to `personal_newAccount` it also has access to unrestricted `personal_listAccounts`. We may introduce a distinction between standard http RPC/IPC and dapps RPC, but imho I would prefer to keep it consistent (maybe we will also figure out a way to distinguish the dapps on those transports).

**Comment by tomusdrw** [comment]
We decided to restrict the accounts by default, but there are additional RPCs to alter this policy.
