### ISSUE TITLE
Focus remains on the background page when a popup shows up

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3814]
To reproduce:

- open a popup (transfer, shapeshift, etc...)
- don´t click anywhere
- hit TAB a few times

=> you will see the focus jumping in the main page under the modal "popup".

**Comment by derhuerst** [comment]
It would be possible to give all inputs in a modal a higher tab index. However, `material-ui` doesn't seem to support them throughout all components, and it would be difficult not to interfere with existing tab index mechanisms.

The cheaper solution would be to – once the modal is shown – focus the first input in the modal manually.

**Comment by chevdor** [comment]
Right, probably not perfect but better than the current behaviour. Beware, the first input is often an address input field and I fear that you cannot focus.

**Comment by derhuerst** [comment]
Another option might be to set `autofocus` on every input (in a modal). Will quickly check if that helps.
