### ISSUE TITLE
Fail deploying simple contract due to gas limit

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3820]
I tested with the following contract:
```
pragma solidity ^0.4.4;

contract Simple {
    address recipient;
    function Simple(address rec) {
        recipient = rec;
    }
}
```
and I get the following message before deploying:
`Provides 60,000,000 gas (20,000M/ETH) for a total transaction value of 1.20000 ETH`
Going further:
```
[-32010] Transaction cost exceeds current gas limit. Limit: 5183626, got: 60000000. Try decreasing supplied gas.
CLOSE
```

I am compiling with the compiler version 0.4.4

**Comment by chevdor** [comment]
I tested with 0.4.7-nightly.2016.12.11+commit.84d4f3da and it worked.

**Comment by chevdor** [comment]
0.4.6 fails as well.

**Comment by rphmeier** [comment]
What method are you using to deploy the contract? Manual transaction through RPC or a UI feature?

**Comment by chevdor** [comment]
Only UI features.
First I compiled and used the solc --combined output (solc 0.4.4).
Running into the issue I tried letting the parity UI compile and got
similar issues as well.

**Comment by jacogr** [comment]
Parity returns 50M (which we helpfully increase by 20%) when it cannot execute the transaction. (We should however be adding the same "this will throw an exception message" to the deploy UIs as well - in the queue)

**Comment by chevdor** [comment]
The fact that parity returns a huge/max amount of gas is fine when the contract throws. Indeed a clear message would be better but that´s no big deal.

The issue here is/was that I don´t think the contract I used to test can throw in any case during deploy.

Today, I tested again:
- deploying from a combined output from solc (latest)
- compile/deploy from the UI using 0.4.6
- compile/deploy from the UI using latest compiler

All of those tests succeeded so I close this one.

@jacogr you may want to add a new issue for the "this will throw an exception message" message.
