### ISSUE TITLE
Consider another license or dual license for Parity ?

### ISSUE THREAD

**Issue by dlecan** [ethcore/parity#3841]
Licenses:
- Geth: [GPLv3](https://github.com/ethereum/go-ethereum/blob/master/COPYING) and [LGPLv3](https://github.com/ethereum/go-ethereum/blob/master/COPYING.LESSER)
- Cpp-Eth: [GPLv3](https://github.com/ethereum/cpp-ethereum/blob/develop/LICENSE), but there is a [relicensing plan to APLv2](https://bobsummerwill.com/2016/07/12/c-re-licensing-plan/)
- EthereumJ: [MIT](https://github.com/ethereum/ethereumj/blob/develop/LICENSE)
- Parity: [GPLv3](https://github.com/ethcore/parity/blob/master/LICENSE)

Do you think Parity could be released under a more permissive license? LGPL, APLv2 or MIT?

**Comment by keorn** [comment]
Parity is dual license, please get in touch at legal@ethcore.io if you would like to obtain access to a commercial license.
