### ISSUE TITLE
Support web hosted dapps

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3845]
This is meant to be an MVP effort. Doesn't need to be perfect at this point.

UI: A text box at the top of the page allowing users to type a URL (e.g. `https://mkr.market/`) which would then lead to something like `(http://127.0.0.1:8180)/proxy/https://mkr.market/`.

Core: Parity would interpret the content `/proxy/https://mkr.market/` as meaning "grab content from `https://mkr.market/` and serve as a dapp in an iframe".

End result users can easily get to web-server-hosted dapps in Parity.

**Comment by tomusdrw** [comment]
IMHO if it's a MVP it's better to integrate it as a builtin dapp (called "Web2.0 Browser") or something like this, it won't pollute current UI that much.

Also we need to be careful with XHR calls cause this allows the dapp to fetch arbitrary data overcoming SOP (example: `POST http://localhost:8080/proxy/http://localhost:8545/`)

**Comment by gavofyork** [comment]
sure but then it'll need to have higher permissions than normal due since it'll need to access unsafe APIs. that ok?

**Comment by tomusdrw** [comment]
Yup. Will figure out some scheme.

**Comment by gavofyork** [comment]
that would be useful to have anyway so i can get my console dapp to use all the APIs.
