### ISSUE TITLE
populate_from_parent may violate (YP:45) in certain cases

### ISSUE THREAD

**Issue by lgpawel** [ethcore/parity#3861]
See case starting at https://github.com/ethcore/parity/blob/master/ethcore/src/ethereum/ethash.rs#L185

Assume that `bound_divisor = gas_limit` (*) and `gas_used ≥ ⅚ gas_limit`. Then, in the expression in lines 188-189, `⌊gas_limit / bound_divisor⌋ = 1 = ⌊(gas_used * 6 / 5) / bound_divisor⌋` and the terms cancel out. The expression is then equal to `gas_limit + 1`, ie. strictly larger than `gas_limit`. If `gas_floor_target` is less than that and `gas_ceil_target` greater than that, this will become a new gas limit value.

However, with (*), (YP:45-46) translate to `gas_limit - 1 < new_gas_limit < gas_limit + 1` (as the floor term equals 1). So this is a legitimate parameter combination which prevents the gas limit from changing, and so, the block mined according to the above will be invalid.

The effect is still present if (*) is replaced by `divisor > ½ gas_limit`, so it's not limited to that _very_ specific case.

**Comment by tomusdrw** [comment]
> The effect is still present if (*) is replaced by divisor < ½ gas_limit, so it's not limited to that very specific case.
Shouldn't it be `divisor > ½ gas_limit`?

**Comment by lgpawel** [comment]
Definitely right, corrected.

**Comment by gavofyork** [comment]
Note: fix by adding `min(

**Comment by gavofyork** [comment]
Fixed in #3884
