### ISSUE TITLE
API call to selectively delete old transactions and receipts

### ISSUE THREAD

**Issue by ethernomad** [ethcore/parity#3913]
Certain transactions may contain content that node operators do not wish to store or transmit due to moral or legal reasons.

It would be really great if Parity had an API command to permanently prevent the database from storing transactions and receipts with specific txids.

Of course there is nothing that can be done about such content in state, but having the option to remove transactions and receipts would go a long way.

**Comment by gavofyork** [comment]
block pruning and our upcoming LES client will help this to some degree, and there are more important things to be doing that implementing a flawed personal censorship system.
