### ISSUE TITLE
eth_estimateGas under-estimating for token xfer

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#3930]
From chat on gitter.

**Comment by jacogr** [comment]
UI does use eth_estimateGas. Process is -

1. Call eth_estimateGas
2. Adjust by factor of 1.2 (giving slightly better chance of success)
3. Call using those calculated values

**Comment by sammy007** [comment]
I tried to transfer token which requires 100K gas. UI estimated less than 30K. I had `--gas-floor-target 500000` setting on a node. So I guess it uses something different. cc @gavofyork

**Comment by gavofyork** [comment]
@sammy007 could you detail what steps you went through to transfer the token?

**Comment by sammy007** [comment]
1. Set `--gas-floor-target 500000`
2. Transfer token
3. out of gas exception

**Comment by tomusdrw** [comment]
Could it be related to #3749

**Comment by gavofyork** [comment]
@tomusdrw / @jacogr any luck in reproducing this?

**Comment by tomusdrw** [comment]
I wasn't trying to reproduce this exact issue, but could easily reproduce #3749

**Comment by gavofyork** [comment]
will probably push this to a patch release.

**Comment by gavofyork** [comment]
this may be fixed by #4100. to help me reproduce, @sammy007 could you be more specific as to the type of token you were transferring and how exactly you transferred it?

**Comment by sammy007** [comment]
It was ICN tokens.

**Comment by sammy007** [comment]
Tried again with 1.4.9. You can see history https://etherscan.io/address/0xb85150eb365e7df0941f0cf08235f987ba91506a (all failed txes).
