### ISSUE TITLE
Error message inaccurate when querying future block.

### ISSUE THREAD

**Issue by flyswatter** [ethcore/parity#3939]
[It seems](https://github.com/MetaMask/metamask-plugin/issues/945) that when querying something (like a balance or a transaction count) at a future-numbered block, geth throws an error with an inaccurate message:
```
This request is not supported because your node is running with state pruning. Run with --pruning=archive.
```

If someone queries for a future block, it should probably be either the latest block or throw a consistent error.  Geth right now returns a mal-formed reply, so you both might want to take this opportunity to coordinate a consistent behavior.

**Comment by rphmeier** [comment]
This seems like a quick fix. Querying a block which isn't stored should definitely return some kind of error as opposed to returning another block entirely (latest or pending).
