### ISSUE TITLE
URL input on Applications tab

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3957]
...to go directly to URL from `Applications` tab.

Requires including browsing address in routing, i.e. `#/web/https://mkr.market`.

![screenshot from 2016-12-23 12 59 14](https://cloud.githubusercontent.com/assets/581548/21453661/aa14c504-c911-11e6-8ba7-438209027c92.png)

After: #3956

**Comment by gavofyork** [comment]
3956 is now merged - will need someone on this...
