### ISSUE TITLE
parity_newAccountFromPhrase no longer works in master

### ISSUE THREAD

**Issue by SyRenity** [ethcore/parity#3972]
Trying to generate dev account with empty passphrase:

> curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["","password"],"id": 1}' localhost:8545

Returns:

>{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":null},"id":1}

**Comment by tomusdrw** [comment]
`parity_newAccountFromPhrase` is part of `parity_accounts` namespace which is not exposed by default on JSON-RPC over HTTP.

Please run with `--jsonrpc-apis eth,...,web3,parity_accounts` to make it work.
