### ISSUE TITLE
Enabling applications is instantly forgotten

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3985]
Clean build of latest master Parity/v1.5.0-unstable-4e51f93-20161227/x86_64-macos/rustc1.14.0

At http://127.0.0.1:8180/#/apps

Applictions -> Edit -> [Enable the additional two] -> Ok
(They show up)
[Reload]
(They've gone again)

**Comment by jacogr** [comment]
Was fixed as part of https://github.com/ethcore/parity/pull/3966
