### ISSUE TITLE
[Object object] in new account selector placeholder

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3986]
build JS / latest master (`bc3dacc952056ffea6c709e1f92653cd0e29cf63`)
![screenshot from 2016-12-28 14 00 05](https://cloud.githubusercontent.com/assets/581548/21522468/fe3dd466-cd05-11e6-81cb-e5aedfb69e55.png)

**Comment by jacogr** [comment]
@ngotchac made a fix for this in https://github.com/ethcore/parity/pull/3992
