### ISSUE TITLE
UI: Wrong balance unit

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#4006]
I wish I had such a balance in ETH but I think there is a little confusion between ETH and WEI.
<img width="672" alt="screen shot 2017-01-01 at 21 34 59" src="https://cloud.githubusercontent.com/assets/738724/21582931/4f625a8a-d06a-11e6-9ce4-943755174775.png">

See on a version that is already a few days old.

**Comment by tomusdrw** [comment]
@ethcore/ui-devs can someone confirm?

**Comment by ngotchac** [comment]
I think I saw that a few days ago, but it should be fixed now

**Comment by derhuerst** [comment]
Cannot replicate the error.

**Comment by ngotchac** [comment]
From this commit change : https://github.com/ethcore/parity/commit/fd41a10319ee1689d2d7dc74a355c1694e978d85#diff-95334a1abae76b5a9876cb89027274beR386

**Comment by ngotchac** [comment]
Closed with #3990 
Feel free the re-open it if it ever happens again
