### ISSUE TITLE
Parity 1.4.7 excessive upload traffic

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#4007]
Running on Windows 10 64bit.  Upload traffic sits consistantly around 100KB/sec, compared to Geth which hovers around 10KB/sec.

If this is expected bandwidth consumption, perhaps a command line arg to throttle bandwidth usage.

**Comment by derhuerst** [comment]
See also #2831.

**Comment by tomusdrw** [comment]
Duplicate of #2831, see also #1596 and #2053
