### ISSUE TITLE
Account password is invalid or account does not exist.  CLOSE

### ISSUE THREAD

**Issue by sammy007** [ethcore/parity#4009]
Account password is invalid or account does not exist.

CLOSE

 fuck yeah, this shit just does not work.
Transaction gas is too low. There is not enough gas to cover minimal cost of the transaction (minimal: 23320, got: 0). Try increasing supplied gas.

This shit just does not work.

**Comment by tomusdrw** [comment]
Could you provide more details?

Which RPC method are you invoking? Could you provide a log of running with `-lrpc=trace`? (make sure to remove your password from log if you're using `personal_signAndSendTransaction`)

**Comment by gavofyork** [comment]
user unresponsive. closing. @sammy007 please reopen if you still have an issue.

**Comment by sammy007** [comment]
Will double check later next week. Also sorry for such a style.

**Comment by sammy007** [comment]
All ok. Typed in old password on several accounts previously :(
