### ISSUE TITLE
error compiling ethcore-bigint

### ISSUE THREAD

**Issue by inmathwetrust** [ethcore/parity#4025]
Compiling quick-error v1.1.0
   Compiling serde v0.8.19
   Compiling phf_shared v0.7.14
   Compiling phf v0.7.14
   Compiling serde_json v0.8.1
   Compiling ethcore-light v1.5.0 (file:///home/ubuntu/parity/ethcore/light)
   Compiling phf_generator v0.7.14
   Compiling rpassword v0.3.0
   Compiling rocksdb-sys v0.3.0 (https://github.com/ethcore/rust-rocksdb#64c63ccb)
   Compiling sha3 v0.1.0 (file:///home/ubuntu/parity/util/sha3)
warning: ar: `u' modifier ignored since `D' is the default (see `U')
   Compiling nix v0.6.0
   Compiling rust-crypto v0.2.36
   Compiling num v0.1.32
   Compiling number_prefix v0.2.5
   Compiling rocksdb v0.4.5 (https://github.com/ethcore/rust-rocksdb#64c63ccb)
   Compiling primal-check v0.2.2
   Compiling primal v0.2.3
   Compiling kernel32-sys v0.2.2
   Compiling time v0.1.35
   Compiling transient-hashmap v0.1.0
   Compiling heapsize v0.3.6
   Compiling term v0.2.14
   Compiling bigint v1.0.0
   Compiling ethcore-bigint v0.1.2 (file:///home/ubuntu/parity/util/bigint)
error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:458:1: 458:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:458:1: 458:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:458:1: 458:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:458:1: 458:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:458:1: 458:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:459:1: 459:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:459:1: 459:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:459:1: 459:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:459:1: 459:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:459:1: 459:20 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:460:1: 460:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:460:1: 460:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:460:1: 460:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:460:1: 460:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:460:1: 460:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:461:1: 461:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:461:1: 461:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:461:1: 461:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:461:1: 461:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:461:1: 461:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:462:1: 462:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:462:1: 462:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:462:1: 462:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:462:1: 462:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:462:1: 462:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:463:1: 463:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:463:1: 463:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:463:1: 463:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:463:1: 463:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:463:1: 463:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:464:1: 464:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:464:1: 464:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:464:1: 464:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:464:1: 464:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:464:1: 464:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:465:1: 465:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:465:1: 465:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:465:1: 465:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:465:1: 465:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:465:1: 465:22 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:466:1: 466:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:466:1: 466:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:466:1: 466:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:466:1: 466:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:466:1: 466:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:170:13
    |
170 | 				let a = s.from_hex()?;
    | 				        ^^^^^^^^^^^^^
util/bigint/src/hash.rs:467:1: 467:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:184:6
    |
184 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:467:1: 467:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:193:6
    |
193 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:467:1: 467:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:195:5
    |
195 | 				write!(f, "…")?;
    | 				^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:467:1: 467:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: the `?` operator is not stable (see issue #31436)
   --> util/bigint/src/hash.rs:197:6
    |
197 | 					write!(f, "{:02x}", i)?;
    | 					^^^^^^^^^^^^^^^^^^^^^^^
util/bigint/src/hash.rs:467:1: 467:24 note: in this expansion of impl_hash! (defined in util/bigint/src/hash.rs)

error: aborting due to 50 previous errors

error: Could not compile `ethcore-bigint`.

**Comment by tomusdrw** [comment]
Please update your rust compiler:
`rustup update stable`
