### ISSUE TITLE
accessing parity wallet through --geth flag doesn't work

### ISSUE THREAD

**Issue by mirage007** [ethcore/parity#4026]
Not exactly sure if this is a bug or just not part of the --geth feature.

on Parity/v1.4.7-beta-f2058bd-20161227/x86_64-linux-gnu/rustc1.14.0, when i launch via 

    parity --geth --datadir datapath --keys-path keypath

and then run geth console via `geth attach` and try to list the corresponding accounts via `personal.listAccounts` I get an empty list. Does the --geth flag only change the communication protocol? If so, how can I access the wallet via the geth console to send transactions?

**Comment by tomusdrw** [comment]
I couldn't reproduce the issue running the command you specified, but please not that using `--tesnet` is actually overriding provided `--keys-path` (it's mentioned in the docs).

Is it possible that your were experiencing this issue while using `--testnet`?

**Comment by keorn** [comment]
`--keys-path` is just the base path for different chain key folders. Each `--chain` setting will have its own key store. You will need to move the keys across if you need them on another chain.

**Comment by tomusdrw** [comment]
@keorn wasn't that change introduced in 1.5?

**Comment by mirage007** [comment]
OK I guess coming from geth my mental model of the directory structure was
reversed.

Switching chains in parity does not require switching data path or keys
path, each chain will have subdirectories under the appropriate location.

Great thanks!
