### ISSUE TITLE
Using symbolic link to redirect blockchain data to automounted Samba share

### ISSUE THREAD

**Issue by MadMcJack** [ethcore/parity#4044]
I am using Parity on Linux however because of disk space restrictions I want to redirect the blockchain data to my NAS. I'd like to keep everything else on my Linux box.

So I made a symbolic link from ~/.parity/906a34e69aec8c0d to /smb/NAS/Parity/Blockchain/906a34e69aec8c0d and fired up parity and get this error:

`Client service error: Client(Database("Invalid argument: You have to open all column families. Column families not opened: col5, col4, col3, col2, col1, col0"))`

Why am I getting this error? And can it be fixed?

**Comment by MadMcJack** [comment]
I don't think so as I synced the chain first succesfully and then moved the data to the NAS and restarted parity.

**Comment by tomusdrw** [comment]
Can you check the integrity of created files (compare hashes before and after copying)? Maybe something was broken during the process.

**Comment by MadMcJack** [comment]
No, everything was correctly copied. And I also tried with an empty directory resulting in the error in my comment above.

**Comment by 5chdn** [comment]
NFS is a unix file sharing protocol and SMB a windows file sharing protocol, I'm not an experts on these protocols, but if you got it working with NFS it seems your Linux has issues with SMB. In general, it's not recommended to access the blockchain and database through network unless you can live with the negative performance impacts and other unexpected side-effects.
