### ISSUE TITLE
CSS issue with the tags in the new account search dialog

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#4045]
See the tags

<img width="356" alt="screen shot 2017-01-05 at 10 14 40" src="https://cloud.githubusercontent.com/assets/738724/21674870/ee552eb6-d32f-11e6-9133-62e6ced8048f.png">

**Comment by ngotchac** [comment]
NB: there's the same issue for accounts in the Accounts/Addresses/Contracts views. They are wider so it's less problematic though

**Comment by derhuerst** [comment]
In the long term, a merge with / switch to `ui/AccountCard` will be necessary anyways to keep the codebase small and consistent. So **this is just about temporary fixes**, possibly even for 1.5.

It is surprisingly hard to solve the issue without reworking the whole layout. I see these ways to solve it:

- Make the tags collection `position: static`, would mean that the rest of the content (icon etc) won't be align with it's the other accounts
- Introduce two columns, however this would get very very narrow with non-desktop-sized non-fullscreen windows. 
- Put the tags somewhere else, e.g. below the name & address. Consumes more space but is the most robust.

**Comment by ngotchac** [comment]
Something that I also tried was hidding the tags the overlays with the name. The code was a bit crap but it worked. However might be worth adding an icon to show that there are actually more tags than those displayed, or something similar.

**Comment by derhuerst** [comment]
@ngotchac is experimenting with a new tags layout.
