### ISSUE TITLE
Multi-sig contract does not send any amount on Ethereum Classic

### ISSUE THREAD

**Issue by SyRenity** [ethcore/parity#4057]
After the UI problem has been fixed, I tested the multi-sig sending both on ETH and on ETC.

On ETH it works fine, on ETC the contract doesn't actually send anything, despite being signed by minimum amount of co-signers, and the sign request disappearing from Parity UI.
http://gastracker.io/addr/0x677c0cca27b705b59d13a6ffd419bec3ef0a8cd8

**Comment by SyRenity** [comment]
@ngotchac Seems ETH contract code not working under ETC for some reason?

**Comment by SyRenity** [comment]
Attached is the screenshot of parity after the sending attempt.
![etc multi-sig](https://cloud.githubusercontent.com/assets/203866/21689881/a9b7ecbc-d37a-11e6-8966-769a70a3fdca.png)

**Comment by ngotchac** [comment]
@SyRenity It seems that a lot of transactions have failed due to gas estimation issues (eg. http://gastracker.io/tx/0x41720e414e29b63916656facdb2813f0abc14ca05d9610c84d6ab5f1db7103bb)

Could you try to resend those transactions increasing the supplied gas amount (from the _Edit Gas_ button in the signer, before signing the transaction). Gas estimation might sometime be a little off...

**Comment by SyRenity** [comment]
@ngotchac The transactions indeed failed until I've manually increased to a quite large value, and then they went through for remaining 2 co-signers. The contract unfortunately never performed any sending afterwards (compared to the Eth one).

**Comment by ngotchac** [comment]
@SyRenity It seems that the created transaction (http://gastracker.io/tx/0x186d0790809ebca2a12b89e924ed87b0527654d45160ba45f86119f4dfdf4360) had the wrong input, because it tried to send `0x10da15446e63d1e6169deb000000000` wei, which is about `1,400,000,000,000,000,000` eth (quite a bit more than the balance aha). It might be an error in the Transfer source code, but that should be fixed. Could you try to build from `master` once again?

**Comment by SyRenity** [comment]
@ngotchac Sure, should I redeploy a new multi-sig contract as well?

**Comment by ngotchac** [comment]
I don't think so, you shouldn't have to at least

**Comment by SyRenity** [comment]
@ngotchac Tried this again, unfortunately it didn't work:
http://gastracker.io/addr/0x677c0ccA27B705b59D13a6ffd419BeC3ef0a8CD8

You can see that the transactions went fine, but the contract was stll not executed.

So, would it be a good idea to redploy?

**Comment by ngotchac** [comment]
Something is wrong on our side on how we convert the user input to actually token/wei value. A PR is out (#4098) that would maybe fix that. If not, some logging info will be available for an easier debug...

**Comment by SyRenity** [comment]
@ngotchac Will specifying higher gas limit help with that? I tried up to 999999 with the same result.

**Comment by ngotchac** [comment]
No, unfortunately the issue is that the UI creates a transaction with the wrong info (the amount has too many zeros basically)

**Comment by ngotchac** [comment]
@SyRenity You should be able to try again, after having built `master`. If it still doesn't work, please copy and paste this in the JS console:

```javascript
window.localStorage.setItem('loglevel:modals/Transfer/store', 'TRACE');
```

This will add more logging/debugging. Then try again from scratch to send some eth, and share the logs printed in the console, that would help greatly !

**Comment by SyRenity** [comment]
> Then try again from scratch to send some eth

@ngotchac Just to be on same page, we speak about ETC (ETH works just fine) :).

**Comment by ngotchac** [comment]
Ok so I just tried with ETC, and everything works fine on my end... So I would suggest to try to again with the extras logging enabled as described above (will only work on latest master), and share those logs....

**Comment by SyRenity** [comment]
@ngotchac In the latest master the transaction never sent (despite setting a high gas of 999999), the UI shows the error "the transaction will throw an exception with the current values", and the console contains the following logs:

> index.c451ba0572.js:11 eth_estimateGas([{"to":"0x677c0cca27b705b59d13a6ffd419bec3ef0a8cd8","from":"0x0675c8d905fc2bf5d95e6f703e31e0dad84a184b","gas":"0x2faf080","data":"0xb61d27f600000000000000000000000000a41e254d371dd2b2b2ecfe693c8c4f51c0e4b6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"}]): -32015: Transaction execution error.
> a._onMessage @ index.c451ba0572.js:11
> index.c451ba0572.js:10 execute.estimateGas ["0x00a41e254d371dD2b2B2eCfe693c8C4f51C0e4B6", t, ""] t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}
> (anonymous) @ index.c451ba0572.js:10
> index.c451ba0572.js:17 etimateGas t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}
> (anonymous) @ index.c451ba0572.js:17
> index.c451ba0572.js:11 eth_estimateGas([{"to":"0x677c0cca27b705b59d13a6ffd419bec3ef0a8cd8","from":"0x0675c8d905fc2bf5d95e6f703e31e0dad84a184b","gas":"0x2faf080","data":"0xb61d27f600000000000000000000000000a41e254d371dd2b2b2ecfe693c8c4f51c0e4b6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"}]): -32015: Transaction execution error.
> a._onMessage @ index.c451ba0572.js:11
> index.c451ba0572.js:10 execute.estimateGas ["0x00a41e254d371dD2b2B2eCfe693c8C4f51C0e4B6", t, ""] t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}
> (anonymous) @ index.c451ba0572.js:10
> index.c451ba0572.js:17 etimateGas t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}
> (anonymous) @ index.c451ba0572.js:17
> index.c451ba0572.js:11 eth_estimateGas([{"to":"0x677c0cca27b705b59d13a6ffd419bec3ef0a8cd8","from":"0x0675c8d905fc2bf5d95e6f703e31e0dad84a184b","gas":"0x2faf080","data":"0xb61d27f600000000000000000000000000a41e254d371dd2b2b2ecfe693c8c4f51c0e4b6000000000000000000000000000000000000000000000000136dcc951d8c000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"}]): -32015: Transaction execution error.
> a._onMessage @ index.c451ba0572.js:11
> index.c451ba0572.js:10 execute.estimateGas ["0x00a41e254d371dD2b2B2eCfe693c8C4f51C0e4B6", t, ""] t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}
> (anonymous) @ index.c451ba0572.js:10
> index.c451ba0572.js:17 etimateGas t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}
> (anonymous) @ index.c451ba0572.js:17
> index.c451ba0572.js:11 eth_estimateGas([{"to":"0x677c0cca27b705b59d13a6ffd419bec3ef0a8cd8","from":"0x0675c8d905fc2bf5d95e6f703e31e0dad84a184b","gas":"0x2faf080","data":"0xb61d27f600000000000000000000000000a41e254d371dd2b2b2ecfe693c8c4f51c0e4b6000000000000000000000000000000000000000000000000136dcc951d8c000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"}]): -32015: Transaction execution error.
> a._onMessage @ index.c451ba0572.js:11
> index.c451ba0572.js:10 execute.estimateGas ["0x00a41e254d371dD2b2B2eCfe693c8C4f51C0e4B6", t, ""] t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}
> (anonymous) @ index.c451ba0572.js:10
> index.c451ba0572.js:17 etimateGas t {code: -32015, type: "EXECUTION_ERROR", method: "eth_estimateGas", text: "Transaction execution error.", message: "eth_estimateGas: -32015: Transaction execution error."…}

**Comment by ngotchac** [comment]
@SyRenity This should have been fixed via #4165

**Comment by SyRenity** [comment]
@ngotchac Confirmed, ETC sending works fine now :).

**Comment by ngotchac** [comment]
Great, thanks for taking the time to test !!
