### ISSUE TITLE
Creating account with empty phrase does not work as expected

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4059]
(To check)

From Slack -

peter [7:01 PM]  
cant import account with empty recovery phrase through UI, will that be changed? if not I will change the account in the dev chain.

jacogr [8:42 PM]  
Let me check, I’m sure we are supposed to allow empty phrases now.`

It is definitely supposed to allow it according to the what is intended by the code since we removed all length checks, there may be a bug with a completely empty phrase, will investigate.

**Comment by ngotchac** [comment]
Can confirm
