### ISSUE TITLE
Block size coerced to zero for uncle (should be null)

### ISSUE THREAD

**Issue by phleemac** [ethcore/parity#4062]
On Ropsten Testnet, 

- in console: `eth.getUncle(292832)` returns size of 0

- using JsonRpc,  `curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getUncleByBlockNumberAndIndex","params":["292832", "0x0"],"id":1}' localhost:8545` returns size of null

According to spec https://github.com/ethcore/parity/wiki/JSONRPC-eth-module#eth_getunclebyblocknumberandindex I expect them to return valid size of the uncle block.

**Comment by gavofyork** [comment]
it should be `null` in both circumstances. uncle block data (and therefore its size) is generally unavailable.

documentation updated.

**Comment by gavofyork** [comment]
@jacogr `size` is returned from RPC as `null` for uncles - this should be reciprocated into the JS result rather than being coerced to `0`.
