### ISSUE TITLE
Default “token deployment” Dapp issue

### ISSUE THREAD

**Issue by vbaranov** [ethcore/parity#4080]
I'm using Parity 1.4 testnet on OSX. When I'm trying to test default token deployment Dapp,

![screen shot 2017-01-03 at 01 06 34](https://cloud.githubusercontent.com/assets/4341812/21740628/48fc22a6-d4d0-11e6-915e-1c253e3507bd.png)

transaction sending responds with "Transaction cost exceeds current gas limit. Limit: 5183626, got:60000000. Try decreasing supplied gas."

![screen shot 2017-01-03 at 01 03 21](https://cloud.githubusercontent.com/assets/4341812/21740633/598752a8-d4d0-11e6-8e1f-a18c65fa137d.png)

Why is token deployment so expensive? Is it possible to avoid such error for this Dapp?

**Comment by gavofyork** [comment]
dapp should be stating how much gas is required directly.

**Comment by jacogr** [comment]
The 6M is when Parity throws an exception. Tested and there seems to be an issue with the actual contract as deployed on Ropsten, the dapp currently doesn't work at all.

**Comment by jacogr** [comment]
The dapp-specific TokenReg contract fee was set at the default value which is not passed through when registering tokens - fee adjusted & sample token deployed to verify that it now operates as intended.
