### ISSUE TITLE
SHA3 stuck on flawed "binary" encoding

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#4081]
`parity.api.util.sha3` interprets its argument as 'binary' information. This is problematic since there are certain binary blobs that JS cannot encode as a string, which get opaquely coerced to some other string. 

`web.sha3` addresses this by interpreting `0x` prefixed strings as hex-encoded data - other inputs are assumed to be binary-block strings.

It should probably be consistent with `web3.sha3`. Failing that, it should remain consistent with the JSONRPC's conventions and only accept `hex-encoded` data.

**Comment by tomusdrw** [comment]
Seems that `web3.sha3` has an additional option to indicate that data is hex-encoded bytes: https://github.com/ethereum/web3.js/blob/develop/lib/utils/sha3.js#L26

Looks like we already do something similar:
https://github.com/ethcore/parity/blob/master/js/src/api/util/sha3.js
