### ISSUE TITLE
Losing connection counts and sync stops at 1.4.7

### ISSUE THREAD

**Issue by miningpoolhub** [ethcore/parity#4082]
Parity wallet is slowly losing connection counts day by day and sync stops finally.
Printing same logs over time from that time.
It establishes new connection smoothly when I restart the daemon.
If I don't restart daemon it just stays in that situation forever.

It needed about 1 week to see this behaviour for one of my machine.
It happened ETH/ETC both even from previous version 1.4.6 and 1.4.7
I haven't tried 1.4.8 yet but I can't see similar issue fix logs so I'm reporting this problem.

**Comment by miningpoolhub** [comment]
Still happening at 1.4.9
Slowly losing connection counts and doen't recover.

**Comment by arkpar** [comment]
@miningpoolhub could you give version 1.5 a try? You'd need to compile it from source. See https://github.com/ethcore/parity#build-dependencies for instructions.

**Comment by gavofyork** [comment]
closing for now. please reopen if still an issue.

**Comment by miningpoolhub** [comment]
I was testing with 1.4.10 lately, and it seems like this issue is fixed.
Maybe I'll try 1.5 later.
Anyway I'm already satisfied with 1.4.10.

Great works. Thanks.

**Comment by miningpoolhub** [comment]
No. It's much better than before but 1.4.10 still has this issue.
