### ISSUE TITLE
solc and eth_compileSolidity produce different bin

### ISSUE THREAD

**Issue by phleemac** [ethcore/parity#4083]
> curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_compileSolidity","params":["contract test { function multiply(uint a) returns(uint d) {   return a * 7;   } }"],"id":1}' localhost:8545

produces:

"0x6060604052346000575b6077806100176000396000f300606060405263ffffffff60e060020a600035041663c6888fa181146022575b6000565b34600057602f6004356041565b60408051918252519081900360200190f35b600781025b9190505600a165627a7a72305820**74397332f2c8302bc8cd31c09504aae1c2af069d2cd8440338dd247251b439d50029**"

However, 

> echo "contract test { function multiply(uint a) returns(uint d) {   return a * 7;   } }" | solc --optimize --bin

produces:

"0x6060604052346000575b6077806100176000396000f300606060405263ffffffff60e060020a600035041663c6888fa181146022575b6000565b34600057602f6004356041565b60408051918252519081900360200190f35b600781025b9190505600a165627a7a72305820**d53603d2766cdda236d7f6d447943a40ea95b05468b36e287b5872a66869732f0029**"

**Comment by phleemac** [comment]
solc: 0.4.7+commit.822622cf.Linux.g++
parity: v1.4.6-beta-5feccf1-20161205/x86_64-linux-gnu/rustc1.13.0

**Comment by rphmeier** [comment]
@phleemac `eth_compileSolidity` just calls the local`solc`. I think the issue here is that `solc` itself generates the swarm hash from the source in a whitespace-sensitive manner (and `echo` without the `-n` flag is outputting a newline at the end).

**Comment by phleemac** [comment]
@rphmeier you are right.  thanks.
