### ISSUE TITLE
HackerGold contract swap

### ISSUE THREAD

**Issue by romanman** [ethcore/parity#4117]
Hi Guys, 

We found a flaw in our token contract
and swapped it to a new one. 

That is active HKG token now: 
https://live.ether.camp/account/14f37b574242d366558db61f3335289a5035c506

@gavofyork @jacogr

**Comment by rphmeier** [comment]
(I guess this is a deployment thing? a `Registry` label might make sense)

**Comment by jacogr** [comment]
Thank you, will update.

**Comment by romanman** [comment]
Thanks

**Comment by jacogr** [comment]
Updated.
