### ISSUE TITLE
Verify if gas estimation works correctly in the UI

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#4120]
Since `eth_estimateGas` was changed in #4100 it now returns different values in case of OoG, @jacogr mentioned that UI is expecting parity to return 50M in case of failure, now the function will just return JSON-RPC error instead.

**Comment by gavofyork** [comment]
I'm happy to consider returning a non-error (`null`?), or an alternative error (`TransactionException`) if we decide that would be better form, but 50M is definitely wrong :-)

**Comment by jacogr** [comment]
Not finicky either way, we will just need to go through the estimateGas UI calls ASAP to conform to the new requirements, whatever it is, Error or 0. (And test, test, test - it touches a large amount of places)

**Comment by gavofyork** [comment]
ok - stick with the error then.
