### ISSUE TITLE
All new accounts start with 0x00

### ISSUE THREAD

**Issue by dasmarc** [ethcore/parity#4156]
When i create an account with the website interface, all accounts start with 0x00...
I have tried this multiple times with different web browsers.
When i use the "parity account new" command, i don't have this issue.

My OS is macOs 10.11.6 (15G1212).
I tried it in Opera, Chrome and Safari.

**Comment by jacogr** [comment]
It is done to conform to the standards https://github.com/ethereum/wiki/wiki/Brain-Wallet to allow interoperability between different wallets and implementations in the wild.

When using `parity account new` no recovery phrase is provided, so the above is not applicable.

**Comment by tomusdrw** [comment]
Closing, since it indeed works as expected. Addresses starting with `0x00` are also ICAP compliant
