### ISSUE TITLE
Trying to send transaction (transfer) shows exception

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4161]
![parity 2017-01-13 12-35-39](https://cloud.githubusercontent.com/assets/1424473/21928751/e188daee-d98c-11e6-9efe-a77a1cc97f90.png)

(Marked both core & ui, just need to check logic on UI to make sure everything is set correctly)

**Comment by jacogr** [comment]
@ngotchac Verified removing/adding gas, data, value etc from the UI - all with the same result, doesn't seem to be UI introduced.

**Comment by derhuerst** [comment]
Had the same, after `rustup update`, `cargo clean`, `cargo build --release`, `npm run clean`, `npm run build`, `npm run start:app` it was better. Not sure if there's a shorter way though. :P

**Comment by ngotchac** [comment]
Should be fixed with #4165
