### ISSUE TITLE
Add alias of web3_k256 to JSON APIs that maps to web3_sha3 since web3_sha3 inaccurate

### ISSUE THREAD

**Issue by cseberino** [ethcore/parity#4214]
Ethereum method ids are based on Keccak-256 hash function which is similar but NOT the same
as SHA3.  So web3_sha3 is incorrectly named (bug).

Propose alias of web3_k256 to JSON API of Parity that maps to web3_sha3 (incorrectly named).

Eventually can discuss coordinating with Geth to jointly obsolete the incorrect web3_sha3 API but
not necessary immediately.

**Comment by gavofyork** [comment]
this should really be in the EIP process; we try to avoid unilaterally changing shared specs. please reopen once according EIP is accepted.
