### ISSUE TITLE
Where to place exactly config.toml file on Windows 10?

### ISSUE THREAD

**Issue by Nogreedy** [ethcore/parity#4232]
Hello,
I'm a new (French) parity user (it's great by the way and I love ETH).
I use Parity 1.5.0 with Windows 10/64 bits (with Mist for now).
I start with cmd "J:\Program Files\ETHCore\Parity\parity.exe" --geth --force-ui
It works well ...  but it doesn't use my customized options.
I've generated config.toml with Parity Config Generator... but I don't know exactly where to put this famous file... it's indicated to place it in "$HOME/.parity/config.toml"... but where is it with Windows 10?
I have not a C:\Users\kingETH\.parity folder...
I have : 
C:\Users\kingETH\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d\overlayrecent\db   and also  C:\Users\kingETH\AppData\Roaming\Parity\Ethereum ...
Then I don't know where to place config.toml file...
Thanks you in advance for your answers.

**Comment by Nogreedy** [comment]
Well, I answer myself to my question.
I think, after testing, config.toml file have to be placed (for Windows) in "C:\Users\kingETH\AppData\Roaming\Parity\Ethereum"
I think we have too to include special characters ... I had to escape each single special symbol with a backslash ( \\ )... 
e.g. to change database path : 
# Parity database will be stored in Z:\db-parity.
db_path = "Z:\db-parity"   ------------> it doesn't work
I had to change this line in :  db_path = "Z:\\db-parity"

**Comment by tomusdrw** [comment]
Hi @Nogreedy thanks for reporting!

Yes, the config should indeed by default go to `C:\Users\<username\AppData\Roaming\Parity\Ethereum`, you can use `--config` CLI argument to customize this.

This was recently changed and `parity-config-generator` was not updated yet. The second issue sounds like a bug in config generator. I've created issues there: https://github.com/ethcore/parity-config-generator/issues/8, https://github.com/ethcore/parity-config-generator/issues/9

Closing this issue, cause it seems it's more a config-generator problem.
