### ISSUE TITLE
Build fails for latest nightly

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#424]
Build fails with the latest rust nightly

Probably breaking changes for aster lib
work in progress
https://github.com/serde-rs/aster/pull/65

changes
https://github.com/rust-lang/rust/pull/31487

**Comment by mseri** [comment]
Not just those.

Even after fixing `docopt_macros` (see https://github.com/docopt/docopt.rs/pull/169) there is another issue with `jsonrpc-core` (see https://github.com/debris/jsonrpc-core/issues/4)

**Comment by kirushik** [comment]
@NikVolf I'm updating your branch in #426 — it finally builds, please merge at will.

**Comment by NikVolf** [comment]
https://github.com/serde-rs/quasi/issues/31
quasi

**Comment by NikVolf** [comment]
https://github.com/serde-rs/quasi/pull/32

**Comment by NikVolf** [comment]
https://github.com/serde-rs/aster/pull/66

**Comment by NikVolf** [comment]
serde_codegen fails
https://github.com/serde-rs/serde/issues/235

**Comment by debris** [comment]
https://github.com/serde-rs/serde/pull/236
- fixed (not merged yet)

**Comment by NikVolf** [comment]
It is building now with `cargo build --release`

**Comment by kirushik** [comment]
@NikVolf Awesome work, thank you very much!
