### ISSUE TITLE
Parity 1.5 Stage 1 block verification failed

### ISSUE THREAD

**Issue by alexjavabraz** [ethcore/parity#4256]
After upgrade to version 1.5 of parity, with the --chain option, i noticed that i started getting the 'Stage 1 block verification failed error'. 
This machine (where the error occurred) specifies the run Windows version.
We have other 2 machines running ubuntu with parity old version.
After upgrade the ubuntu machines to 1.5 version, parity is running normally, may have a bug in windows version.

2017-01-20 18:24:51  Stage 1 block verification failed for 4bb4…ff2d: Block(InvalidTimestamp(OutOfBounds { min: None, max: Some(1484943921), found: 1484943942 }))

**Comment by rphmeier** [comment]
This is due to changes for timestamp validity checking in 1.5.0.  Not a major error, just intermittent warnings which can be more or less safely ignored.

**Comment by alexjavabraz** [comment]
When it occurs, i need to restart node, because the rest of net cant see my node.

**Comment by gavofyork** [comment]
can you ensure your windows machine has an up to date time (go to time.is and check it's synchronised). if you continue to have problems keeping nodes, please reopen.
