### ISSUE TITLE
1.5 .deb release fails with libssl error

### ISSUE THREAD

**Issue by davebryson** [ethcore/parity#4257]
I'm installing parity_1.5.0_amd64.deb via Vagrant on ubuntu/xenial64. 

`sudo dpkg -i parity_1.5.0_amd64.deb`  returns  the error:

 `parity depends on libssl; however: Package libssl is not installed`

Parity is installed and appears to be working, just getting this libssl error for some reason

**Comment by slyon** [comment]
This small change should be enough: https://github.com/ethcore/parity/pull/4260

**Comment by tomusdrw** [comment]
Fixed in #4620
