### ISSUE TITLE
Verify email fail

### ISSUE THREAD

**Issue by lekanovic** [ethcore/parity#4280]
When I try to use the new feature "Verify email" I get this error:
**Failed to request a confirmation code: This e-mail has already been verified.**
 I have tried with different account but they all give me this error.

**Setup:**
OS: OSX el Capitan
Parity: 1.5.0

**Comment by Nogreedy** [comment]
I had this error on mainnet... but it worked on testnet (Ropsten)...
I'm curious to know if this new function is only available on testnet or also on mainnet... I think it's not the same contract...

**Comment by lekanovic** [comment]
Yes you are correct it looks like this is only supported on Ropsten. I was watching this youtube clip: https://youtu.be/2aI3HXSDFy8?t=460
And I thought this was for mainnet but it was not. Hopefully they will enable this feature on mainnet soon, its a really cool thing.

**Comment by rphmeier** [comment]
AFAIK email verification is supposed to be deployed on the mainnet as well. @derhuerst is working on solving the current issue.

**Comment by derhuerst** [comment]
I'm working on it.

**Comment by derhuerst** [comment]
@lekanovic @Nogreedy Did you try on `testnet` or on `mainnet`. Both should work theoretically.

As we're still sorting things out with this service, I'd like to help you get your accounts verified. Would you mind sending me your the email address you tried to verify? We only store `sha3` hashes in the database.

I'm available for further support at https://gitter.im/derhuerst .

**Comment by lekanovic** [comment]
@derhuerst I only tried this on the mainnet. But while I was trying I saw two different messages I didn't mention this before. The other message was something about contract failed to do perform some action. I did not save this log. Does this feature work for you?

**Comment by derhuerst** [comment]
@lekanovic I've tested it quite often in the last week on `testnet` (on `mainnet` this would have been expensive), but there's no automatic monitoring on wether it works, besides a simple health check that i now put in place. This health check only reports if the Parity node on the verification server i fully synced.

**Comment by derhuerst** [comment]
@lekanovic The reason you get these "You already requested verification" messages is that I built so that you cannot request hundreds of SMS (which cost us money) once you paid the ETH fee.

**Comment by derhuerst** [comment]
@lekanovic To help me debug this, you could write down the steps you took and what message you get and, most importantly, report it to me quickly e.g. on Gitter. I appreciate the help a lot!

**Comment by Nogreedy** [comment]
I tried again (Windows 10) on mainnet (Homestead) - new account ... and now, it seems to work for me...
I received email confirmation code and my email is now verified for my mainnet account...
https://etherscan.io/tx/0x21fb53e64ba6f90fdb5576a1006e4a6a2906d5481e2b48c8e52e283b7b6485ad
https://etherscan.io/tx/0xef92f2e0e02153d49dd4744f43941012461e79fb7d2b17078f23148f6b2ab551
![parity2](https://cloud.githubusercontent.com/assets/6340683/22251309/932dc794-e24a-11e6-80b9-e0c7d6c94efd.JPG)
![parity4](https://cloud.githubusercontent.com/assets/6340683/22251331/a7cf8944-e24a-11e6-903c-f951d001d9a0.JPG)
![parity8](https://cloud.githubusercontent.com/assets/6340683/22251449/0c17385c-e24b-11e6-84df-889cd895a3eb.JPG)




parity4.20.didier26@dfgh.net

Thanks for your support and for your great Parity work...

**Comment by derhuerst** [comment]
@Nogreedy Good to hear that it's working for you! With a completely "new" account & address/number it has worked before as well, however. I'm more interested in the cases when it didn't.

**Comment by lekanovic** [comment]
Can this be a OSX related problem? Because it does not work for me on mainnet(did not test Ropsten)

**Comment by derhuerst** [comment]
> Can this be a OSX related problem?

No, I don't know how it should be.

>  Because it does not work for me on mainnet(did not test Ropsten)

As I said, please give me more details [on Gitter](https://gitter.im/derhuerst).

**Comment by derhuerst** [comment]
As #4317 got merge, please try again on `master`. A few problematic cases should be fixed now.

If you run into issues, give me the details of the steps you took, [on Gitter](https://gitter.im/derhuerst). Thanks! Note that you cannot use the email/phone number twice you tried with before.
