### ISSUE TITLE
Raspberry Pi2/Raspbian install fails because libssl dependency missing

### ISSUE THREAD

**Issue by Nogreedy** [ethcore/parity#4281]
I tried to install Parity 1.5.0 - armv7 	parity_1.5.0_armhf.deb on my raspberry Pi2 (Raspbian-Debian Jessie).
My RPI2/Raspbian is updated (Linux raspberrypi 4.4.38-v7)
sudo apt-get update 
sudo apt-get dist-upgrade
But when I try to install i get the error message :  parity depends on libssl; however: Package libssl is not installed.
And then the install doesn't proceed...
On my system I have these packages installed : libssl1.0.0        libssl1.0.0-dbg    libsslcommon2      libsslcommon2-dev  libssl-dev         libssl-doc         libssl-ocaml       libssl-ocaml-dev .
I think this issue is related to other issues (but I'm not sure)  : #4257 #4260 #4224
Thanks in advance for your answer and support.

**Comment by rphmeier** [comment]
I think #4260 (as you've already seen) should address this issue, but our 1.5.0 packages are not built using it. You may have better luck building from source, perhaps by cross-compiling to save time.
