### ISSUE TITLE
Web3/Parity Console does not work at all

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#4290]
![screenshot from 2017-01-24 16 14 49](https://cloud.githubusercontent.com/assets/581548/22253006/5d2b688a-e250-11e6-8972-8ed49a698050.png)

`s/window.parity.api/window.api/g` should fix it.

**Comment by 3esmit** [comment]
Still not working in 1.5.2

![image](https://cloud.githubusercontent.com/assets/224810/22894195/4a1d4cfe-f1ff-11e6-910b-a73ebe7d05d2.png)

**Comment by tomusdrw** [comment]
Closed with #4569 and #4544
