### ISSUE TITLE
What is the necessary openssl version for a Raspberry installation?

### ISSUE THREAD

**Issue by Nogreedy** [ethcore/parity#4293]
Because when I try to install parity_1.5.0_armhf.deb on my Raspberry Pi2/Raspbian, I have such error message : 
parity dépend de libssl ; cependant : Le paquet libssl n'est pas installé. (missing libssl packet).
When I try to force install, I have these error messages : 
parity: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by parity)
parity: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by parity)
But the last openssl version for my updated and upgraded Jessie Raspbian (Debian) is openssl _1.0.1t-1+deb8u5  !!!
Thanks you in advance for your answer.
PS : Can you say if this issue will be resolved in parity 1.6.0 version?
PS : sorry, I'm only a basic user and I don't compile, cargo, docker...

**Comment by arkpar** [comment]
We are going to switch to libssl 1.0.1 for Parity 1.5.1 and 1.6.0
