### ISSUE TITLE
Remove daily limit from multisig wallet.

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#4310]
It doesn't play well with tokens &c

**Comment by ngotchac** [comment]
Should it be hidden and put to 0 by default ?

**Comment by gavofyork** [comment]
it's the contract that needs altering. setting to zero won't help since tokens require only 0-value transactions which will always go through.

**Comment by gavofyork** [comment]
see new code in https://github.com/ethcore/contracts/blob/master/Wallet.sol

**Comment by gavofyork** [comment]
after an audit (will need diff with ethereum.org/dapp-bin/wallet/Wallet.sol) then should be used.

**Comment by jacogr** [comment]
Wallet code update PR https://github.com/ethcore/parity/pull/4805

**Comment by ngotchac** [comment]
@gavofyork This can be closed now, right?

**Comment by ngotchac** [comment]
Closed via integration of the new Wallet contract
