### ISSUE TITLE
Can I delete 1 block from 3,000,001 to 3,000,000 so that I can download the ETC hardfork chain?

### ISSUE THREAD

**Issue by studious3** [ethcore/parity#4319]
I did not know there was a hard fork for ETC, I was running a parity version from early December. I hit block 3,000,001. It stopped, I found there was a hard fork. I then downloaded version 1.5 Nativety. It seems to be stuck where I left off. I assume this is due to me having 1 block after 3,000,000 or maybe even the 3,000,000 block too on the old chain. It takes me a week to download the blockchain, so I am looking for away to roll back just a bit and see if everything works as it should.

**Comment by gavofyork** [comment]
What is your current block number?

**Comment by studious3** [comment]
As far as my current block number, Mist said 3,000,001, by block number do you mean something other than that?. I ended up finding the .sst files in the db folder. I initially used the "./target/release/parity" way, but when I tried updating, I was running in to problems, so I used the bash method of installing the newer parity version. It seems to use the directories from the initial method so I can start parity by either "parity -j" or (cd parity) "./target/release/parity" now; however the directories are way different, like there is no /.parity, the keys are in a /.ethash/light directory and the chain data is in a /.local/share/io.parity.ethereum/chains/ethereum/db/(bunch of numbers here)/overlayrecent/db. 

I deleted the .sst furthest down, and that gave me: Client service error: Client (Database("Invalid argument: You have to open all column families. Column families not opened: col5, col4, col3, col2, col1, col0"))

So then I just deleted everything because I need to get this working. But it doesn't work even now. However the eth chain has continued to work. I can even delete the whole blockchain and it works just fine. So there seems to be an issue with the classic chain only since updating to 1.5.

Also, when I first ran it after updating, after "Configured for Ethereum Classic using Ethash engine", I got "Error parsing node table file: SyntaxError("E0F While parsing value", 1, 1). I never got that error again, but I wonder if it has something to do with my issue running the Classic chain.

**Comment by studious3** [comment]
I want to withdraw my classic from the WHG group and dump my original duplicate classic. Have not gotten around to it yet.

**Comment by gavofyork** [comment]
It is currently not possible to delete just a few blocks. See #4324 to track the feature.

Deleting arbitrary parts of the database file structure is indeed unlikely to result in a desirable outcome.

The directory structure changed from 1.4 to 1.5; this is detailed in the 1.5 release notes which you can find on the [Github releases page](https://github.com/ethcore/parity/releases).

To delete all existing classic chain data, you can use `parity db kill --chain=classic`.

Downgrading from 1.5 to any earlier version is not supported; please ensure that any old Parity versions do not accidentally get run. Deleting (or moving/renaming) any pre-existing Parity versions would help ensure that they do not inadvertently get executed.
