### ISSUE TITLE
Expose abi + options + parameters encoding on parity.js

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4325]
Inputs 

- an ABI (e.g. `[{"name":"_content","type":"bytes32"},{"name":"_url","type":"string"}]`)
- a function name (e.g. `"hintUrl"`)
- an array of values (e.g. `["0xbaabababababba", "http://foo.bar/"]`) 

Output -

- the hex data for a call

**Comment by gavofyork** [comment]
would be good to have two (basically) symmetric calls:

- `parity.api.util.abiEncode(name, types, params) -> data` (name may be `null`, in which case it skips the function sig, making it useful for encoding events/constructor/fallback)
- `parity.api.util.abiDecode(types, data) -> params`

Here's my polyfill for the current PR:

```
parity.api.util.abiEncode = function(name, types, data) {
    let r = parity.api.util.encodeMethodCall(name || '', types, data);
    return name === null ? `0x${r.substr(10)}` : r;
};
parity.api.util.abiDecode = function (types, data) {
    return parity.api.util.decodeMethodInput({inputs: types.map(t => {return {type: t};})}, data);
};
```
