### ISSUE TITLE
Allow setting of default account for sending from UI

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4328]
Default account appears first in list for calls to `parity_setDappsAddresses(dapp, [accounts])` or `parity_setNewDappsWhitelist([accounts]))`

Related to https://github.com/ethcore/parity/pull/4323

**Comment by gavofyork** [comment]
is this "first==default" rule for internal APIs (signer) or for public dapp APIs? i think for dapp APIs i'd prefer a specific call (similar to `eth_coinbase`) which is subscribable for changes (and which returns whatever account has been selected in the snippet).

**Comment by jacogr** [comment]
Related to https://github.com/ethcore/parity/issues/3797
