### ISSUE TITLE
Registry Case Sensitivity

### ISSUE THREAD

**Issue by MicahZoltu** [ethcore/parity#4340]
1. Reserve an all lowercase name.
2. Try to register the same name with different casing.
3. Notice that you get an error that `<lower_case_version>` has already been reserved.
4. Try to query the registry for the not-lower-cased version of the name.
5. Notice that you get a message `Not reserved yet`.

The registry should be consistent on casing.  Either support querying for any casing (always to-lower it or something) or allow users to register different casings of the same name.

![image](https://cloud.githubusercontent.com/assets/886059/22399767/3bbad846-e559-11e6-99fe-1abbc708aeda.png)

**Comment by gavofyork** [comment]
all interactions with the registry should see the names lower-cased.

**Comment by MicahZoltu** [comment]
I am curious, what is the standard for lower-casing that is being followed?  Is full UTF-8 supported or just Latin or just ASCII-7?  Does it follow the DNS specification (which is amazingly constraining to deal with this problem) or is the expectation that it will work well for non-English speakers?  Does it also do case folding, or only capitalization?  Does it take into consideration Turkish `i`/`I` problems?

As I'm sure many of you are aware, localization is hard (impossible?), so some decisions need to be made and should be documented and adhered to everywhere.

Resources:
https://www.w3.org/International/wiki/Case_folding Good general resource that describes why this is a hard problem and some common pitfalls.
https://tools.ietf.org/html/rfc952 A "name" (Net, Host, Gateway, or Domain name) is a text string up to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus sign (-), and period (.).  Note that periods are only allowed when they serve to delimit components of "domain style names".
https://en.wikipedia.org/wiki/Internationalized_domain_name

Having attempted to "do capitalization right" in the past and come to the conclusion that there is no "right", I general prefer to just support arbitrary UTF-8 and be done with it.  However, that does open one up to certain spoofing attack vectors.  Tentatively, I would suggest that full UTF-8 be supported and leave the spoofing problem up to the UI.  Chrome, for example, will convert international domain names to/from ASCII for the user to help protect them against spoofing attacks, and it can make this choice based on locale information available at runtime (information that wouldn't be available to a contract).

**Comment by derhuerst** [comment]
@MicahZoltu Thanks for putting effort into reporting this bug! The current behaviour is unintuitive to say the least. And thanks for the useful links on internationalised case-mapping.

Right now, the lower-casing is just naive [`String.prototype.toLowerCase()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase). I'm not even sure if it's used everywhere, will check.

Moving on, we might use [`String.prototype.toLocaleLowerCase()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase). This might break in the future as well: If I try to register a Turkish name on my computer with German locale, it will register a different thing than what people with Turkish locale might expect when they look this name up. So to build on the JS environment doesn't seem like a robust way of dealing with this.

> […] there is no "right", I general prefer to just support arbitrary UTF-8 and be done with it. However, that does open one up to certain spoofing attack vectors. […] Chrome, for example, will convert international domain names to/from ASCII for the user to help protect them against spoofing attacks […].

We won't be able to rely on Chrome as the helping hand of the Registry. There's going to be many cases in which we won't even have a browser, but a fully scripted environment that queries the registry. As a future-proof solution, I'd suggest that we use e.g. [`normalize-for-search`](https://github.com/ikr/normalize-for-search#about) to make all queries ascii.

Another way might be to use [punycoding](https://en.wikipedia.org/wiki/Punycode). This will have the advantage that it will work with domain names, which we (and others) will most likely support soon.

Both solution would require to clearly communicate that registering `Äöý` means actually registering a different, "escaped" name and that there might be "collisions".

@MicahZoltu @gavofyork @tomusdrw what do you think?

**Comment by MicahZoltu** [comment]
punycoding is what was previously selected as the "solution" to this problem.  It isn't particularly elegant but I suspect the people who came up with it put a lot of thought into the problem and it is the best they could come up with given their constraints.  That being said, Ethereum is starting from a more pristine/healthy place so has fewer constraints (International Domain Names had to work on top of existing DNS infrastructure).  Perhaps there is a better solution out there?

I don't think `toLocaleLowareCase` will work for the reasons you specified, `Locale` is different per user and the rules between locals conflict with each other in some places.

I'm not particularly a fan of normalize-for-search, mainly because it isn't particularly well defined what exactly it does and it doesn't solve the full problem of protecting people from spoofing attacks (e.g., non-printing characters).

Perhaps to better come to a decision, the goals should be stated up front?  Is there a desire to protect users from spoofing attacks at the contract level or is that a UI problem?  Are we trying to solve the contract problem here or the UI problem here?  It seems like the contract goals and problem should be addressed first, and then move on to the UI/UX problem once that is hashed out.

**Comment by gavofyork** [comment]
the registry itself works only by name-hashes so will support any character set. the real question is trying to standardise what names UIs to this should support placing into it.

i see two goals, in order of importance:
1. no more likely to spoof a name than restricting to ASCII-7;
2. as much locale richness as possible.

right now, i'm tempted to just stick with ASCII-7 as it (by definition) suffices for the primary goal. further subsets of unicode may be added in order to better address (2) as we determine they don't compromise (1).

eventually, i'd like to have a reputation system set up so that we don't have to rely on this shit at all and can, as you say, just accept UTF-8 and be done with it.

**Comment by MicahZoltu** [comment]
Since this is a UI-only concern I'm not nearly as worried about coming up with a perfect solution today.  I support the simple solution to only support ASCII-7 in the UI (and maybe even a limited subset of that) for now and then, as demand for wider language support rises over time, more thought can be put into the issue and the team can iteratively expand the allowable character set or solve the spoofing problem in a different way and allow full UTF-8.
