### ISSUE TITLE
After the classic hardfork, Does parity sync classic over UDP?

### ISSUE THREAD

**Issue by studious3** [ethcore/parity#4364]
I am trying to figure out why since the hardfork I have not bee able to run parity --chain=classic over tor.

After someone mentioned to make sure UDP wasn't blocked, I thought that maybe parity started syncing classic over UDP after the hardfork.

One major reason I use parity is that geth used UDP and Tor only supports TCP.

If this is in fact the case, how can I manually make parity sync classic over TCP?

**Comment by gavofyork** [comment]
UDP is required for the node discovery process. if you have good bootnodes, you shouldn't need UDP - if you do not, then you'll need to add them manually (`--reserved-peers`).
