### ISSUE TITLE
InvalidNonce while syncing with 32-bit Parity

### ISSUE THREAD

**Issue by brenzi** [ethcore/parity#4390]
My node stopped synching (once again...this seems to happen every other week and I'm sick of resynching the whole chain whenever it happens. there must be another option)

Parity is up to date (1.6 unstable)
I've followed the tips in the FAQ. nodes.json deleted, time is in sync and I've waited for hours.

[parity_stalling.txt](https://github.com/ethcore/parity/files/745486/parity_stalling.txt)

thanks for your help

**Comment by gavofyork** [comment]
thanks for the logs!

**Comment by arkpar** [comment]
```
2017-02-01 17:45:05  Verifier #0 WARN client  Block import failed for #3069596 (99db…6b89)
Error: Execution(InvalidNonce { expected: 0, got: 39 })
```
caching issue perhaps?

@brenzi consider using stable or beta (1.5.x) version for now.

**Comment by arkpar** [comment]
Could be also 32-bit linux specific (`x86-linux-gnu` platform)

@brenzi We also recommend running 64-bit version (x86_64)

**Comment by 5chdn** [comment]
@brenzi do you still experience the sync stalling? Did you try running a beta or stable node?

**Comment by brenzi** [comment]
I'm running a 64bit node now, so I can't tell, sorry. Haven't had any stalling since ;-)

**Comment by 5chdn** [comment]
All right, let me know if you experience similar issues in the future.
