### ISSUE TITLE
--keys-path dont work

### ISSUE THREAD

**Issue by Solaso** [ethcore/parity#4400]
Hello. In the latest version --keys-path don't work. It was worked in a previous version. What should I to do?

**Comment by tomusdrw** [comment]
1.5 comes with major re-organizing of directory structure. All data is currently split between different chains.

`--keys-path` points to a base location for keys, inside for each chain you need to create another folder and place keys there.

Example:
1.4
`--keys-path /home/me/keys` Keys located at `/home/me/keys`

1.5
`--keys-path /home/me/keys` Keys for mainnet located in `/home/me/keys/ethereum`, for testnet in `/home/me/keys/test`

**Comment by 5chdn** [comment]
Closing as answered, please get back to us if you still experience issues.

**Comment by x3medima17** [comment]
@tomusdrw but what if I want to set-up keys path from a specific directory, without adding chain name?
Thanks.
