### ISSUE TITLE
Parity crashed on Windows

### ISSUE THREAD

**Issue by JanKalin** [ethcore/parity#4416]
Came to work today and saw that Parity has died at 2017-02-02 23:07:45. This is from the Windows error box
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	parity.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5839d185
  Fault Module Name:	parity.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5839d185
  Exception Code:	c0000005
  Exception Offset:	0000000000929c60
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	81e7
  Additional Information 2:	81e70011b689b981636c82d83464ff22
  Additional Information 3:	f1a2
  Additional Information 4:	f1a2b8a0ac46ffa8e063fbd2f69b5ce0
```
The process is still in memory consuming 580MB of memory. I've attached the log file from `C:\Users\jank\.parity\906a34e69aec8c0d\v5.3-sec-overlayrecent\db`
[LOG.txt](https://github.com/ethcore/parity/files/749832/LOG.txt), the application log is, unfortunately, nonexistent

Windows is a relatively fresh install of Windows 7, machine has 6GB of memory

**Comment by tomusdrw** [comment]
Any chance you have a Parity log (from the console; the one attached is only contains database-related info)?

**Comment by JanKalin** [comment]
I have not been able to find it, but I think it's not available. Parity is started from the ptray.exe automatically at startup and, if I understand correctly, the log goes nowhere in this case.

If you wish, I can start it in a console, have output redirected to a file and hope for a crash :)

**Comment by tomusdrw** [comment]
Thanks! Yes, that would be very helpful.

**Comment by JanKalin** [comment]
Done. I've deleted the blockchain directory and started parity with a normal sync, so if there's a problem with a specific block it should be reproduced. I'll report back in the event of a crash during sync or afterwards.

**Comment by 5chdn** [comment]
@JanKalin can you still reproduce the crash on windows?

**Comment by JanKalin** [comment]
No, I think this issue can be closed. I will reopen it if the crash occurs.

**Comment by 3eph1r0th** [comment]
I have same problem on windows. I start app. it works for 40 seconds and crashes. What should i do? Where can i find blockchain folder to delete?

**Comment by jupiter50** [comment]
Hitting the same issues:

Fault bucket 120776134218, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: parity.exe
P2: 0.0.0.0
P3: 5939637b
P4: parity.exe
P5: 0.0.0.0
P6: 5939637b
P7: c000001d
P8: 0000000000a8c5e4
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF7E2.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_parity.exe_501061f86213f840bd385af2d4afa5662511b758_9329fcd4_360d01d5

Analysis symbol: 
Rechecking for solution: 0
Report ID: 1eb80fde-34aa-4290-8999-19212f137743
Report Status: 0
Hashed bucket: 48aed4a508bbac192c7553034038faac

**Comment by jupiter50** [comment]
Keeps crashing every time I load it up and leave it running for a small part
[Report.txt](https://github.com/paritytech/parity/files/1147436/Report.txt)
