### ISSUE TITLE
Parity sometimes crashes on account deletion

### ISSUE THREAD

**Issue by 3esmit** [ethcore/parity#4420]
Sometimes I create accounts for testing porpouses, like testing recovery, or just to help someone with screenshots, and I don't even set a password for them.
Happened for me twice, that when I pressed Yes to delete, parity crashed in that moment, no error message displayed. I just reopened it using Parity Ethereum Windows shortcut. When parity reopens the account is gone, as expected, and all runs normal. 

The first time it happened I tried to delete with wrong password, it told me could not delete, then I put the right password and parity gone.
The second time I created an account to test if MEW accepted Parity recovery phrase and didn't set any password. tested there, come back to parity, deleted and parity gone. 

I'm running Windows 10 and Parity 1.5.0.

**Comment by 3esmit** [comment]
I was wondering about Windows telemetry/indexing services and imagined the situation where parity tries to delete a file when Windows is reading it. So I created an account and opened with notepad the account file. When I try to delete it in parity, parity crashes but is able to delete the account.
I tried again doing the same and parity didn't crashed. Also tried to mark "read only" but then parity says it cannot delete the account with no crashes.

**Comment by rphmeier** [comment]
Have you got any console output? My guess is we're just hitting a panic of some kind in the deletion code.

**Comment by 3esmit** [comment]
Found out how to reproduce the bug.
Open more then one Parity UI tab. While other Tabs are looking at accounts page, use one of the UI to delete a account.

````
2017-02-08 10:24:52  Invalid key file: "C:\\Users\\Ricardo\\AppData\\Roaming\\Parity\\Ethereum\\keys\\ethereum\\UTC--2017-02-08T12-23-58Z--925abb68-93e0-8f48-7620-ef1abed3a2f6" (O sistema não pode encontrar o arquivo especificado. (os error 2))
thread '<unnamed>' panicked at 'Entry exists, because it was returned by `get`; qed', ../src/libcore\option.rs:705
stack backtrace:
   0:     0x7ff6bb2f68ba - <unknown>
   1:     0x7ff6bb2f3aca - <unknown>
   2:     0x7ff6bb2f44ad - <unknown>
   3:     0x7ff6bb2f4348 - <unknown>
   4:     0x7ff6bb2f4264 - <unknown>
   5:     0x7ff6bb2f41f9 - <unknown>
   6:     0x7ff6bb302d57 - <unknown>
   7:     0x7ff6bb302dbf - <unknown>
   8:     0x7ff6bb113709 - <unknown>
   9:     0x7ff6bb1052f6 - <unknown>
  10:     0x7ff6baf95401 - <unknown>
  11:     0x7ff6ba9fc898 - <unknown>
  12:     0x7ff6ba989bc2 - <unknown>
  13:     0x7ff6bacff717 - <unknown>
  14:     0x7ff6bad061ab - <unknown>
  15:     0x7ff6bace7227 - <unknown>
  16:     0x7ff6bacec14b - <unknown>
  17:     0x7ff6bacdf836 - <unknown>
  18:     0x7ff6bacdba90 - <unknown>
  19:     0x7ff6bb2f93d1 - <unknown>
  20:      0x29fa1b0152f - <unknown>
  21:  0x10000ffffffffff - <unknown>
  22: 0xfffffffffffffffd - <unknown>
  23:       0xea081ff3ff - <unknown>
  24:       0xea081feacf - <unknown>
  25:     0x7ff6bacf6cc8 - <unknown>
  26:              0x29e - <unknown>
````
![parity acc delete crash](https://cloud.githubusercontent.com/assets/224810/22737217/4560b94a-ede9-11e6-97a3-160128f2846d.png)

**Comment by 5chdn** [comment]
@3esmit a possible fix should be included in latest beta, can you check if you can still reproduce this with 1.5.4 or later?

**Comment by 3esmit** [comment]
In 1.5.4 it does not crashes anymore. However, when I delete an account in a tab, it still appear in the other. Is not a real problem, when reload the account disappears.

**Comment by 5chdn** [comment]
Thanks for confirming!
