### ISSUE TITLE
Transaction signer doesn't pop up in dev chain mode

### ISSUE THREAD

**Issue by CJentzsch** [ethcore/parity#4447]
When starting parity with `parity --chain dev` and using the UI ( `http://127.0.0.1:8180/`) the transaction signer does not pop up after trying to send a transaction.

**Comment by rphmeier** [comment]
Is `--chain dev` the only flag you have enabled? Certain other flags do disable the signer.

**Comment by tomusdrw** [comment]
I believe the issue might have been fixed in #4387. Let's wait for 1.5.2 and check if it's still the case.

**Comment by 3esmit** [comment]
I had this issue too. Once a transaciton is made by RPC the UI start poping up the transaction signer.

**Comment by CJentzsch** [comment]
@rphmeier yes. The rest is set to the default values.

**Comment by keorn** [comment]
@CJentzsch Can you try `master` after https://github.com/ethcore/parity/pull/4467 or `beta` branch?

**Comment by CJentzsch** [comment]
Tried out 1.5.2, works now.
