### ISSUE TITLE
deb package fails to install

### ISSUE THREAD

**Issue by tokyo3** [ethcore/parity#4449]
Trying to install parity 1.5.0 (x86_64) from published deb in the releases page https://github.com/ethcore/parity/releases but I get this.

I do have libssl installed which is libssl1.0.0
```
Preparing to unpack parity_1.5.0_amd64.deb ...
Unpacking parity (1.5.0) ...
dpkg: dependency problems prevent configuration of parity:
 parity depends on libssl; however:
  Package libssl is not installed.

dpkg: error processing package parity (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 parity

```
I found there was a fix made for this issue here https://github.com/ethcore/parity/issues/4257, but the published download still fails to install (parity_1.5.0_amd64.deb - MD5:c1fef1842425852d2f17f6ebef0e8106)

**Comment by tokyo3** [comment]
the issue is because the package on the downloads page has not been updated to the appropriate dependency which is [libssl1.0.0](https://github.com/ethcore/parity/pull/4260/commits/ea29e7b33b8d21f3257ac1d7886613c06579c0d9) and not libssl, the .deb file on the downloads page needs to be fixed.

```
Package: parity
Version: 1.5.0
Source: parity
Section: science
Priority: extra
Maintainer: Ethcore <devops@ethcore.io>
Build-Depends: debhelper (>=9)
Standards-Version: 3.9.5
Homepage: https://ethcore.io
Vcs-Git: git://github.com/ethcore/parity.git
Vcs-Browser: https://github.com/ethcore/parity
Architecture: amd64
Depends: libssl
Description: Ethereum network client by Ethcore
```

**Comment by adalmieres** [comment]
Same here

**Comment by tomusdrw** [comment]
Generating deb packages are fixed in both `beta` and `master` branches, we are just waiting for a new release (and it should be soon).
For now a workaround is to build branch `beta` from source.

**Comment by tokyo3** [comment]
@adalmieres thank you for the script, it worked, I'm also on ubuntu 16.04, @tomusdrw I see so it's out on the next release, thank you
