### ISSUE TITLE
--chain=dev doesn't seal when transactions are sent in parallel

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#4494]
Possible workaround is to use `--reaseal-min-period`, but probably we should just check if there is anything in the queue after the block is mined to trigger sealing again.

**Comment by slothbag** [comment]
Just stumbled upon this same issue.  I have a bunch of contract tests using mocha which submit multiple transactions in rapid succession.  I have to force it to wait 2 seconds between each tx which is frustrating.

I agree with checking for pending tx's and then seal again.

**Comment by keorn** [comment]
That would be against `--reseal-min-period` (in `Ethash` you do not want to seal again even if there are more transactions). This option is also a problem with other async `Engine`s that can create blocks more often than every 2 seconds.
It would be best if this would be `Ethash` specific option rather than something global: ignore otherwise like `--engine-signer`?

**Comment by awgneo** [comment]
@slothbag Have you successfully removed your delay in between transactions for unit tests? I too am using mocha and I have to have a delay or parity cannot take the test load, causing the time to fall behind in solidity and generally, intermittent transaction failures.

**Comment by keorn** [comment]
Use `--config dev` instead of `--chain dev` then you will get a bunch of other presets that make it work out of the box.

**Comment by awgneo** [comment]
I am using a custom chain configuration as I need to populate a bunch of accounts with ether for my tests to function. Additionally, I need my owner config file for other customizations. Finally, even that I still experience this issue.

**Comment by awgneo** [comment]
Oh, and using 1.8.2z

**Comment by awgneo** [comment]
*/z
