### ISSUE TITLE
Support geth-style address-in-keyfile

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#450]
geth stores the address of a key in plain-text in the JSON key file. while not being especially sensible from a privacy point of view, it allows geth to know which keyfile corresponds to which address prior to decryption without an additional key directory (as eth uses).

we should support reading these files.

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/issues/450

**Comment by gavofyork** [comment]
fixed with #509
