### ISSUE TITLE
Manifest not found on docker pull ethcore/parity

### ISSUE THREAD

**Issue by gfrivolt** [ethcore/parity#4503]
I use Docker for Mac, I get `Error response from daemon: manifest for ethcore/parity:latest not found` when I run `docker run ethcore/parity`

```
➜ docker pull ethcore/parity
Using default tag: latest
Error response from daemon: manifest for ethcore/parity:latest not found
```

**Comment by General-Beck** [comment]
@gfrivolt try `nightly`

**Comment by gfrivolt** [comment]
Thanks, I could pull and start it. I've got 50 Gb of space eaten up, then I stopped it. Why is that? Is it supposed to use so much space?

**Comment by General-Beck** [comment]
@gfrivolt `parity --pruning fast`

**Comment by ashoksoo** [comment]
Hi - I am seeing the same error when I try to pull to anything from my docker on Windows-10. 
What is nightly ?

**Comment by FryDerm** [comment]
Hi - I am also seeing the same error on Windows 10.

**Comment by JackPrice** [comment]
FYI @ashoksoo @FryDerm  there's currently an issue affecting the docker registry - [see the status page](http://status.docker.com/)

**Comment by FryDerm** [comment]
Thank you for your response @JackPrice.  I will monitor the status page.

**Comment by mdeangelo272** [comment]
Same Error on Ubuntu:
```
$ docker run docker/whalesay cowsay boo
Unable to find image 'docker/whalesay:latest' locally
docker: Error response from daemon: manifest for docker/whalesay:latest not found.
See 'docker run --help'.
$ docker --version
Docker version 1.13.1, build 092cba3
```

**Comment by Numblesix** [comment]
Same on Fedora 
```bash
[root@claptrap-fritz-box haproxy-nodejs-docker]# docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: manifest for hello-world:latest not found.
See 'docker run --help'.
[root@claptrap-fritz-box haproxy-nodejs-docker]# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:41:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:41:33 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by nTahiri** [comment]
If your facing of the manifest not found i think it's because of the docker hub is discurpted.
http://status.docker.com/

**Comment by Schmetterling** [comment]
they are working on this, sounds good, I did not faced with this problem before, interesting.

**Comment by okram999** [comment]
i know this is closed... 
I got the same err on win7. i got it working by specifying the specific tag, in the `docker pull` command. For some reason, docker trying to pull `latest` when unspecified failed.

**Comment by 5chdn** [comment]
Docker containers for Parity are available via [Docker Hub](https://hub.docker.com/r/ethcore/parity/):

```bash
$ docker search ethcore/parity
NAME                     DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
ethcore/parity           Parity is Ethcore's initial fully-featured...   14                   [OK]
ethcore/parity-poa                                                       2
ethcore/parity-arm       Parity is Ethcore's initial fully-featured...   1                    [OK]
ethcore/parity-centos    Parity is Ethcore's initial fully-featured...   1                    [OK]
ethcore/parity-jit       Parity is Ethcore's initial fully-featured...   1                    [OK]
ethcore/parity-aarch64   Parity is Ethcore's initial fully-featured...   1                    [OK]
ethcore/parity-dev       Parity is Ethcore's initial fully-featured...   0
```

To get a list of available versions, use `curl` and `jq`:

```bash
$ curl -sS 'https://registry.hub.docker.com/v2/repositories/ethcore/parity/tags/'  | jq '."results"[]["name"]' | sort
"beta"
"latest"
"master"
"nightly"
"stable"
"v1.5.12"
"v1.6.6"
```

In general, you want one of `stable`, `beta`, or `nightly`, which always pulls the latest version from the according release channel, e.g., for `beta` run:

```bash
$ docker pull ethcore/parity:beta
```

**Comment by cibelix** [comment]
OMG ... "...:stable" is the solution!

**Comment by hayesgm** [comment]
Experiencing a similar issue with `parity/parity:v1.8.2`. This thread is ... light on details of why this occurred other builds.

**Comment by KamuelaFranco** [comment]
@hayesgm `docker pull parity/parity:stable` as suggested above just worked for me.

**Comment by hayesgm** [comment]
For me, I was using Kubernetes and was not properly passing the image tag. Changing the image tag to "stable" also fixed the problem for me. Thanks.
