### ISSUE TITLE
Error in Firefox browser

### ISSUE THREAD

**Issue by JanKalin** [ethcore/parity#4506]
When test sending a small amount of Ether an error popped up: `can't convert undefined to object CLOSE`.

Firefox 51.0.1 (32-bit) on Windows 7 64 bit, Parity/v1.4.5-beta-a028d04-20161126/x86_64-windows-msvc/rustc1.13.0

![image](https://cloud.githubusercontent.com/assets/18305372/22821153/22f49290-ef7a-11e6-8857-463f85d726f9.png)

**Comment by ngotchac** [comment]
Could you try to update your Parity version ? v1.5.2 is out :)

**Comment by JanKalin** [comment]
This was the only occurence, of the error so yes, I switched to v1.5.2.

**Comment by ngotchac** [comment]
Great, thanks !
