### ISSUE TITLE
How is derived recovery phrase (seed)? Is it standard and compatible?

### ISSUE THREAD

**Issue by Nogreedy** [ethcore/parity#4518]
Hello,
I use and appreciate very much Parity (V. 1.5.2 - Linux and Windows) but I have a question about recovery phrase.
When I create an account I get a 12 words recovery phrase.
@NikVolf 
How is it derived from ?
Is it    m/44'/60'/0'/0   ?   
Is it compatible with myetherwallet.com mnemonic phrase import?
Is it compatible with Mnemonic Code Converter from Ian Coleman https://iancoleman.github.io/bip39/  (new coin added : Ethereum) ?
is it compatible with Metamask?
https://github.com/ethereum/EIPs/issues/84

Thanks in advance for your answer.

**Comment by gavofyork** [comment]
it is vaguely "standard"; specified on https://github.com/ethereum/wiki/wiki/Brain-Wallet

other than that, no.

**Comment by 3esmit** [comment]
myetherwallet.com is planning to add support to parity owner recovery phrase, for now is not supported.

**Comment by 3esmit** [comment]
@Nogreedy myetherwallet.com implemented parity owner phrase, so now you can use it there. 

Node.js snippet to generate parity private-key (adapted from myetherwallet):
```
var ethUtil = require('ethereumjs-util');
function fromParityPhrase(phrase) {
    var hash = ethUtil.sha3(new Buffer(phrase));
    for (var i = 0; i < 16384; i++) hash = ethUtil.sha3(hash);
    while (ethUtil.privateToAddress(hash)[0] != 0) hash = ethUtil.sha3(hash);
    return '0x' +(hash.toString('hex'));
}
```

I always wondered why the first byte of parity address is zero, now I understand that it was a vanity check that aggregates in top of 16384 sha3 passes, which make bruteforce slower.

**Comment by 5chdn** [comment]
closed as fixed / answered with the mew 3.5.0 release. please, let me know if you have any additional questions.

**Comment by mikasalabi** [comment]
MEW removed parity recover phrase because it was insecure, can this be reopened?

**Comment by 5chdn** [comment]
> MEW removed parity recover phrase because it was insecure, can this be reopened?

Could you clarify what exactly you need?

**Comment by mikasalabi** [comment]
Nothing at the moment, but since the resolution of this ticket relied on mew supporting parity owner phrase, and that is not the case anymore, I was suggesting this could be revisited. I believe original request was how to determine the private key from the owner phrase, is there a easy tool doing this?

**Comment by 5chdn** [comment]
You still can use parity via wallet interface or RPC

https://github.com/paritytech/parity/wiki/JSONRPC-parity_accounts-module#parity_newaccountfromphrase

Also I already recommended re-enabling of the parity recovery phrase for MEW here:

https://github.com/kvhnuke/etherwallet/issues/551

The actual code to generate the accounts is here: 

https://github.com/paritytech/parity/blob/master/ethkey/src/brain.rs#L30
