### ISSUE TITLE
Bytecodes of Parity contract development environment and https://ethereum.github.io/browser-solidity/ don't match

### ISSUE THREAD

**Issue by retotrinkler** [ethcore/parity#4522]
Last 68 Bytes of bytecode of the two dev environments seem to be off. Everything up until then seems to match.

**Comment by 3esmit** [comment]
This is related to #4488. The different bytes are about your contract deploy name.
Test by yourself in browser-solidity, change the contract name at the tab and compare the compiled bytecodes. 
Parity is not passing the filename, so your contracts will end up named `:MyContract`, even if you save the contract with some name, while in browser-solidity will end up named `SourceFile.sol:MyContract`. 
I think user should have a better control over this in Parity, as in browser-solidity is. 

Parity:
![image](https://cloud.githubusercontent.com/assets/224810/22868294/15e88e44-f173-11e6-99cf-47a793507f6c.png)
At end of bytecode the resulting different is 
`f25a3a2999ba2d47bbe49d096a67b74ecc541e0b66d37e23de78177d3b4029f1`
Browser-Solidity:
![image](https://cloud.githubusercontent.com/assets/224810/22868300/34194d2c-f173-11e6-846d-4749cca460cc.png)
Browser-Solidity ends up with `7a1f45e180d2c29d39e31ff708be37369ae6d5590da4f7f1efbdf7652f15dde`

That is the only difference, and when you verify the contract at like etherscan.io you just need to enter the correct deploy name, in my case for parity would be `:DocumentRegistry` or for Browser Solidity `DocumentRegistry.sol:DocumentRegistry`.

**Comment by gavofyork** [comment]
wtf? why is the name of the contract being placed in the bytecode at all?

**Comment by derhuerst** [comment]
This? https://solidity.readthedocs.io/en/develop/miscellaneous.html#encoding-of-the-metadata-hash-in-the-bytecode

**Comment by 3esmit** [comment]
@gavofyork I still don't understand the reasons behind this, but is for swarm and I guess to "help" smart contract verification. This is from Solidity 0.4.7+. Parity 1.5.2 still have an issue about this, but next version should be fixed with Parity sending the contract name to solidity compiler.

**Comment by jacogr** [comment]
Yes, it is the Swarm metadata. @ngotchac did add a fix to master to send the contract name along - https://github.com/ethcore/parity/issues/4488

**Comment by ngotchac** [comment]
Yes this should be fixed.
