### ISSUE TITLE
Stratum compatibility with sgminer

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#4535]
originally reported on gitter with this:

```
[...] Discarded cloned or rolled work
```

**Comment by NikVolf** [comment]
![screenshot - stratum](https://cloud.githubusercontent.com/assets/3186518/22896675/6eea8a8e-f23a-11e6-8096-d22f49352cac.png)

**Comment by NikVolf** [comment]
https://github.com/genesismining/sgminer-gm/issues/33

guys from sgminer think that it is a normal message and everything works fine

**Comment by megacrypto** [comment]
it seems that this is the case , as per sgminer guys ... thanks for your support
