### ISSUE TITLE
Parity 1.5.2 --geth "Method Not Found" when used with Mist

### ISSUE THREAD

**Issue by 3esmit** [ethcore/parity#4543]
Users have been reporting this error when trying to use Mist/Ethereum Wallet

@Nogreedy opened an issue at Mist https://github.com/ethereum/mist/issues/1659

@tomusdrw [Fev 14 12:29 in gitter](https://gitter.im/ethcore/parity?at=58a314549eb1bd81481cbc2d)
> `personal_signAndSendTransaction` was recently renamed to `personal_sendTransaction` to match geth name, I suppose Mist might still expect the old method name.

From: https://www.reddit.com/r/ethereum/comments/5tm610/parity_152_not_working_with_ethereum_wallet/
> Hello, I have upgraded to Parity 1.5.2 and I can't make transactions in Ethereum Wallet. I run parity with --geth flag and get see correct block in EW, but when I try to make any transaction, get these errors: "Method not found" and "Method eth_sendTransaction not allowed".
> 
> Everything is working correctly when I install Parity 1.5.0. Is this intentional or a bug?

@kasper1223 [Fev 14 10:08 in gitter](https://gitter.im/ethcore/parity?at=58a2f32321d548df2c095a04)

> I (noob) have a problem using Mist with Parity (on Linux Mint):
> I normally run "parity --geth" first, in order to sync, and then start Mist.
> Everything was fine with parity 1.4.9 and Mist 0.8.8, but then I did an update to Parity 1.5.2 and Mist 0.8.9 and now, when I open Mist, I can no longer send any ether from any of my accounts. If I try, I get "Method not found". Some of the accounts also got "shuffled": for instance: what used to be account 1, is now account 3 etc.
> I also tried Parity GUI and that does work without a problem.
> Possible reason maybe: the difference between Mist browser and Ethereum Wallet is not very clear to me. Maybe I had been using Ethereum Wallet 0.8.8 before (I downloaded: Ethereum-Wallet linux64-0-8-8), and am I using Mist browser 0.8.9 now (I installed Mist-linux64-0-8-9.deb), with the two now both on my computer and interfering??? When I first started Mist 0.8.9 after the update, I got a message "detecting new node" (if I remember correctly)
> Any idea how I can get Mist (running on Parity) working properly again?

@bittylicious [Fev 13 18:12 in gitter](https://gitter.im/ethcore/parity?at=58a20d9d238b1dae570518fa)
> Does "personal_signAndSendTransaction" still exist in Parity? Just started getting "Method not found" errors
> Oh, looks like it's been renamed. Let me try that in my code.
> Yup, works. Ignore me

**Comment by tomusdrw** [comment]
Closed with #4569 and #4554
