### ISSUE TITLE
Build error at hidapi v0.3.1

### ISSUE THREAD

**Issue by megacrypto** [ethcore/parity#4546]
trying new git pull i got this error when building (thats on ubuntu 16.04)

`

> Build failed, waiting for other jobs to finish...
> error: failed to run custom build command for `hidapi v0.3.1 (https://github.com/ethcore/hidapi-rs#9a127c1d)`
> process didn't exit successfully: `/home/mylin/Downloads/parity/target/release/build/hidapi-48cd60fc57c38e3c/build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("3")
> PROFILE = Some("release")
> TARGET = Some("x86_64-unknown-linux-gnu")
> debug=false opt-level=3
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-I" "etc/hidapi/hidapi" "-o" "/home/mylin/Downloads/parity/target/release/build/hidapi-49dd0e7df14cad72/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c"
> cargo:warning=etc/hidapi/linux/hid.c:44:21: fatal error: libudev.h: No such file or directory
> cargo:warning=compilation terminated.
> ExitStatus(ExitStatus(256))
> 
> 
> command did not execute successfully, got: exit code: 1
> 
> 
> 
> --- stderr
> thread 'main' panicked at 'explicit panic', /home/mylin/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.35/src/lib.rs:897
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

`

**Comment by megacrypto** [comment]
apt-get install libudev-dev

fixed it ... thank you Tomasz Drwięga @tomusdrw

**Comment by forgetso** [comment]
Thanks @megacrypto

**Comment by bilbma** [comment]
thanks @megacrypto

**Comment by DaniRumpi** [comment]
thanks @megacrypto
