### ISSUE TITLE
Simple value transfer show exception (however it completes)

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4550]
Reported by @tomusdrw 

1. Simple value transfer (mainnet)
2. no exceptions shows while preparing
3. when completed, it shows exception (Provided 21,000 gas (20,000M/ETH) for a total transaction value of 0.00042 ETH)

![screenshot from 2017-02-15 09-44-02](https://cloud.githubusercontent.com/assets/1424473/22968197/c93cfbae-f369-11e6-909b-e88badc616d2.png)

**Comment by ngotchac** [comment]
Yes. That comes from #4504 

@tomusdrw 
Is there any way of really knowing when a transaction went oog ? A simple `gasUsed === gasProvided` is not really working... We could whether not check OOG if there is no input data to the transaction (ie. simple transactions) ; or display it only with trace mode enabled. Or have access to this info somehow via RPC ?

**Comment by tomusdrw** [comment]
Afaik currently there is none. There is a discussion ongoing here: https://github.com/ethereum/interfaces/issues/1

As a workaround you could check `gas=21k, data=0x, code(recipient)=0x` and disable a warning in such cases.

**Comment by ngotchac** [comment]
Okay, will do then ! Is the last check necessary ? It would make one extra call per transfert, which might not be necessary (thinking about Light Client mainly).

**Comment by tomusdrw** [comment]
It's not necessary, although sending a transaction to a contract (fallback function) with only 21k gas will definitely go OOG, and if the check is omited the warning would not be displayed.
