### ISSUE TITLE
ERC20-compatible token doesn't register via TokenReg

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4552]
As reported by @tomusdrw 

Mainnet -

- Address 0x922131A0eC60FAE04BDA9ec7b1677705aeCaC960
- totalSupply available (see attached screenshot)

Trying to register -

![parity 2017-02-15 10-53-12](https://cloud.githubusercontent.com/assets/1424473/22969033/3146c678-f36d-11e6-8503-b56c29c6b45c.png)

Contract with ERC20 ABI -

![screenshot from 2017-02-15 10-47-16](https://cloud.githubusercontent.com/assets/1424473/22968923/bde8ec9c-f36c-11e6-9897-23229cd5d093.png)

**Comment by tomusdrw** [comment]
Closing, since I messed up addresses. Maybe a good improvement would be to display identicon in TokenReg?
