### ISSUE TITLE
Pasting value into an input field erases the previous entered text

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4553]
e.g. trying to post `_base` into TokenReg ABI resets all other values already entered

As reported by @tomusdrw

**Comment by ngotchac** [comment]
I cannot reproduce this one. I'm not sure I fully understood what the issue is though (TokenReg ABI ?).

**Comment by tomusdrw** [comment]
Yes, when trying to Execute `registerAs` method of TokenReg contract go to `_base` field and:
1. Type `1000`
2. Copy last `000` and try to paste it after `1000`
3. It will reset to `000` instead of appending.

**Comment by ngotchac** [comment]
Ah yes you're right ! Will look into it.
