### ISSUE TITLE
Docker optimization

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#4562]
1. 
```
$ docker pull ethcore/parity
Using default tag: latest
Pulling repository docker.io/ethcore/parity
Tag latest not found in repository docker.io/ethcore/parity
```
Default tag needs to be fixed.

2. Docker image contains a lot of build artefacts and requires a 1500MB download. Should only be the binary.

**Comment by General-Beck** [comment]
https://github.com/ethcore/parity/commit/a3bbdce61324c0cdeabd35669c2fae42534da03a refactoring

**Comment by General-Beck** [comment]
1 https://github.com/ethcore/parity/commit/163e2af5682f66ceb8444b77602f3206e8d49f14
2 reduced filesize to 133 MB
