### ISSUE TITLE
dockerhub ethcore/parity:v1.5.2 contains version 1.6.0

### ISSUE THREAD

**Issue by vincentserpoul** [ethcore/parity#4568]
within ethcore/parity:v1.5.2:

```
parity -v
version Parity/v1.6.0-nightly-4fa1717-20170205/x86_64-linux-gnu/rustc1.15.0
```

**Comment by vincentserpoul** [comment]
I can help if the scripts to push/select/build according to versions are public

**Comment by General-Beck** [comment]
https://github.com/ethcore/parity/blob/master/docker/hub/Dockerfile#L60

**Comment by vincentserpoul** [comment]
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/parity\": permission denied".

**Comment by vincentserpoul** [comment]
the Dockerfile in dockerhub is also not synced with the one in the parity repo /docker/hub

**Comment by General-Beck** [comment]
https://hub.docker.com/r/ethcore/parity/tags/ need for test
