### ISSUE TITLE
Mathematica code in sizes.rs is not the correct source for the data

### ISSUE THREAD

**Issue by peterjoel** [ethcore/parity#457]
I had an idea to rewrite [`sizes.rs`](https://github.com/ethcore/parity/blob/master/ethash/src/sizes.rs) to use Rust or a Rust macro. However, I got different results from the Mathematica functions that are shown in the comments, so I tried running them in Mathematica.
The full results are in these gists:
https://gist.github.com/peterjoel/cca5742438fb07fb27dd
https://gist.github.com/peterjoel/97393e0ae8aa8a83a2ee

The Mathematica output for the function given as the source for [`DAG_SIZES`](https://github.com/ethcore/parity/blob/master/ethash/src/sizes.rs#L32)  is actually the same as the value given for [`CACHE_SIZES`](https://github.com/ethcore/parity/blob/master/ethash/src/sizes.rs#L459-L787)

The Mathematica output for the function given for [`DATA_SIZES`](https://github.com/ethcore/parity/blob/master/ethash/src/sizes.rs#L447), however, gives these numbers:
```
{1048384,1055552,1064512,1072832,1080896,1089344,1096768,1104448,1113664,1121216,1130176,1138624,1146304,1155008,1162816,1171264,
 ⋯ 2016 ⋯ 
,17693888,17702336,17710144,17718208,17726528,17734336,
17743808,17751872,17759936,17766592,17776448,17784512,17791936,17801152,17809216,17817152}
```
which do not resemble the given numbers at all.

**Comment by peterjoel** [comment]
The numbers however do match those given in the Ethereum project: https://github.com/ethereum/wiki/wiki/Ethash, and the python functions given there are probably a better reference (the old Mathematica functions, in the history of that document, also do not give the same numbers).

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/issues/161

**Comment by peterjoel** [comment]
Ah thanks. I guess you can close this one then.

**Comment by NikVolf** [comment]
there will be link here from earlier issue
