### ISSUE TITLE
Master branch failing for latest nightly [move to rustc beta]

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#458]
meanwhile, this instructions from beta branch (with specific toolchain) may be useful:
https://github.com/ethcore/parity/tree/beta

**Comment by NikVolf** [comment]
https://github.com/serde-rs/aster/pull/67

**Comment by debris** [comment]
aster is already fixed in 0.13.0

**Comment by debris** [comment]
quasi fix: https://github.com/serde-rs/quasi/pull/33

**Comment by NikVolf** [comment]
yep but serde - still no fix

**Comment by debris** [comment]
I was trying to fix it, but finding and fixing a bug in codegen code is quite complicated... :/

**Comment by gavofyork** [comment]
local workaround: install older nightly
fix: move to rustc beta https://github.com/ethcore/parity/issues/453
