### ISSUE TITLE
Access parity v.1.5.2 in docker container

### ISSUE THREAD

**Issue by vincentserpoul** [ethcore/parity#4584]
macosX
Docker 1.13 (no more docker machine, docker accessible on 127.0.0.1 forwarded ports)
ethcore/parity:v1.5.2

even though the ports are published, parity wouldn't allow connection on 127.0.0.1:8180 or 127.0.0.1:8080.

I tried the  --ui-no-validation but still the same thing.

Any idea?

**Comment by vincentserpoul** [comment]
This makes the whole docker experience useful only to run a public node without any interaction with it, which kind of hide all the nice work done around Parity.

**Comment by tomusdrw** [comment]
What kind of errors do you get? Could you post the commands you used to start the docker container?

**Comment by tomusdrw** [comment]
Parity by default listens only on `localhost` interface, probably you need to expose bind to external IPs of the container as well.

**Comment by vincentserpoul** [comment]
The most simple run I can do is:
```
docker run -dit --name testparity -p 8180:8180 -p 8080:8080 -p 8545:8545 ethcore/parity:v1.5.3
```

On mac, Docker publishes ports on localhost, so it should be exactly like the default config.

Is anybody running a ethcore/parity:v1.5.3 container and accessing the UI?
If yes, could you post your config?

**Comment by tomusdrw** [comment]
Could you try altering CLI parameters (or create a config file) and set `--ui-interface 0.0.0.0 --ui-no-validation --dapps-interface 0.0.0.0 --dapps-hosts all`?

Afair you need to listen on docker external interface for any port publishing to work.

**Comment by vincentserpoul** [comment]
@tomusdrw just tried on linux and tested each params.
The --ui-interface 0.0.0.0 is the one needed to access the parity UI.
I'm not sure why it's not needed on the non containerized parity though.

I will test on a mac to confirm in a few hours.

**Comment by tomusdrw** [comment]
So container has it's own `localhost` interface, to which parity is binding to. It's different than the host `localhost` interface.
You can use port-forwarding in docker, but it exposes a service listening to external interface of your container and makes it available on `localhost` of the host.

**Comment by vincentserpoul** [comment]
for mac: --ui-interface 0.0.0.0 --ui-no-validation worked too.

In the config file, I just added
```
force = true
interface = "0.0.0.0"
```

and I can reach my node on http://0.0.0.0:8180!

**Comment by dcorking** [comment]
Please add Vincent's finding to the wiki: https://github.com/paritytech/parity/wiki/Docker . The parity UI doesn't work (ERR_EMPTY_RESPONSE) on Mac OS X Docker without `--ui-interface 0.0.0.0`.

**Comment by tomusdrw** [comment]
@dcorking Updated, thanks!
