### ISSUE TITLE
All my accounts was removed 

### ISSUE THREAD

**Issue by yanikkoval** [ethcore/parity#4598]
Not sure why, but after chain of actions, all my accounts was whipped out and I started with step #1 default parity dialog. The weirdest thing that I never stopped the node and even don't close parity browser window. 

## Chain of actions 
1) create a transaction from one of my wallets 
2) failed with password like 10+ times 
3) cancel transaction on singer tab
4) clicked on account/password and tried to guess my password. On this step, something went wrong, did not even get a message about the correct/incorrect password. 
5) everything is wiped out, all my 3 accounts disappeared and it looks like fresh parity now 

**version** Parity/v1.5.2-beta-948a538-20170208/x86_64-macos/rustc1.15.1
**chain** mainnet

**Comment by tomusdrw** [comment]
Could you go to `/Users/<yourusername>/Library/Application Support/io.parity.ethereum/keys` and list the content there?

**Comment by yanikkoval** [comment]
@tomusdrw I can but there are only 2 newly created addresses

**Comment by yanikkoval** [comment]
UP. After switching to `ropsten` chain I discover my accounts. 
But I'm 100% sure they were created and managed on main chain, I even had some small balance, to test things https://etherscan.io/address/0x00C65035dd188085e448a63F24E0Eb6866B1F271

That's to say keys were moved from ethereum to test folder, how it possible? 😧
@tomusdrw you conclusion was very accurate.

**Comment by tomusdrw** [comment]
Keys directories were changed between 1.4 and 1.5 versions, perhaps you had two different version running? In 1.5 introduced per chain spearation of keys and when running 1.5 for the first time we are migrating all you keys. So if you run 1.5 for the first time with `--chain=ropsten` your keys will move there.

Are you using Mac installer?

**Comment by yanikkoval** [comment]
@tomusdrw that's clarified the situation. 
I had 1.4.x and update to 1.5.x like: 

`brew unlink parity`
`brew install parity --beta`

I get now that it was not wise.
Now its mix and for example, only old accounts are available as executable in parity applications

**Comment by tomusdrw** [comment]
Assuming solved. Please re-open if there is still an issue.
