### ISSUE TITLE
Parity on Mac OS X newbie questions

### ISSUE THREAD

**Issue by Doweig** [ethcore/parity#4601]
Hello guys,

Got a cool presentation on Parity from Gavin at the Edcon today so I decided to give it a try. I have a few questions that I can't find answer to, so I decided so put them all together here.
Those are all concerning Parity 1.5.2 on Mac OS X, installed from `parity-1.5.2-osx-installer-EXPERIMENTAL.pkg`

1) How to see the logs from the command line?

2) How to stop Parity? Killing the process won't work, it just relaunches itself.
Also tried to use `launchctl stop io.parity.ethereum` from [here](https://github.com/ethcore/parity/blob/beta/mac/install-readme.txt) won't stop it.
#4517 says 
```
This has been removed from the master codebase because the latest installer on Mac
uses a different auto start mechanism and user now has an option to disable it through
the standard Login Items UI or the Parity icon in the top bar.
```
Can't find that either

3) Is the option to pause the blockchain syncing works during the initial download? I'm at "1,706,028/3,211,695 syncing" and my CPU is just 100% contently, tried to change the sync options from the web interface but the CPU load just stays up max.

4) Where is the blockchain stored?

5) Is using `parity-1.5.2-osx-installer-EXPERIMENTAL.pkg` the recommended way to install Parity on Mac OS X? If not, which one is?

Thank you guys in advance for your help :)

PS: Installing from brew is giving the 1.4 while the website is stating the 1.5 as the latest. Might be related to the fact that last release on github is 1.4 https://github.com/ethcore/parity/releases. Not sure that's a bug, just let you know

**Comment by Doweig** [comment]
1) `/Users/$USER/.parity/log.{out,err}`

2) Because the agent is configured with `KeepAlive`, it will auto reboot on stop. Correct way to stop it is by using `unload` like this `launchctl unload /Users/$USER/Library/LaunchAgents/io.parity.ethereum.plist`. Use `load` to start it again

**Comment by rphmeier** [comment]
@Doweig Just to add: the Mac OS installer/control UI will be vastly improved with the 1.6 release.
