### ISSUE TITLE
Contract development panel error: "TypeError: t is undefined"

### ISSUE THREAD

**Issue by catageek** [ethcore/parity#4603]
As described in title, whenever I open the contract development panel, I got this error on the right panel. The error stays even if I fill the left panel with a correct source code.

Parity version:
Parity//v1.6.0-unstable-5f154b9-20170211/x86_64-linux-gnu/rustc1.14.0-beta.2
Unknown capability

**Comment by gavofyork** [comment]
almost certainly an error in your solidity code; please paste the minimum code needed for this.

**Comment by catageek** [comment]
The error is displayed even when there is no code, as soon as I open the panel, and it stays whatever I type on the left pane.

I am currently trying to rebuild parity but I am stuck with a build error on nanomsg. I will give a feedback when I can build parity.

**Comment by catageek** [comment]
So I built parity from scratch with a fresh rustup installation, and I still have the error.

see this [capture](http://i.imgur.com/E40KXVy.png). This message appears after a brief "loading Solidity version ..."

**Comment by derhuerst** [comment]
that looks a lot like an error in the UI code. could you post your browser and operating system versions?

**Comment by catageek** [comment]
Firefox version ESR 45.7.0
Linux athlon 4.8.6-gentoo-20161106 #5 SMP PREEMPT Sun Nov 6 20:21:14 CET 2016 x86_64 AMD FX(tm)-8350 Eight-Core Processor AuthenticAMD GNU/Linux

**Comment by catageek** [comment]
I have also this in the browser console:

[checkUpgrade] available: null version: Object { major: Getter, minor: Getter, patch: Getter, 1 de plus… } consensusCapability: unknown index.beeefb2334.js:6:18439
[lookupAddress] dappreg: 0x724A8602fc0C2b346f8eC56Df2913710742d3fD0 index.beeefb2334.js:6:14280
[lookupAddress] signaturereg: 0x336D7c77B87754fF5c5CF8138605bAAB05B1D9Ba index.beeefb2334.js:6:14280
[lookupAddress] tokenreg: 0x7Ae6d608CD96f5D34eD989211de85d7de1a31585 index.beeefb2334.js:6:14280
[lookupAddress] githubhint: 0xfA29053696C1353a53656a3F15710CD59D08Fce8 index.beeefb2334.js:6:14280
[lookupAddress] badgereg: 0xcF5A62987294fd2087252FD812443508528C52bF index.beeefb2334.js:6:14280
[solidity] evaluating 0.4.9+commit.364da425 index.beeefb2334.js:31:26881
[solidity] compiling... index.beeefb2334.js:31:25969
DappsStore:fetchManifest SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by catageek** [comment]
I noticed there is another message that appears a few ms before the other error message when I load the panel:
"SyntaxError: In strict mode code, functions may be declared only at top level or immediately within another function"

**Comment by ngotchac** [comment]
I can reproduce it on your Firefox version. Not sure how long would a fix take ; in the meanwhile, you might want to upgrade your Firefox version :)

**Comment by ngotchac** [comment]
@catageek Please try again on master after #4860 gets merged, or directly on the branch.
