### ISSUE TITLE
How to run parity on Mac Sierra?

### ISSUE THREAD

**Issue by jordimorris** [ethcore/parity#4604]
I have installed parity following the steps at 
https://ethcore.io/parity.html

How can I run parity? it is said in github to run:

To start Parity manually, just run
$ ./target/release/parity

but I get the error "command not found" and I don't understand where is installed. 

How to know and find the folder from where the command has to run?

thanks

**Comment by keorn** [comment]
If you used the installer it should be running as a service already, just go to `localhost:8080` for UI. If you used homebrew, then `parity` should be the command to start it.

**Comment by rphmeier** [comment]
@jordimorris the "run `target/release/parity`" instruction is only relevant when building from source. If you've installed using the installer, then "Parity Ethereum" should be in your applications folder.

**Comment by 5chdn** [comment]
Or, if you installed it via `brew`, just type `parity` in your terminal.

**Comment by shcheuk** [comment]
I installed it via installer, how can I use parity in my terminal? uninstall it in the applications folder and reinstall it using brew? I have geth installed, which block the port 30303, I think I need to try  parity --geth option, but command line tool seems not available when install through the installer, is it true? I think it need to be stated in the web site at the begining....

**Comment by arkpar** [comment]
If you used the installer parity CLI is available at `/Applications/Parity\ Ethereum.app/Contents/MacOS/parity`. You can add this to PATH, or make a shell alias.

**Comment by shcheuk** [comment]
Thx a lot! It solved ! in case someone have the see this, here is the procedure of using command line parity if you install parity as an mac application via packager.
open ~/.bash_profile, add the following line:
`export PATH=/Applications/Parity\ Ethereum.app/Contents/MacOS:$PATH`
notice that there is a space and it is verse slash before Ethereum.app, as said by arkpar
restart terminal, (no need to restart your mac)

**Comment by ltfschoen** [comment]
Append to bash_profile and restert the terminal with single command:
```
echo 'export PATH=/Applications/Parity\ Ethereum.app/Contents/MacOS:$PATH' >> ~/.bash_profile && source ~/.bash_profile
```
