### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#462]
###### Dependencies:
* [x] RocksDB
* [x] sha3 build script
* [x] nanomsg buils
probably others

###### Parity:
* [ ] getifaddrs
* [ ] Data directory
* [ ] Daemonization

**Comment by debris** [comment]
regarding sha3, we can also use rust implementation

**Comment by gavofyork** [comment]
i'm not in the slightest bit bothered about supporting windows prior to 1.0.

**Comment by arkpar** [comment]
This is just to track potential issues

**Comment by debris** [comment]
@arkpar can we close this one?
