### ISSUE TITLE
IPC geth path different for testnet

### ISSUE THREAD

**Issue by momchilov** [ethcore/parity#4634]
For example, on my Mac, the IPC path for the testnet is set to `/Users/<user>/Library/Ethereum/testnet/geth.ipc`. Geth always sets the IPC path to `/Users/<user>/Library/Ethereum/geth.ipc`, no matter which net it is running on. 

edit: looking at the code, this seems to be done intentionally - 226fe8e0bb3f33bd7ed793d24f5c4057b49ff088, in `parity/helpers.rs`, `if testnet {`... and e6d141e14f18b021ef7d8c3b555a91291c47a863 in `util/src/path.rs`

**Comment by NikVolf** [comment]
How did you find out that geth always sets IPC path to the main dir?

I have just run it with `geth --testnet` and it shows this:

```
I0226 12:46:38.235168 node/node.go:340] IPC endpoint opened: /Users/admin/Library/Ethereum/testnet/geth.ipc
```

**Comment by momchilov** [comment]
That's odd. When I start Mist, I'm seeing this in my process list ` /Users/<user>/Library/Application Support/Mist/binaries/Geth/unpacked/geth --testnet --fast --ipcpath /Users/kiril/Library/Ethereum/geth.ipc` and the file is indeed there. Parity however creates it in the `testnet/` location.

**Comment by NikVolf** [comment]
that's because mist is setting IPC path other than default would be

you can just run parity with custom IPC path as well to match those above

`parity --warp --ipc-path /Users/<user>/Library/Ethereum/geth.ipc`
