### ISSUE TITLE
InstallParity.exe v 1.5.4 for windows installs v 1.5.2

### ISSUE THREAD

**Issue by charlieknoll** [ethcore/parity#4646]
From the command line:

C:\Program Files\Ethcore\Parity>parity -v
Parity
  version Parity/v1.5.2-beta-948a538-20170208/x86_64-windows-msvc/rustc1.14.0

**Comment by JanKalin** [comment]
Yup, something isn't quite right with the update. In my case the `InstallParity.exe` does install the correct version:
```
quark % parity.exe -v
Parity
  version Parity/v1.5.3-beta-0f99b1e-20170220/x86_64-windows-msvc/rustc1.14.0
```
but each time the when run, the old version is downloaded:
```
2017-02-23 14:28:13  Starting Parity/v1.5.3-beta-0f99b1e-20170220/x86_64-windows-msvc/rustc1.14.0
2017-02-23 14:28:13  State DB configuration: fast
2017-02-23 14:28:13  Operating mode: passive
2017-02-23 14:28:13  Configured for Frontier/Homestead using Ethash engine
2017-02-23 14:28:13  Updated conversion rate to Îž1 = US$12.79 (9307867000 wei/gas)
2017-02-23 14:28:15  Attempting to get parity binary 2462â€¦07ca
2017-02-23 14:28:17  Imported #3236303 9711â€¦86d0 (4 txs, 0.08 Mgas, 2.57 ms, 0.98 KiB)
2017-02-23 14:28:18  Fetched latest version (1.5.2-beta-948aâ€¦b0c1) OK to C:\Users\jank\AppData\Local\Temp\VzzDexRrkRsy
2017-02-23 14:28:18  Installed updated binary to C:\Users\jank\AppData\Roaming\Parity\EthereumUpdates\parity-1.5.2-948a5387b3d58f39e0d4972ccaf98033e541b0c1
```
without it being started:
![image](https://cloud.githubusercontent.com/assets/18305372/23261350/1c6455c6-f9d6-11e6-9416-e82276e59da7.png)

But, when clicking on the `Upgrade` in the browser this pops up:
![image](https://cloud.githubusercontent.com/assets/18305372/23261407/4cb6ceac-f9d6-11e6-907d-ba983aa923a2.png)
and the installer crashes if you try to install:
![image](https://cloud.githubusercontent.com/assets/18305372/23261509/c6989e8a-f9d6-11e6-9739-8f4cefc9f944.png)

From then on it tries to run Parity v1.5.2 from the `C:\Users\jank\AppData\Roaming\Parity\EthereumUpdates` directory, even if you start it with `detach "C:\Progra~1\Ethcore\Parity\parity.exe --log-file C:\Users\jank\.parity\parity.log"`, as I normally do,

To restore v1.5.3, you need to delete  `C:\Users\jank\AppData\Roaming\Parity\EthereumUpdates` directory and re-run `InstallParity.exe`

**Comment by charlieknoll** [comment]
Thanks @JanKalin.  I checked the latest v 1.5.4 release and the issue is still happening.  It automatically reverts to 1.5.2

**Comment by 5chdn** [comment]
Just tried on a fresh system. `InstallParity.exe` from the 1.5.4 release with md5sum `ab4f38cd47d095c8a9922c8b8e1f57d3` actually installs 1.5.4:

     C:\Program Files\Ethcore\Parity>parity.exe -v
     Parity
       version Parity/v1.5.4-beta-74b850e-20170223/x86_64-windows-msvc/rustc1.14.0

Could you try uninstalling the old version first and reinstalling the new version?

**Comment by 5chdn** [comment]
@JanKalin it looks like a different issue though, the installer executable is something different than then downloader. If your issue persists, please create a new ticket.

**Comment by arkpar** [comment]
This was an issue with auto-updater. Should be resolved now.
