### ISSUE TITLE
Is this a light wallet that doesn't need to sync blockchain?

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [ethcore/parity#4648]
I am simply looking for a light wallet to store the tokens on my linux PC. Since I read it is a light client of ethereum I have compiled and run it but it seemed to starting syncing the blockchain.

Sorry for the noob question.

**Comment by rphmeier** [comment]
No, Parity doesn't include any "light wallet" which doesn't have to sync. It will include a "light client" soon, but this just reduces the amount of synchronization which must be done.

**Comment by GreatBigWhiteWorld** [comment]
Thank you. @rphmeier
