### ISSUE TITLE
Make Warp-sync default

### ISSUE THREAD

**Issue by williambanks** [ethcore/parity#4651]
It would be remarkably faster if there were a way to download a snapshot of the blockchain in whatever DB format you are using natively.

In order to reduce your server load, perhaps you could seed it as a zip file via bittorrent or something.

Would it be feasible to maybe add a feature like that?  The torrent checksum, should be enough to validate the contents of the chain so long as enough nodes were in agreement about the snapshot, or you published the current snapshot checksum here.

It just seems that at least on initial install, validating a downloaded chain would be much faster than the current method of grabbing the chain a block or two at a time and trying to validate it.

For reference, I've been trying to sync this thing for going on a week now and I'm about 2/3rds of the way there.  I'm on a dedicated quad core box with 4GB of RAM and 1GB connection at my host.  Bitcoin took less time to sync.

**Comment by maciejhirsz** [comment]
Parity already has [Warp Sync](https://github.com/ethcore/parity/wiki/Warp-Sync).

**Comment by williambanks** [comment]
Thank you, just a comment but really that should be the default option IMHO.
Also it should be featured more prominently.
