### ISSUE TITLE
Parity Config Generator stops updating preview after changing the Auto Update value

### ISSUE THREAD

**Issue by lgpawel** [ethcore/parity#4693]
Steps to reproduce:
- https://ethcore.github.io/parity-config-generator/
- Change the value of Parity » Auto Update. :ok: 
- Change some other options. :ok:
- Change the value of Parity » Auto Update again (to none, but sometimes happens for other values). This is not reflected in the preview.
- Change any options, load a predefined config. Nothing shows up in the preview.
- Refresh the page. All (?) preceding changes now appear.

My user agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0`.
Calling @tomusdrw

**Comment by lgpawel** [comment]
Somewhat similar behaviour happens for the Network » Disable Network switch.

**Comment by tomusdrw** [comment]
Thanks for reporting, should be fixed now.
