### ISSUE TITLE
Unable to load default account in the UI: "Method not found"

### ISSUE THREAD

**Issue by yuanfeiz** [ethcore/parity#4712]
**Reproduce Steps**:

1. Open UI
2. Create account
3. The account didn't show up: ![image](https://cloud.githubusercontent.com/assets/705367/23453383/2065a360-fea3-11e6-84b2-b364a8871f25.png)
4. `Method not found error`s: ![image](https://cloud.githubusercontent.com/assets/705367/23453397/3006a968-fea3-11e6-8c10-fbc3eb70b417.png)
5. UI has connected to the RPC: ![image](https://cloud.githubusercontent.com/assets/705367/23453406/3bafc9c0-fea3-11e6-845f-7bc5ff608c16.png)

I disabled MetaMask and tried again but it didn't work either.

**Versions**:
Parity//v1.4.12-stable-b884729-20170222/x86_64-macos/rustc1.15.1

**Comment by 5chdn** [comment]
Some on gitter had the same issue with 1.4.12, just copy-pasting here:

> Mac OS X Sierra - newest version of home-brew - sync was succesfull - error: parity_defaultAccount([]): -32601: Method not found
[Error] parity_upgradeReady([]): -32601: Method not found
_onMessage (index.f0bd4644b8.js:11:19797)
[Error] parity_consensusCapability([]): -32601: Method not found
_onMessage (index.f0bd4644b8.js:11:19797)
[Error] parity_versionInfo([]): -32601: Method not found
_onMessage (index.f0bd4644b8.js:11:19797)
parity_allAccountsInfo([]): -32601: Method not found

**Comment by 3esmit** [comment]
This issue seems to be getting frequent now ethereum is hot in mainstream.

**Comment by jacogr** [comment]
This has been fixed in the 1.5.8 stable release. (As well as the upcoming 1.6.x beta series)
