### ISSUE TITLE
Sent Transaction Not Arriving at Destination

### ISSUE THREAD

**Issue by Ural2121** [ethcore/parity#4755]
I attempted to send some ETH but I must have done something wrong and could not figure out how to get out of the signer so I did a reject transaction.

I then attempted to send the ETH again and it appeared to send the ETH but again it did not get to the destination.
Instead, The amount I sent landed in what appears to be a new wallet for me using the address I sent to.

Since this is not my wallet, how do I get my coins back?

**Comment by rphmeier** [comment]
> The amount I sent landed in what appears to be a new wallet for me using the address I sent to.

I'm not sure I 100% understand the issue here. Doesn't this mean it's been sent to the address you chose?

**Comment by Ural2121** [comment]
Here are the transaction IDs:
0x6fb32c08182e52494cbb94374ca11b020bb56a851a39d8157c23033c35940fc6
0xd2b9d735c323b79af3091af411e94a2c46a6af16be30e34d1dc7fe7f9071287a

This is the address I sent to:
0xa692e8aFe4aa0F8829D1cE8FbEe98ddD2d288a07

The amount shows up in my parity client as if it was one of my wallets but I can not do anything with such as send it back to myself so I can try again. I do not have a password for this wallet since it is not mine. Why for example, is it in my parity client at all? What did the reject transaction do? I thought it was cancelling my send request.

If still unclear, please ask for more info. Thanks.

**Comment by Ural2121** [comment]
It is becoming a little clearer to me now. I sent to an exchange address. The exchange has now given me a new address. I just do not know what is going on.

**Comment by gavofyork** [comment]
still not sure what you're actually asking here...

**Comment by 5chdn** [comment]
Both transactions you provided went through to the desired address. If the destination was an exchange and you have issues to access these funds, please contact their support staff.

In case I misunderstood your question, please add more details on expected behavior versus actual behavior of the wallet.

**Comment by Ural2121** [comment]
It appears I was mistaken. In my confusion, the ETH was sent to an Account I have. It must have been the account, if I recall correctly that was created when I installed parity, never wanted, and did not know how to delete. Since I did not want this account to exist, I do not remember any details about it, especially it's password. Is any help available to recover it?

**Comment by 5chdn** [comment]
What OS are you using? Windows? Do you have any backups of the wallet? Do you remember any parts of the password used? You can also look into this resource: [How can I recover or reset a lost wallet password?](http://ethereum.stackexchange.com/q/97/87)

**Comment by Ural2121** [comment]
Thanks for your reply. I am using Windows 10. Since I did not want this account, I could have entered anything as a password. I looked at the recovery link you provided and at this time kind of lost how to go about it. Would it be possible to get a brief tutorial for beginners? Links to the python (I know nothing about python) code to use, How to convert to json, etc. Also, what response is given, for example, when the password is found?

**Comment by 5chdn** [comment]
Before trying to recover the passphrase, could you please check if you can locate the json key on your disk? Have a look at `/Users/You/AppData/Roaming/Parity/Ethereum`, and if you can find it we can proceed.

**Comment by Ural2121** [comment]
I did not find it at the location you specified, but did find it here:
C:\Users\ME\.parity\keys

**Comment by Ural2121** [comment]
There appears to be three keys. I do have three accounts now.

**Comment by 5chdn** [comment]
Does this include the account in question which holds your Ether?

**Comment by Ural2121** [comment]
Yes, I believe so.

**Comment by Ural2121** [comment]
I did a search and found some more at: C:\Users\ME\AppData\Roaming\Ethereum\keystore

These files are dated in September 2016 and may not the ones of interest.

**Comment by Ural2121** [comment]
Ok. I have the file now.

**Comment by 5chdn** [comment]
And can you try to import it to Parity now? (Accounts -> New -> Import)

**Comment by Ural2121** [comment]
It appears to be already imported and shows as one of the three accounts I now have with the correct balance.
The three accounts I now have are here:  C:\Users\ME\.parity\keys

**Comment by 5chdn** [comment]
Okay, can you please state which version of parity you are using?

If the account is added now, can you see the correct balance? Can you access the funds now?

**Comment by Ural2121** [comment]
Parity version:  Parity//v1.4.4-beta-a68d52c-20161118/x86_64-windows-msvc/rustc1.13.0

I can see what I recall to be the correct balance. I can not send. Error message says the it is either a wrong password or account does not exist. However, I was able to rename the account. You need a cancel button there perhaps to remove the attempted transaction from the signer.

**Comment by 5chdn** [comment]
Okay, all I can do for you now is to recommend you a commercial, trusted wallet recovery service if you do not remember the passphrase and the linked resources above did not help.
