### ISSUE TITLE
Ubuntu install panic

### ISSUE THREAD

**Issue by rfikki** [ethcore/parity#478]
Compiling ethcore-util v0.9.99 (file:///home/rocky/parity)
util/src/panics.rs:78:7: 78:12 warning: unused variable: `guard`, #[warn(unused_variables)] on by default
util/src/panics.rs:78 		let guard = PanicGuard { handler: self };
                      		    ^~~~~
util/src/panics.rs:111:1: 116:2 warning: function is never used: `convert_to_string`, #[warn(dead_code)] on by default
util/src/panics.rs:111 fn convert_to_string(t: &Box<Any + Send>) -> Option<String> {
util/src/panics.rs:112 	let as_str = t.downcast_ref::<&'static str>().cloned().map(|t| t.to_owned());
util/src/panics.rs:113 	let as_string = t.downcast_ref::<String>().cloned();
util/src/panics.rs:114 
util/src/panics.rs:115 	as_str.or(as_string)
util/src/panics.rs:116 }

   Compiling parity v0.9.99 (file:///home/rocky/parity)
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/rocky/parity/target/release/parity.0.o" "-o" "/home/rocky/parity/target/release/parity" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/rocky/parity/target/release" "-L" "/home/rocky/parity/target/release/deps" "-L" "/home/rocky/parity/target/release/build/eth-secp256k1-f54a83b9ad792914/out" "-L" "/home/rocky/parity/target/release/build/rust-crypto-daa20c09deb34369/out" "-L" "/home/rocky/parity/target/release/build/sha3-3ec72520eb4f3acc/out" "-L" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/rocky/parity/target/release/deps/libctrlc-39e3d2ab6959b27c.rlib" "/home/rocky/parity/target/release/deps/libfdlimit-f08546cad833d098.rlib" "/home/rocky/parity/target/release/deps/libdaemonize-e99fc88a654cf113.rlib" "/home/rocky/parity/target/release/deps/libdocopt-eb02b06dca39e75f.rlib" "/home/rocky/parity/target/release/deps/libstrsim-fa50309ddd5f7139.rlib" "/home/rocky/parity/target/release/deps/libethcore_rpc-357a287dd21d367d.rlib" "/home/rocky/parity/target/release/deps/libjsonrpc_http_server-7747024a10cfa0ba.rlib" "/home/rocky/parity/target/release/deps/libethsync-9c77a75299133480.rlib" "/home/rocky/parity/target/release/deps/libhyper-6df9e9da10e4a36f.rlib" "/home/rocky/parity/target/release/deps/libcookie-9ec7d33888fc3f77.rlib" "/home/rocky/parity/target/release/deps/libethcore-38949555f71e57b2.rlib" "/home/rocky/parity/target/release/deps/libethash-99f98e76aaf17ddf.rlib" "/home/rocky/parity/target/release/deps/liblanguage_tags-1002a4c10b7723f2.rlib" "/home/rocky/parity/target/release/deps/libethcore_util-cf63b75860342e31.rlib" "/home/rocky/parity/target/release/deps/libmio-1f497c4fa6c81f43.rlib" "/home/rocky/parity/target/release/deps/libmiow-406fbfc011e7018a.rlib" "/home/rocky/parity/target/release/deps/libcrossbeam-598603aac01a491c.rlib" "/home/rocky/parity/target/release/deps/libsecp256k1-f54a83b9ad792914.rlib" "/home/rocky/parity/target/release/deps/libtarget_info-7ef339b5d48bf484.rlib" "/home/rocky/parity/target/release/deps/libtiny_keccak-1cb2645f95e198e2.rlib" "/home/rocky/parity/target/release/deps/libigd-fa27abe09c7e1663.rlib" "/home/rocky/parity/target/release/deps/libxmltree-58762dfe968cbd41.rlib" "/home/rocky/parity/target/release/deps/libarrayvec-bcf06b3ef065493b.rlib" "/home/rocky/parity/target/release/deps/libnodrop-145776e59f1ff881.rlib" "/home/rocky/parity/target/release/deps/libslab-73afbb2a6dbe517a.rlib" "/home/rocky/parity/target/release/deps/libxml-b898dc3a55f0f1e4.rlib" "/home/rocky/parity/target/release/deps/libenv_logger-2fedde90a22290a6.rlib" "/home/rocky/parity/target/release/deps/libregex-bd2295b5426133ed.rlib" "/home/rocky/parity/target/release/deps/libaho_corasick-eea45523c8483aac.rlib" "/home/rocky/parity/target/release/deps/libslab-9047f35959d0e98e.rlib" "/home/rocky/parity/target/release/deps/libxml-abb1893902afb9eb.rlib" "/home/rocky/parity/target/release/deps/libnet2-3cf5e0e8113ba5ec.rlib" "/home/rocky/parity/target/release/deps/libkernel32-a6ecb7771eb9fd8d.rlib" "/home/rocky/parity/target/release/deps/libbytes-c5ffc5f017602734.rlib" "/home/rocky/parity/target/release/deps/libbitflags-a5765347a1f15202.rlib" "/home/rocky/parity/target/release/deps/libcrypto-daa20c09deb34369.rlib" "/home/rocky/parity/target/release/deps/liblazy_static-007034d2ad8108ce.rlib" "/home/rocky/parity/target/release/deps/libitertools-4a188e3fc7b95184.rlib" "/home/rocky/parity/target/release/deps/libwinapi-96db160368c72f00.rlib" "/home/rocky/parity/target/release/deps/libhyper-2ba027f1404b8ddb.rlib" "/home/rocky/parity/target/release/deps/libmime-b95e634e9256396c.rlib" "/home/rocky/parity/target/release/deps/libsolicit-8632432b3a4330d6.rlib" "/home/rocky/parity/target/release/deps/libtraitobject-4ea485452a3a4a0b.rlib" "/home/rocky/parity/target/release/deps/libhttparse-5c82294627258d33.rlib" "/home/rocky/parity/target/release/deps/libcookie-14f7332b9f1085f4.rlib" "/home/rocky/parity/target/release/deps/libtime-22c21fe32894ddad.rlib" "/home/rocky/parity/target/release/deps/libtypeable-7ddee84661471c9b.rlib" "/home/rocky/parity/target/release/deps/libnum_cpus-9a6b3f359403ec12.rlib" "/home/rocky/parity/target/release/deps/liblanguage_tags-668f109940a16d3d.rlib" "/home/rocky/parity/target/release/deps/libhpack-8f91a695370f3d75.rlib" "/home/rocky/parity/target/release/deps/liblog-0b1f2bad29d31333.rlib" "/home/rocky/parity/target/release/deps/libunicase-010a3d083a955b43.rlib" "/home/rocky/parity/target/release/deps/libregex_syntax-bd4ec68a5240de5f.rlib" "/home/rocky/parity/target/release/deps/librocksdb-9575b3c35c6df239.rlib" "/home/rocky/parity/target/release/deps/libmemchr-545f7c18e4fb5174.rlib" "/home/rocky/parity/target/release/deps/libcrossbeam-799b558d256c3719.rlib" "/home/rocky/parity/target/release/deps/libnix-0a0f17046b629e37.rlib" "/home/rocky/parity/target/release/deps/liblibc-dd3420cb049117bb.rlib" "/home/rocky/parity/target/release/deps/libbitflags-646076c1f4684754.rlib" "/home/rocky/parity/target/release/deps/libcfg_if-9d1a6a7bb7e59611.rlib" "/home/rocky/parity/target/release/deps/libjsonrpc_core-ade33bf9a261d530.rlib" "/home/rocky/parity/target/release/deps/libserde_json-a315649c5c9d7dbd.rlib" "/home/rocky/parity/target/release/deps/libserde-4c727162e825127b.rlib" "/home/rocky/parity/target/release/deps/libnum-d3b232b2ec3de579.rlib" "/home/rocky/parity/target/release/deps/liburl-3f8ca9274c8ba747.rlib" "/home/rocky/parity/target/release/deps/libheapsize-a00ec68b9e8bd80c.rlib" "/home/rocky/parity/target/release/deps/libodds-a282c05a18154572.rlib" "/home/rocky/parity/target/release/deps/libelastic_array-f92e792c0c7c367c.rlib" "/home/rocky/parity/target/release/deps/libutf8_ranges-afda04de2a52d0c6.rlib" "/home/rocky/parity/target/release/deps/libsha3-311ec133316d68db.rlib" "/home/rocky/parity/target/release/deps/liburl-724ce393f65d83e3.rlib" "/home/rocky/parity/target/release/deps/libunicode_normalization-96775aa97caeb805.rlib" "/home/rocky/parity/target/release/deps/libuuid-fed17b74aa7673e2.rlib" "/home/rocky/parity/target/release/deps/librand-6fab17fc670a2bc8.rlib" "/home/rocky/parity/target/release/deps/librustc_serialize-79a17eda1cd94e46.rlib" "/home/rocky/parity/target/release/deps/libunicode_bidi-95db49b0dd3b3cbd.rlib" "/home/rocky/parity/target/release/deps/libmatches-737aa40e66529b02.rlib" "/home/rocky/parity/target/release/deps/liblibc-c862fb1c783dd674.rlib" "/home/rocky/parity/target/release/deps/libws2_32-48ce3a74759818f2.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-fd663c41.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-fd663c41.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-fd663c41.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-fd663c41.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-fd663c41.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-fd663c41.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-fd663c41.rlib" "/home/rocky/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-fd663c41.rlib" "-l" "rocksdb" "-l" "c" "-l" "m" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "compiler-rt"
note: /home/rocky/parity/target/release/deps/libheapsize-a00ec68b9e8bd80c.rlib(heapsize-a00ec68b9e8bd80c.0.o): In function `heap_size_of::h0b3f8faa2163ab3aIaa':
heapsize.0.rs:(.text._ZN12heap_size_of20h0b3f8faa2163ab3aIaaE+0x7): undefined reference to `je_malloc_usable_size'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `parity`.

**Comment by gavofyork** [comment]
could you paste the output of `rustc --version`?

**Comment by gavofyork** [comment]
if that doesn't begin with:

```
rustc 1.7.0-beta
```

then you need to switch to beta by running

```
multirust default beta
```

**Comment by rfikki** [comment]
rustc 1.8.0-nightly (57c357d89 2016-02-16)

**Comment by gavofyork** [comment]
indeed yes.

**Comment by gavofyork** [comment]
closing - if it still doesn't work for you, please reopen.
