### ISSUE TITLE
Failed to fetch the contract: Certifier smsverification does not exist.

### ISSUE THREAD

**Issue by vkobel** [ethcore/parity#4782]
Hi,
Just trying to get some kETH on kovan but the automatic faucet doesn't work, I get the following message when trying to verify my account with parity's web UI: `Failed to fetch the contract: Certifier smsverification does not exist.` and the same for email verification.

Am I missing something?

Thanks!
Vincent

**Comment by hitchcott** [comment]
@vkobel 

I had this issue before - please make sure you have disabled any Adblockers/PrivacyBadger for  localhost, and ensure you're fully synced.

**Comment by vkobel** [comment]
Ok my mistake then, I was on kovan chain. Thanks!

**Comment by panicape** [comment]
Hi everyone, i was trying to do the same, i'm in mainnet and still with the same error, is it possible that the chain still not syncronized??

**Comment by tomusdrw** [comment]
@panicape What best block and chain does it show in the bottom right corner?

**Comment by panicape** [comment]
3,808,258 best block
