### ISSUE TITLE
Token Balance Not Showing Up After Registering

### ISSUE THREAD

**Issue by btcmacroecon** [ethcore/parity#4790]
Dear Parity,
I created SAVEtheTIGERS (TIG) and registered tokens in the Registry at Parity.
The token contract is:   0x059d4329078dcA62c521779c0Ce98EB9329349e6
I used MyEtherWallet to create the contract for TIG and I did a BalanceOF check and it shows sitting at the Parity Wallet:  0x0084b8Df67C0ca75DF8Fc447dfFA096bA1A8ff47

I'm not sure what else I need to do to get the balance to show up correctly but it shows it did go through. Please advise, let me know if you need any more info. Thanks a lot.
btcmacroecon

**Comment by tomusdrw** [comment]
Some balance is indeed in the address you posted, you can verify that by quering a contract from Parity UI (Contracts -> Watch Contract):

![screenshot from 2017-03-07 09-37-46](https://cloud.githubusercontent.com/assets/581548/23648190/db733332-0319-11e7-927c-189ccbb796d0.png)

The token address is also registered in Parity Token Registry:
![screenshot from 2017-03-07 09-39-15](https://cloud.githubusercontent.com/assets/581548/23648205/efc9abd6-0319-11e7-9243-092caaed5a2a.png)

And the balance also displays correctly in the UI:
![screenshot from 2017-03-07 09-40-11](https://cloud.githubusercontent.com/assets/581548/23648236/15ba2ffa-031a-11e7-86c0-edb294205490.png)

Seems that everything works correctly on Mainnet.
Please make sure that you were checking that on a correct chain and your node was fully synced.
Please re-open if the problem persists or I misunderstood your issue.

**Comment by btcmacroecon** [comment]
thanks! have no way of knowing if Im on right chain but it's showing up
now. DONE DEAL!
