### ISSUE TITLE
I Deployed Tokens at Parity and Registered but balance is not showing up correctly

### ISSUE THREAD

**Issue by btcmacroecon** [ethcore/parity#4791]
I deployed 2 tokens at Parity (IND, STV) and after deployment in the application at Parity, it showed both showing up and both had correct supply of 100,000,000 each.
I registered the tokens and both (IND, STV) showed by name in my wallet, but not what I saw in Deploy. 
What do I need to do to resolve to reflect correct balance of 100,000,000 tokens each (IND, STV)?
[](https://paste.linux.community/view/e46d07ba) There is more info if you need it. 
Also, a concern though not Parity related is how to resolve such an issue after the fact with EtherScan so as to how to reflect correct amount for sake of standardization and anybody that has the tokens so they don't get confused? I'm learning still and I do apologize for that, but I want to get it right. I think part of my mistake is I should have created 100,000,000 (and then added 18 zeros after that) to get correct balance. But I am just trying to make this right after the fact. Thanks!
BTCMACROECON

**Comment by tomusdrw** [comment]
Yes, indeed `totalSupply` of the token is way too low for a token with `18` decimals.
If the token contract doesn't support minting new coins there is not much you can do.

The token is fully usable though, you may change the way it's displayed by altering number of decimals in Parity registry.

Deploying a token is a one-time action that should be taken with great care I'd suggest experimenting on a testnetworks first (Ropsten is a little bit dead, but you may try [Kovan PoA testnet](https://github.com/kovan-testnet/proposal)).

**Comment by btcmacroecon** [comment]
http://www.awesomescreenshot.com/image/2267238/250ba75732d3758ef053620f96e7a5cd It keeps saying I am not the owner...I am trying to up it to 100,000,000 (plus 18 zeros more) What am I doing wrong here? thanks for your help.

**Comment by tomusdrw** [comment]
You cannot top up the supply in the registry. Total Supply is encoded in your deployed contract, if the contract code doesn't have a function to increase the supply it is not possible (most probably it doesn't).

**Comment by btcmacroecon** [comment]
man I sure just tried and paid gas and registration fee again because it said I didn't own the contract, thought I had to do that again to up the balance....will try to salvage somehow. Has to be a better way like with clear instructions! Which brings me to Golden Token. I take it that's the contract to deploy tokens. I'll try to research capabilities, see what I got myself into now. Thanks for help. If you know anything about Golden token (I take it's the original contract, please let me know)

**Comment by tomusdrw** [comment]
You can try `unregistering` your previous token, deploying a new one and registering it again with correct parameters.
