### ISSUE TITLE
Email and SMS Verification for Mainnet fails

### ISSUE THREAD

**Issue by NiklasKunkel** [ethcore/parity#4792]
Failed to fetch the contract: Certifier smsverification does not exist.
Failed to fetch the contract: Certifier emailverification does not exist.

**Comment by 5chdn** [comment]
Are you sure you are on mainnet? Please add some details on OS, Parity version, configuration and what you are trying to do.

**Comment by tomusdrw** [comment]
Are you using https://www.eff.org/privacybadger?

**Comment by NiklasKunkel** [comment]
Issues seems to have fixed itself. Closing.

**Comment by noisy** [comment]
I have encounter exactly the same problem. However I just installed parity. Is it possible that node is not synced yet?

**Comment by 5chdn** [comment]
> Is it possible that node is not synced yet?

Exactly. Check the status tab or the progress in the footer of your wallet.
