### ISSUE TITLE
1.5.7 "--testnet" now defaults to kovan

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#4812]
when running with the  "--testnet" option it now defaults to "kovan" . In previous versions the default testnet chain was ropsten.

**Comment by mtbitcoin** [comment]
I think its less confusing to have "--testnet" default to "ropsten" (or whatever the default testnet chain that is adopted by the other clients in the future)

**Comment by JosefJ** [comment]
Minor stuff: also there is a missing distinction for ropsten/kovan links to Etherscan within the parity UI - links are still to testnet.etherscan (on kovan as default)

**Comment by 5chdn** [comment]
Ropsten is unusable and therefore the current `--testnet` is defaulting to kovan. As far as I know there are no other working public testnets available currently. 

You can still run `--chain ropsten` if you want to use the old network.
