### ISSUE TITLE
Spec json is invalid in Two Node PoA Tutorial

### ISSUE THREAD

**Issue by belsyuen** [ethcore/parity#4825]
Hi, 

I have followed the steps in the tutorial 
https://github.com/ethcore/parity/wiki/Demo-PoA-tutorial

I have pulled the repo from https://github.com/keorn/parity-poa-tutorial

When I run 
parity --config node0.toml or the longer command without the .toml file, I get a return of 

"Spec json is invalid"

Not sure how to proceed.  thanks!

**Comment by keorn** [comment]
What `parity --version` are you using?

**Comment by belsyuen** [comment]
Hi, 

version Parity/v1.4.12-stable-b884729-20170222/x86_64-macos/rustc1.15.1

**Comment by rphmeier** [comment]
@belsyuen PoA is supported only in version 1.5 and up. Please update and give it another go.

**Comment by keorn** [comment]
@belsyuen Is this good to close?

**Comment by belsyuen** [comment]
hey yes sorry, I just got it update, it is good to close! thanks!

**Comment by geneweng** [comment]
I got "Spec json is invalid" with
 version Parity/v1.6.6-beta-8c6e3f3-20170411/x86_64-linux-gnu/rustc1.16.0

**Comment by 5chdn** [comment]
@geneweng please share your spec.json.
