### ISSUE TITLE
Cant create dylib using parity.

### ISSUE THREAD

**Issue by Radagast-red** [ethcore/parity#4836]
When using parity as a library for dylib project. Project cant be build.

Please try to build attached project this with:
rustc 1.15.1 (021bd294c 2017-02-08)
cargo 0.16.0-nightly (6e0c18c 2017-01-27)

: cargo build
[parityIssue.tar.gz](https://github.com/ethcore/parity/files/831026/parityIssue.tar.gz)

and error occur during build.

**Comment by rphmeier** [comment]
Gist here: https://gist.github.com/rphmeier/8179b3da8c7023eb2bb7641af237d9f6

**Comment by rphmeier** [comment]
The only linker error I get is because of https://github.com/servo/heapsize requiring `jemalloc` (presumably, dylibs only link against the system allocator)

**Comment by rphmeier** [comment]
Everything works with `crate_type="lib"`.

My take on this is that it would be far too much work to try and change out our memory instrumentation to work on the system allocator as well for such a niche use-case. If you'd like to make a PR, would gladly review and merge it.

**Comment by paulperegud** [comment]
This method of linking was working fine against Parity v1.5.7 and below.

**Comment by Radagast-red** [comment]
Can you post your error log?

**Comment by Radagast-red** [comment]
Doesn't make sense. I have found commit:
https://github.com/ethcore/parity/commit/b5219bc7238006c75bf5d79784d1786a4e677e8f

This decorates snappy to be linked statically despite everything. So its copy ends up in each dynamic lib i believe. Simply removing static link fix this, works for lib and dylib.

**Comment by debris** [comment]
@arkpar do we need to link snappy statically?

**Comment by arkpar** [comment]
We do, but it looks like the `link` directive is  superfluous here since libsnappy is already linked by one of dependencies of ethcore-util

**Comment by arkpar** [comment]
@Radagast-red does #4841 resolve an issue for you?

**Comment by Radagast-red** [comment]
Yes, thank you.
