### ISSUE TITLE
Mining tutorial outdated

### ISSUE THREAD

**Issue by chriseth** [ethcore/parity#4853]
The wiki page https://github.com/ethcore/parity/wiki/Mining lists directions to install ethminer for mining with parity. Support for GPU mining has been dropped from the cpp-ethereum project for quite a while now and it is generally recommended to switch to Genoil's gpu-mining focused version of cpp-ethereum at github.com/Genoil/cpp-ethereum

**Comment by arkpar** [comment]
@NikVolf could you please update it and add stratum instructions?

**Comment by NikVolf** [comment]
@chriseth 

Updated, thanks for reporting!
