### ISSUE TITLE
Weird 'tile' behavior in Mac Safari browser

### ISSUE THREAD

**Issue by tjayrush** [ethcore/parity#4887]
When I look at the newest version (1.6.2) of Parity in Chrome, it works perfectly. The animation that occurs when the mouse moves over the various tiles in the home page or the wallet page behaves exactly as I would expect.

With Safari on a Mac, it's a totally different story. The animation is very messed up. On the home page, with only two tiles, it sort of works, but with  the ten or more tiles on the wallet page, things go totally haywire. It looks to me to be sort of Javascript rendering problem.

I'm running 1.6.2 beta (which installed using the Mac installer) and Version 10.0.3 (12602.4.8) of Safari on macOS Sierra 10.12.3

**Comment by jacogr** [comment]
Confirmed. The layout stretch behaves very weirdly.

https://www.youtube.com/watch?v=3TQRJR1i9hw&feature=youtu.be
