### ISSUE TITLE
Optimise bigint arithmetic

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#490]
Subtractions are suboptimal; probably other operations, too.

Use assembly to make it all good.

http://accu.org/index.php/articles/1849

https://doc.rust-lang.org/book/inline-assembly.html

**Comment by NikVolf** [comment]
would like to take this
used to code in asm :)

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/pull/515
rather rush optimization for x64

**Comment by tomusdrw** [comment]
Do you plan to optimize rust (non-asm) code as well (for other platforms)? If not I would also like to have a look :)

**Comment by NikVolf** [comment]
Nah, but was going to add more asm to the most called operations

**Comment by NikVolf** [comment]
for tracking purpose
https://github.com/ethcore/parity/pull/539
