### ISSUE TITLE
Ubuntu package conflicts with ethereum package

### ISSUE THREAD

**Issue by d10r** [ethcore/parity#4904]
I can't install the Ubuntu package from https://github.com/ethcore/parity/releases on my server running Ubuntu 16.04 due to a conflict with the also installed ethereum package:

```
# dpkg -i parity_1.6.2_amd64.deb
(Reading database ... 61664 files and directories currently installed.)
Preparing to unpack parity_1.6.2_amd64.deb ...
Unpacking parity (1.6.2) over (1.5.4) ...
dpkg: error processing archive parity_1.6.2_amd64.deb (--install):
 trying to overwrite '/usr/bin/evm', which is also in package evm 1.5.9+build8841+xenial
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 parity_1.6.2_amd64.deb
```

**Comment by tomusdrw** [comment]
Conflict in binary names was addressed in #4899 

As a workaround you can either:
1. Remove existing `evm` package (`$ sudo apt-get remove evm`)
2. Backup `evm` binary `$ sudo cp /usr/bin/evm /usr/bin/evm-backup` and force install parity `dpkg -i --force ...`
