### ISSUE TITLE
Specifying addresses and/or working with RPC & contracts

### ISSUE THREAD

**Issue by xavieryvez** [ethcore/parity#507]
This is quite obviously a lack of documentation or problem-between-keyboard-and-chair issue ...

I would really like to test Parity - close to going live, so the time is actually right. I just cannot figure out how to give the thing an address, or create an address for it.

Basically the use-case will be to only sync blocks, attach my deployed contracts (reading public data on it) and getting events from it. (i.e. calls to public exposed variables and using the web3 allEvents functionality on contracts) 

Current when running -

(a) I get a coinbase of 0x0000...0000 returned via RPC to my app
(b) as soon as I can a method on a contract (rather read a public variable) - get an exception

So, as originally mentioned I'm missing something basic. It does offer full RPC, nothing I do consumes ETH, but I only run with `parity -j` (no other options passed) before I attach to it via web3 (node.js server). No issues with Geth on my Mac.

EDIT: This is with both the released and more expansive-options GitHub (0.9.99) versions

**Comment by NikVolf** [comment]
Address (account) management is going to be introduced in coming few days
Pull request: https://github.com/ethcore/parity/pull/497
Parity will just import your geth addresses on start (if you have some) and will allow you to create new ones in the same manner
Related functionality will be available via RPC as well

**Comment by arkpar** [comment]
RPC is a work in progress. It will be ready by the upcoming 1.0 release.
