### ISSUE TITLE
Bad reply to GetBlockHeaders, starting header missing

### ISSUE THREAD

**Issue by karalabe** [ethcore/parity#511]
I've noticed that when the Go client asks for headers from block 0 upwards, Parity sends headers from 1 upwards, even though the [protocol spec](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol#new-model-syncing-pv62) states it should send from the requested block.

> Reply must contain a number of block headers [...] beginning at block `block`.

Thought I'd notify you about it :)

**Comment by NikVolf** [comment]
Indeed, thank you Peter!
