### ISSUE TITLE
Fix rpc server dependency loop

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#513]
When running `parity -j` main thread is terminated without calling Client's drop sequence. Presumably there is an Arc pointer loop in RPC server

**Comment by debris** [comment]
I've investigated the issue and it seems to be nontrivial to fix. Hyper uses std `TcpListener` which has blocking `accept`. I don't know if it's possible to gracefully break it or how to do that. Without shutting it down, rpc server is not being properly disposed and drop sequence is not called.

There are already few open issues related with this problem.

https://github.com/hyperium/hyper/issues/338
https://github.com/hyperium/hyper/issues/395

Using mio's `TcpListener` in hyper would solve the issue, cause it has nonblocking `accept` (https://github.com/carllerche/mio/blob/master/src/sys/unix/tcp.rs#L28).

Hyper devs are already working on it (https://github.com/hyperium/hyper/tree/mio), so I suggest to wait for the next release of hyper.

**Comment by arkpar** [comment]
You can just cleanup the the client reference and let the accept thread terminate.
Or use `Weak` pointers instead of `Arc`.
Otherwise we should move to a different library. Having unclean exit and crash on shutdown is not an option.

**Comment by arkpar** [comment]
https://github.com/ethcore/parity/blob/master/parity/main.rs#L146
This code looks very dodgy. What happens to the `server` object when the function exits? Is it dropped? How can it continue working after it  is dropped? What happens to `client` and `sync` references? How do I cleanup resources allocated to it?
