### ISSUE TITLE
Don't clone rocksdb

### ISSUE THREAD

**Issue by petevine** [ethcore/parity#566]
Either bundle a source snapshot at the required revision or switch to master and use `--depth=1`.

Right now it takes overly long and needlessly wears SD storage down.

**Comment by petevine** [comment]
And besides, it doesn't even compile on ARM at that revision. The following line would have to be ported back:

https://github.com/facebook/rocksdb/blob/3492889ab858ff25aa6d12aac3a08200366a50e2/Makefile#L88

**Comment by arkpar** [comment]
Updated rocksdb repo to this commit. Will add `--depth=1` once it hits a stable branch

**Comment by arkpar** [comment]
Fixed in latest master. Switched to using a subtree.
