### ISSUE TITLE
Fix chain memory management

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#576]
Gets to > 300MiB when downloading the chain. Should not resort to randomly removing items, but be a proper fix to the current conveyor-belt style cache.

**Comment by arkpar** [comment]
It is a bug fixed here: https://github.com/ethcore/parity/pull/499/files#diff-422bab2793f9fb234587f1dadcf690d3R468

**Comment by gavofyork** [comment]
fixed in #580
