### ISSUE TITLE
eth/63 advertised but not implemented

### ISSUE THREAD

**Issue by karalabe** [ethcore/parity#659]
Parity nodes notoriously advertise that they support eth/63, but they reply with empty packets to all data requests that need receipts or state trie entries.

**Comment by gavofyork** [comment]
@arkpar?

**Comment by arkpar** [comment]
Work in progress )

**Comment by karalabe** [comment]
Not entirely. The protocol allows returning only a subset, the protocol does not allow returning none. 

> Does not need to contain all; best effort is fine. If it contains none, then has no information for previous hashes.

The problematic part with having peers that don't return any data is that they inherently stall syncing nodes who assume peers have good faith. By allowing nodes to not return anything, the optimal behavior for a node is actually to not return anything and as such save on bandwidth. However as more and more nodes do this, the network would start falling apart.

**Comment by NikVolf** [comment]
requires https://github.com/ethcore/parity/pull/634 to be working for all options

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/pull/686
parity with archive journaldb (which is default) will return the state

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/pull/687
parity will return receipts up to configured maximum

**Comment by gavofyork** [comment]
@karalabe as a point of logic the empty set is strictly a subset of all sets, so none is not only _a_ perfectly valid response, but in many cases may be _the only_ valid response a node can give.

**Comment by NikVolf** [comment]
@karalabe can you test if it's working with 1.1 (master branch)
we have some internal tests, but since we are not using this requests ourselves, we can't be sure if it is ok

**Comment by karalabe** [comment]
If you can point me to a running instance of this code I can run a fast sync against it.

**Comment by arkpar** [comment]
`enode://579beb0903efb88ca5988b51405a79ec7ac9ef1652e077f98b0abf469f23c742ada6e4a37332075b8aef42998ce605dfdd33a9d114e0a903da46e3cdb10759b1@37.139.25.218:30303`
