### ISSUE TITLE
Optimize CI build times

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#707]

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/pull/718

@tomusdrw maybe you might look into it
putting our build to container infrastructure
now Travis is running out of memory (probably) during the build

**Comment by rphmeier** [comment]
it may also be worthwhile to look into using a travis cache for our crates.io dependencies

**Comment by tomusdrw** [comment]
We already do that manualy: https://github.com/ethcore/parity/blob/master/.travis.yml#L49

**Comment by rphmeier** [comment]
working on getting a shared target directory to prevent recompilation of dependencies, but am running into this: https://github.com/rust-lang/cargo/issues/2746

**Comment by gavofyork** [comment]
an ongoing problem that we're all aware of - doesn't make sense to have a single issue on it.
