### ISSUE TITLE
netstats keeps failing

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#731]
but only on parity clients. JSONRPC hanging?

**Comment by gavofyork** [comment]
@cubedro any idea why the latest netstats client code results in delayed latest-block reporting?

**Comment by cubedro** [comment]
Looking into it. Will let you know what I find

**Comment by gavofyork** [comment]
*bump* any idea what's going on here? ethstats.net consistently demonstrate that nodes running the latest version of netstats client fall behind.

**Comment by cubedro** [comment]
@gavofyork wrote a fix. hope it solves the problem. I tested it locally and it works for me.
https://github.com/cubedro/eth-net-intelligence-api/pull/234

**Comment by arkpar** [comment]
Confirmed. Thanks @cubedro
