### ISSUE TITLE
Stratum/Eth API for mining

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#755]
Need to introduce a protocol that allows work to be pushed to a miner/updated at will, in order to reduce potential time wasted with the polling.

**Comment by gavofyork** [comment]
waiting on #492

**Comment by gavofyork** [comment]
seems unnecessary with HTTP events. one for middleware, probably.

**Comment by intagger** [comment]
So how can I connect Genoil's ethminer to the parity?

**Comment by 5chdn** [comment]
We updated our Mining Wiki for Stratum Support: https://github.com/ethcore/parity/wiki/Mining#stratum

> Since 1.6, Parity offers Stratum protocol support (beta). This protocol has number of advantages compared to the JSON-RPC polling, which results in better hashrate and less node strain. To run parity with Stratum on, use

> ```
> parity --author 0037a6b811ffeb6e072da21179d11b1406371c63 --stratum
> ```

> By default Stratum listens on local network interface (`127.0.0.1`) and port `8008`. You can change it by providing `--stratum-interface` and `--stratum-port` arguments, respectively. For example, to use all network interfaces on the local machine and listen on port 9009:

> ```
> parity --author 0037a6b811ffeb6e072da21179d11b1406371c63 --stratum --stratum-interface=0.0.0.0 --stratum-port=9009
> ```

> To utilize Stratum, miner also needs to be started in Stratum mode. For genoil, it will be
> ```
> genoil -G -S 127.0.0.1:8008
> ```
