### ISSUE TITLE
Parity -j panick on MacOSX, doesn't start; installed with bash <(curl https://get-parity.ethcore.io -Lk)

### ISSUE THREAD

**Issue by BenTuras** [ethcore/parity#759]
$ bash <(curl https://get-parity.ethcore.io -Lk)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    514      0 --:--:-- --:--:-- --:--:--   518
100 13004  100 13004    0     0  12339      0  0:00:01  0:00:01 --:--:-- 55811
==> Checking OS dependencies
 ✓	 OS X Version 10.11.3
 ✓	 git
 ✓	 Ruby 2.0.0
 ✓	 Homebrew 0.9.5 (git revision 56727; last commit 2016-03-15)

Found all dependencies (4/4)
==> OK, let's install Parity now!
==> Last chance! Sure you want to install this software? [Y/n] 

==> Installing Parity build dependencies
==> Adding ethcore repository
==> Tapping ethcore/ethcore
Cloning into '/usr/local/Library/Taps/ethcore/homebrew-ethcore'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
Tapped 1 formula (27 files, 18.6K)

==> Updating brew
Updated Homebrew from 567278e to a2b9ace.
Updated 1 tap (ethereum/ethereum).
==> New Formulae
buku
==> Updated Formulae
afl-fuzz           awscli             devd               gjstest            libgraphqlparser   neofetch           parrot             remctl             vc4asm           
avrdude            caf                elasticsearch      infer              libqglviewer       node               qbs                swiftlint          yank             
avro-c             cake               erlang             jboss-forge        libsigc++          nsd                quex               telegraf           zsh-completions  
avro-cpp           conan              flatbuffers        lfe                logtalk            openrtsp           redpen             v8               

==> Installing parity
==> Installing parity from ethcore/ethcore
==> Installing dependencies for ethcore/ethcore/parity: multirust, lz4, rocksdb
==> Installing ethcore/ethcore/parity dependency: multirust
==> Downloading https://homebrew.bintray.com/bottles/multirust-0.7.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring multirust-0.7.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/multirust/0.7.0: 15 files, 144.4K
==> Installing ethcore/ethcore/parity dependency: lz4
==> Downloading https://homebrew.bintray.com/bottles/lz4-r131.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lz4-r131.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/lz4/r131: 12 files, 376.8K
==> Installing ethcore/ethcore/parity dependency: rocksdb
==> Downloading https://homebrew.bintray.com/bottles/rocksdb-4.4.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring rocksdb-4.4.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/rocksdb/4.4: 71 files, 10.2M
==> Installing ethcore/ethcore/parity
==> Cloning https://github.com/ethcore/parity.git
Cloning into '/Library/Caches/Homebrew/parity--git'...
remote: Counting objects: 356, done.
remote: Compressing objects: 100% (337/337), done.
remote: Total 356 (delta 68), reused 131 (delta 10), pack-reused 0
Receiving objects: 100% (356/356), 767.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (68/68), done.
Checking connectivity... done.
==> Checking out branch beta
==> multirust update stable
==> multirust run stable cargo build --release
==> Caveats
To have launchd start ethcore/ethcore/parity at login:
  ln -sfv /usr/local/opt/parity/*.plist ~/Library/LaunchAgents
Then to load ethcore/ethcore/parity now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.parity.plist
==> Summary
🍺  /usr/local/Cellar/parity/1.0.0: 5 files, 9.6M, built in 8 minutes 47 seconds

==> Parity has been installed

==> All done
==> Next steps
==> Run `parity -j` to start the Parity Ethereum client.

$ parity -j
thread '<main>' panicked at 'unexpected -vV format', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/rustc_version-0.1.7/src/lib.rs:126
$

**Comment by arkpar** [comment]
Use `multirust default stable` command as a temporary workaround

**Comment by arkpar** [comment]
Should be working now, please reopen in case of problems

**Comment by BenTuras** [comment]
It's indeed working after running command multirust default stable as suggested by arkpar.

**Comment by arkpar** [comment]
The workaround is no longer required with the latest brew version
