### ISSUE TITLE
Make `Externalities::ret` consume self

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#779]
Currently `ret` can be called more than once; it should consume `self` to avoid this. Will need refactoring so it's called from the owner (`Executive`, not JIT/Interpreter). This will make much of its code cleaner by avoiding dicking around with `mut&`s, where moving is actually what should be done.

**Comment by rphmeier** [comment]
I am interested in working on this.

**Comment by arkpar** [comment]
@rphmeier Cool, post here or reach us at https://gitter.im/ethcore/parity in case you need any help.
