### ISSUE TITLE
v1.0.0 compilation issue

### ISSUE THREAD

**Issue by loxal** [ethcore/parity#808]
“cargo build --release“ gives me    

```
Compiling rust-crypto v0.2.34
error: could not find native static library `_rust_crypto_helpers`, perhaps an -L flag is missing?
Could not compile `rust-crypto`.
```

whereas “cargo build” works fine.

**Comment by arkpar** [comment]
@loxal Try deleting `target/release` directory and building again. If that still fails please tell use your OS info and `rustc --version` output

**Comment by loxal** [comment]
I’ve run a few commands and reinstalled the entire Rust ecosystem again (this time without root privileges like the command on the front page suggests) and it worked.

**Comment by NikVolf** [comment]
maybe we should add warning not to use sudo for multirust, it's not the first issue on that )
