### ISSUE TITLE
Switch to using hyper mio branch 

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#823]
Otherwise we're stuck without queuing and limited RPC connections

**Comment by peterjoel** [comment]
Is this just used for USD price lookup? I couldn't see it anywhere else.

**Comment by debris** [comment]
it's also used by [rpc server](https://github.com/debris/jsonrpc-http-server) and [upnp](https://github.com/sbstp/rust-igd). You can see the full list in [`Cargo.lock`](https://github.com/ethcore/parity/blob/master/Cargo.lock)

**Comment by arkpar** [comment]
#901
