### ISSUE TITLE
Sync sometimes stops on bad block (morden chain)

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#827]

**Comment by markrtgh** [comment]
[archivemainsync.log.zip](https://github.com/ethcore/parity/files/236485/archivemainsync.log.zip)

**Comment by Jab1one** [comment]
I have same issue, synced at block:
4839212
with hash:
0xf418b3b2fbadccab0a6e7009792906006f66e17356c7640e874def344933e847
wtf
