### ISSUE TITLE
eth_estimateGas doesn't handle execution failures correctly

### ISSUE THREAD

**Issue by trapp** [ethcore/parity#860]
`eth_estimateGas` always returns the value of the parameter `gas` when the execution would fail. One example is estimating gas of the now closed digix crowd sale contract:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xf0160428a8552ac9bb7e050d90eeade4ddd52843","value":"0xff22","gasPrice":"0x051da038cc","gas":"0xffffff"}],"id":1}' http://localhost:8545
-> {"jsonrpc":"2.0","result":"0xffffff","id":1}
```

Parity says a transaction would use several million of gas for its execution.

However, an actual transaction only uses 121,000 gas because the execution fails: http://etherscan.io/tx/0xf0512cb94a5c04643cbc846f70e7308f6e81c44097da61a42a4b9b86f3565fda

Gas estimates should be correct, whether the execution succeeds or fails.

**Comment by gavofyork** [comment]
not sure what you mean here. we define the "correct" amount of gas as the minimum amount of gas such that the transaction succeeds. if the transaction always fails regardless of how much gas is given, then there is no "correct" amount of gas.

**Comment by trapp** [comment]
Yeah, it's a while since I wrote the ticket. I think the main issue was to detect if transactions would fail by using estimateGas. A simple approach would be to check if suppliedGas == estimatedGas. There remains the edge case where the execution succeeds but uses the exact amount of gas provided, though I think we can neglect that.
