### ISSUE TITLE
Syncing "hangs" on ARM

### ISSUE THREAD

**Issue by petevine** [ethcore/parity#868]
Could be the same problem as reported by @phonikg [here](https://github.com/ethcore/parity/issues/266#issuecomment-202689733) but the symptoms are slightly different.

The peers are there, network traffic is more or less steady @ 0.1-1 Mbit but there are no io writes:
![hang](https://cloud.githubusercontent.com/assets/12054457/14218521/f580a1fe-f854-11e5-9206-f8bec35bd5a1.png)
 
I've got 2 revs: `af14c68` and `3e09f99` not able to progress any further, even after a few hours of read-only disk io and network activity.

What could be the problem here? In case it's some sort of DB corruption, which logs should I upload?

**Comment by petevine** [comment]
Ok, so it's (was?) a regression -  my first published build (`d7fb464)`was able to pull through almost immediately.

**Comment by arkpar** [comment]
Please update to latest commit, run with `-l sync=trace` and share the log.

**Comment by petevine** [comment]
Right, `3468b9a` was left running overnight and it's been completely fine since. So it it definitely wasn't a corruption.
