### ISSUE TITLE
Take nonce from TransactionQueue at a preference to BlockChain

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#875]
Sending two similar transactions (e.g. calling `eth_sendTransaction` two consecutive times with the same params) will result in:

```
WARN:ethcore_rpc::v1::impls::eth: Error sending transaction: Transaction(AlreadyImported)
```

which is invalid.

**Comment by tomusdrw** [comment]
Most probably `nonce` should be taken from `transaction_queue` instead of chain.

**Comment by gavofyork** [comment]
exactly.
