### ISSUE TITLE
eth_call broken.

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#887]
this eth_call RPC request fails on Parity, but succeeds on Geth, and I'm trying to figure out why:

```
 {
  "id": 157,
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
      "from": "0xd3e0607e17369a58e71796fb8df178b15a23ef68",
      "to": "0x513087e06ea1a05b858f6da58befb0012c775e63",
      "data": "0x7a66d7ca00000000000000000000000000000000000000000000000000000000000f69b5",
      "gas": "0x2fd618"
    },
    "latest"
  ]
}
```

(on Parity, it returns 0x; on Geth, it returns 0x10, which is what is expected)
I am attempting to call method getReportPeriod on contract address 0x513087e06ea1a05b858f6da58befb0012c775e63, on Morden
getReportPeriod accepts a single int256 parameter; the value being passed is 0x0f69b5

**Comment by MIGUELWAXX** [comment]
me too

**Comment by debris** [comment]
@MIGUELWAXX can you elaborate?
