### ISSUE TITLE
Clarify minimum bandwidth requirement

### ISSUE THREAD

**Issue by MagaTailor** [ethcore/parity#910]
Mostly out of curiosity I tried running parity on a link that'd been capped at 4 kB/s - even after many hours not a single block has been downloaded. 

My question is: can it never work or is it a matter of relaxing certain timeouts perhaps?

If anything, it should make for a nice addition to the docs if someone were to determine the viable minimum.

**Comment by gavofyork** [comment]
not sure if this is parity-side - did you try with other clients?

**Comment by petevine** [comment]
I'll give it a go in geth! (pun intended)

I can see geth has a `maxpendpeers` option which might just be what I need.

**Comment by petevine** [comment]
You were right - there's no difference between the clients and the peer limiting options don't help either.

Even though, e.g. 20MB/30MB of data get downloaded/uploaded respectively, it doesn't translate to any progress whatsoever.

**Comment by petevine** [comment]
I think there might be one actionable item here - parity fails to even start on a link like this:

`ERROR: Unable to retrieve USD value of ETH from etherscan. Rerun with a different value for --usd-per-eth`

which sounds wrong for a single number. After bumping every network timeout to 2x its original value, I was able to start without having to use the `--usd-per-eth` option. It didn't help with the data transfer though.

Maybe a `--slow-network` switch (instead of recompilation) could take care of these issues?

**Comment by petevine** [comment]
After some aggressive scaling down of the following [values]( https://github.com/ethcore/parity/blob/ca6c91f591e62c5b5aaa1e105572370bae0a57d0/sync/src/chain.rs#L111#L120) I was able to see parity sync from `0 to 5000` overnight on a 4kbyte/s down, 2kbyte/s up link using `--peers 2`. A vanilla binary is unable to sync a single block under the same conditions.

I think that answers my question about feasibility. I wonder however if a single binary could do some self-tuning at runtime?

**Comment by 5chdn** [comment]
Are you running a mobile connection via GPRS or EDGE? 

Ehtereum blocks are on [average 2KB in size](https://etherscan.io/chart/blocksize), so they should fit into GPRS packages, but you should not expect to be able to download the full blockchain with such a connection. Also keep in mind the node is doing more than just downloading blocks.

I am suspecting the minimum viable connection quality _should be_ somewhere around 48 KB/s. Do you have the chance of testing any 384kbit/s connections (e.g., EDGE)?
