### ISSUE TITLE
Ctrl-C does not generate SIGINT when started with "cargo run"

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#917]
Run parity; use JSONRPC; Ctrl-C; parity process still running.

Can only be klled with `killall -9 parity`

**Comment by arkpar** [comment]
Similar issue reported in https://github.com/rust-lang/cargo/issues/2343

**Comment by gavofyork** [comment]
using `cargo run`. this was caused by the now-fixed deadlock.

**Comment by arkpar** [comment]
Should be resolved with cargo issue mentioned above

**Comment by gavofyork** [comment]
works now.
