### ISSUE TITLE
fn calculate_difficuty need a condition header.timestamp >= parent.timestamp for more safety

### ISSUE THREAD

**Issue by efaysal** [ethcore/parity#986]
about this (header.timestamp - parent.timestamp), it may that rust will show "panicked at 'arithmetic operation overflowed'" and if unchecked, something as value will be surprising? Just to be sure that what you expect, rust is helping you to have it for sure ... safe if a condition is there: header.timestamp >= parent.timestamp , if not "panicked at 'arithmetic operation overflowed'" will pops if you are lucky ...

I know that implicitly one is supposing that  header.timestamp >= parent.timestamp but we never know!

**Comment by arkpar** [comment]
Difficulty calculation function expects valid input. The timestamp is validated here:
https://github.com/ethcore/parity/blob/master/ethcore/src/verification/verification.rs#L202
