### ISSUE TITLE
count initialization, in the fn nearest_node_entries, not in the write place?

### ISSUE THREAD

**Issue by efaysal** [ethcore/parity#990]
count was initialled  out of two loops:

1) loop over k-buckets
2) loop over nodes in each k-bucket

Surprisingly the count was incremented inside them, and tested:
if count == BUCKET_SIZE  ...  which is BUCKET_SIZE: usize = 16;	

Something is not  adequate there. 

count is a flag that control how many nodes have been discovered given that target and placed in the appropriate k-bucket, each  k-bucket should not contain more than 16, your case. For each k-bucket, a specific count should be assigned, and if it exceed 16, a removal process has to start on that k-bucket. 

Given a target, normally the search has to fill, 511 k-buckets,  each k-bucket should have only 16 nodes.  Note that as Ethereum is using node ID  with 512 bits, only few k-buckets will really be filled, 511,510,  till around, let's say 490,  at most , other k-buckets after are quasi-empty.  This is supported by a lot of simulations that I did, and can be statistically demonstrated. 

The code will be more simple, if one just select, well scrambled or well randomly selecting, a specific number of nodes  from all the k-buckets that the server(client)  has and send them any time a target is asking for. It will be more efficient ( at the level of coding and also to concretely connect the peers randomly) than following blindly what Kademlia was proposing. Kademlia is simply not designed for node ID  with 512 bits and more.

**Comment by arkpar** [comment]
`nearest_node_entries` is not supposed to update node table in any way. Removal process is started in `update_node`. Ethereum p2p protocol is defined here: https://github.com/ethereum/devp2p/blob/master/rlpx.md
You should submit an issue with that repo or https://github.com/ethereum/EIPs if you feel it should be changed.
